### ISSUE TITLE
Implement open ID connect, relying party authentication

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#100]
All requests that modify data, should be authenticated as a OIDC RP.

We should have a transitional env variable that disables this, so we can test it without authenticating.

**Comment by leolara** [comment]
@coffeejunk the entity for the user is called "API consumer"

**Comment by leolara** [comment]
This is part of the design here: https://docs.google.com/document/d/1LcZD8dJXeDnOrYtdrEZ6Dq3820mi2P0FUZNJL6Jd-Dg/edit?usp=sharing

**Comment by cwd-mparsons** [comment]
@steve @coffeejunk @jbaird123 What is the status of this?

**Comment by jbaird123** [comment]
@cwd-mparsons - We'll make this a priority

**Comment by jbaird123** [comment]
This is addressed in the "publish on behalf of" feature.  Access tokens need to be passed in the header (pre-shared secret) instead of using OpenID Connect.
