### ISSUE TITLE
Enable resolving the registry URI for a resource

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#103]
@leolara @science 
As part of the registry spec, we have documented that URIs like the following will be resolvable in the registry:
http://credentialengineregistry.org/resources/ce-14525AEA-57C5-4F5A-8F1C-BDC95C7F8B9C
For the current lr-staging server, the URI would be:
http://lr-staging.learningtapestry.com/resources/ce-14525AEA-57C5-4F5A-8F1C-BDC95C7F8B9C

Code needs to be added to resolve a URI like the latter to the applicable entry in the registry.

**Comment by leolara** [comment]
@cwd-mparsons I am not sure what you mean?

http://lr-staging.learningtapestry.com/resources/ce-14525AEA-57C5-4F5A-8F1C-BDC95C7F8B9C

urls don't work?

**Comment by cwd-mparsons** [comment]
@leolara 
The referenced url (above) doesn't work.
I have been checking a few more, and have found that they do work, for example:
http://lr-staging.learningtapestry.com/resources/ce-82CBFD02-8CD0-4D2F-8A74-65E28AFD99BF

The latter is a credential. 
However, I noticed that the ones in issue are non-credentials like assessments.
I need to update the schema to include CTID for assessments, orgs, and learning opportunities. 
So I am closing this issue.
