### ISSUE TITLE
Add our SSH keys and disable password login on servers

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#104]

**Comment by leolara** [comment]
@leolara ssh key:

```ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkVQBPLH4znBRrv4v1XWRGlJuwOl4ROSnJ1AzG1+3NQnq6yyVf3tt64ADimKuRjzEQ+79K9HejLD55Il5u4Kze8FyF8dzocecnNqZvJtT574gpWmKJfXIzRW8zzttzyObzTPvP2gz2T6W1Ae4RnI3IIe/hNkl48KE+1XOLiwZsB3lQ2qCyuPIX5ZUke6vi0rSgACKSKxYBia+6z4SbUVspYeQjGl4cY6zXQM4RBw1j7MMZRol03I8TmySRWr7kRcnmIdZaQqcazpqIdYfl0QgpKvZJCbL08dqjMAY7L302RO1Twy66YLx96o7oglsA3m2qQYhHN7dZ23fVWoCuehWWB1nDCGKmt8UyTt85ug4bGm56fZTSNbUKe9qdv7w9PVpCwgSsutVBYgtkMYiLw2B+42+EleNlTLPBZw2mwkbji56E7R6fHrqf4D0Tl1zc3tuzxbDkJMxVykhNzsbjUMts5CN4xVJ+jBsTji6Gdtmfk/CeJg+WSdRXN79Hcyj0GvrF9d1xRTnkkZp0vgMkTRKXny8DC1MuLabIpnhRmxeW6GfWZl58yMs3CAVxpsEHHpLgF0GXDcPCotP8zTbvx5ABWw3FQUTN+L/aZuv18Cc3h2ylaCWF26KqQbLc5RvXmQLmSNADc6DSJqrGr03RLz9We+mQuVGhBX5hPGw3iuC5FQ== leo@Leos-MacBook-Pro.local```

@coffeejunk : 

```ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBsrezqZaK26EcKdOFvVaHkQwjs5pOuwIJhe/7xKX5yunHn+i1Gil5IAk7jfExxCEfxR3JbdiJTXptnH64lB5AZu9gJqoJDrRCslNkuuwMFksPHhYYvVROPVAkV9km22saIXrLZY5YVjwl7Vy7K+eH10aW2svjgjMT84UDe26pANOIpUCzFkoKf64NPFTKyRFAtzXAC810c4qrUp1swVNaVevBaog54HXacNXLa7vRffO5QKXhTDvaNl1sLmOZp1GWO+oEaJbMIdIVNltGMFz+zf0AgdAsSSlTBldEg9vPwcfN00AapU661WPL8O1dfCZjazpqqkGmyjuLrtavCr4B```

**Comment by leolara** [comment]
Servers:

| Internal IP        | Public IP          | Host name  |
| ------------- |:-------------:| :-----:|
| 
172.22.152.13      | 207.68.194.46 | cerSandbox |
| 172.22.152.16      | 207.68.193.48 | cerStaging  |
| 172.22.152.17 | 207.68.193.47 | cerProduction |

**Comment by coffeejunk** [comment]
- [x] cerSandbox
- [ ] cerStaging
- [ ] cerProduction
