### ISSUE TITLE
Update validation for CostManifest and ConditionManifest

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#106]
These need to be top-level entities, externally referenceable just like assessments, learning opportunities, etc.  They will need to be published independently of the organizations that manage them.

Tasks:
- Add ConditionManifest to JSON schema validation
- Add ConditionManifest to publishing process (separate from its owning org)
- Add CostManifest to JSON schema validation
- Add CostManifest to publishing process (separate from its owning org)

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara 
Both of these schemas exist in github:
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/Schema-2017-04-28

I need to create some test cases, and upload these - in the next few days.

**Comment by leolara** [comment]
@coffeejunk does this need coding or just adding the new schemas and test jsons will do?

**Comment by coffeejunk** [comment]
@leolara if the `ConditionManifest` and `CostManifest` are just data added to the existing json blobs than this should only require an update of the schemas.

**Comment by siuc-nate** [comment]
You can see the schema for any class in CTDL with this:
http://credreg.net/ctdl/schema/validation/ConditionManifest/json?asGroup=true
CostManifest isn't in there yet but will be with the upcoming release of CTDL. The ?asGroup=true part doesn't do anything in this case, but if we ever did add something to the "group" of ConditionManifest, it would.

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara 
I updated the schemas and test cases, and ensure the folder names were appropriate based on the #readme instructions :+1: https://github.com/CredentialEngine/CTDL_Json_Validation_Schema
Schemas:
![image](https://user-images.githubusercontent.com/26332112/27647054-fdd2b22a-5bef-11e7-97b9-82a2ad35a4de.png)

I added test cases. I understand that whenever a schema changes, a process will be initiated to run the test cases against the schemas in github. I am not sure where I go to check the results. As before, I thought there was a notification email. Last time, Max eventually provided a link to me, but I don't see where to check the results at this time.

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara 
NEVERMIND - I did find the link.

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara
The last set of test cases were all successful. Can the registry now be updated with the current schemas from github?

**Comment by coffeejunk** [comment]
@cwd-mparsons the schemas have been updated

**Comment by leolara** [comment]
@cwd-mparsons Ok, I close this issue. Reopen it if there is any problem

**Comment by cwd-mparsons** [comment]
@coffeejunk I just tried to publish a conditonProfile and get the following error:

{"errors":["Cannot load json-schema. The property '@type' has an invalid value 'ceterms:ConditionManifest'"]}
attached is the payload file.

[2017-06-30_ConditionManifest_6_payload_failed.txt](https://github.com/CredentialEngine/CredentialRegistry/files/1116229/2017-06-30_ConditionManifest_6_payload_failed.txt)

**Comment by cwd-mparsons** [comment]
@coffeejunk 
I also get a similar error when publishing a costManifest

Cannot load json-schema. The property '@type' has an invalid value 'ceterms:CostManifest'

Payload file:
[2017-06-30_CostManifest_2_payload_failed.txt](https://github.com/CredentialEngine/CredentialRegistry/files/1116234/2017-06-30_CostManifest_2_payload_failed.txt)

**Comment by leolara** [comment]
@coffeejunk please have a look at this

**Comment by coffeejunk** [comment]
@cwd-mparsons sorry about that. I didn't add the necessary configuration for the new schemas. A fix is deployed and I was able to publish your sample: http://lr-staging.learningtapestry.com/ce-registry/envelopes/e52123dd-39db-4b63-bcde-87e98318df42

**Comment by leolara** [comment]
I close this as this is solved
