### ISSUE TITLE
Update validation to allow for a pointer class

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#107]
As discussed toward the end of https://github.com/CredentialEngine/vocabularies/issues/394 the validation will need to allow for either a `{ "@id": "[URI]" }` structure or a minimal object as a pointer for things that do not have records in the registry with these properties:
- name
- description
- subjectWebpage
- socialMedia
- sameAs

See also #37

**Comment by stuartasutton** [comment]
@siuc-nate, please confirm that this "pointer class" is an issue local to the CER and does not affect the CTDL. I'm uncertain as to this matter because there's a lot of discussion bouncing across multiple girhub issues :-(

**Comment by leolara** [comment]
@stuartasutton  I think this is a JSON schema creation issue. This could be allowed in the JSON schema without changing the actual CTDL

**Comment by leolara** [comment]
I close this as it seems my answer was enough

**Comment by siuc-nate** [comment]
@stuartasutton we haven't discussed this in a while, but the current approach is to use an object of the correct type (e.g. ceterms:CredentialOrganization) with the properties listed in the first post and specifically _without_ an `@id` property so as to make it clear that the data is meant to be a pointer to something rather than an actual record.

**Comment by stuartasutton** [comment]
@siuc-nate, when you say an object of the correct type "without an @id property", you are saying in RDF-speak, a bNode (blank node). Yes, that was my understanding. To flesh that out so we can be sure what we mean. let's assume we have a degree in engineering that has been accredited by the Accreditation Board for Engineering and Technology (ABET). The degree is described in a record in the registry and ABET is not so described. 

If ABET did have such a record in the registry, we could then make an accreditation statement that looks like this (Turtle):

### Case 1
```
@prefix ceterms: <http://purl.org/ctdl/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://credentialEngineRegistry.org/resources/CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC> a ceterms:BachelorDegree ;
    ceterms:ctid "CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC" ;
    ceterms:name "Bachelors in Electrical Engineering"@en-US ;
    ceterms:accreditedBy <http://credentialEngineregistry.org/resources/ce-78efdf49-3473-4068-a023-fc9c12451bb4> .
```

Now, in the wild, we could also use a URI for ABET found in another repository -- e.g., an ABET rdf record in Wikidata. That would look just like the code above but with a Wikidata URI:

### Case 2
```
@prefix ceterms: <http://purl.org/ctdl/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://credentialEngineRegistry.org/resources/CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC> a ceterms:BachelorDegree ;
    ceterms:ctid "CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC" ;
    ceterms:name "Bachelors in Electrical Engineering"@en-US ;
    ceterms:accreditedBy <https://www.wikidata.org/entity/Q4650304> .
```

Now, again in the wild and in the absence of any URI identifying ABET, the degree description could create a **blank node** of the right type (`ceterms:QACredentialOrganization`) and give just enough descriptive data so someone would know who the accreditor is. E.g.:

### Case 3
```
@prefix ceterms: <http://purl.org/ctdl/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://credentialEngineRegistry.org/resources/CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC> a ceterms:BachelorDegree ;
    ceterms:ctid "CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC" ;
    ceterms:name "Bachelors in Electrical Engineering"@en-US ;
    ceterms:accreditedBy [ a ceterms:QACredentialOrganization ;
        ceterms:name "Accreditation Board for Engineering and Technology (ABET)"@en-US ;
        ceterms:subjectWebpage <http://www.abet.org/accreditation/> ] .
```

I believe what you are referring, @siuc-nate, to what happens with Case 3. 

Case 2 isn't part of the discussion or problem here...but is a perfectly valid solution to the ABET identity problem in the wild.

**Comment by siuc-nate** [comment]
That sounds about right, yes.

**Comment by leolara** [comment]
@siuc-nate @stuartasutton I think having records without an ID would be problematic, what is the use of it if you cannot find it, or knowing if there are duplicates?

@coffeejunk what do you think?

**Comment by leolara** [comment]
@science ??

**Comment by stuartasutton** [comment]
@leolara, use of blank nodes in this manner is standard fare in RDF and expressible in jsonld:

```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "http://credentialEngineRegistry.org/resources/CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC",
      "@type": "ceterms:BachelorDegree",
      "ceterms:accreditedBy": {
        "@id": "_:ub139bL9C26"
      },
      "ceterms:ctid": "CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC",
      "ceterms:name": {
        "@language": "en-US",
        "@value": "Bachelors in Electrical Engineering"
      }
    },  
    {
      "@id": "_:ub139bL9C26",
      "@type": "ceterms:QACredentialOrganization",
      "ceterms:name": {
        "@language": "en-US",
        "@value": "Accreditation Board for Engineering and Technology (ABET)"
      },
      "ceterms:subjectWebpage": {
        "@id": "http://www.abet.org/accreditation/"
      }
    }
  ]
}
```
You are correct that it cannot be "found" except in the context of the graph in which it is defined.  **That is exactly the intended result.** In this sense, it is no different from expressing an address of someplace as a bnode filled with informing text instead of as a resource (e.g., a place identified by URI from GeoNames).  

Of course, if the Accreditation Board for Engineering and Technology (ABET) had a record in the CER, then it should be used (or some URI identifying the Board). But that's not always the case. When there is nothing to reference by URI, then use of a bnode **of the correct class** is perfectly appropriate.

**Comment by siuc-nate** [comment]
It should be clarified that these wouldn't be standalone records - they would be embedded within the JSON document of the entity that is pointing to them.

For example:
Credential -> requires -> Assessment

If the assessment doesn't exist in the CER as a standalone thing, then the "pointer" object that refers to the assessment would be embedded in the JSON for the credential.  So there would be no separate record for the assessment in that case (unless/until one was created normally).
