### ISSUE TITLE
Design and test process for registry to manage public/private key pairs

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#108]
@science @leolara 
I am creating this issue to track the progress of the keys management by the registry. 
I created a place holder google doc, for this topic. 
https://docs.google.com/document/d/1426xOxJyxKFni76Gky3yaigNPykLlar8HBhULnsfTpE/edit
 
Summary
A popular publishing model is one where the registry manages the public/private key pairs. This feature will be dependent on the implementation of account management. The two main use cases are:
- a partner is doing direct publishing to the registry, and doesn't want to have to manage the keys. Related would be the ability to share the account with other parties. So the other party would not have to have physical access to the keys. 
- a partner prefers to use the a helper (registry assistant - RA) API to publish to the registry. In this case, the partner sends credential data to the API, the RA validates, and formats the resource, then publishes to the registry. The API will have to authenticate as the partner, and have the registry use the proper keys.

**Comment by leolara** [comment]
@cwd-mparsons 

I created a detailed design document here:

https://docs.google.com/document/d/1LcZD8dJXeDnOrYtdrEZ6Dq3820mi2P0FUZNJL6Jd-Dg/edit#heading=h.9eb1b9xngsnr

This task is the first step towards this:

https://github.com/CredentialEngine/CredentialRegistry/issues/100

**Comment by leolara** [comment]
@cwd-mparsons I think I should close this, as we are taking care of this as part of the overall design I attached here
