### ISSUE TITLE
The remote name could not be resolved: 'lr-staging.learningtapestry.com'

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#109]
@leolara @coffeejunk 
It seems that the first time the registry API is called in a day, or perhaps after a long period of inactivity, the service returns with the error:
The remote name could not be resolved: 'lr-staging.learningtapestry.com'

If I immediately request another publish request, the server will be found, and barring metadata errors, the publish will be successful.

**Comment by coffeejunk** [comment]
This sounds like a problem with your DNS to me. Unless I'm misunderstanding something here, none of the CR servers should be hit for name resolution.

**Comment by leolara** [comment]
What @coffeejunk says makes sense to me. How is the client written @cwd-mparsons ?

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
The key point is that I only get this error the first time I call the service on any given day. 
Whenever I encounter this error, I immediately re-issue the same request and it works fine. 
I have run batch jobs that issue tens or hundreds of requests, and have no issues - other than the first request.

**Comment by coffeejunk** [comment]
To me that sounds like a DNS caching issue/race condition: Something in your DNS resolution path is reporting a false negative and something else is going on finding the actual record. On the second attempt whatever was reporting the failure is now finding what it is looking for. Or something along those lines..

I'm unsure what we could do from our end (the server/setup) to help with this :/

**Comment by leolara** [comment]
@cwd-mparsons If your client library is reporting a DNS problem I cannot see how CredReg code can be involved. DNS resolution has to be done before calling the API, so the API cannot be involved in DNS resolution

**Comment by leolara** [comment]
@cwd-mparsons I am closing this, as you have not said anything I guess it is solved. Feel free to reopen it if there any any further problems
