### ISSUE TITLE
Services: Feature to mark up envelop containing invalid supplemental URLs

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#111]
Per the May 26th, 2017 TAC
A link checker will be developed to periodically check existing URLs, and confirm if still valid. 
If a **canonical** URL (i.e. the subject webpage) is no longer valid, the owner is notified, and the resource is set inactive. (Link checker will provide notification several times to the publisher via the contact information provided by the publisher).

**ACTION**
For **supplemental** URLs (most URLs other than the subject webpage), the resource will stay active. 

If there is no response after set period, the link checker will annotate the resource's envelope to indicate that certain fields in the resource are expired, such as an array of field names that may be expired.
It will also augment the raw CTDL resource metadata when consumers access APIs that don't return envelopes. 

What form will this annotation take?

**Comment by leolara** [comment]
@cwd-mparsons @science why not making this metadata part of CTDL?

**Comment by leolara** [comment]
If that is not a possibility perhaps we can add a "user metadata" field to the envelope for these cases.

**Comment by cwd-mparsons** [comment]
@leolara @science 
For your first post, the messages are returned to the user, and should not be part of CTDL. 
To your second post, it appears that part of the solution would be to have a common field for messages, whether regarding errors, or warnings. The user would then know that part of the workflow will be to check for messages.

**Comment by leolara** [comment]
@cwd-mparsons I like that approach having a list of warnings in the envelope. We can conside these errors as a higher level validation than the JSON schema, that produce warnings but do not prevent the record for being in the registry.

**Comment by edgarf** [comment]
@jeannekitchens - we are closing it now, since the information in this issue is out-dated, once we get to Currency Policy feature, we will have a new task opened.
