### ISSUE TITLE
Services: Feature to mark up envelopes containing URI for a deleted resource

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#112]
If any top-level resource such as credential, assessment, organization, learning opportunity, or manifest, is deleted, there may be resources left with bad data - that is with references to deleted resources.
A possible solution could be similar to the actions for handling supplemental URLs that are no longer valid (#111 ). The registry could:

- search for references to the deleted resource
- mark up the envelope in some fashion with messages indicating the resource that is no longer valid
- thus consumers of these marked up resources can be informed of incorrect data

Another POSSIBLE action, could be to notify owners of resources that refer to now defunct resources. These owners could then take action at the earliest opportunity to ensure the accuracy of their resources.

**Comment by leolara** [comment]
@cwd-mparsons @science we risk re-implementing relational DBs on top of the metadata registry if we go by this line. Cannot we assume that the information in the registry might be incomplete and that will be completed in the future?

**Comment by leolara** [comment]
@cwd-mparsons @science any ideas?

**Comment by siuc-nate** [comment]
I think what Mike was suggesting is that we use some property on the envelope to indicate when something in that envelope's payload is invalid or no longer available.  In the example he gave (if I understand correctly), the envelopes for the resources that were not deleted would be marked up with some indication that their payloads reference a resource that was deleted.

This keeps the data confined to the envelopes and should hopefully avoid creating a relational model (unless I misunderstand what you mean by that).

**Comment by cwd-mparsons** [comment]
@leolara This is a data quality concern. The organization that references an entity that no longer exists in the registry would not know that their data now contains inaccurate information. Nor would anyone consuming the information, via the registry envelope. 
**Notification**
From the credential owner's perspective, it would be useful to have a process to be notified when an action occurs that affects the accuracy of their credential. If the only registry action is notification, then responsibility for the accuracy of the data becomes the credential owner, which is good. 
If this owner does not update their data, then any consumers could be downloading bad data. 

If credential owners are responsible and respond quickly to data quality notifications, then there would be minimal impact on new consumers of their data. 

So, we have to consider whether it is too difficult, or not really appropriate to try to mark up envelopes with helpful messages regarding changes that affected the current credential. At the very least, I think a notification process will be important.
