### ISSUE TITLE
Registry search - will it be possible to combine a full text search with a named property

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#114]
As I understand, the full text search is only applicable by itself, not with a named property. So the following will find the phrase accounting anywhere in the registry:
http://lr-staging.learningtapestry.com/ce-registry/search?fts=Accounting

If person wants a specific resource by name, they would have to enter the exact proper name
http://lr-staging.learningtapestry.com/ce-registry/search?ceterms:name=Name of the credential
This would complicate searches for competencies, for example.

Will it be possible to use a full text search by property? 
This would be equivalent to LIKE in sql server. http://lr-staging.learningtapestry.com/ce-registry/search?ceterms:name like "Name%"

**Comment by leolara** [comment]
@coffeejunk what do you think?

**Comment by coffeejunk** [comment]
If I'm reading the code and documentation correctly, this is not possible at the moment but I think it would make sense to add full text/fuzzy search for named properties.

```
/ce-registry/search?ceterms:name=%2AName%2A <- *Name*
/ce-registry/search?ceterms:name=%25Name%25 <- %Name%
```

**Comment by leolara** [comment]
@coffeejunk @cwd-mparsons I created this https://github.com/CredentialEngine/CredentialRegistry/issues/122 and put it in the backlog. I think we should focus on the authentication and automatic singing first

**Comment by leolara** [comment]
Close because #122 should solve this
