### ISSUE TITLE
Issues with the full text search

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#115]
I entered the following search query, to do an fts on ceterms:Competency:
http://lr-staging.learningtapestry.com/ce-registry/search?fts=ceterms%3ACompetency

I get results back for organizations that do not have competencies. One example:
http://lr-staging.learningtapestry.com/resources/186fbc60-47e3-4616-b160-72cac9e78f54

As well I get other results that do not have ceterms:Competency, but do have ceterms:targetCompetency.
I also tried:
http://lr-staging.learningtapestry.com/ce-registry/search?fts=ceterms%3AtargetCompetency
and again gets many results without an reference to the latter text.

**Comment by leolara** [comment]
@coffeejunk please have a look at this. If the search is not fully documented or the documentation is old/wrong I think it would be a good idea to fix the docs.

**Comment by siuc-nate** [comment]
In the first case, do the results have the word "competency" (or some permutation thereof) anywhere in them? The full text search is probably reading the : as a dividing character and looking for "ceterms" and "competency"

In the second case, you would get targetCompetency because the only "ceterms:Competency" we have is an unused placeholder class with no properties.

**Comment by siuc-nate** [comment]
While we're at it, is there a way to include the total number of search results in the response data?  The response itself is just the array of search results with no wrapping object.

**Comment by coffeejunk** [comment]
@cwd-mparsons Doing a fts will only search through the values of [`ceterms:name`, `ceterms:description` (see config)](https://github.com/CredentialEngine/CredentialRegistry/blob/master/fixtures/configs/ce_registry.json#L49-L83) so your query `ce-registry/search?fts=ceterms%3ACompetency` will look for `ceterms:Competency` in the name and description. If you'd want to add other fields (such as `ceterms:Competency`) we'd have to add them to the configuration. The fts does Trigram matching which I think is why it's returning resources that seem unrelated.

That being said, unless I'm mistaking [`ceterms:Competency` doesn't seem to be defined anywhere in the CTDL Schema](https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/search?utf8=%E2%9C%93&q=ceterms%3ACompetency&type=)?

**Comment by coffeejunk** [comment]
@siuc-nate meta information such as the [number of results is returned in the HTTP Headers](https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/07_search.md#pagination)

**Comment by leolara** [comment]
@siuc-nate any info?

**Comment by siuc-nate** [comment]
@coffeejunk Competency is one of a few placeholder classes in CTDL we use for some schema-related things but we don't use in actual production, so there aren't any properties defined for it, nor should it show up in the validation JSON for the registry.

@leolara This would be more of a question for @cwd-mparsons as he is the one who started the thread. If it's something that we can configure then it's probably not an issue.

**Comment by cwd-mparsons** [comment]
Additional properties for fts
SubjectWebpage (all)


As well, currently there is no fts entries for conditionManifest or costManifest. These should both have name, description, and subject webpage.

**Comment by leolara** [comment]
@coffeejunk got it?

**Comment by cwd-mparsons** [comment]
@jbaird123 Could we get an update on the progress of this task.

**Comment by jbaird123** [comment]
@cwd-mparsons - I think this is nearly ready.  I just need to connect with @excelsior to confirm.

I'll let you know for sure shortly...

**Comment by jbaird123** [comment]
@cwd-mparsons - Please review the latest functionality and let me know if we can close this.
