### ISSUE TITLE
Getting resources by CTID fails for some resources

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#118]
For some resources, trying to get a record by its CTID fails.  For example:

http://lr-staging.learningtapestry.com/resources/ce-fcb90ae2-fa79-48f1-addf-062bd2c98985
and
http://lr-staging.learningtapestry.com/ce-registry/ce-fcb90ae2-fa79-48f1-addf-062bd2c98985
give 404s.  The structure of these 404s is also different, which may deserve its own issue (but is beside the point for now).
The record, however, does exist:
http://lr-staging.learningtapestry.com/ce-registry/envelopes/2577e5cd-c5da-49ea-a5e4-ca339ea0efd5
Note the CTID in that envelope's resource matches the CTID provided in the above links.

However, other resources _can_ be retrieved by CTID:
http://lr-staging.learningtapestry.com/resources/ce-AB30C9E1-F9E5-4C42-A2B9-CE004DD6DA2E
works, however
http://lr-staging.learningtapestry.com/ce-registry/ce-AB30C9E1-F9E5-4C42-A2B9-CE004DD6DA2E
fails

Additionally, using the search API endpoint does find it when the get endpoint fails:
http://lr-staging.learningtapestry.com/ce-registry/search?ceterms%3Actid=ce-fcb90ae2-fa79-48f1-addf-062bd2c98985

@science @cwd-mparsons Thoughts?

**Comment by siuc-nate** [comment]
Edit: apparently, the CTID does not match - there seems to be an error in workit. 

Disregard for now.

**Comment by siuc-nate** [comment]
I feel like the system is determined to make a liar out of me - but the issue presented is apparently real after all.

**Comment by leolara** [comment]
@coffeejunk I think this might be caused by the latest changes on CTID structure and perhaps the configuration do not have the new prefix or something

**Comment by coffeejunk** [comment]
`http://lr-staging.learningtapestry.com/ce-registry/ce-AB30C9E1-F9E5-4C42-A2B9-CE004DD6DA2E` is not a valid URL as `/resources` is missing from the path. The URL would have to be `http://lr-staging.learningtapestry.com/ce-registry/resources/ce-AB30C9E1-F9E5-4C42-A2B9-CE004DD6DA2E` or optionally with omitted community `http://lr-staging.learningtapestry.com/resources/ce-AB30C9E1-F9E5-4C42-A2B9-CE004DD6DA2E` 

However in addition to this, the domain in the `@id` of the [resource in question](http://lr-staging.learningtapestry.com/ce-registry/envelopes/2577e5cd-c5da-49ea-a5e4-ca339ea0efd5) deviates from the configuration:

```
"@id": "http://credentialEngineRegistry.org/resources/ce-fcb90ae2-fa79-48f1-addf-062bd2c98985"
```

and the configuration states 

```
"id_prefix": "http://credentialengine.org/resources/"
```

As such the retrieval for this particular resource will only work via the envelope.

If the desired domain is `credentialEngineRegistry.org` instead of `credentialengine.org` we can change the configuration. Alternatively we could add the option for multiple domain names for a community.

**Comment by stuartasutton** [comment]
Mulltiple domain names for a community seems unwise.

**Comment by siuc-nate** [comment]
My understanding was that ce-registry was the actual name of the community and that resources/ was just a wrapper of sorts to facilitate our particular use case of retrieval by CTID.  So I thought that using ce-registry would/should work too (since another community name could be used in its place).

What would the correct URL structure be to get back a resource with some specific community name?

**Comment by coffeejunk** [comment]
You can omit the community and just use `/resources` which will use the default community (`ce-registry`). So

- `/ce-registry/resources/ce-AB30C9E1-F9E5-4C42-A2B9-CE004DD6DA2E`
- `resources/ce-AB30C9E1-F9E5-4C42-A2B9-CE004DD6DA2E`

are both fine. For other communities it would have to be:

- `/$community_name/resources/ce-AB30C9E1-F9E5-4C42-A2B9-CE004DD6DA2E`

**Comment by leolara** [comment]
@stuartasutton we have not decided to have several domain names, it seems at some point in development we were using credentialengine.org and now the tests are being done with credentialEngineRegistry.org this "confuses" the engine, because it is configured for credentialengine.org.

@siuc-nate We should settle on which domain we are doing the tests with.

**Comment by siuc-nate** [comment]
What is the status of this?  Our partners need to be able to retrieve data by CTID.

**Comment by coffeejunk** [comment]
Retrieval by CTID is possible but has to happen under the right domain and path. 

We would need to know if the domain (prefix) should be changed to `credentialEngineRegistry.org`?

**Comment by siuc-nate** [comment]
When the registry API receives a request in the form of `/resources/[ctid]`, shouldn't it look to see if any record matches that CTID and return it if so? I don't see why the domain should be relevant to a simple ID based lookup like that.

Is it getting the records by their `@id` rather than their `ceterms:ctid` property?

**Comment by cwd-mparsons** [comment]
The API needs to function based on the current environment. For the current (sandbox) environment, the following should be resolvable:
@id: "http://lr-staging.learningtapestry.com/resources/ce-587b9648-bc0a-4161-8972-e7be1378edcc"

We will eventually have CER domains for all of sandbox, staging, and production. Each should be able to resolve:
Sandbox
http://sandbox.credentialEngineRegistry.org/resources/ce-587b9648-bc0a-4161-8972-e7be1378edcc
OR staging
http://staging.credentialEngineRegistry.org/resources/ce-587b9648-bc0a-4161-8972-e7be1378edcc
OR production
http://credentialEngineRegistry.org/resources/ce-587b9648-bc0a-4161-8972-e7be1378edcc
http://www.credentialEngineRegistry.org/resources/ce-587b9648-bc0a-4161-8972-e7be1378edcc

**Comment by leolara** [comment]
@cwd-mparsons I think currently it is configured to work with http://www.credentialngineregistry.org/ or something like that for all deployments, this is, the ```@id``` is not forced by the system to start by the host name of the server.

The @id matches a pattern {prefix}{ctid} and that prefix is configured per server and per community.

The good news is that we can configure it to work as you expected. @coffeejunk  ??

**Comment by leolara** [comment]
@cwd-mparsons , @coffeejunk have prepared a PR https://github.com/CredentialEngine/CredentialRegistry/pull/130 to change the prefix to ```http://credentialengineregistry.org/resources/```

in all deployments,

so 

staging.credentialengineregistry.org/resources/ce-ABC , sandbox.credentialengineregistry.org/resources/ce-ABC and credentialengineregistry.org/resources/ce-ABC itslef will have to have objects which @id : "http://credentialengineregistry.org/resources/ce-ABC"

@cwd-mparsons that does work for you?

**Comment by siuc-nate** [comment]
My expectation would be that 
`http://credentialengineregistry.org/resources/[some CTID]`
would be roughly the equivalent of
`http://credentialengineregistry.org/ce-registry/search?ceterms:ctid=[some CTID]`
where the most recent result is returned (not as an array).  In other words, the domain name should be irrelevant, and only the CTID should matter.

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
That approaches seems appropriate for domains using credentialEngineRegistry .
What about for the current test environment, that is: 
http://lr-staging.learningtapestry.com

**Comment by leolara** [comment]
@cwd-mparsons  our idea would be to set it to http://credentialengineregistry.org/resources/

staging is just a way of testing a different version of the registry. Anyway, we could change it and make it different per deployment, but I am not sure if that is necessary.

Regarding the search parameters, I think both ways of using /search should work eventually. I understand not all entities will have CTID? Or that has changed?

**Comment by siuc-nate** [comment]
@leolara All top-level entities (credentials, organizations, assessments, learning opportunities, and cost/condition manifests) have CTID - the thinking is that if it's something you should be able to look up directly (not as part of something else) then it needs a CTID.

**Comment by leolara** [comment]
@siuc-nate but then the root ```@id``` field has the same value as  ```ctid``` ?

**Comment by siuc-nate** [comment]
No, the CTID would still be just the identifier, and the `@id` would be the full URI.
```
{
   "ceterms:name": "My Certificate",
   "@type": "ceterms:Certificate",
   "@id": "http://credentialengineregistry.org/resources/ce-457bd99b-a9ee-4100-8237-2962a50f6029",
   "ceterms:ctid": "ce-457bd99b-a9ee-4100-8237-2962a50f6029"
}
```

What we're trying to suggest is that when the registry receives any request to the `/resources/` endpoint, that it then look for records by their `ctid` so that the domain name becomes irrelevant (as it should not matter).

For example:
1. Request is made to:
```
http://credentialengineregistry.org/resources/ce-457bd99b-a9ee-4100-8237-2962a50f6029
```
2. Server software only cares about the end part of the URL:
```
ce-457bd99b-a9ee-4100-8237-2962a50f602
```
3. Server software does a lookup for records that match that CTID
4. Server software returns the latest record for that CTID

Therefore, if a record like this exists in the registry, whether it's on lr-staging or credentialengineregistry.org or anywhere else:
```
{
   "ceterms:name": "My Certificate",
   "@type": "ceterms:Certificate",
   "@id": "http://someotherdomain.net/resources/ce-457bd99b-a9ee-4100-8237-2962a50f6029",
   "ceterms:ctid": "ce-457bd99b-a9ee-4100-8237-2962a50f6029"
}
```
and a request is made:
```
http://credentialengineregistry.org/resources/ce-457bd99b-a9ee-4100-8237-2962a50f6029
```
The server will **not** look for the `@id` of
```
http://credentialengineregistry.org/resources/ce-457bd99b-a9ee-4100-8237-2962a50f6029
```
but will instead look for the `ceterms:ctid` of
```
ce-457bd99b-a9ee-4100-8237-2962a50f6029
```
and find and return the record even though it has an `@id` with a different domain in it.

**Comment by leolara** [comment]
@siuc-nate 

This was already thought on previously, and I think we got to a good solution.

The domain name in the request is not being look up when using the request, only the part after the resource /resource/. Then there is a hard-coded "prefix" in the community that for example it could be http://credentialengineregistry.org/resources/ and then it concatenates with the part after resource.

For example:
Let's assume in staging.credentialengineregistry.org the configured id_prefix is http://credentialengineregistry.org/resources/

The for the request http://staging.credentialengineregistry.org/resources/ce-457bd99b-a9ee-4100-8237-2962a50f6029

will take the ce-457bd99b-a9ee-4100-8237-2962a50f6029 part and concatenate with http://credentialengineregistry.org/resources/ and search in the DB by @id="http://credentialengineregistry.org/resources/ce-457bd99b-a9ee-4100-8237-2962a50f6029".

This is how it is implemented now, and it is the most general way without making the field "ctid" special in the software.

If we want to implement it as you say, it would not be difficult, we basically would add a community configuration field saying which is the special ID field.

So configuring the community with:
id_prefix="" (empty string)
id_field="ceterms:ctid"

it would convert the request http://staging.credentialengineregistry.org/resources/ce-457bd99b-a9ee-4100-8237-2962a50f6029 into searching for ceterms:ctid="ce-457bd99b-a9ee-4100-8237-2962a50f6029"

It is all configurable, we can implement this, but I think the current implementation works for your need although it might be more confusing for the user.

**Comment by siuc-nate** [comment]
@leolara That's interesting, thanks.  Out of curiosity, why is the community prefix tied to the domain name? Wouldn't it make more sense to just map "/resources/" to "/ce-registry/" and leave the domain out of it altogether?

**Comment by leolara** [comment]
@siuc-nate If the prefix was set to "/ce-registry/" then the @id would have to be "/ce-registry/ce-457bd99b-a9ee-4100-8237-2962a50f6029"

Is that what you want?

The configuration prefix only affects how the @id is constructed for searching in the DB. So as long the @id s are stored with "{prefix}{ctid}" it will work. We just need to match the configuratioj prefix with the values you are giving to @id

**Comment by jbaird123** [comment]
@siuc-nate, @leolara - We will modify the search as suggested by @siuc-nate so that if you are performing a lookup based on ctid (instead of @id), the system will use the ceterms:ctid field instead of attempting to re-construct the @id based on the prefix specified in the config file.  We may also make it configurable as suggested by @leolara by using an "id_field" parameter in the config file.

**Comment by leolara** [comment]
@siuc-nate @jbaird123 Ok

**Comment by siuc-nate** [comment]
Is this still an outstanding issue? Partners are beginning to use the system, and it doesn't reflect well on us if they can't reliably do a simple ID based lookup.

**Comment by jbaird123** [comment]
@siuc-nate - We're finishing the changes and expect to have it ready today.

**Comment by jbaird123** [comment]
@siuc-nate - We still have some testing to do, but I believe this will work for your purposes:  http://lr-staging.learningtapestry.com/resources/ce-fcb90ae2-fa79-48f1-addf-062bd2c98985

Please let me know.
