### ISSUE TITLE
All tests fail with ' No schema defined for ...' after creating new schema folder for 2017-06-30

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#120]
@coffeejunk 
I created a new folder under Schema-2017-06-30. 
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/Schema-2017-06-30

I uploaded the schemas for June 30. I then changed the value of 'latest' to **Schema-2017-06-30**.
At first the auto tests all passed except for condition and cost manifests (which was expected). Then a new round of tests started, and they all failed with a message similar to the following:

>   16) JSON Schema Validation test_data/assessmentProfileSchema validates resources 2017-06-27_assessment_10_payload.txt
>       Failure/Error: expect(resource).to match_json_schema(schema_name)
>         No schema defined for assessmentProfileSchema. Available schemas are [].
>       ./spec/json_validation_spec.rb:26:in `block (6 levels) in <top (required)>'

I then changed the value of 'latest' back to Schema-2017-04-28. The auto tests were executed and these again all failed with errors like the one above.

> 1) JSON Schema Validation test_data/agentSchema validates resources 2017-06-28_organization_1079_payload.txt
>      Failure/Error: expect(resource).to match_json_schema(schema_name)
>        No schema defined for agentSchema. Available schemas are [].
>      ./spec/json_validation_spec.rb:26:in `block (6 levels) in <top (required)>'

**Comment by coffeejunk** [comment]
I'm not quite sure what, but something was wrong with your symbolic link from `latest -> Schema-2017-04-28`

`ls -l` showed a `?` character at the end of the target and my file system couldn't resolve the link:

<img width="551" alt="screenshot 2017-07-11 20 34 09" src="https://user-images.githubusercontent.com/205556/28084462-fdbb2d24-6678-11e7-97e5-4ca15f83c0d2.png">

I've updated the link to `Schema-2017-06-30` and [the tests are now running as they should](https://travis-ci.org/CredentialEngine/CTDL_Json_Validation_Schema/jobs/252526158).

**Comment by cwd-mparsons** [comment]
@coffeejunk That was a very strange error. Good that this has been resolved - thanks.

**Comment by leolara** [comment]
@coffeejunk @cwd-mparsons I am not quite in agreement with the symbolic link approach and it wasn't on the original design:

https://github.com/CredentialEngine/CredentialRegistry/issues/96

I think the best idea is to have latest as a folder, and work there like a development branch. Once a version is released the files are copied to to it's release folder, Schema-{date}.

I think this will be easier for people working on Windows.

**Comment by coffeejunk** [comment]
If we had a `latest` folder as well as a latest-release (`Schema-{date}`) folder, for which should the tests run? Or should we have tests for each of the releases as well as the "development" one?

A simple alternative to renaming and copying around files would be to keep the general structure as is however change the symbolic link `latest` to a text file that just contains the name of the name of latest released spec. Text files work across systems and right now we're just using the link for it's convenience.

I also feel like the development of new releases should in fact be done in a development branch of the repository - it seems unnecessary to re-invent git inside of git?

**Comment by leolara** [comment]
@coffeejunk 

My current position is that:

 1. The test should run in latest. All the changes will be tested as the editing of the files should be done in latest.
 2. The Schema-{date} are kind of snapshots for the convenience of users that just want the latest realease of the schema.

I see your point that we are kind of reinventing git inside git with this design. The point is that we are using the github page also as a convenient place for the users to find the released versions of the schema.

Perhaps a solution that mixes both, would be to have a README.md that links to a git tag that marks the release, and the link going inside the latest forlder, so if the person clicks on it goes to the schemas of that version. We can go this path if the people working on the schemas feels comfortable with git tags.

In this other design we would have:
 +  the schemas in a folder named Schemas. 
 + A git tag for each realease
 + in the README.md, for each release a link to the corresponding tag inside the folder Schemas.

**Comment by coffeejunk** [comment]
I think if we want to use GitHub as a way to give users access to the releases of the spec we should either user git tags or even better [GitHub releases (which work on top of tags)](https://help.github.com/articles/creating-releases/) as they show up under their specific release category on the project page:

<img width="1075" alt="screenshot 2017-07-17 12 38 13" src="https://user-images.githubusercontent.com/205556/28264858-2ea2c208-6aed-11e7-8ac8-a526c4ac071b.png">

which then gets a nice overview page such as this one:

<img width="1064" alt="screenshot 2017-07-17 13 01 38" src="https://user-images.githubusercontent.com/205556/28265454-1af01064-6af0-11e7-85bd-256e02b66b24.png">

This would make it pretty obvious which is the latest release without requiring a user to mentally parse the dates in a list of folder names.

**Comment by leolara** [comment]
@coffeejunk I like merging both thigns, what I said with github releases

**Comment by leolara** [comment]
Related #84

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
I think the concept of github releases will be a good one to pursue. I believe that I have not been using Github as intended. I had just been updating the schemas and test cases locally and then pushing without first considering whether I should be creating a branch. As noted the use of branches might result in confusion for travis.ci, as to where the proper target schemas and test cases reside. 
Actually, first should we consider closing this issue, and continue all additional discussions in #84 ?

**Comment by leolara** [comment]
Closed, we continue on #84
