### ISSUE TITLE
Allow searching for multiple values for the same field

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#121]
I created this query with the intent of showing all Credential types in the registry (please excuse the bulkiness of it):
http://lr-staging.learningtapestry.com/ce-registry/search?%40type=ceterms%3AApprenticeshipCertificate&%40type=ceterms%3AAssociateDegree&%40type=ceterms%3ABachelorDegree&%40type=ceterms%3ABadge&%40type=ceterms%3ACertificate&%40type=ceterms%3ACertification&%40type=ceterms%3ACredential&%40type=ceterms%3ADegree&%40type=ceterms%3ADigitalBadge&%40type=ceterms%3ADiploma&%40type=ceterms%3ADoctoralDegree&%40type=ceterms%3AGeneralEducationDevelopment&%40type=ceterms%3AJourneymanCertificate&%40type=ceterms%3ALicense&%40type=ceterms%3AMasterCertificate&%40type=ceterms%3AMasterDegree&%40type=ceterms%3AMicroCredential&%40type=ceterms%3AOpenBadge&%40type=ceterms%3AProfessionalDoctorate&%40type=ceterms%3AQualityAssuranceCredential&%40type=ceterms%3AResearchDoctorate&%40type=ceterms%3ASecondarySchoolDiploma&page=1&per_page=10

In its unencoded form, it looks like:
```
http://lr-staging.learningtapestry.com/ce-registry/search?@type=ceterms:ApprenticeshipCertificate&@type=ceterms:AssociateDegree&@type=ceterms:BachelorDegree&@type=ceterms:Badge&@type=ceterms:Certificate&@type=ceterms:Certification&@type=ceterms:Credential&@type=ceterms:Degree&@type=ceterms:DigitalBadge&@type=ceterms:Diploma&@type=ceterms:DoctoralDegree&@type=ceterms:GeneralEducationDevelopment&@type=ceterms:JourneymanCertificate&@type=ceterms:License&@type=ceterms:MasterCertificate&@type=ceterms:MasterDegree&@type=ceterms:MicroCredential&@type=ceterms:OpenBadge&@type=ceterms:ProfessionalDoctorate&@type=ceterms:QualityAssuranceCredential&@type=ceterms:ResearchDoctorate&@type=ceterms:SecondarySchoolDiploma&page=1&per_page=10
```

However, it returns 0 results. 

The problem appears to be tied to the last two items in the list: SecondarySchoolDiploma and ResearchDoctorate. Removing both of those items causes results to be returned (removing only one of them is not enough - you will still get 0 results):
http://lr-staging.learningtapestry.com/ce-registry/search?%40type=ceterms%3AApprenticeshipCertificate&%40type=ceterms%3AAssociateDegree&%40type=ceterms%3ABachelorDegree&%40type=ceterms%3ABadge&%40type=ceterms%3ACertificate&%40type=ceterms%3ACertification&%40type=ceterms%3ACredential&%40type=ceterms%3ADegree&%40type=ceterms%3ADigitalBadge&%40type=ceterms%3ADiploma&%40type=ceterms%3ADoctoralDegree&%40type=ceterms%3AGeneralEducationDevelopment&%40type=ceterms%3AJourneymanCertificate&%40type=ceterms%3ALicense&%40type=ceterms%3AMasterCertificate&%40type=ceterms%3AMasterDegree&%40type=ceterms%3AMicroCredential&%40type=ceterms%3AOpenBadge&%40type=ceterms%3AProfessionalDoctorate&%40type=ceterms%3AQualityAssuranceCredential&page=1&per_page=10
```
http://lr-staging.learningtapestry.com/ce-registry/search?@type=ceterms:ApprenticeshipCertificate&@type=ceterms:AssociateDegree&@type=ceterms:BachelorDegree&@type=ceterms:Badge&@type=ceterms:Certificate&@type=ceterms:Certification&@type=ceterms:Credential&@type=ceterms:Degree&@type=ceterms:DigitalBadge&@type=ceterms:Diploma&@type=ceterms:DoctoralDegree&@type=ceterms:GeneralEducationDevelopment&@type=ceterms:JourneymanCertificate&@type=ceterms:License&@type=ceterms:MasterCertificate&@type=ceterms:MasterDegree&@type=ceterms:MicroCredential&@type=ceterms:OpenBadge&@type=ceterms:ProfessionalDoctorate&@type=ceterms:QualityAssuranceCredential&page=1&per_page=10
```

Searching just for those two items returns no results (which may be accurate; I'm not sure if there are any records in the registry for either of them):
http://lr-staging.learningtapestry.com/ce-registry/search?%40type=ceterms%3ASecondarySchoolDiploma&page=1&per_page=10
http://lr-staging.learningtapestry.com/ce-registry/search?%40type=ceterms%3AResearchDoctorate&page=1&per_page=10

But for some reason, including those items in the query, no matter what else is included, causes 0 results to be returned. Here I have removed a random selection of other items (to ensure it wasn't simply a problem of too many things being a part of the query):
http://lr-staging.learningtapestry.com/ce-registry/search?%40type=ceterms%3AAssociateDegree&%40type=ceterms%3ABachelorDegree&%40type=ceterms%3ACertificate&%40type=ceterms%3ACertification&%40type=ceterms%3ADegree&%40type=ceterms%3ADiploma&%40type=ceterms%3AGeneralEducationDevelopment&%40type=ceterms%3AJourneymanCertificate&%40type=ceterms%3AMasterCertificate&%40type=ceterms%3AMasterDegree&%40type=ceterms%3AOpenBadge&%40type=ceterms%3AProfessionalDoctorate&%40type=ceterms%3AResearchDoctorate&%40type=ceterms%3ASecondarySchoolDiploma&page=1&per_page=10
It still returns 0 results unless you remove the last two items.

Any ideas?

**Comment by siuc-nate** [comment]
Similarly, for organizations:
Credential and QA fails:
http://lr-staging.learningtapestry.com/ce-registry/search?%40type=ceterms%3ACredentialOrganization&%40type=ceterms%3AQACredentialOrganization&page=1&per_page=10

QA alone fails:
http://lr-staging.learningtapestry.com/ce-registry/search?%40type=ceterms%3AQACredentialOrganization&page=1&per_page=10

Credential alone works:
http://lr-staging.learningtapestry.com/ce-registry/search?%40type=ceterms%3ACredentialOrganization&page=1&per_page=10

Since the queries seem to be of the "x OR y OR z" nature (rather than ANDs), it seems odd that if one of those returns nothing, the entire query returns nothing.

**Comment by siuc-nate** [comment]
On further inspection, it appears that it just looks for whatever the last item in the list is - I hadn't noticed that all of the results for the functional query in the first post happened to all be QualityAssuranceCredentials.

Is there a way to do ORs with this type of query?

**Comment by leolara** [comment]
@coffeejunk please have a look at this

**Comment by coffeejunk** [comment]
Listing several terms under the same key individually doesn't work as the last one overwrites the prior in the deserialization process

```
type=A&type=B 

=> 

type: B
```

**Comment by coffeejunk** [comment]
While it's possible to list multiple values as json:

```
/search?@type=["ceterms:CredentialOrganization","ceterms:QACredentialOrganization"]
```

the API currently doesn't know how to handle this and as such tries to match the entire array against the field which obviously doesn't yield any results.

If matching multiple values is desired (which I think it would/should be) we'll have to make changes to the code behind the search API.

**Comment by siuc-nate** [comment]
We do need these changes - and a way to specify AND vs OR searches when multiple values are provided for the same field.

**Comment by siuc-nate** [comment]
In our call on 8/17/2017, @science  suggested http://graphql.org/ as one possibility.  It looks interesting and perhaps worth exploring, though I worry that maintaining the configuration as the schema evolves could be cumbersome, and it isn't clear from reading through the guidance how to specify and vs or in the queries themselves.

**Comment by leolara** [comment]
@siuc-nate I see the search engine is not working for your needs and needs an overhaul from this and other issues about the search.

My suggestion is that we implement the Authentication/auto-signature and then we design the search engine from your actual requirements. That might be using GraphQL or REST, or both.

cc/ @science @jbaird123

**Comment by cwd-mparsons** [comment]
@jbaird123 Could we get an update on the progress of this task.

**Comment by jbaird123** [comment]
@cwd-mparsons - We are having internal discussions about it.  We need to evaluate a number of third party products (Neo4j and GraphQL are two examples), so this will take some time.  I'll let you know as soon as we start to gain traction on this one.

**Comment by cwd-mparsons** [comment]
Closing as covered under Gremlin search
