### ISSUE TITLE
Retrieving records is very slow

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#123]
http://credreg.net/registry/tableviewer This page enables retrieving records by CTID. Yesterday, it was very quick - but today, it is very slow. The same issue exists when trying to get records via the API directly.

Is something going on with the servers today, or did something happen overnight, that might cause the slowdown?

**Comment by coffeejunk** [comment]
@siuc-nate I've rolled back the last changes and retrieval should be fast again.

**Comment by siuc-nate** [comment]
It seems to have worked. Thanks.

Were the changes related to the issue of retrieving by CTID in a case-insensitive manner, or was it something else?

**Comment by coffeejunk** [comment]
Yes exactly, the case insensitive retrieval seems to create a lot of load in Postgres. Will have to investigate further.

**Comment by leolara** [comment]
@coffeejunk why closing? is it solved?

**Comment by coffeejunk** [comment]
@leolara The issue itself is fixed as I've rolled back the previous changes and the retrieval of resources is fast again. However the code (case-insensitive retrieval of resources) needs optimization.
