### ISSUE TITLE
Search API Guidance

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#126]
http://credreg.net/registry#search_api
http://credreg.net/registry/search
http://credreg.net/registry/tableviewer

The guidance and tools for the Registry search API need to be reviewed and checked for accuracy, problems, suggestions, etc.

Please take a look at these and let me know your thoughts.  We use these tools with our partners and they have helped us reveal some issues.

**Comment by leolara** [comment]
@siuc-nate I would propose to jump into this after the authentication and auto-signing
