### ISSUE TITLE
Storing Competency frameworks, and competencies in registry

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#134]
We are exploring storing competency frameworks and competencies in the registry.
The following google doc will be used to document the details regarding storing competencies in the registry. 
https://docs.google.com/document/d/1VyAlt8sMwU32EqF0xICLE4hCFBAoG1MOReTjLSGkC8Y/

The key points are:

- developing an API to allow publishing and searching/extracting competencies (documents and statements)
- using the CTDL-ASN schema: 
http://credreg.net/ctdl/frameworkschema
- maintenance of a separate validation schema for competencies

Overview of the registry services, including competencies
![image](https://user-images.githubusercontent.com/26332112/29330473-e3dfc624-81be-11e7-894f-ddfb4f9ee145.png)

Note that the diagram includes a reference to a CTDL-SKOS schema and API. This would be a schema for concept schemes (vocabulary related to competenties). This schema is at the concept level, and will likely be addressed in the near future.

**Comment by siuc-nate** [comment]
It may well be that all three of the APIs depicted above end up being the same API, just pointed at different communities.  The existing publish, search, etc., APIs should all work for the other data types already.

**Comment by siuc-nate** [comment]
Updated diagram:
https://drive.google.com/file/d/0Bye25TO-7pllR1NhckxrUXNOYms/view

**Comment by siuc-nate** [comment]
As I understand it, this isn't really an issue in terms of the Registry team needing to do anything - once we create JSON schema validation documents for competencies and competency frameworks, the existing infrastructure should "just work", correct?

**Comment by cwd-mparsons** [comment]
@science @jbaird123 We will create the updated JSON validation schema and begin testing it. Will the existing search APIs work for new types of entity in the registry?

**Comment by cwd-mparsons** [comment]
@jbaird123 @science @siuc-nate 
Nate is nearing completion of the validation schema for the competencies. 
Following is an image showing the proposed relationships for the competency frameworks.
![image](https://user-images.githubusercontent.com/26332112/31103144-2b50baac-a79b-11e7-9c4c-4a37afb07b35.png)

**Publishing**
At this time, it appears that the whole framework is published, rather than being able to publish a competency separate from the framework. A competency couldn't be published separately, as the relationship to other competencies would not be illustrated. 
However we want to be able to directly reference a competency, say from an assessment. This suggests a competency will have a Ctid. So the difficulty is how to store the competencies to allow directly referencing a record, without having to get the framework, and then the competency.

Nate had suggested that perhaps the competency framework could be saved as a graph. This might be  better stated, that as well as competencies being saved with the competency framework (ie in an envelope), the entire hierarchy would have to be saved outside the envelope, in order to enable direct access via a competency Url. 

Has any work started on enabling storing competencies? If so, the hierarchical structure of competency frameworks, and competencies has to be accounted for.

**Comment by jbaird123** [comment]
@cwd-mparsons - How soon do you think you'll be able to provide us with the json-schema for this?  Any chance you can also provide some sample data?

**Comment by andersoncardoso** [comment]
@cwd-mparsons on the following PR (https://github.com/CredentialEngine/CredentialRegistry/pull/157), I listed a few issues that might help you on the schema definition.

**Comment by cwd-mparsons** [comment]
@siuc-nate Can you provide some sample data of ctdlAsn for Joe's team?
