### ISSUE TITLE
Develop search API for Competency frameworks, and competencies in registry

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#135]
This issue was created to track separately from the request ( #134  ) to store competencies in the registry. 
Details regarding this request are documented in the same google doc used for the publishing design:
https://docs.google.com/document/d/1VyAlt8sMwU32EqF0xICLE4hCFBAoG1MOReTjLSGkC8Y/

A search API would be developed for competency frameworks and competencies. 
The search should enable the following use cases:

- Full text search against:
- Framework (Standard Document) 
-- Title
-- Description
-- Publisher (more meaningful than Author?
-- Subject 
- Competency (Statement class)
-- Description
-- Concept term
-- Statement Notation

Searching against competencies within a framework
The key objective would be to list competencies within a framework, that is to be able to search for a framework, with the objective to list the competencies (all or by some filter)

Results
The competencies (statements) have a List ID property that is used for organizing statements both for sort order and for the hierarchy. This property must be available for sorting output - especially where content is being extracted for import into external systems.

**Comment by siuc-nate** [comment]
The existing search API may already handle this, at least for basic searches.
