### ISSUE TITLE
Now that envelope UUIDs are not required for updates, what is the process for deleting a resource

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#136]
The ability to update a registry resource without the envelope Id, is great feature, especially for use in third party publishing.  
Now, what about deleting a resource?
The current process to delete a document requires:
- creating a delete envelope that includes a ctid, and serialize for the post body
- using a registry url with the related envelope
http://lr-staging.learningtapestry.com/ce-registry/envelopes/3d666efc-f9cb-4283-94df-7f322e511f37
- issue a Delete request

We will need an envelope independent solution in order to enable deletion by a third party publisher.

**Comment by leolara** [comment]
@cwd-mparsons I think the right design is that a DELETE to http://lr-staging.learningtapestry.com/resources/{resource_id} should work. I think it was implemented that way by @coffeejunk but I am not sure

cc/ @jbaird123

**Comment by science** [comment]
I believe that in order for a direct delete of the resource_id to work, it would have to be a "server signed" resource. As long as that is true, a delete should function as well as a create, and is probably hardly any (if any) additional work.

cc @excelsior

**Comment by cwd-mparsons** [comment]
@science @excelsior Is there an updated status on how to do deletes without an envelope identifier?

**Comment by excelsior** [comment]
@cwd-mparsons Since #118 was fixed, it's possible now to delete envelopes by their custom IDs (`ceterms:ctid` in the case of CE Registry) via the `DELETE /resources/{resource_id}` endpoint.

Please let me know how that works for you.

**Comment by cwd-mparsons** [comment]
@excelsior @jbaird123 
Sorry for the delay, I was testing deletes last week and noticed that the delete by envelope no longer worked. I was testing against sandbox.credentialengineregistry.org. 

I can try again using the referenced endpoint. 

However I was wondering about the security. Providing the public/private keys via the delete envelope will be more secure than calling an endpoint.

**Comment by andersoncardoso** [comment]
I just tested the delete, on both the `envelopes` and `resources` enpoints, and it all worked.
A few points to consider:
- only the same user (same key pair) that created a resource can delete it
- you must pass an delete_envelope (which a json encoded using the same key for validation)
- later I found a little bug when comparing the keys. If you created a key with a trailing newline, and use the public_key on the envelope without it, then the check could fail. So I made a commit just now to fix that. Maybe it was this.

For more info: https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/02_ce-registry_walkthrough.md#8---deleting-resources

**Comment by cwd-mparsons** [comment]
@andersoncardoso @rradonic  
I have no problem using a delete envelope where the key pairs are being managed on a source machine. I want to add a delete endpoint to our registry assistant API, which is a proxy used by our clients to wrap up a request and call the registry endpoint. 
For the scenario where the keys are managed by the registry, an envelope can not be used (no keys to encode a request). The referenced document seems to only cover a delete using an envelope. 
So how do we make a secure delete request? We will have the organization CTID (that owns the data), from the registry, and the private key that is created when an organization is registered, and the CTID of the entity to be deleted.

**Comment by rradonic** [comment]
We actually hadn't implemented that. It's now implemented and deployed to the sandbox server.

Sending a DELETE request to "/resources/organizations/[:organization_id]/documents/[:ctid]", with an authorization token in the header like for publishing, will delete the envelope containing that resource. 

We perform the same checks as for publishing, so e.g. attempting to delete an envelope that was published on behalf of organization X will fail unless the publisher performing the DELETE is authorized to publish on behalf of that organization.

**Comment by cwd-mparsons** [comment]
@rradonic Thanks, I will test this function this week.

**Comment by cwd-mparsons** [comment]
@rradonic FYI - I have been to successfully test the delete for credentials, I will work on the other document types later this week.
