### ISSUE TITLE
What is the default sort order for search results, and is the order configurable

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#138]
I have been working on importing documents from the registry using the search API.
Even though I use the same date range for each request, the documents (for example organization), are returned in a different order.
First what  is the default sort order for search results?
Second how can this be customized?

For the import I want to get results sorted by the last updated date (updated_at).

**Comment by jbaird123** [comment]
@cwd-mparsons - The current sort order is arbitrary (unspecified).  We can add some sorting logic.  Are there any fields other than updated_at or created_at that you would find useful for sorting on?  We can add parameters like

`sort_by=created_at+asc` or `sort_by=updated_at+desc`

To allow you to sort the result set.

**Comment by cwd-mparsons** [comment]
@jbaird123 The dates are a good start. I will ask Nate for input as well.

**Comment by jbaird123** [comment]
Ok - great.  We reviewed this internally and couldn't see much value in any other fields.  I'll wait for @siuc-nate 's confirmation before implementing.

**Comment by siuc-nate** [comment]
Is it possible to set it up so that the field to sort by can be passed as part of the request?

**Comment by jbaird123** [comment]
@siuc-nate - Yes, this is possible, but maybe not possible for every field.  updated_at and created_at are no problem.  What other fields did you have in mind?

**Comment by siuc-nate** [comment]
Nothing specific at the moment - just trying to future-proof it.

Since it's a search rather than a straight get, perhaps alphabetical order might have some (minimal) value? And of course relevance, if that's not already implemented. Most of the desirable sort options (distance, time, cost, etc.) are locked up in embedded objects, and there are usually more than one of said objects, making sorting in that fashion all but impossible.  So date fields should work for now.

**Comment by jbaird123** [comment]
@cwd-mparsons, @siuc-nate - This is completed.  Let me know if you have any concerns.

Example:
http://lr-staging.learningtapestry.com/ce-registry/search?sort_by=updated_at&sort_order=asc

**Comment by siuc-nate** [comment]
Thanks.  What is the current list of valid values for sort_by?

**Comment by jbaird123** [comment]
Today it is only created_at and updated_at.  We can add more when / if the need arises.

Swagger has been updated with these values as well:  http://lr-staging.learningtapestry.com/swagger/index.html
