### ISSUE TITLE
Moving forward with third party publishing via the Registry Assistant API

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#139]
@science @jbaird123 
As mentioned in past TAC meetings, an API was suggested to simplify publishing to the registry. The primary benefits were to insulate organizations from the exact details of the CTDL schema, and formatting requests as JSON-LD. We have completed the majority of the functionality planned for the initial beta release.  A high level summary can be found at:
http://credreg.net/registry/assistant
Copies of the input and output classes are currently available here (pending a separate repository):
https://drive.google.com/drive/folders/0Bw7oOYI0D-o4Q3RYY1hOT3owWkE

Currently the API  just uses a single set of public/private keys. This is fine for initial testing. 
Soon we will want to test using:
- Authentication - or to start with, an API key
- Where registry manages the key pair

I understand that part of this process is the overall authentication process of registration, account authorization, and authentication methods. What is the status of the account management ( referenced in #100  )?
Is there some aspect that we can start to test, where even an account with a single set of keys is available to reference?

**Comment by siuc-nate** [comment]
Third-party publishing has been enabled.
