### ISSUE TITLE
Adding advanced search capability

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#143]
@science  @jbaird123 
We need to have some advanced query capability from the registry. This is due to the structure of CTDL (See http://credreg.net/ctdl/basics for examples).  Below are examples of queries; we need the ability to pass complex/dynamic queries to search deep into the relationships between entities.  This is particularly important where entities reference each other rather than include/embed one another (e.g., a credential references a learning opportunity).

**Registry handling of queries, joins, and "bubbling"**
**Query/Join Examples:**
- Search for all credentials that have 1-n competencies that match a given string query
- Search for all credentials that have requirements that are of 1-n audience level types
- Search for all credentials that are offered by organizations in a given state

**Bubbling Examples:**
- Display all competencies for a credential, which come from:
- The credential (requires)
  - Its required assessments (assesses, requires)
  - Its required learning opportunities (teaches, requires)
  - Learning opportunities recursively required by the credential's required learning opportunity (teaches, requires)
- Display all subjects for a credential, which come from:
  - The credential
  - Its required assessments
  - Its required learning opportunities

**Comment by cwd-mparsons** [comment]
@jbaird123 Could we get an update on the progress of this task.

**Comment by jbaird123** [comment]
@cwd-mparsons - same as #121 .  We need to evaluate some third party solutions, so this will take some time.  I'll let you know when we start to gain traction.

**Comment by cwd-mparsons** [comment]
closing as this has been supplanted by the Gremlin search
