### ISSUE TITLE
References to versions of envelopes is confusing, could this be changed to a different term like snapshots?

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#144]
In an envelope, the node_headers has the versions property that lists any past versions of the envelope, and the current version. 
![image](https://user-images.githubusercontent.com/26332112/30604174-a76d30b4-9d2f-11e7-8354-8ac8e2d48873.png)

The word _versions_ is causing confusion with partners, as we reference new and past versions of the actual credential. The suggestion was made to use a term like snapshot to a point time incarnation (avoiding the word version!) of a credential.
This would also require a change to the url for a version to be something like:
  url: "/ce-registry/envelopes/30850c99-8c76-4fc1-803a-4d18c605478b/**snapshots**/112238"

**Comment by jbaird123** [comment]
@cwd-mparsons - So would you be ok with using "revision_history" instead of "versions"?  I think we would then change the URL to use the word "revision":

/ce-registry/envelopes/30850c99-8c76-4fc1-803a-4d18c605478b/**revision**/112238

**Comment by cwd-mparsons** [comment]
@jbaird123 That is fine with me. 
@stuartasutton @siuc-nate @jkitchensSIUC  
Is the use of revision_history, and revision acceptable to the team?

**Comment by excelsior** [comment]
@cwd-mparsons The property was renamed to `revision_history`.

**Comment by cwd-mparsons** [comment]
@excelsior Thanks I see that versions property has been changed to revision_history. 
However the urls to the revision still use **version**. This was to be changed to revision (as shown in Joe's comment from Sep. 21st).

![image](https://user-images.githubusercontent.com/26332112/30986252-67bee798-a458-11e7-9ccd-305af92fa1e7.png)

**Comment by excelsior** [comment]
@cwd-mparsons My bad. `versions` in URLs were renamed to `revisions` (in plural, in order to conform to the names of the other endpoints). The Swagger docs were updated accordingly.

**Comment by cwd-mparsons** [comment]
@excelsior No you are good, thanks for the update.

**Comment by cwd-mparsons** [comment]
confirmed to be complete
