### ISSUE TITLE
We need a process for the registry to relate past and current implementation of a credential

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#145]
The CTID for a credential is essentially a product identifier. If a vendor makes significant changes to a credential, a new CTID would be created, and a new credential would be published. We need a systematic means to related past and current credentials.

**Problem Statement**:
There is an issue that that has to be addressed within the registry:
> Within any envelope there's snapshot  (see #144 ) information and a means to get to that information.  Once an entity is replaced by a new version that requires that a new CTID be associated with that entity, there is no way to identify the new version. To solve this, there needs to be a workflow process to ensure systems/applications consuming information about the prior version know it has been replaced. Going forward, all snapshots about the new version of the entity are within a new envelope using a new CTID and Envelope ID.

**Solution Ideas for Inherent in the Registry:**
> In the publishing API, enable identifying the CTID that is being replaced/superseded by the entity being published (when the CTID changes). The registry would then provide the new CTID (and/or envelope ID) as part of the data when the old envelope is retrieved.
> 
> For example, this could create a new snapshot in the envelope's list of snapshots with an event type of "replaced" or "replacedBy" and a URL that points to the new envelope ID. Additionally, the new envelope may have a snapshot with an event type of "replaces" and a URL that points to the old envelope ID.

**Inherent in the Registry:**

All entities in the registry are described within envelopes.

In addition to the CTID and Envelope ID, each envelope in the registry contains as set of "version" information that is for the purpose of identifying any updates, as snapshots to any information referenced by a CTID.  Each version within an envelope is a snapshot.  A snapshot is a specific JSON-LD document published to the registry at a specific time and date. Multiple snapshots can be associated with one envelope (and one CTID). Envelopes in the Registry maintain references to individual snapshots. Always get the latest envelope to get the complete list of snapshots.

- CTID: The unique identifier for a top-level thing in the registry including a Credential.
- Envelope ID: The unique identifier for a chain of envelopes in the registry. Envelope IDs are not the same as CTIDs, but each Envelope ID will have a matching CTID. Retrieving an envelope by its ID will always return the latest envelope unless a snapshot identifier is appended (see below).
- Version: version information embedded in the credential document. Multiple versions can be associated with one CTID.
- Event: Within the registry, an envelop contains references to "event".  The event is either a "create", "update", or "delete".
- Created_at: The date the snapshot was created.
- URL: The link to the information contained with the snapshot.

**Optionally, in the data:**

- Version Identifier: http://credreg.net/ctdl/terms/versionIdentifier - In addition to the data in the Registry envelope, publishers can include data in the CTDL JSON document to uniquely identify specific versions of Credentials and Assessments using the versionIdentifier property.
- Previous Version: http://credreg.net/ctdl/terms/previousVersion - The URI for the previous version of a Credential. Enables a new credential to point to a previous credential's CTID.
- Latest Version: http://credreg.net/ctdl/terms/latestVersion - The URI for the latest version of a Credential. This should be the same as the Credential's URI, since the Registry will always return the latest version of the data for a CTID when data is retrieved by CTID. Alternatively, it should be an externally-maintained URI managed by the publishing organization (such as a PURL) that redirects to the latest Credential's URI even if the CTID changes.
- Credential Status Type: http://credreg.net/ctdl/terms/credentialStatusType - A controlled vocabulary that points to a set of statuses for a specific CTID (e.g., Active, Completed, Failed, Potential)

**Comment by siuc-nate** [comment]
In other words, we want to enable data that connects like this:
![ctid envelopeid](https://user-images.githubusercontent.com/21346519/30610739-c8a3a0aa-9d44-11e7-8398-312b94456c7f.png)

So we need:
- Registry Envelopes to have a property that indicates the version number for that envelope so that it can be stored and referenced later by the publishing system
- A means through the API of indicating when one CTID has replaced another
  - Should this be a parameter used during publishing or a standalone API call? Both?
  - This information should be reflected when data for either the new CTID or the old CTID is retrieved
  - This may be a part of the "versions" field (with an event type of "replaced"/"replaces"), or its own property

**Comment by cwd-mparsons** [comment]
@jbaird123 @science Has any progress been made on a solution for this issue?
Would this necessitate a new endpoint (something like replaces), where the new and old previous Ctid would have to be provided? Or would there be a new property on the envelope for including a Ctid that is being replaced?

**Comment by jbaird123** [comment]
@cwd-mparsons, @siuc-nate,

Just circling back on this.  Last I recall (from one of our meetings in early October), we suggested that the "replaced by" data should be stored within the CTDL rather than as part of the envelope.  I believe this would require a change to the CTDL to accommodate this information.  Did this ever get discussed on your side?

**Comment by jbaird123** [comment]
@cwd-mparsons, @siuc-nate - Is this still relevant?

It's marked High Priority, but nothing has happened apparently since November 2017.  I know you've made a lot of changes since then, so I'm not clear whether you found a solution.

Let me know whether this can be closed or is still an issue.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons @siuc-nate remove @jbaird123 from this and mark this, per our recent discussion,  as for plus to determine if it's our issue.

**Comment by siuc-nate** [comment]
Wasn't this taken care of via the revision history in the envelope?

**Comment by mparsons-ce** [comment]
@jeannekitchens @stuartasutton @siuc-nate 
I think this issue has been resolved with the addition of the properties:
- previousVersion
- supercedes
- supercededBy
