### ISSUE TITLE
Clear out old data from the credential registry

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#148]
@coffeejunk @excelsior @jbaird123 
I would like to clear out all of the registry data, so that we can start fresh with publishing. 

Per @coffeejunk from issue #51 , the following would be the task to execute.

> There is a task for this: rake envelopes:clear_community\['ce_registry'\]. 

Thanks

**Comment by excelsior** [comment]
@cwd-mparsons Yes, this is the task, it'll remove all the envelopes belonging to the `ce_registry` community.

**Comment by cwd-mparsons** [comment]
@excelsior can you initiate this task?

**Comment by excelsior** [comment]
@cwd-mparsons Done.

**Comment by cwd-mparsons** [comment]
@excelsior Thanks
