### ISSUE TITLE
Notification scheme for new resources in the Credential Registry.

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/CredentialRegistry#152]
Part of the interaction between CASS and the CER is for CASS to publish to the CER, but to also monitor the CER for ASN frameworks directly published and harvest those back into CASS. Is there a mechanism (webhook, websocket, rss feed, ?since=<last checked>) to know when resources have been updated in the CER?

**Comment by cwd-mparsons** [comment]
@Lomilar I am looping in Joe Baird @jbaird123 for this question.
Certainly a customizable notification capability could be very useful.

**Comment by jbaird123** [comment]
I haven't checked to see if it works, but have you tried filtering based on the updated_at field?  That might be the simplest solution, and if it's not working already I'm sure we could add that without too much difficulty.

**Comment by Lomilar** [comment]
That would likely work, but it's still requiring, at its core, polling. A callback based system like webhooks would lower bandwidth and improve time-to-consensus.

I can start here though.

**Comment by Lomilar** [comment]
On second, third, and fourth thought, one live callback based method and one timestamp method would probably be best. The timestamp based method would help servers that are offline for a period of time catch up, and the live method will keep servers in sync more actively without requiring polling.

**Comment by siuc-nate** [comment]
This is something to investigate on our end.
