### ISSUE TITLE
Request to update Json validation schema

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#153]
@jbaird123 
I would like the schema files from the following folder promoted to the staging registry server: 
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/Schema-2017-10-27
I would like this done as early as possible on Monday, Oct. 23rd. (I thought it was too late to call tonight)

There should be  a script for this, as referenced in the following github post, created by Leo, with input from Max
https://github.com/CredentialEngine/CredentialRegistry/issues/131

The latter references some proposed changes that have not been implemented. I will be creating another folder tomorrow for the next set of changes.

**Comment by excelsior** [comment]
@cwd-mparsons The script was improved to respect both yours and Leo's suggestions. It's possible now to specify the name of the directory containing the schema files to be updated. It also uses `Production_Schema` as the default value of the aforementioned parameter, so you can put updated files into that directory and run the script.

```
Usage: update_json_schemas [options]
    -d, --dir-name=DIR_NAME          schema directory name (default: Production_Schema)
    -h, --host=HOST                  target host
        --private-key=PATH           private key
        --public-key==PATH           public key
```

Please let us know how that works for you.

**Comment by cwd-mparsons** [comment]
@excelsior This approach sounds good.
I have created a Production_Schema folder and uploaded the versions of the schemas to be deployed to the registry site. 
Please run this script - I don't know that I have access to the script.
Thanks

**Comment by andersoncardoso** [comment]
@cwd-mparsons I run the script just now.
Please check, if anything isn't right let me know.
http://lr-staging.learningtapestry.com/schemas/info

**Comment by cwd-mparsons** [comment]
@andersoncardoso Thanks, I am checking the publishing now.
