### ISSUE TITLE
Process for updating, testing, and deploying the Ctdl-ASN schema

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#156]
@jbaird123 What will be the process for testing and deploying the CTDL-ASN validation schema?
Should the schema be added to the same folder as the other schemas?
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/Production_Schema

It may depend on how this schema is handled in the registry, that is whether Ctdl-asn schema is stored or deployed differently. 
Work on the schema may not be done at the same time as work on the ceterms schema. 
As well a separate process will be necessary for the testing. Whenever content changes under the test data folder, the TravisCI process kicks off to run tests:
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/test_data

So we would want to keep the Ctdl-asn related test data separated, as well as the TravisCI process - just guessing at this time.

**Comment by andersoncardoso** [comment]
@cwd-mparsons @jbaird123 
These schemas will be under the CER community the same ways as others right? then I guess they would only be another `type` inside the community, like we did for `competency` and `competency_framework` on https://github.com/CredentialEngine/CredentialRegistry/pull/157. 
Being that way, they can be placed on the same folder and use the same structures we already have (e.g.: the schemas update script, etc).
That sounds right? or I'm missing something?

**Comment by cwd-mparsons** [comment]
@andersoncardoso @jbaird123 
I was thinking that I would like to be have the schemas separate, so tests and deployment could be separate. It is very likely that changes to the Ctdl schema would be tested and updated together. The ctdlAsn schemas are used by separate processes, such as the CASS editor. I would not likely be making changes at the same time as for Ctdl. 
On one hand it may not matter that all the ctdl tests are run if we are only making changes to the ctdlAsn. I could just use a separate folder for ctdlAsn only changes, and change the latest symbolic link to point to the target ctdlAsn folder. I would guess that if there are no test cases for ctdl in the referenced ctdlAsn, then the TravisCI process would not complain?
Similarly, when requesting a deployment of validated schemas (from the Production_Schema folder), it might be cleaner to have separate processes. In this case, there would be two production schema folders.
I am not sure if this is becoming too complicated to manage cleanly. 
Let me know your thoughts.

**Comment by andersoncardoso** [comment]
Got it, the script has a few options, one of them is the directory name inside the CTDL_Json_Validation_Schema repo. So if you use a separate folder from `Production_Schema` to ASN I just need to know the folder, and have the corresponding schema file names to adapt the script. 
For example: `"compentency" => "https://raw.githubusercontent.com/CredentialEngine/CTDL_Json_Validation_Schema/master/<folder-name>/competency.json"`

**Comment by cwd-mparsons** [comment]
@andersoncardoso I decided to just go with the simple route. I added competency_framework and competency schemas folders under test_data, and updated production_schema
