### ISSUE TITLE
Request to update Json validation schema

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#159]
@andersoncardoso  @jbaird123  @excelsior 
I have completed testing of the json validation schema changes introduced Oct.27 - except language maps.
I have updated the Production_Schema folder with the updated schemas, per approach outlined in #153 
Please run the script to promote the new schemas to the registry.
The latter would be for the learningtapestry sandbox.

We would like to also establish a process to promote updates to the new azure servers. 
These changes could arbitrarily be promoted to each of the production, staging and sandbox servers. I could then do some testing against these servers.

**Comment by excelsior** [comment]
@cwd-mparsons The script was run on staging. Could you please confirm the schemas look good to you?

**Comment by cwd-mparsons** [comment]
@excelsior Thanks, I have verified the updated schema looks good.
