### ISSUE TITLE
Generated swagger file should be useful for creating clients

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#16]

**Comment by leolara** [comment]
@coffeejunk perhaps test that you can call the api using https://github.com/swagger-api/swagger-codegen for Ruby or perhaps Node

**Comment by coffeejunk** [comment]
trying to generate code yields:

```
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_api_0`
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: default
  Operation: putApiEnvelopes
  Resource: put /api/{community_name}/envelopes
  Definitions: {ApiRoot=io.swagger.models.ModelImpl@2a6d1d6d, ApiInfo=io.swagger.models.ModelImpl@d1371901, SchemasInfo=io.swagger.models.ModelImpl@46ec0c60, Community=io.swagger.models.ModelImpl@6dbd6a64, CommunityInfo=io.swagger.models.ModelImpl@dd881366, EnvelopesInfo=io.swagger.models.ModelImpl@7dc09cd8, SingleEnvelopeInfo=io.swagger.models.ModelImpl@b05af054, Envelope=io.swagger.models.ModelImpl@e1bbd80f, NodeHeaders=io.swagger.models.ModelImpl@22335e7, Version=io.swagger.models.ModelImpl@4d7eda6, ValidationError=io.swagger.models.ModelImpl@4b5e6915, DeleteToken=io.swagger.models.ModelImpl@2fca6187, RequestEnvelope=io.swagger.models.ModelImpl@2d704475, Ctid=io.swagger.models.ModelImpl@e281b14f, EnvelopesInfo_POST=io.swagger.models.ModelImpl@1a05c330, EnvelopesInfo_PUT=io.swagger.models.ModelImpl@62428fb3, SingleEnvelopeInfo_PATCH=io.swagger.models.ModelImpl@ee3bb95a, SingleEnvelopeInfo_DELETE=io.swagger.models.ModelImpl@725747c5}
  Exception: null
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:827)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:729)
```
[full trace here](https://gist.github.com/coffeejunk/188d8cea06bf5c0e59c7b638a11b0e3e)

**Comment by leolara** [comment]
@andersoncardoso do you know something about this?

@coffeejunk can you fix it?
@coffeejunk does this happen also when generating clients for other languages?

**Comment by coffeejunk** [comment]
> @coffeejunk can you fix it?
Let's find out, I'm diving into all the swagger related things that are going on here…

> @coffeejunk does this happen also when generating clients for other languages?
Yes, this is unrelated to the output language

**Comment by coffeejunk** [comment]
Hmkay, the problem is that we're defining multiple body parameters for HTTP operations that can contain payloads (`POST`, `PUT`, …). However given that there can only be one body, [only one body parameter can be defined](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object). If the body contains multiple parameters (as part for example of a JSON payload) this has to be defined as a schema.

```ruby
# https://github.com/CredentialEngine/CredentialRegistry/blob/master/lib/swagger_docs.rb#L254-L255
    swagger_path '/api/{community_name}/envelopes' do

      operation :put do
        parameter community_name
        parameter envelope_id
        parameter delete_token
       # ...
  # ...
```

`community_name` is a path parameter
`delete_token` is a defined schema

`envelope_id` is the offender here: it's not part of any schema and `swagger-blocks` (the gem used to generate the `swagger.json`) derives that since it's not part of the path it ought to be part of the body. Not wrong per se but also not correct in combination with the `delete_token`.

The seemingly obvious solution is to merge the `envelope_id` field into the `DeleteToken` schema, which fixes the previously mentioned Exception (yielding new Exceptions for different parts).

**Comment by leolara** [comment]
@andersoncardoso please give your feedback about the proposed solution by @coffeejunk 

@coffeejunk do you think it is much effort what you propose? Will it have implications somewhere else?

**Comment by andersoncardoso** [comment]
👍 no problem. We only scratched the surface of swagger as a  quick solution to document the api, we never bothered with generators and etc before. So if you need to change anything on the swagger-blocks to handle it, feel free to do any.

**Comment by leolara** [comment]
@coffeejunk please if this is easy do it

**Comment by coffeejunk** [comment]
related to learningtapestry/metadataregistry#16

**Comment by coffeejunk** [comment]
With #63 somewhat usable swagger clients can be generated. I've written up a [tiny walkthrough in a Gist here](https://gist.github.com/coffeejunk/29d255f3be8d0e2b6b5064e1aced64dc).

**Comment by leolara** [comment]
@coffeejunk Thanks, what do you mean by somewhat usable?

**Comment by coffeejunk** [comment]
@leolara because of #71 the generated code for the `/resources` endpoint doesn't do anything.

**Comment by leolara** [comment]
@coffeejunk nothing nothing, like it does not work, or you mean that it does not validate the response json?

**Comment by coffeejunk** [comment]
Nothing meaning, it creates code for the endpoint but doesn't do anything with the response it is getting from the server as it doesn't know anything about it.

**Comment by leolara** [comment]
@coffeejunk well, from the point of view of the API design, a resource can be any json. The json validation is done at another level different from the API validation.

I do not think we should expect the swagger client to do the JSON validation based on the community and @type, because that information is state of the API, not interface of the API.

I do not know if I explained well my opinion?

Is that all?

**Comment by coffeejunk** [comment]
makes sense and I agree. I'll modify swagger to accept any json value. Let's continue any further discussion in #71
