### ISSUE TITLE
Add envelope endpoints with a default community

### ISSUE THREAD

**Issue by rradonic** [CredentialEngine/CredentialRegistry#162]
Currently we have resource endpoints like /resources/... as well as /:community/resources/..., the first form uses a default community.

Envelope endpoints, however, only have the second form, with the community explicitly set in the URL. 

Implement envelope endpoints of the first kind.

**Comment by siuc-nate** [comment]
This has been implemented.

https://credentialengineregistry.org/envelopes/da4364db-3bd0-4ff9-9191-459886757d26
and
https://credentialengineregistry.org/ce-registry/envelopes/da4364db-3bd0-4ff9-9191-459886757d26
resolve the same data.
