### ISSUE TITLE
Add auth token checks for all API endpoints that modify data

### ISSUE THREAD

**Issue by rradonic** [CredentialEngine/CredentialRegistry#167]

**Comment by siuc-nate** [comment]
Can this be closed?

**Comment by rsaksida** [comment]
I was not working on this project when the issue was opened, so I don't know if a thorough review was completed. I'd prioritise this. @edgarf

**Comment by jeannekitchens** [comment]
@excelsior @edgarf @siuc-nate provide status update.

**Comment by excelsior** [comment]
The task needs some clarification.

**Comment by siuc-nate** [comment]
Is there any way to modify data in the registry without authorization? If yes, this issue needs to stay open. If not, we can close this.

**Comment by excelsior** [comment]
@siuc-nate I couldn't find any: all of the endpoints that modify data require authentication (either via a key or a token).
