### ISSUE TITLE
@id and ceterms:ctid should be marked as required in all top level entities

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#17]

**Comment by leolara** [comment]
Of course, regarding ceterms:ctid I mean in the entities that have such a field

**Comment by stuartasutton** [comment]
@leolara, 'yes', all "top level" entities require an @id and the `ceterms:ctid` property is required for `Credential` only.

**Comment by leolara** [comment]
@siuc-nate do you agree on implementing this as such, as @stuartasutton and me agree on this?

**Comment by siuc-nate** [comment]
It makes sense to me, since `@id` is required for JSON-LD and (if I understand correctly) the registry will **not** be generating CTIDs (as this would interfere with the publishing/signing process) then yes all Credentials should require CTIDs.

**Comment by siuc-nate** [comment]
This has been done:
![image](https://cloud.githubusercontent.com/assets/21346519/24008113/ad5de6f0-0a3e-11e7-80ee-7e3641e775e7.png)

Note:
- `@type` is required for **all** classes
- Additionally, `@id` and `@context` are required for **top-level** classes
- Additionally, `ceterms:ctid` is required for **Credential** subclasses

**Comment by leolara** [comment]
@siuc-nate 

regarding @type:
 + my interpretation is it is not required in JSON-LD  http://json-ld.org/spec/latest/json-ld/#specifying-the-type
 + I think it is needed for top level domain entities, as in the "envelop" we will put Credential, so we need a way to distiguish from different sub-classes
 + As some fields could contain different classes, it is needed for the sub-entities as well.

My conclusion is that you are correct regarding `@type` and should be mandatory

Regarding `@context`:
 + It is not mandatory in JSON-LD
 + Our field names and types use namespaces, so we need to define those on @context, or our JSON would not be a wf JSON-LD

My conclusion is that you are correct on `@context`

I think it is obvious you are correct on `@id` and ```ceterms:ctid```.

I close this issue then.
