### ISSUE TITLE
Gather encoding for a complete "description set"

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CredentialRegistry#172]
I am needing to see the json encodings for a complete "description set" defined as a credential and all of its related entities in the registry. So that would include all related top-level entities--credential, organization(s), learning opportunities, assessments, competencies. The seed credential for this description set should be as robust and full as we can find. If necessary, more than one description set will work if the first set lacks key inter-entity relationships.

**Comment by siuc-nate** [comment]
We're currently building these.
