### ISSUE TITLE
Description set(s) needed for review

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CredentialRegistry#173]
I am needing to see the json encodings for a complete "description set" defined as a credential and all of its related entities in the registry. So that would include all related top-level entities--credential, organization(s), learning opportunities, assessments, competencies. The seed credential for this description set should be as robust and full as we can find. If necessary, more than one description set will work if the first set lacks key inter-entity relationships.

**Comment by stuartasutton** [comment]
@jkitchensSIUC, @siuc-nate,

**Comment by stuartasutton** [comment]
@jkitchensSIUC, @siuc-nate, @mparsons1953, I want to return to this issue of description sets (names graphs) with additional force. **This has to happen!** We need to have a simple means for the CER to provide a validating description set for a credential using `@graph` and identified by URI; e.g., 

```
{
    "@graph": "https://credentialengineregistry.org/graph/ce-5BD8C9CE-120E-466E-B13F-C4AB0536D86C"
     ...
```

identifying the graph for CER resource https://credentialengineregistry.org/resources/ce-5BD8C9CE-120E-466E-B13F-C4AB0536D86C.

Such a named graph (description set) would include the json-ld for the following:
* credential
* assessment profiles
* learning opportunity profiles
* condition profiles/manifests
* cost profiles/manifests
* all bnodes related to the above

Nothing precludes adding credential organization(s) to the set, but nothing commands it. While assigning the graphs a URI is not *absolutely* necessary, it is a useful since it provides the only means for unambiguously referring to such description sets. 

Note that in the JSON-LD 1.1 specification [example for named graphs](https://json-ld.org/spec/latest/json-ld/#named-graphs), they include a generation date stamp for the graph using the W3C [provenance vocabulary's](https://www.w3.org/ns/prov#) [`generatedAtTime`] (https://www.w3.org/TR/2013/REC-prov-o-20130430/#generatedAtTime) term.

This same description set (named graph) matter is true for: (1) competency frameworks & competencies, and (2) concept schemes and concepts--although I think that concept schemes already provide description sets (i.e., uses `@graph`) while not (yet) going so far as named graphs--i.e., graphs assigned URI.

**Comment by siuc-nate** [comment]
Work on description sets is in progress.
