### ISSUE TITLE
Purpose of `comments` in CER JSON 

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CredentialRegistry#178]
Does the addition of comments (`// [comment text]`) in the json encoding of URI-identified resources in the CER (see example below) serve any purpose internally? JSON does not natively support comments and that means that files containing them have to have some process strip them out before handing them to a json parser. In the example below, the second comment simply repeats the URI of the resource and the first --`// 20180101061415`-- appears to be partially comprised of the current date. 

```
// 20180101061415
// https://credentialengineregistry.org/resources/ce-186FBC60-47E3-4616-B160-72CAC9E78F54

{
  "@id": "https://credentialengineregistry.org/resources/ce-186FBC60-47E3-4616-B160-72CAC9E78F54",
  "@type": "ceterms:CredentialOrganization",
  "@context": "http://credreg.net/ctdl/schema/context/json",
  "ceterms:ctid": "ce-186FBC60-47E3-4616-B160-72CAC9E78F54",
  "ceterms:name": "CompTIA",
```

**Comment by siuc-nate** [comment]
Where are you seeing these comments?

**Comment by stuartasutton** [comment]
Ah, very interesting...it appears to be something added at the top of json files when viewed with the Chrome json viewer...not there with Firefox json viewer.

**Comment by siuc-nate** [comment]
It sounds like they are the product of a browser extension.  There may be an option in there to view the raw JSON, which shouldn't contain the comments.

**Comment by cwd-mparsons** [comment]
Closing as doesn't appear to require further discussion.
