### ISSUE TITLE
Search API Documentation

### ISSUE THREAD

**Issue by jbaird123** [CredentialEngine/CredentialRegistry#179]
Update search API documentation to include the recent additions of the GraphQL / Neo4j functionality.
This will likely include refactoring this page:
https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/07_search.md

Source material can be found here:
https://github.com/aspino/CredentialRegistry/blob/patch-1/graphql-examples.md
https://github.com/aspino/CredentialRegistry/blob/patch-1/graphql-spec.md

**Comment by aspino** [comment]
Source documents have been merged into the official repo by https://github.com/CredentialEngine/CredentialRegistry/pull/183.

**Comment by siuc-nate** [comment]
@rradonic @jbaird123 
What is the endpoint for the GraphQL API?
Can requests be made to it via GET and/or POST or some other method?

**Comment by siuc-nate** [comment]
GraphQL was replaced by gremlin.
