### ISSUE TITLE
Provide the specifications for configuring the credential registry staging server

### ISSUE THREAD

**Issue by mparsons1953** [CredentialEngine/CredentialRegistry#18]
@leolara 
We are going to set up a staging server for the credential registry. 
We need the specifications for the server:
- OS
- HD space
- Any needed software, not open source, any that has to be purchased

OR, is the current staging server on a virtual machine that could possible be just backed up and restored? This would of course simplify the initial setup.

As discussed, the preferred approach will be to have resources from your team be responsible for the initial setup of the server, as well as ongoing deployment.

**Comment by leolara** [comment]
@andersoncardoso please, do this task

**Comment by andersoncardoso** [comment]
Our current server (staging) has the following specs: 
- GNU/Linux Ubuntu 14.04.5 LTS
- 2G mem
- 20 Gb HD
- 1 cpu `Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz`

We manage the servers using Cloud66, our current instances run on AWS. 
But I guess you can also use Linode or other providers. 

The application is composed of 3 blocks:
- the ruby app (ruby 2.3.1)
- postgresql (9.4 or later)
- elasticsearch (2.2.0)

we don't use any proprietary software for this app.

any question let me know. 
cheers

**Comment by cwd-mparsons** [comment]
Thank you @andersoncardoso 
I have sent a request to our data center to create a virtual machine with those specifications. 
Once we have the VM setup, we can plan the install of the necessary software and all configuration.

**Comment by siuc-nate** [comment]
Can this be closed?
