### ISSUE TITLE
How do I link to the "CompTIA A+" credential in the CER?

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CredentialRegistry#180]
@jkitchensSIUC, @cwd-mparsons & @siuc-nate,  I see no way for a credentialing organization that is not registered with the CER to link one of its credentials to a credential in the Registry. Assume this organization has a credential that `requires` the "CompTIA A+" credential and it wants to point (link) to CER for the description of it? 

At the moment, all that organization has (that is apparent) is the Credential Finder URL for the "CompTIA A+" credential--https://credentialfinder.com/credential/48. This is NOT the CompTIA credential's URI identifying the RDF representation; and, with only the viewer available, there is now no access to the underlying json-ld representation. So, how is linked data supposed to work if we don't easily expose the URI to the open world so they can be used?

The real measure of success in the Linked Data world is how many incoming links there are...i.e., how many links from outside in. If they cannot easily ascertain the URI of a resource, they can't link to it!

**Comment by siuc-nate** [comment]
We hid the registry information section because it was determined to be too confusing/unfriendly to end-users.  Perhaps we could bring it back but hide the display of the raw data so that only the link to the registry (and any other relevant info) is shown.

@jkitchensSIUC @stuartasutton Would that work?

**Comment by stuartasutton** [comment]
OK, why not do what many, many others have done and simply provide a small JSON or RDF linkable icon just large enough to be 'present'. Tech folks will "get it". Will some people click it who won't understand? Yes. But if they have an ounce of common sense, they'll go "not for me" and move on.  

Developers and data wranglers are users too and we have to provide them with a means to 'connect' to the json without impediment (logging into something).

![jsonld](https://user-images.githubusercontent.com/2939046/34679639-6a422ef6-f44b-11e7-9fa7-b57a2eb1a68b.png)

**Comment by siuc-nate** [comment]
Works for me, but it's @jkitchensSIUC's call.

Proposal:
- Unhide the "Registry Info" button/section on detail pages on the credential finder
- Hide(?) the pre-rendered JSON (in the gray box in that window)
- Add a linked data icon after the link to the JSON in the registry

**Comment by cwd-mparsons** [comment]
I would think that we don't want to have the JSON, hidden or not, just a link to the registry with the appropriate icon. That is have the link visible always, not in a panel/section.

**Comment by stuartasutton** [comment]
I am probably confused, Nate and Mike. My suggestion was to introduce the linked jsonld icon instead of having the "Registry info" unhidden. "Registry info" is a kind of general invitation to look further and tempts the novice to click. However, the jsonld icon link should act exactly like the old "Registry info".

**Comment by siuc-nate** [comment]
In that case, perhaps just adding a linked data icon next to the name of the credential/org/etc on the detail page at the top would work?

**Comment by stuartasutton** [comment]
Would work for me...and technical savvy folks would get it.

**Comment by siuc-nate** [comment]
This has been taken care of.
