### ISSUE TITLE
How to provide the publisher_id and secondary_publisher_id without an envelope.

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#184]
@rradonic I noticed that two new properties are now present in an envelope:
"publisher_id": 
"secondary_publisher_id": 

How do we provide the secondary_publisher_id?

**Comment by rradonic** [comment]
When sending a publishing request with a secondary publisher, you need to supply two tokens. One goes in the "Authorization" header like before, that determines the publisher, and the other goes in the "Secondary-Token" header, that determines the secondary publisher.

**Comment by cwd-mparsons** [comment]
@rradonic 
Thanks. Will these properties be searchable? I don't recall if envelope properties are searchable.

**Comment by cwd-mparsons** [comment]
@rradonic The secondary publisher is not being saved. I add the Authorization token, and if the scenario is a third party publisher, I add the Secondary-Token

```
client.DefaultRequestHeaders.Add( "Authorization", "Token " + registryAuthorizationToken );
if ( publishingOrganization.RowId != owningOrganization.RowId )
                    client.DefaultRequestHeaders.Add( "Secondary-Token", "Token " + publishingOrganization.RegistryIdentifier );

```
I see that data exists in the headers:
![image](https://user-images.githubusercontent.com/26332112/37234353-dcc9af94-23bc-11e8-80b0-5caf576eb910.png)

But the envelope doesn't have a value for 
![image](https://user-images.githubusercontent.com/26332112/37234469-9dd67eba-23bd-11e8-8e37-ca8ad69c2ea4.png)

**Comment by rradonic** [comment]
Which server is this happening on?

**Comment by cwd-mparsons** [comment]
This is on the sandbox

**Comment by rradonic** [comment]
The secondary token you're sending is the ID of an organization. It needs to be the auth token of a user that's linked to the publisher you want, like the first token.

I see there's actually only one publisher in the sandbox database, you (or we) will need to create more to use the secondary publisher feature.

**Comment by siuc-nate** [comment]
We need to follow up on this.

**Comment by edgarf** [comment]
This needs some deeper analysis, but It's possible (rough estimate) it's going to take 1-3 hours.

**Comment by excelsior** [comment]
@cwd-mparsons This functionality should work exactly as described by Ranko. And indeed, all the servers have only one publisher available. For the sake of testing, you can still use this same publisher as a secondary one. Alternatively, you can create a new publisher, there's an endpoint for that (`POST /metadata/publishers`).

Important: the auth token of the user associated with a publisher should be supplied in the header, not an organization's ID or a publisher's ID.
