### ISSUE TITLE
Greater search capabilities

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#186]
Moving this discussion from #185 so that that issue can get back on track.

@jkitchensSIUC, @cwd-mparsons, @stuartasutton and myself have discussed the registry search, and these are some of the conclusions we've come to:
 
We need to get together to discuss how we can achieve the best possible search for our developers.  Unfortunately, we haven't been able to dedicate sufficient time to planning/reviewing this aspect of the system until now. The searches so far have shown promise, but we need to be able to maximize what we offer to developers.

Ideally, such a search capability would:
- Be one search endpoint/system/schema/etc., so that developers don't need to learn or implement multiple ways of searching in order to be able to query everything they need
- Support both [CTDL](http://credreg.net/ctdl/terms) and [CTDL-ASN](http://credreg.net/ctdlasn/terms) schemas
- Be capable of very simple queries (see below)
- Be capable of very complex queries (see below)
- Be flexible enough to cover as many possible future use cases as we can without requiring tech staff (on CE or CR teams) to create new query pathways
- Support full-text search (preferably with stemming/fuzziness ala elasticsearch)
- Support pre-defined filters for controlled-value properties (i.e. all of the [Concepts](http://credreg.net/ctdl/terms#concepts) in [Concept Schemes](http://credreg.net/ctdl/terms#conceptschemes) in CTDL and CTDL-ASN)
- Enable retrieving the payload on its own
- Enable retrieving the envelope (which contains the payload and other data like revision history)

In other words, we need to be able to retrieve any top-level object by any of its properties (as well as traversing the graph of top-level (and embedded) objects if necessary). To give you an idea of the depth and flexibility we need, these pages offer an object-oriented way to look at the otherwise RDF schemas:
http://credreg.net/ctdl/mapping?profileID=registry
http://credreg.net/ctdlasn/mapping?profileID=registry

Examples:
- Return all credentials of a certain type
- Return all organizations where name contains "[word]"
- Return all certificates requiring a learning opportunity that teaches a competency whose text contains "[some phrase]"
- Return all learning opportunities that are accredited by any organization(s) where the organization has an organization type that contains "ceterms:QualityAssuranceOrganization" and a jurisdiction of "Indiana"
- Return all assessments offered by any organization(s) where the organization has a social media value of "[some URL]"
and so on

So far, it would seem that (and I may be wrong):
The JSON sub-document search approach:
- is great for finding individual documents by some property on the document itself
- is not very good for finding data that requires what are, in effect, JOIN statements

The GraphQL search approach:
- is great for finding things along predetermined pathways
- is useful when consumers don't want/need the entire document
- cannot be used for any type of query that doesn't fall along one of said pathways (meaning our team(s) would have to accommodate any additional updates/use cases manually)
- requires third-party developers to manage some degree of translation between the [official CTDL schema](http://credreg.net/ctdl/terms) and the [variant of it](https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/graphql-spec.md) created for use with the GraphQL implementation

One potential way to accomplish this would be to offer read-only access to the Neo4J database itself, allowing users to pass raw Cypher queries (controlling for long-running/overly-expensive/malicious etc. queries of course). This would, I think, grant the fullest possible flexibility for any given search use case, current or future, and require the least maintenance. We would need to ensure that:
- The structure of the Neo4J database is setup to mirror the structure of the CTDL schema as closely as possible, so that developers' knowledge of one can translate well to the other
- Each top-level Neo4J node has some way of getting back to the original JSON document/envelope that it is based on
- The graph is updated appropriately when new documents are published or expire
- Indexing is enabled to support full-text search as best we can

Another potential suggestion would be to implement an RDF triple store. I do not know enough about these to speak to the details of such an implementation, but I'm sure @stuartasutton may have some ideas there.

Databases aren't my specialty (I am, in part, just the messenger here), so I am certainly open to ideas and suggestions. I also invite @jkitchensSIUC @stuartasutton @cwd-mparsons to chime in with anything I may have missed (or misstated).

**Comment by jwrubel** [comment]
Hi @siuc-nate ! I'm going to coordinate the development effort on this. The goals you've laid out here make sense to me and provide great context. Looking at the examples, can you think of some more complex queries that developers might want to use? The challenge in developing a search capability for a data structure like this is finding the right tradeoff between being powerful enough to allow users to express queries that return the correct data but not so complex that the barrier to adoption is too high, as I fear it might become if were to simply provide direct access to Neo4j.

**Comment by siuc-nate** [comment]
This has been handled by the gremlin search implementation.
