### ISSUE TITLE
public_key is not returned in envelope results

### ISSUE THREAD

**Issue by science** [CredentialEngine/CredentialRegistry#188]
Publishers provide a public_key when they create a resource (where resources are server-signed, we should generate this public key). This public_key information should be returned when an envelope is retrieved. Currently it appears that this is not happening (though I think it used to happen)..

Example (but I think it's a universal problem): https://credentialengineregistry.org/ce-registry/envelopes/e8a85e9d-d069-4457-a30a-6f4f7dd3e2dc

As a bonus, we could consider returning the public_key info following Section 3 / Example 6 of this specification: https://web-payments.org/vocabs/security#Key

We'd probably only include a subset of info since we don't collect external URI data about the key (and we don't of course want to present the private key!):
```
{
  "@context": "https://w3id.org/security/v1",
  "@id": "",
  "@type": "Key",
  "publicKeyPem": "-----BEGIN PRIVATE KEY-----\nMIIBG0BA...OClDQAB\n-----END PRIVATE KEY-----\n"
}
```

Not sure if @id should be an empty string or just dropped?

**Comment by rradonic** [comment]
We now return the resource_public_key field, check it out on sandbox when you get the chance. I kept with our naming for the other envelope fields for now.

**Comment by cwd-mparsons** [comment]
@rradonic 
Yes, I see that the public key is now visible in the sandbox envelope - Thanks
![image](https://user-images.githubusercontent.com/26332112/36619214-9e3652aa-18b3-11e8-973a-bc2b81fc0410.png)
