### ISSUE TITLE
Organization registration needs to use CTID rather name to determine if an organization is unique

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#189]
@rradonic @jbaird123 
We had encountered some errors attempting to register organizations. The returned message needs to be improved, as it didn't indicate the actual error:

> StatusCode: 422, ReasonPhrase: 'Unprocessable Entity', Version: 1.1, Content: System.Net.Http.StreamContent, Headers: { Connection: keep-alive Status: 422 Unprocessable Entity Vary: Origin Date: Wed, 28 Feb 2018 21:18:01 GMT X-Powered-By: Phusion Passenger 5.1.11 Server: nginx Server: + Server: Phusion Server: Passenger Server: 5.1.11 Content-Length: 39 Content-Type: application/json 

Upon investigation, we found the issue was due to a duplicate name. While we are following up as why there are duplicate (one case for a marketing dept of an org), we need to have a dependably unique identifier for an organization. Duplicate names become more likely as the number of partners increases. 

To that end, CTID should be added as required for an organization. It would then be the unique identifier.

**Comment by rradonic** [comment]
We've now added a new "_ctid" field to organizations ("ctid" is a special PostgreSQL system field so we couldn't use that name). The new field is unique and guaranteed to be present; if the user doesn't provide a value during creation, we generate a value.

The "name" field no longer has a unique constraint.

Take a look at the sandbox and see if it's looking as you expect.

**Comment by rradonic** [comment]
Looking into the error message now.

**Comment by rradonic** [comment]
I reproduced the error on staging, it looks ok to me. Response code is 422, response body is "{"error":"Name has already been taken"}".

**Comment by cwd-mparsons** [comment]
@rradonic I did a quick test via the sandbox, providing a ctid and was successful.

![image](https://user-images.githubusercontent.com/26332112/36878128-29f28f2e-1d83-11e8-85b0-93d80ea81500.png)

BTW, the CTDL definition/format of a ctid is the string ce- followed by the UUID (see attached image). The ctid for an organization is published with it the registry. 

So our next step will be how to get the ctids for organizations that have already been registered in the production registry to be associated with metadata organization? I can send you a file that contains the org name, registry UUID, and CTID. Would you be able to then update the ctid for the production orgs?

**Comment by cwd-mparsons** [comment]
Complete, the database has been updated.
