### ISSUE TITLE
Top level entities should be always reffered never linked

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#19]
From issue https://github.com/CredentialEngine/CredentialRegistry/issues/11

@siuc-nate Looking at Credential group json schema, one thing that is important is that either you reference or embedded, you cannot put both even in JSON-LD that can be valid.

Because if something is embedded it will not be a retrievable top level entity.

For example:

    "ceterms:advancedStandingFrom": {
      "anyOf": [
        {
          "$ref": "#/definitions/meta:identifier"
        },
        {
          "$ref": "#/definitions/ceterms:ConditionProfile"
        }
      ]
    },
Is class ceterms:ConditionProfile a top level entity, or a sub-entity.

If it is an entity it should be "$ref": "#/definitions/meta:identifier" only, if it is a sub-entity "$ref": "#/definitions/ceterms:ConditionProfile"

Never mix fields that can be identifiers or embedded.

Perhaps this was confused when I suggested using something "$ref": "#/definitions/ceterms:ConditionProfileID" to highlight the type of the referred to the developer.

**Comment by leolara** [comment]
This should be applied to all four:

http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true
http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?asGroup=true
http://credreg.net/ctdl/schema/validation/LearningOpportunityProfile/json?asGroup=true

**Comment by siuc-nate** [comment]
The problem here is that the "advancedStandingFrom" property (along with several other related properties) all have a range of _either_ a Credential (which would be referenced) _or_ a ConditionProfile (which would be embedded).

Therefore both of these would be correct:
```
{
	"@type": "ceterms:Certificate",
	"ceterms:requires": [
		{
			"@id": "http://www.credentialregistry.org/resource/urn:ctid:[UUID1]"
		}
	]
}
```
and
```
{
	"@type": "ceterms:Certificate",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:description": [
				{
					"@value": "The description of this profile",
					"@language": "en-US"
				}
			},
			"ceterms:targetCredential": [
				{
					"@id": "http://www.credentialregistry.org/resource/urn:ctid:[UUID1]"
				}
			]
		}
	]
}
```

Mixing the structures would also be considered valid (presumably with two different credentials/UUIDs):
```
{
	"@type": "ceterms:Certificate",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:description": [
				{
					"@value": "The description of this profile",
					"@language": "en-US"
				}
			},
			"ceterms:targetCredential": [
				{
					"@id": "http://www.credentialregistry.org/resource/urn:ctid:[UUID1]"
				}
			]
		},
		{
			"@id": "http://www.credentialregistry.org/resource/urn:ctid:[UUID2]"
		}
	]
}

```

**Comment by leolara** [comment]
@siuc-nate in that case is alright, if "@type": "ceterms:ConditionProfile", is always embedded and "@type": "ceterms:Certificate" is always refered, we cannot mix RDF classes that are refered and also embedded.

Although in JSON-LD sense it makes sense, for a registry only the root objected is retrievable. so credential information you would embed it would not be retrievable.

All this would be mcuh more clear if we wrote down:
 + List of top level entities, always referred, never embedded
 + List of sub-entities, always embbeded, enver reffered

Thost two lists, (togetther with the list of literal classes) should be part of the JSON schema genration algorithm, if we do not want to go in circles.

**Comment by siuc-nate** [comment]
Those two lists are already used in generating the JSON schema - The Credential subclasses, CredentialOrganization, QACredentialOrganization, AssessmentProfile, and LearningOpportunityProfile are all top-level entities, so the schema is generated with properties pointing to them as references.

Everything else is embedded - for now, at least. There is talk of creating some new profiles in the coming months (CostManifest and ConditionManifest) that would also be top-level entities.

**Comment by leolara** [comment]
@siuc-nate to clarify

> we cannot mix RDF classes that are refered and also embedded.

We can mix them, in the sense that if a RDF property the range have both types, we can do as you said.

We cannot mix them in the sense that having a RDF class, let's call it X, refered somewhere by ID, and in other place embedded

**Comment by leolara** [comment]
@siuc-nate awesome, so if I understand correctly, it is already implemented in the way I was proposing then? In that case please close the issue

**Comment by siuc-nate** [comment]
Yes, that is how it is supposed to work. As far as I can tell, it is working as such.
