### ISSUE TITLE
Implications of "potential security vulnerabilities in your dependencies."

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#190]
@jbaird123 @science 
Github has issued the following warning:

> We found potential security vulnerabilities in your dependencies.
> Some of the dependencies defined in ./Gemfile.lock have known security vulnerabilities and should be updated.

![image](https://user-images.githubusercontent.com/26332112/38754878-30d06a56-3f29-11e8-8fda-49004b7d755b.png)

What should be done to address this vulnerability?

**Comment by andersoncardoso** [comment]
probably just need to update the referred gems (unless they introduce some incompatibility).
I can't see this warning, can you paste here which gems are flagged as vulnerable?

**Comment by jbaird123** [comment]
@cwd-mparsons - Let me know if you have any questions or concerns.

**Comment by cwd-mparsons** [comment]
@jbaird123 I see the warning no longer appears for this repository, so I take that to mean that Github has 'verified' that the issue has been fixed. I will close this issue.
