### ISSUE TITLE
GIthub has issued a new: potential security vulnerability in one of your dependencies.

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#192]
@rradonic 
I see there is another Github warning about a potential security vulnerability.

![image](https://user-images.githubusercontent.com/26332112/39431822-7faec5c4-4c57-11e8-9fd5-dee87a30369b.png)

Ranko had previously corrected the last vulnerability notice documented in issue #190

**Comment by rradonic** [comment]
Updated.

**Comment by cwd-mparsons** [comment]
Thanks
