### ISSUE TITLE
Request to promote production schemas from github to the sandbox site

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#193]
@jbaird123 @rradonic
We would like to have the json validation schemas updated to the credential engine **sandbox** environment. There are a few small changes, such as no longer requiring ceterms:targetNodeName for ceterms:CredentialAlignmentObject.
I have updated the Production_Schema folder with the updated schemas:
**https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/Production_Schema**
I will do some testing in the sandbox site, and then submit a separate request to promote these changes to the other environments. 
Please run the script to promote the updated schemas to the registry sandbox environment.

**Comment by rradonic** [comment]
Updated! Sorry for the delay.

**Comment by cwd-mparsons** [comment]
Thanks
