### ISSUE TITLE
Envelopes metadata should indicate what json-schema file was used to validate

### ISSUE THREAD

**Issue by science** [CredentialEngine/CredentialRegistry#197]

**Comment by cwd-mparsons** [comment]
@science @rsaksida Is this issue still pertinent? The CTDL schema doesn't have a version (date or number), and the validation is being done by the API.
Can this be closed?

**Comment by siuc-nate** [comment]
Per our 5-31-2019 meeting:
This is something we will handle by republishing data after a major change.
