### ISSUE TITLE
Use of type at the same level of anyOf, and anyOf with one element

### ISSUE THREAD

**Issue by mparsons1953** [CredentialEngine/CredentialRegistry#2]
per @leolara

At a JSON Schema formal level I see:
 + You have:

"ceterms:approvedBy": {
      "type": "object",
      "anyOf": [
        {
          "$ref": "#/definitions/meta:identifier"
        }
      ]
    },

I think that, you should not have "type" at the same level as "anyOf", and also it is a contradiction as what the $ref points to is not type object.
Also, I do not think it is "nice" to have AnyOf with one element, it is slightly confusing.

I would do:
"ceterms:approvedBy": { "$ref": "#/definitions/meta:identifier"} 

shorter and means what you try to mean.

**Comment by siuc-nate** [comment]
"anyOf" with one item is a side-effect of the generator being coded to handle 1-n items in the same fashion. I did make some adjustments to smooth that sort of thing over in other aspects of the schema; I suppose I could do it here as well.

However, I haven't seen the notation given in the example in any of the documentation for JSON-LD - does the schema parser know to assume that something like
`"ceterms:approvedBy": { "$ref": "#/definitions/meta:identifier"}`
has a type of object?

**Comment by leolara** [comment]
@siuc-nate I see here:

http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.26

precisely that example.

the thing refered can be a literal or whatever, I think the idea is that all JSON schmea should be in the refered definition. and hence if it is an object it should be there.

Even more in this case, the type is not object, it is string.
> "ceterms:approvedBy": { "$ref": "#/definitions/meta:identifier" }

If you wanted to redundantly say the type I guess the correct one would be:

>"ceterms:approvedBy": { "$ref": "#/definitions/meta:identifier", "type": "string" }

**Comment by leolara** [comment]
@siuc-nate 

I see now that meta:identifier definiton is an object, which contains a field @id of type string. In that case,

> "ceterms:approvedBy": { "$ref": "#/definitions/meta:identifier", "type": "object" }

I think it is ok but redudant as meta:identifier says that it is an object already.

Another point is that perhaps it is simpler for the developer to have meta:identfier as string, I think

**Comment by siuc-nate** [comment]
Thanks.

If we don't need to indicate explicitly that it's an object, that is fine.  

As for the structure of it, I don't think there's anything we can do - as far as I know, JSON-LD requires identifiers to be setup as an object with an `@id` property:

```
{
   "@type": "ceterms:CredentialAlignmentObject",
   "@id": "_:{someblanknodeguid}",
   "ceterms:targetNodeName": "Some target item",
   "ceterms:targetNode": "http://nodeurl.com/123"
}
```
doesn't conform to the JSON-LD spec in the sense that the URL (`http://nodeurl.com/123`) is actually a resource identifier.  So you have to use:
```
{
   "@type": "ceterms:CredentialAlignmentObject",
   "@id": "_:{someblanknodeguid}",
   "ceterms:targetNodeName": "Some target item",
   "ceterms:targetNode": { "@id": "http://nodeurl.com/123" }
}
```
in order to reliably convey to some JSON-LD interpreter that the URL is in fact an identifier (either an absolute URI as shown here, or an identifier to something else in the JSON-LD document's graph) and not just a string.

Again, I could be wrong, but I'm 99% sure that's how it works.

**Comment by leolara** [comment]
@siuc-nate actually, after writting that I went to look into the JSON-LD spec because I remembered something and I agree, it has to be inside an object in a field @id

**Comment by leolara** [comment]
@siuc-nate 

So it seems the conclusions from this ticket are:

 + If there is only one element inside AnyOf, it is more clear for the user-developer if there is no AnyOf
 + "ceterms:approvedBy": { "$ref": "#/definitions/meta:identifier"} and "ceterms:approvedBy": { "$ref": "#/definitions/meta:identifier", "type": "object"} are probably both correct, but I think first version is better, bec
 + the current definition of meta:identifier should stay the same to follow JSON-LD, it should be an object with the property @id: string

**Comment by siuc-nate** [comment]
So the output should look like this, right?:
![image](https://cloud.githubusercontent.com/assets/21346519/23766465/836f79d6-04ca-11e7-96ae-65efbb51cdb1.png)

**Comment by leolara** [comment]
@siuc-nate 

After looking at:

http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.23
http://json-schema.org/latest/json-schema-core.html#rfc.section.7
http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.21

My interpretation is that the type directly inside cterms:exactAligment should be ignored by the validator, and any other conditions outside the reffered should be ignored.

But I see this example: http://json-schema.org/example2.html it seems to contradict that.

I am pretty certain that if you put there type: object and then one of the reffered are actually not of type object that must cause problems.

So I think the best thing is to try both thigns in a json schema validator. I will do that.

**Comment by siuc-nate** [comment]
I can just remove the object designation if it's enough to have the $ref objects inside the anyOf.

Note that there are a very small number of properties that can be either an object or something else. This is one example:
![image](https://cloud.githubusercontent.com/assets/21346519/23771261/f48218d4-04db-11e7-8f98-f3ac6e254853.png)

**Comment by leolara** [comment]
@siuc-nate 

It is enough.

For me, the problem is not when it can be of two different primitive types. The problem is if one of the referred is of a different type of the referand, in that case I am afraid of.

I run some tests:

```js
{
  "$schema": "http:\/\/json-schema.org\/draft-04\/schema#",
  "definitions": {
	  "a":{
		  "type": "object",
		  "required": ["fielda"]
	  },
	  "b": {
		  "type": "object",
		  "required": ["fieldb"]
	  }
  },
  "anyOf": [
	  {"$ref": "#\/definitions\/a"},
	  {"$ref": "#\/definitions\/b"}
  ],
  "type": "string"
}
```

This schema will always result in invalid documents, if the json is an object it will fail because it has to be a string, if it is a string it will not be neither defintions/a or defintions/b ; that type of bug is the one I am concerned. So If we make always the type in the referred definiton and never in the referand we will avoid this type of bug

**Comment by siuc-nate** [comment]
I have removed the object designation outside of the anyOf blocks:
![image](https://cloud.githubusercontent.com/assets/21346519/23801802/09d68a58-0577-11e7-8b6b-69716feaa381.png)
