### ISSUE TITLE
Do not include in definitions of not embedded sub-entities

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#20]
For example:

Because a credential is always referenced  from another entity with meta:identifier, there is no need to put them on the definitions of a AssesmentProfile.

That way, we should include in definitions only the RDF classes JSON schemas that are acutally embedded in this JSON.

This is regearding these JSON schemas

http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true
http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?asGroup=true
http://credreg.net/ctdl/schema/validation/LearningOpportunityProfile/json?asGroup=true

**Comment by siuc-nate** [comment]
I'm not sure what you mean - The definition of Credential is not embedded in the AssessmentProfile JSON schema document.  Or do you mean something else?

**Comment by leolara** [comment]
@siuc-nate ok then, I mean it in general that we are not putting in definitions things that we are not using in that file.

I understand now that it is the case so I close the issue, open it if it is not the case
