### ISSUE TITLE
Support new data model

### ISSUE THREAD

**Issue by rsaksida** [CredentialEngine/CredentialRegistry#202]
- [x] Language maps
- [x] `@graph` elements

May result in changes in the way envelopes are processed and indexed by the backend API.

**Comment by rsaksida** [comment]
Questions:

- Can an envelope with a `@graph` property also have other properties aside from `@id` and `@type`? Meaning, can the payload be a mix between a `@graph` and a regular document?
- In the `@graph` envelopes that already exist in the CER, it’s not always obvious how to connect the secondary objects to the primary object. It is implied that secondary objects are related to the primary object by virtue of being in the same graph, but I don't see the `{ "@id": ... }` relationship objects that occurred in the previous version of the data model. I do see `{ "ceasn:isPartOf": "id..." }` which appears to serve the same purpose.

  It would be important to clarify this. How do secondary objects connect to the primary object if there isn't an explicit relationship? How will the relationships look like, old-style `{ "@id": ... }` or `{ "ceasn:isPartOf": "id..." }`? If the latter, we need a list of all the properties for which their values are actually IDs.
- I've made some assumptions about how `@graph` will affect existing API methods, and how the new API methods should behave:

  `/resources/:id` will return the **inner** object from the graph with the corresponding ID, and will also add the `@context` property to the result. Blank node IDs will 404.

  `/graph/:id` will return the complete **outer** graph object for graphs that contain the corresponding ID, even when the ID does not belong to the primary object. Blank node IDs will 404. For non-graph objects, `/graph` will behave the same as `/resources`.

  Are these correct?
- For the moment, I've implemented the changes so that the system is backwards-compatible with the previous data model. I'm only adding functionality, not removing. Is this the right approach?
- I'd like to understand what kind of features are expected from the full text search endpoint (`/search`). Is this endpoint being used currently? I see three possible approaches for reconciling FTS with `@graph`:
  1. Only index the primary object in the graph. In practice, you can search for content in the primary object, but not for content in the secondary objects. You will get the primary object as a search result (or alternatively the entire graph).
  _Est. timeline_ (for delivery, not actual implementation work): I've already implemented this.
  2. Index the content for all objects in the graph but store all of it under the primary object. You can search for content for any elements in the graph. You will get the primary object as a search result (or alternatively the whole graph).
  _Est. timeline_ (for delivery, not actual implementation work): 1 week.
  3. Index the content for all objects in the graph and store each document separately. You can search for content for any elements in the graph. You will the individual documents as search results (or alternatively the whole graph).
  _Est. timeline_ (for delivery, not actual implementation work): 1-2 weeks.
- Again for `/search`, should we add a filter for language? How would this filter look like? Would it look at the inner keys or the main language for the document?

**Comment by stuartasutton** [comment]
@rsaksida, can you please provide here full sample encoding that illustrates your issues 1-3?

**Comment by rsaksida** [comment]
Issue 1:

What I expect is:

```
{
  "@id": "https://credentialengineregistry.org/resources/ce-7c4b7cb0-0f37-4e21-a8a8-f4a88622f1f2",
  "@type": "ceasn:CompetencyFramework",
  "@graph": [...],
  "@context": "http://credreg.net/ctdlasn/schema/context/json",
  "ceterms:ctid": "ce-7c4b7cb0-0f37-4e21-a8a8-f4a88622f1f2"
}
````

I'm asking if I should expect:

```
{
  "@id": "https://credentialengineregistry.org/resources/ce-7c4b7cb0-0f37-4e21-a8a8-f4a88622f1f2",
  "@type": "ceasn:CompetencyFramework",
  "@graph": [...],
  "@context": "http://credreg.net/ctdlasn/schema/context/json",
  "ceterms:ctid": "ce-7c4b7cb0-0f37-4e21-a8a8-f4a88622f1f2",
  "ceasn:name": {
    "en-us": "Lift Director Mobile Crane Specialty Written Exam"
  },
  "ceterms:ctid": "ce-7c4b7cb0-0f37-4e21-a8a8-f4a88622f1f2",
  "ceasn:creator": [
    "https://credentialengineregistry.org/resources/ce-160a75db-a039-4bf7-b4c8-479dcf243561"
  ],
  ...
}
```

**Comment by rsaksida** [comment]
Issue 2:

The previous format was:

```
{
  "@id": "https://credentialengineregistry.org/resources/ce-095a7b13-cbbe-45c8-bd0b-817af1d8cb29",
  "@type": "ceterms:Certification",
  "ceterms:ownedBy": [
    {
      "@id": "https://credentialengineregistry.org/resources/ce-a67a31b4-9dab-409b-9778-9919ee14e4fb"
    }
  ],
...
```

The format I'm seeing in the `@graph` envelopes is:

```
  {
    "@id": "https://credentialengineregistry.org/resources/ce-7c4b7cb0-0f37-4e21-a8a8-f4a88622f1f2",
    "@type": "ceasn:CompetencyFramework",
    "ceasn:creator": [
      "https://credentialengineregistry.org/resources/ce-160a75db-a039-4bf7-b4c8-479dcf243561"
    ],
    "ceasn:hasTopChild": [
      "https://credentialengineregistry.org/resources/ce-e24e65c3-6051-4ad0-9cfa-0cfc9f2b2db8",
      "https://credentialengineregistry.org/resources/ce-ceec0ec6-0892-4e98-9248-589659814e61",
      "https://credentialengineregistry.org/resources/ce-dc9e6d0b-2e5a-4222-a57c-414e842468d0",
     ...
```

The new format makes it hard to identify references to other resources. With the old format I knew that an object with an `@id` property was a reference. There's no way to know whether a string is a reference unless we get a list of all the property keys that are supposed to be references (`ceasn:hasTopChild`, etc).

**Comment by rsaksida** [comment]
For issue 3, `/resources` will always return top level objects. Example: https://credentialengineregistry.org/resources/ce-ba172056-7e6d-4f18-b584-1ebb51e0c9e8

If the ID in the URL belongs to an object inside a graph, `/resources` will extract that object and return it as above.

`/graph` will return the whole graph, raw. Example: https://credentialengineregistry.org/resources/ce-7c4b7cb0-0f37-4e21-a8a8-f4a88622f1f2

**Comment by rsaksida** [comment]
@stuartasutton I've added some comments illustrating my points.

**Comment by siuc-nate** [comment]
>1. Can an envelope with a @graph property also have other properties aside from @id and @type? Meaning, can the payload be a mix between a @graph and a regular document?

My understanding (correct me if I'm wrong) is that there should only be JSON-LD properties at that level.  We have discussed including the CTID here but I don't think it's necessary since that could instead be included in the envelope (e.g. "main_entity": "ce-12345") and/or fished out of the `@id`.  So the `decoded_payload` should only contain `@context`, `@id`, and `@graph`.  Does that sound right @lomilar @stuartasutton @cwd-mparsons ?

>2. In the @graph envelopes that already exist in the CER, it’s not always obvious how to connect the secondary objects to the primary object. It is implied that secondary objects are related to the primary object by virtue of being in the same graph, but I don't see the { "@id": ... } relationship objects that occurred in the previous version of the data model. I do see { "ceasn:isPartOf": "id..." } which appears to serve the same purpose.
>It would be important to clarify this. How do secondary objects connect to the primary object if there isn't an explicit relationship? How will the relationships look like, old-style { "@id": ... } or { "ceasn:isPartOf": "id..." }? If the latter, we need a list of all the properties for which their values are actually IDs.

This was due to a change in the `@context` that explicitly names those properties as having a `@type` of `@id`.  Any property listed in http://credreg.net/ctdl/schema/context/json or http://credreg.net/ctdlasn/schema/context/json as having a `{ "@type": "@id" }` should have its value(s) interpreted as URIs.

>I've made some assumptions about how @graph will affect existing API methods, and how the new API methods should behave:
>/resources/:id will return the inner object from the graph with the corresponding ID, and will also add the @context property to the result. Blank node IDs will 404.
>/graph/:id will return the complete outer graph object for graphs that contain the corresponding ID, even when the ID does not belong to the primary object. Blank node IDs will 404. For non-graph objects, /graph will behave the same as /resources.
>Are these correct?

Yes, per https://github.com/CredentialEngine/vocabularies/issues/521#issuecomment-389245464 - though we did not explicitly define the behavior for using /graph/:id for non-primary objects, returning the whole graph anyway is probably fine (and perhaps even desirable). 

>For the moment, I've implemented the changes so that the system is backwards-compatible with the previous data model. I'm only adding functionality, not removing. Is this the right approach?

As much as possible, yes - it isn't clear exactly when we will have all of our systems updated to use the new design. @cwd-mparsons can speak to this more than I can.

>I'd like to understand what kind of features are expected from the full text search endpoint (/search). Is this endpoint being used currently? I see three possible approaches for reconciling FTS with @graph:

I prefer option 2 (with returning the whole graph), as it most closely reflects the structure of the published documents and the way CTDL works. @cwd-mparsons @stuartasutton @lomilar do you have any thoughts on this?

>Again for /search, should we add a filter for language? How would this filter look like? Would it look at the inner keys or the main language for the document?

In order to avoid confusion, are you referring to:
a. The language of the JSON-LD document itself (e.g. the available language map fields), or
b. The language used in the `ceterms:inLanguage` property (which reflects the language of the underlying credential/assessment/learning opportunity, and is independent of the language(s) used in the JSON-LD)

For `a`, it might be best to include `@language` in the root of the `decoded_payload` even if it is technically redundant with the included language maps - just to simplify searching/filtering.  This would, however, require publishers to provide that information (or we could assume it if left blank, since publishing goes through our system).  I'm open to suggestions.

For `b`, this should probably simply work like any other filter/query for any other property.

**Comment by rsaksida** [comment]
> My understanding (correct me if I'm wrong) is that there should only be JSON-LD properties at that level. We have discussed including the CTID here but I don't think it's necessary since that could instead be included in the envelope (e.g. "main_entity": "ce-12345") and/or fished out of the @id. So the decoded_payload should only contain @context, @id, and @graph. Does that sound right @Lomilar @stuartasutton @cwd-mparsons ?

Got it. In that case, I'll wait for an answer on whether that information will be addded to the envelope or if I can rely on `@id` to consistently reflect the primary object's CTID.

> This was due to a change in the @context that explicitly names those properties as having a @type of @id. Any property listed in http://credreg.net/ctdl/schema/context/json or http://credreg.net/ctdlasn/schema/context/json as having a "@type": "@id" should have its value(s) interpreted as URIs.

I see. I believe the schema URLs are not part of the CER API - is that correct? It also doesn't look like they're versioned. This could potentially become a challenge when parsing the payloads for building a graph (or doing other kinds of analysis), because the `@context` information may have changed between the time when the document was submitted and the time of analysis. Probably not a concern right now, but something to have in mind.

> Yes, per CredentialEngine/vocabularies#521 (comment) - though we did not explicitly define the behavior for using /graph/:id for non-primary objects, returning the whole graph anyway is probably fine (and perhaps even desirable).

Okay. I guess the alternative would be returning 404, but I think it makes sense to return the graph since that's where the object is stored.

> I prefer option 2 (with returning the whole graph), as it most closely reflects the structure of the published documents and the way CTDL works. @cwd-mparsons @stuartasutton @Lomilar do you have any thoughts on this?

Alright. That option is slightly simpler to implement than 3). One downside is that if you're building a search UI, for example, and you want to return granular results for documents inside the graph, it will be more challenging as the API won't give you that information (it will search and index all content inside the graph, but will return the whole graph and not the individual documents as results).

> In order to avoid confusion, are you referring to:
> a. The language of the JSON-LD document itself (i.e., the available language map fields), or
> b. The language used in the ceterms:inLanguage property (which reflects the language of the underlying credential/assessment/learning opportunity, and is independent of the language(s) used in the JSON-LD)

I was actually thinking about the examples mentioned in the "Data Design Implementation" document: `"ceterms:description": {"en": "..."}` and `"ceterms:keyword": { "en": [...] }`. I'm not sure whether those fit in 1) or 2). To be honest, I don't know enough about the domain model or your requirements to answer this. It depends on what you need from the `/search` API - I need more information.

Thanks for the detailed responses.

**Comment by siuc-nate** [comment]
>Got it. In that case, I'll wait for an answer on whether that information will be added to the envelope or if I can rely on `@id` to consistently reflect the primary object's CTID.

The `@id` in the root of the `decoded_payload` will always end in the CTID of the primary object, e.g:
```
"@id": "https://credentialengineregistry.org/graph/ce-02c481aa-0a31-40b0-82dd-d78eff147ee1"
```
where `ce-02c481aa-0a31-40b0-82dd-d78eff147ee1` is the CTID for the main entity in the graph.  Storing that CTID somewhere else in the envelope would just be for convenience, possibly to speed up searches or retrieval depending on how the rest of the system is built.

>I see. I believe the schema URLs are not part of the CER API - is that correct?

I'm not quite sure what you mean - can you expand on this a bit?

>It also doesn't look like they're versioned. This could potentially become a challenge when parsing the payloads for building a graph (or doing other kinds of analysis), because the `@context` information may have changed between the time when the document was submitted and the time of analysis. Probably not a concern right now, but something to have in mind.

Are you referring to versioning on the `@context` URI? Technically we do store different versions of it (matched up to releases of CTDL), but it very rarely changes.  You are right that it is something to keep in mind, though.

>Alright. That option is slightly simpler to implement than 3). One downside is that if you're building a search UI, for example, and you want to return granular results for documents inside the graph, it will be more challenging as the API won't give you that information (it will search and index all content inside the graph, but will return the whole graph and not the individual documents as results).

The vast majority of the information inside the graph for credentials and related info will be in the main document anyway, but this might be more of an issue where competencies are concerned.  Good catch. For those, it may make sense to return just the competency that matches the query.  Alternatively, return the graph but include something in the returned result that indicates (probably via `@id`) the document within the graph that matched the result.  We should probably work this through in greater detail to make sure it does what is best for the searcher in various use cases.

>I was actually thinking about the examples mentioned in the "Data Design Implementation" document: `"ceterms:description": {"en": "..."}` and `"ceterms:keyword": { "en": [...] }`. I'm not sure whether those fit in 1) or 2). To be honest, I don't know enough about the domain model or your requirements to answer this. It depends on what you need from the `/search` API - I need more information.

Wouldn't both of those just be filters for the "en" property of a language map?  To further clarify my previous bullet points on language data, the following would be separate queries:
- Give me all of the JSON-LD documents for credentials where:
  - The JSON-LD is in english, regardless of what language(s) the credential is in
    - This would be a case for including `@language` in the root of the `decoded_payload` since you wouldn't need to inspect the JSON-LD looking for english language maps
  - The credential is in english, regardless of what language(s) the JSON-LD is in
    - The only relevant value here is the value of `ceterms:inLanguage` - even if the JSON-LD is in some other language, as long as "en" appears as a value for `ceterms:inLanguage`, it matches
  - The JSON-LD is in english (and possibly other languages) **and** the credential is in english (possibly with other languages too)
    - Here you would inspect both `@language` (for the JSON-LD) and `ceterms:inLanguage` (for the credential)

**Comment by rsaksida** [comment]
>The `@id` in the root of the `decoded_payload` will always end in the CTID of the primary object. Storing that CTID somewhere else in the envelope would just be for convenience, possibly to speed up searches or retrieval depending on how the rest of the system is built.

Okay. There's no problem in extracting out the CTID from the `@id` URL, as long as it's reliable - will everyone posting to CER follow this convention?

>I'm not quite sure what you mean - can you expand on this a bit?

When I parse the envelope payloads to build a graph, I need to know how to construct the vertices and the edges of the graph. When a payload document references another document in a property, I construct that as two vertices connected by an edge. In the previous data model it was trivial to identify vertices and edges - the references would consistently follow the format `"edge_label": { "@id", "@type" }`. Now they look like `"edge_label": "@id"`, and if I understood it correctly, the information about which properties are actually document references (and thus akin to edges) is contained in the JSON returned by the `@context` URL.

That means I need to make an HTTP for `@context`, parse the data and use it to inform the indexing process. However, the URL in `@context` doesn't appear to have any versioning information. If the data in the JSON returned by the `@context` URL changes between the envelope submission time and the indexing/analysis time, we might run into problems because document references won't be correctly identified.

>The vast majority of the information inside the graph for credentials and related info will be in the main document anyway, but this might be more of an issue where competencies are concerned.  Good catch. For those, it may make sense to return just the competency that matches the query.  Alternatively, return the graph but include something in the returned result that indicates (probably via `@id`) the document within the graph that matched the result.  We should probably work this through in greater detail to make sure it does what is best for the searcher in various use cases.

Agreed. To clarify, these differences between approaches are subtle but may result in very different implementations. Right now we are using PostgreSQL's native FTS capabilities, which work fine, but they query results have an 1:1 relationship with rows. One table row = one result. If I need to identify the specific document for the search term (and not just the primary one), I'll need to normalise the `@graph` into a second table.

>Wouldn't both of those just be filters for the "en" property of a language map?  To further clarify my previous bullet points on language data, the following would be separate queries

From your response, I think we might not need to support this explicitly in the `/search` (full text) API, and instead allow users to query the information via Gremlin. Does that make sense? It's really up to you, I don't know what search requirements you guys have for `/search`.

**Comment by siuc-nate** [comment]
>Okay. There's no problem in extracting out the CTID from the @id URL, as long as it's reliable - will everyone posting to CER follow this convention?

It's the required format for URIs for stuff in the registry, so yes, that will be reliable.

>If the data in the JSON returned by the @context URL changes between the envelope submission time and the indexing/analysis time, we might run into problems because document references won't be correctly identified.

Doesn't the indexing happen immediately upon submission? Is there a significant time gap?  Changes to the context are very rare so you can probably load it up once per day and cache it (realistically you could cache it for months and only update it when CTDL releases happen, but a daily refresh should be fine just in case).  Would that help?

>Agreed. To clarify, these differences between approaches are subtle but may result in very different implementations. Right now we are using PostgreSQL's native FTS capabilities, which work fine, but the query results have an 1:1 relationship with rows. One table row = one result. If I need to identify the specific document for the search term (and not just the primary one), I'll need to normalise the @graph into a second table.

Given that competency search results will likely just need to return the competency, and that the graph for that framework can be loaded by tweaking the competency's URI (per your post above), maybe it makes sense to go with your original option 3 after all - provided this means you aren't pulling sub-entities out of the credential or something (no need to return a Cost Profile all on its own, that kind of thing).  In other words, search results should probably work the same way that retrieving stuff via the /resources/ URI works - you get the top-level document that has a match for your search somewhere in it.

>From your response, I think we might not need to support this explicitly in the /search (full text) API, and instead allow users to query the information via Gremlin. Does that make sense? It's really up to you, I don't know what search requirements you guys have for /search.

Ideally it should look at any field that has text in it - perhaps with some optional parameter (or maybe one where we can default the value to english) that tells it to only look at the values for language map keys that are in some given list of languages (e.g. "en-us", "en-gb", "en") for a match. Is it possible to weight fields higher than other fields (i.e. to have a match in the name be more important than a match in the description of a condition profile somewhere deeper in the data)?

**Comment by rsaksida** [comment]
>It's the required format for URIs for stuff in the registry, so yes, that will be reliable.

Got it. I'll build the indexing around the `@id`s then.

>Doesn't the indexing happen immediately upon submission? Is there a significant time gap?  Changes to the context are very rare so you can probably load it up once per day and cache it (realistically you could cache it for months and only update it when CTDL releases happen, but a daily refresh should be fine just in case).  Would that help?

It will, but there are situations when we'll need to index on demand. For example the first time we index the DB. Or if for some reason we need to rebuild the graph. Also, it's not impossible for the URL to be updated in the seconds between submission and indexing. In any case, I'll add something to refresh it daily.

>Given that competency search results will likely just need to return the competency, and that the graph for that framework can be loaded by tweaking the competency's URI (per your post above), maybe it makes sense to go with your original option 3 after all - provided this means you aren't pulling sub-entities out of the credential or something (no need to return a Cost Profile all on its own, that kind of thing).  In other words, search results should probably work the same way that retrieving stuff via the /resources/ URI works - you get the top-level document that has a match for your search somewhere in it.

Alright. It is the more robust solution for this problem.

>Ideally it should look at any field that has text in it - perhaps with some optional parameter (or maybe one where we can default the value to english) that tells it to only look at the values for language map keys that are in some given list of languages (e.g. "en-us", "en-gb", "en") for a match. Is it possible to weight fields higher than other fields (i.e. to have a match in the name be more important than a match in the description of a condition profile somewhere deeper in the data)?

I'm a very recent contributor to the project so I don't know the history of the search feature, but looking at what we have right now, apparently search is configured in a JSON file. [Example](https://github.com/CredentialEngine/CredentialRegistry/blob/master/fixtures/configs/ce_registry.json):

```
  "competency_framework": {
    "fts": {
      "full": [
        "$.ceasn:name.en-us",
        "$.ceasn:description.en-us",
        "$.ceasn:publisher[0].ceterms:name",
        "$.ceasn:localSubject[0].en-us"
      ],
      "partial": ["$.ceasn:name.en-us", "$.ceasn:localSubject[0].en-us"]
    }
  },
```

It is possible to add weights to the terms being indexed in PostgreSQL. One approach would be modifying that configuration file format to account for weights. For example:

```
"full": [
  {
    "path": "$.ceasn:name.en-us",
    "weight": "A"
  },
  {
    "path": "$.ceasn:description.en-us",
    "weight": "B"
  }
  ...
],
```

Also, I've realised that apparently only the english language is being indexed right now. If we are to index multiple languages, I'll probably need to update FTS to reflect that as well.

To clarify the discussion about `/search`, I'm talking about the `/search` endpoint in the CER API, and not the graph (Gremlin) search that is in the works. Those are two different things - `/search` appears to be a general-purpose FTS feature with predetermined filters, whereas Gremlin will allow users to construct arbitrary queries.

**Comment by cwd-mparsons** [comment]
@rsaksida Romulo, as the new data model has been implemented, can this issue be closed? I ask based on the last couple of entries that are related to search. If these are still open issues, we should create a separate issue, so this one can be closed.

**Comment by rsaksida** [comment]
@cwd-mparsons I believe it can be closed, yes. Regarding the discussion on search weights, I don't know if it's still relevant. I do know implementing the weights in Postgres won't be as simple as I had thought at the time (looking at my own comment). Pinging @siuc-nate for input on whether this is still required.

**Comment by siuc-nate** [comment]
We should probably close this one and, if it comes up again, open a new one for weights.

**Comment by stuartasutton** [comment]
Agreed, close it.
