### ISSUE TITLE
Gremlin search

### ISSUE THREAD

**Issue by rsaksida** [CredentialEngine/CredentialRegistry#203]
- [x] Create prototype in sandbox (writes using Neo4j)
- [x] Create more robust version (writes using Gremlin directly)
- [x] Add strategy for syncing up API database with the graph
- [x] Set up Gremlin in staging
- [x] Set up Gremlin in production

**Comment by siuc-nate** [comment]
Can this be closed?

**Comment by rsaksida** [comment]
Yes, thank you.
