### ISSUE TITLE
Request to promote production schemas from github to the PRODUCTION and Staging sites

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#205]
@jbaird123 @rradonic @science 
Followup for requests sent via email July 13th, July 19th, and July 25th
We would like to have the json validation schemas updated to the credential engine **production** and **staging** environments. The only change was to add the audienceType property to credentials, assessments, and learning opportunities.
I have updated the Production_Schema folder with the updated schemas:
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/Production_Schema

Please run the script to promote the updated schemas to the registry production and staging environments.
Thanks

**Comment by jbaird123** [comment]
@cwd-mparsons - I'll check on this....

**Comment by science** [comment]
@cwd-mparsons - this should be completed per email. Please close this or comment, depending..

**Comment by cwd-mparsons** [comment]
Thanks, closing this issue.
