### ISSUE TITLE
Additions to credential registry envelope for @graph updates

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#206]
@science @rsaksida We had discussed adding additional properties to the envelope to aid in identifying the content once we are publishing with @graph. As note in #202, there should not be additional properties at the same level as the graph (i.e. CTID, etc). 
We would like to add:

- CTID (ce-dd6715b8-19b4-4eb5-a765-8e1a197c61a3)
- Type (ceterms:ApprenticeshipCertificate, ceterms:AssessmentProfile, etc)

**Comment by cwd-mparsons** [comment]
@science @rsaksida 
Is there an update on this task?

**Comment by rsaksida** [comment]
@cwd-mparsons do you have an example JSON for the new data model? Ideally something that I could try to publish.

I'm assuming this is what you mean:

```
{
    "@graph": { ... },
    "@type": "...",
    "@ctid": "..."
}
```

If so, I don't think many changes will be necessary (if this results in changes at all).

**Comment by rsaksida** [comment]
I see. I have a couple of questions:

- What would be the use cases for this feature?
- Would `ceterms:ctid` and `@type` still appear in the payload?

It wouldn't be hard to add it, but if `ceterms:ctid` and `@type` disappear from the payload, I'll have to modify the search and indexing parts of the system that depend on those properties.

I suggest using `envelope_ctdl_type` for the `type` key.

**Comment by cwd-mparsons** [comment]
The rational for adding these properties to the envelope was to aid is determining what the envelope contained without having to inspect the payload. With the main content now within an @graph, the inspection is a little more complex. For instance when reviewing search results, I would find it very helpful to see the CTID and the CTDL type at the top of the envelope. 

As _**resource_data**_ is not particularly useful, I could see storing the ctdl type in the envelope_type property.

**Comment by siuc-nate** [comment]
>if ceterms:ctid and @type disappear from the payload, I'll have to modify the search and indexing parts of the system that depend on those properties.

They'll still be there - this is more a matter of convenience for developers.

**Comment by rsaksida** [comment]
@cwd-mparsons @siuc-nate I've added support for the `envelope_ceterms_ctid` and `envelope_ctdl_type` fields and deployed the update to sandbox and staging. I can rename the fields if you prefer something else.

@cwd-mparsons `envelope_type` is used elsewhere in the project. I can use it as well, but I'd have to change the data type for that column and refactor some code that makes different assumptions about it. I'd rather use a different name if possible, just for simplicity's sake, but of course let me know if you feel strongly about this.
