### ISSUE TITLE
Gremlin Search: how to filter by created and last updated

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#209]
We have a process to import data from the registry. We are using the current search and filter by resource type and last updated date (parameter = from). 
For this purpose, the current search should be retained.

However, I would think being to filter by at least last updated date will be useful. These dates are part of the envelope, not the payload. I don't recall if we discussed this. Are the created and last updated dates being stored with the graph versions of the credentials, etc?

**Comment by cwd-mparsons** [comment]
@rsaksida @science  Will it be possible to filter data with a last updated date? That is will the last updated date for a document be available for use in a Gremlin query?

**Comment by rsaksida** [comment]
Right now we're not storing that in the Gremlin documents. I'll add it - it should be done tomorrow.

**Comment by rsaksida** [comment]
For the record, I'm still working on this, which ended up taking a little more time than I expected.

**Comment by rsaksida** [comment]
@cwd-mparsons @siuc-nate it looks like there isn't a straight-forward way to store and query datetimes using Gremlin with a Neo4J backend. I can, however, store the epoch as a workaround (Unix  time). Does that work for you guys? In .NET this means you'd need to do a `.ToUnixTimeSeconds()` when building the query if you're working with a `DateTimeOffset`.

**Comment by cwd-mparsons** [comment]
@rsaksida @siuc-nate My first response would be preferably not, as this would seem to be a bit complex.
Alternately, or as well, could we have LastUpdated defined as a string? The format would be 'yyyy-mm-dd'
The latter would be more useful for display as well.
The epoch version could be included as well to enable more complex queries.

**Comment by rsaksida** [comment]
Storing a string representation is easy, but that won't enable ordering or filtering per date (by clauses such as `greater than` or `smaller than`). To enable querying, it looks like there's no alternative - I'll need to store them as epoch. I can help with implementation for that if you're writing queries in .NET.

For the record, I've already implemented storing the epoch. I'll add a string representation as well.

**Comment by edgarf** [comment]
@cwd-mparsons I added this task into the project, since it has "High Priority" label. However, it's a pretty old one. Is this still actual to be reviewed?
