### ISSUE TITLE
Test new JSON schema in Registry

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#21]
http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true
http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?asGroup=true
http://credreg.net/ctdl/schema/validation/LearningOpportunityProfile/json?asGroup=true

Provide examples of created entities

**Comment by siuc-nate** [comment]
Currently I'm in the process of updating our serialized JSON-LD output to match all the changes to CTDL that have been made in the last few months.  I could give you some example data, but it would be fairly small and incomplete (but perhaps still useful for validation).  My plan is to focus on this aspect and build it out so that we can start publishing full-fledged CTDL documents as soon as possible.

**Comment by leolara** [comment]
@siuc-nate Ok. This task was assigened to @andersoncardoso . The idea is that him is going to add your Schema to an actual instance of the registry and start inserting data to see if we missed something out in the schema or there are any bugs in the registry

**Comment by siuc-nate** [comment]
@leolara @andersoncardoso @mparsons1953 
All,
I have updated the JSON schema generator with the following changes:
- It now includes a definition for `@context` (see below)
- It now requires `@context` at the root level of the document
- All classes now have a `@type` property
- All classes now require a `@type` property
- All classes now have a `@id` property (because any class _could_ have an ID, either as a URI or a blank node identifier)
- Classes that have absolute URIs (credentials, organizations, assessment profiles, and learning opportunity profiles) now _require_ an `@id` property)
- Classes that have absolute URIs use an `@id` reference that is stricter and requires a format of URI (I've called it "`@id_absolute`" so as to have a different object to reference, but the property itself is still `@id`); other classes use a looser version (see below)

![image](https://cloud.githubusercontent.com/assets/21346519/24005310/ab8fe16e-0a36-11e7-95fc-a03ab5aa69b6.png)


Note: I seem to have accidentally (re?)introduced the error referenced in issue #20 - I will work on fixing this next.

**Comment by siuc-nate** [comment]
I have re-fixed the error in #20 as mentioned above.

I have also added enums for `@type` properties.

**Comment by leolara** [comment]
@siuc-nate 

mostly :+1:

I am not sure about your definition of @context, so I started a discussion here:
https://github.com/CredentialEngine/CredentialRegistry/issues/23

Also, I am not sure about `@id` in sub-entities, do we need them for sure? Can you explain?

**Comment by siuc-nate** [comment]
Here is a sample of credential data - it's not 100% complete, but it should be enough to start testing with:
https://gist.github.com/siuc-nate/ef7c26e77bcf683a445bea7f97c72925
Next week I plan to try to get some Organization data available to test with, too.

**Comment by leolara** [comment]
@siuc-nate one think I just realised looking at it, is that you have many fields, (for example ceterms:approvedBy) that are actually arrays of ids, but in the schema they are acutally just an id. Hence it would not work.

We would need to define the field on Credential:

instead of: 

```js
"ceterms:approvedBy": {
  "$ref": "#/definitions/ceterms:approvedBy"
}
```

we would need to have as field in the credential:

```js
"ceterms:approvedBy": {
   "type": "array",
   "items": { "$ref": "#/definitions/ceterms:approvedBy" }
}
```

You can combine both with AnyOf, if you want that "ceterms:approvedBy" can contain either an ID or an array of IDs

**Comment by leolara** [comment]
@andersoncardoso, @coffeejunk will work on this

**Comment by siuc-nate** [comment]
Good catch on the array thing - that completely slipped my mind.  

It will take some additional changes to our source data to enable the generator to reliably determine when something is or isn't supposed to be multi-value, but I will try to work on this today.

**Comment by siuc-nate** [comment]
I have updated the generated schema to use arrays for literals, URIs, and properties that point at profiles.  The results look like this:
![image](https://cloud.githubusercontent.com/assets/21346519/24113030/63cc69c0-0d69-11e7-83d3-983f9d4e2e4d.png)

I believe this is the correct format - if you spot any issues, please let me know.

Note that booleans, date/times, and numbers are deliberately not arrays.  The approach as it is now reflects what I **suspect** we will end up doing in regards to these two issues:
https://github.com/CredentialEngine/vocabularies/issues/352
https://github.com/CredentialEngine/vocabularies/issues/353

Those issues are important, but they have repeatedly slipped through the cracks - hopefully this will help us deal with them.

**Comment by leolara** [comment]
@siuc-nate I think inside anyOf you will need to have `items` otherwise the type object in the reffered will contradict the type array

Also, consider if you want to allow both, single element and multiple options you can do it with AnyOf:

```js
"ceterms:approvedBy": {
  "AnyOf": [
   {
    "$ref": "#/definitions/ceterms:approvedBy"
   },
   {
    "type": "array",
     "items": { "$ref": "#/definitions/ceterms:approvedBy" }
   }
  ]
}
```

**Comment by leolara** [comment]
@siuc-nate @coffeejunk @andersoncardoso to clarify everyone this task has gone a bit off topic. The idea of this task was that LT ( @andersoncardoso  or  @coffeejunk ) will load these schemas on the registry and test that they work and we can add resources.

So this task is currently assigned to @coffeejunk

**Comment by siuc-nate** [comment]
@leolara I have updated the validation code again per your suggestion.  I also cleaned up some of the code for handling literals.  Regarding the two issues I mentioned (specifically https://github.com/CredentialEngine/vocabularies/issues/353 ), we discussed these internally yesterday and went in a different direction from what I had anticipated - so I have changed the validation to match.

This screenshot captures many of the results of these changes:
![image](https://cloud.githubusercontent.com/assets/21346519/24212017/ea71e46c-0efb-11e7-99b9-d104eee12dcf.png)
where those made up meta: items refer to these things near the top of the serialization:
```
"definitions": {
    "@id": {
      "type": "string"
    },
    "@id_absolute": {
      "type": "string",
      "format": "uri"
    },
    "meta:identifier": {
      "type": "object",
      "properties": {
        "@id": {
          "$ref": "#/definitions/@id"
        }
      }
    },
    "meta:identifier_multi": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/meta:identifier"
      }
    },
    "meta:uri": {
      "type": "object",
      "properties": {
        "@id": {
          "$ref": "#/definitions/@id_absolute"
        }
      }
    },
    "meta:uri_multi": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/meta:uri"
      }
    },
    "meta:literal": {
      "type": "string"
    },
    "meta:literal_multi": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/meta:literal"
      }
    }
```

**Comment by leolara** [comment]
@siuc-nate I see from what you are doing that you are decided to using always multiplicity. For me is ok

**Comment by siuc-nate** [comment]
In a nutshell:
- strings and URIs are either single or multiple depending on the property
- properties that point to other objects are always multi value
- numbers, dates, and booleans are always single value

**Comment by coffeejunk** [comment]
I was able to publish a variation of @siuc-nate's [sample credential](https://gist.github.com/coffeejunk/318ff0c55a27db7035540e84372e1058#file-sample_credential-json) (gist includes [diff](https://gist.github.com/coffeejunk/318ff0c55a27db7035540e84372e1058#file-diff-txt) with the original).

Full log of [creation, update and deletion of the resource is available here](https://gist.github.com/coffeejunk/bb7a18f970c9f56987618667185bc7b4#file-log-md)

**Comment by leolara** [comment]
@coffeejunk that's very good!

**Comment by leolara** [comment]
@siuc-nate @cwd-mparsons please, if you were to provide more examples of credentials and other resource types that would be helpful

**Comment by siuc-nate** [comment]
I'm not familiar with the way gist works, so I'm afraid I'm not quite sure how to interpret that diff.  I assume the - and + prefixes mean "remove this line"/"add this line" or something similiar - it seems there are a number of differences if that is the case.

Can you post the version of the JSON that did pass validation? That might be easier for me to work with.

Thanks.

**Comment by leolara** [comment]
@siuc-nate this is the credential:

https://gist.github.com/coffeejunk/318ff0c55a27db7035540e84372e1058#file-sample_credential-json

there is no diff in this in this file, just the test. You can click **raw** to download the actual file

**Comment by leolara** [comment]
@siuc-nate gist diffs are the same as github diffs

And this diff https://gist.github.com/coffeejunk/318ff0c55a27db7035540e84372e1058#file-diff-txt

is the standard diff format, not special for github

**Comment by siuc-nate** [comment]
Regarding the sample: I wasn't sure if that was the sample we gave you or the modified sample that passed the validation, thanks.

Regarding diff: What I meant was, I've not worked with diff before so I am not familiar with how it works or how to interpret it.

**Comment by leolara** [comment]
@siuc-nate Sorry, I misunderstood

**Comment by leolara** [comment]
@siuc-nate Max has created some scripts in bin/ folder that should help you to test the operations against the API:

https://github.com/CredentialEngine/CredentialRegistry/blob/0f0dce8294c6fc7d9f61b17a8ad2bd3e45cb1f41/docs/99_developer_notes.md

Anyway, if we get resource examples we can test them against the platform

**Comment by cwd-mparsons** [comment]
@leolara @siuc-nate 
Leo
I will upload some examples of credentials.
Do you want organizations, assessments, and learning opportunities as well?
Also, we could you, and your team can have access to our test server. Then you can search for data, and view the detail pages, which have  a section that displays the json that would be used to publish to the registry.
To create an account, go to: 
http://ctitest.siuccwd.com/ 
- Register (menu on the right side)
- You will be sent an email to confirm the account
- I will be notified, and then give you or your team members read access to the credentials, etc.

**Comment by cwd-mparsons** [comment]
Credential with the properties as arrays
https://gist.github.com/cwd-mparsons/4fa334d51ddf308ed09bc2f0d096a65c

**Comment by coffeejunk** [comment]
> Credential with the properties as arrays
> https://gist.github.com/cwd-mparsons/4fa334d51ddf308ed09bc2f0d096a65c

```
Resource JSON Schema validation errors: 
[
  "ceterms:jurisdiction : did not match the following type: array",
  "@type : did not match one of the following values: ceterms:SecondarySchoolDiploma"
]
```

> web design
> https://gist.github.com/cwd-mparsons/8492e51ce6073cb4d3d14f2c38eb3a5d

```
Resource JSON Schema validation errors: 
[
  "ceterms:subjectWebpage : did not match the following type: array",
  "ceterms:jurisdiction : did not match the following type: array",
  "@type : did not match one of the following values: ceterms:SecondarySchoolDiploma"
]
```

> another
> https://gist.github.com/cwd-mparsons/4e0b80f5a15a629663a282471e18cf18

works without error

**Comment by leolara** [comment]
@cwd-mparsons please provide examples of the 4 types.

**Comment by leolara** [comment]
@cwd-mparsons @siuc-nate are those comments from @coffeejunk fixed?

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
I believe the issues were fixed, however we need to get the schema updated in the registry, as Nate has made many fixes. You can use the following to get the current schemas:
http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true
http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?asGroup=true
http://credreg.net/ctdl/schema/validation/LearningOpportunityProfile/json?asGroup=true

I would now suggest we close this issue, and open new ones as needed for the current version of the schema.

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
[17-04-14.zip](https://github.com/CredentialEngine/CredentialRegistry/files/922666/17-04-14.zip)

I added a process for  batch publishing/generating a payload. Attached is a zip with 20 or so of each entity.
