### ISSUE TITLE
Gremlin Search: how to control the sort order of results

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#210]
What is the default order of results from a Gremlin query? For example:
g.V().has(label,of('ceterms_BachelorDegree'))

With complex queries, how can the sort order by specified. For example, by:
- credential name
- last updated
- Address.City
etc

**Comment by jbaird123** [comment]
@cwd-mparsons - There is no default sort order in Gremlin.  If you need to sort a result set, use the Gremlin `order()` or `order().by()` functions.  
Examples:
```g.V().values('name').order()
g.V().values('name').order().by(desc)
g.V().hasLabel('person').order().by('age', asc).values('name')```

For reference:
http://tinkerpop.apache.org/docs/current/reference/
