### ISSUE TITLE
Optimise Gremlin proxy endpoint

### ISSUE THREAD

**Issue by rsaksida** [CredentialEngine/CredentialRegistry#211]
Right now, the Gremlin proxy endpoint (`/gremlin`) that decompresses the original submitted payloads is not performing optimally.

We need to measure performance to find out what the bottleneck is, and come up with a solution for improving it.

**Comment by siuc-nate** [comment]
Can this be closed?

**Comment by rsaksida** [comment]
It seems that we know more about the performance issues now, and the performance story is a bit more complex (relates to Azure/AWS, number of simultaneous queries, etc). Plus when it comes to the Gremlin proxy specifically, there's been some discussion about moving away from its current implementation that decompresses payloads on the fly. I believe this issue is too generic in its current format, not relevant anymore, and can be closed.
