### ISSUE TITLE
Registry Service - a new scheduled process to regularly validate links in the registry

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#213]
@science @rsaksida We had early discussions regarding useful services for the registry. One of these was a link checker. A process to regularly crawl through the active registry documents, extract links and verify if still valid. 
We have already received comments that some of the links are no longer correct. 
We need the process to:
- find URL properties
- validate if resolvable
- log the issue
- have a process to do notifications

The notifications process needs to be designed. There may not be contact information for the target document. A possible process would be to expose a new API endpoint in the accounts site. The latter has the necessary information for an organization. The registry process could send a message to the accounts API with the organization CTID, and message. The accounts site would then be responsible for handling contacting the organization. 
What would be the timeframe for creating a service like this?

**Comment by rsaksida** [comment]
@cwd-mparsons that doesn't sound like a complex service. What is the accounts API you are referring to?

If I'm understanding this correctly, this is roughly what the service would do:

- Periodically go through the API's documents, parse out all the URLs referenced anywhere in them
- Check whether the URLs are returning a valid HTTP response. Log the ones that don't
- Notify an external API with some data about the problems that we found

I estimate this can be done in 8 to ~20 hours of development. As for the timeline, it would take around a week.

**Comment by siuc-nate** [comment]
@cwd-mparsons  is working on this as a service that we will handle.
