### ISSUE TITLE
Enabling skip validation when publishing to the endpoint where registry manages the envelope

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#215]
@rsaksida @science 
As a followup to the Email from Oct. 13, 2018, I added this issue to track this task/request. 
Team
As you know there are two approaches for publishing to the registry.
Using self-signed envelope:
https://credentialengineregistry.org/ce-registry/envelopes?update_if_exists=true

Using URL where registry signs envelopes:
https://credentialengineregistry.org/resources/organizations/{0}/documents

Previous to the current update, we had the registry use a Json validation schema to validate the document being published. We are not using the Json validation schema at this time for the new format. Using the first method we have been appending skip_vaidation=true so the Json validation schema is not used.
We need to also skip the Json validation for the second method of publishing.
We need to have the JSON validation turned off, or alternatively enable the equivalent of skip_validation for the second method?

**Comment by science** [comment]
Do you think you want to turn on json validation at some point for the new format? If so, then we need to disable it temporarily for both publish methods, and re-enable it later (rather than deprecate)..

**Comment by cwd-mparsons** [comment]
I suppose that we might want to turn it on at some point. 
I had found creating the JSON validation schema for the new data format to be fairly complicated, so as the API was already responsible for outputting data in the correct format, I deferred implementing the validation schema. 
I would suggest that if just disabling the json validation is simple, then that would be the preferred action at this time.

**Comment by siuc-nate** [comment]
It might be good to have it as a fallback that has relatively simple validation for _anything_ we'd want to put in the registry (e.g., must have `@graph` and `@id`) so as to prevent accidental publishing that may occur otherwise unnoticed later on if we end up with a bug in our publisher or something.

Probably not a high priority at this time, but I agree that trying to generate the JSON schema for CTDL is extremely complex.
