### ISSUE TITLE
Consider including blank node data in an injected field in search results

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#218]
I have been thinking about how to handle blank nodes related to search results.  Currently they are excluded from the search altogether, but it might be useful to do queries along the lines of "all credentials accredited by [organization that only exists via blank nodes]" (e.g. find everything with an `accreditedBy` node whose `subjectWebpage` contains a certain domain).  We want to avoid duplicate search results (this can be done by filtering out blank nodes as things that can be returned on their own, and is already being done) but (perhaps) still include the blank nodes with the results themselves.  

We want to avoid adding `@graph` payloads to the search, as this would no doubt introduce a ton of complexity, but maybe the relevant blank nodes can be artificially injected (at index time?) via some kind of search-only field at the root level of the search result (e.g. `search:blankNodes` or `search:graphItems` or something like that). This would make it possible to query for records by blank node data, and to return/include blank node data inside of whatever result it's relevant to. 

Example search result:

```
{
	"@context": " http://credreg.net/ctdl/schema/context/json",
	"@type": "ceterms:Credential",
	"ceterms:accreditedBy": [
		"_:ABCDEF"
	],
	"search:blankNodes": [
		{
			"@id": "_:ABCDEF",
			"ceterms:subjectWebpage": "http…"
		}
	]
}
```

This might make it easier to consume search result data directly (it also greatly simplifies the documentation). Otherwise, in order to ensure complete data, the user would have to:
- Do a search and get the results
- For each result, convert the `/resources/` `@id` to a `/graph/` `@id`
- For each converted URI, retrieve the `/graph/` data
  - This potentially incurs many additional hits against the registry, if it is automatically done for each result
  - The user would mostly be re-downloading data they already have in the search result itself
  - This is the only way to get the `@context` for a result (see #217)
  - This is the only way to get the blank nodes for a result

**Note:** This data injection would only apply to blank nodes (anything whose `@id` starts with `_:`, not to competencies or other data that rightfully _should_ be retrieved via a request to the `@graph` endpoint
**Note 2:** We would need to decide on what to name such a property (I am currently using the "search" prefix/namespace for all search-specific functionality, though this is not yet documented anywhere).

**Comment by siuc-nate** [comment]
@stuartasutton I think it makes sense to put it there - I just wanted to note (somewhere) that such a namespace exists (sort of).

**Comment by siuc-nate** [comment]
An alternative that may or may not be a better idea in the long run would be to simply replace all of the `/resources/` style `__payload` data in the search index with the equivalent `/graph/` data.  

I'm not sure what impact that would have on any number of aspects of the search, or processing the results, or how that would work with things like competency frameworks (in essence every search result for frameworks would then **have** to include every competency for that framework), but it does avoid the complexity of the proposed field.  It probably creates more problems than it solves, though. Hm.

**Comment by siuc-nate** [comment]
Or, we could leave the search as-is (aside from injecting the `@context`) and thereby avoid deliberately having a _third_ form of data in the registry (the structure of `/resources/` URI data, the structure of `/graph/` URI data, and the structure of a search result, each of which is _almost_ the same but not quite, and has to be documented as such).  

This would entail deciding that the above "get the results and then download the graph only for each one you care about" steps make sense and are a best practice (which might indeed be true), and documenting them as such.

**Comment by cwd-mparsons** [comment]
@rsaksida We need to get blank nodes in search results somehow. We had an example where we searched for credentials approved by a QA org. We got the expected number of results, but as the QA org was referenced via a blank node, there is no information about the org in the results.
I would agree that returning the whole graph could seem to be a problem for competency frameworks, but the number of frameworks is small compared to credentials, and other document types.
Any thoughts on this?

**Comment by rsaksida** [comment]
Just to clarify some points:

- The Gremlin indexer does index blank nodes. For example if you query `g.V().has('__graph_id', 'ce-bae4597a-813d-41eb-897c-1ee5d5952b27').out('ceterms:accreditedBy').valueMap('@id')` you'll get a blank node. It is possible to navigate the graph of blank nodes.
- The injected payload property is very cumbersome to work with. It is implemented in the following way: in the indexer, we compress the JSON representation for the envelope and add it to the `__payload` property. In the API proxy for the Gremlin server, we parse the JSON results from the Gremlin response and replace any found `__payload` properties with the decompressed data.
- Blank nodes do not show up embedded in resource documents, but are instead discrete resources in the graph, thus they are not injected in other resources' payload properties.

If I understood the issue correctly, the problem is you'd like to retrieve the blank nodes in the graph along with the main resource you're querying for. Is that correct?

In that case, I think we should implement this with the solution outlined in https://github.com/CredentialEngine/CredentialRegistry/issues/217#issuecomment-440679054. At the moment, fiddling with the `__payload` property in the indexer would make the code even more cumbersome. I'd like to move this kind of complexity out of the indexer and on to the API proxy.

**Comment by siuc-nate** [comment]
Can you elaborate on how the solution in that comment would be used to return bnodes along with the main documents/results? Would the mode that returns top-level documents essentially return the entire `@graph` instead of just the main resource?  If it were to return the entire published document (that is, the _entire_ payload), that might also solve the issue of the missing `@context`.  If it's something that can be implemented without disturbing the current search setup/API/etc, it may be worth looking into.

**Comment by siuc-nate** [comment]
On the flip side, @cwd-mparsons, is this something that can be handled by just retrieving the `@graph` via the normal /graph/ endpoint after search results are retrieved?

**Comment by rsaksida** [comment]
@siuc-nate 

Yep, the idea is that the Gremlin endpoint in "easy mode" would just return the entire envelope for the CTID that was found in the Gremlin query. Including the `@graph`, `@context`, and everything. We could adjust it as needed. Roughly it'd work in the following way:

1. Send request to `/gremlin?mode=ctid`. The convention would be that the Gremlin query would return a CTID. For example `g.V().has('@id', '...').valueMap('@id')`. The query itself doesn't matter as long as we're able to locate an ID in the query's result.

2. The API endpoint proxying the query will look at the result set returned from Gremlin and find the CTID. It'd then fetch the envelope for that CTID from the CER Postgres database and return that (in JSON format) to the client.

**Comment by siuc-nate** [comment]
This has been taken care of and is now in use in the search API.
