### ISSUE TITLE
Adding @type to JSON schema

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#22]
JSON-LD fields are not in JSON schema by default.

Whereever @type is necessary, it should be added, using JSON schema ```enum``` to fix it values.

To have ```enum``` with only one value is like setting the value of the field to be constant. That plus adding @type as required if that is necessary to comply with JSON-LD

**Comment by siuc-nate** [comment]
I have added this to all classes:
![image](https://cloud.githubusercontent.com/assets/21346519/24007506/cdfb7226-0a3c-11e7-82db-04d0f91f3055.png)

**Comment by leolara** [comment]
@siuc-nate I think this is correct and I close this issue
