### ISSUE TITLE
can't access competency management page

### ISSUE THREAD

**Issue by brandonopened** [CredentialEngine/CredentialRegistry#222]
From: https://credentialengine.org/accounts/Dashboard
I tried to navigate to the Competency Frameworks page by selecting "Get Started" and was given an error
<img width="626" alt="screen shot 2018-12-11 at 2 39 28 pm" src="https://user-images.githubusercontent.com/14943151/49835002-c50e6280-fd52-11e8-892a-575825243956.png">

I am however able to access it via other menus etc - https://credentialengine.org/publisher/Competencies

**Comment by cwd-mparsons** [comment]
@brandonopened This issue has been corrected, thanks for your submission.
