### ISSUE TITLE
Minimum data requirements for CompetencyFrameworks

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CredentialRegistry#224]
Where do we stand on the minimum data requirements for competency frameworks/competencies? The [Minimum Data Policy](http://credreg.net/registry/policy) shows none. We documented the minimum some time ago in the [spreadsheet that guided the editor development](https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803) and memorialized the result in a [google doc](https://docs.google.com/document/d/1_3Ig1YqNyn3k331oquDel71SCi61xHeRQZeGhO2TKDY/edit#heading=h.gjdgxs). 

Can we go ahead and update the [Minimum Data Policy](http://credreg.net/registry/policy)?

**Comment by siuc-nate** [comment]
We have determined the minimum data for competency frameworks.
