### ISSUE TITLE
Graph query that works in production, doesn't return data in sandbox

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#225]
@rsaksida I have been seeing inconsistent results with some queries. The following returns data in production, but not in the sandbox.
  "@type": "ceasn:CompetencyFramework",
  "ceasn:source": "search:anyValue"
The following image shows data exists:
![image](https://user-images.githubusercontent.com/26332112/56306029-25e5e700-6107-11e9-9929-8e4f6b1e787c.png)

The actual queries we need to run are like:
  "@type": "ceasn:CompetencyFramework",
  "educationLevelType": "search:anyValue"

There is no data for the latter in production, but there is in the sandbox. 

There appears to be a difference in the environments.

**Comment by edgarf** [comment]
Hi @cwd-mparsons. Apologies for such late reply here.

Are we getting it right that you expect identical responses from the two environments for the given query? The thing is, sandbox and production have completely different sets of data (the former contains 10x times fewer envelopes than the latter). We can suggest to sync sandbox with production periodically, if it’s important to get consistent search results across both environments.

Let us know if that's the issue!

**Comment by cwd-mparsons** [comment]
@edgarf The issue is that the data does exist. I had specifically published a competency framework with educationLevelType.
Actually I just tried the search again, and now data is being returned. 
{
  "Skip":"0",
  "Take":"10",
  "Query":  {
  "@type": "ceasn:CompetencyFramework",
  "ceasn:educationLevelType": "search:anyValue"
}
}
So the issue now appears to have been resolved.

**Comment by edgarf** [comment]
Clear, thank you!
