### ISSUE TITLE
Some records in the index use /graph/ instead of /resources/ in the @id for their main resource node

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#227]
Republishing the data does not appear to fix the issue.

This results in description sets failing to retrieve any connected data (e.g., loads frameworks with no competencies).  The data is correct in the **registry** but incorrect in the **index**.

Some samples:

**CCO Mobile Crane Operator Written Core Examination**
ce-b0f16f1d-4612-4f54-bb63-11b8584eb8d5
Correct data in the registry: https://credentialengineregistry.org/graph/ce-b0f16f1d-4612-4f54-bb63-11b8584eb8d5
Incorrect data in the index (the `@id` for the framework node uses /graph/ instead of /resources/ ): 
```
g.V().has('@id',test({x,y -> x ==~ y}, /(?i)http.*/)).as('main').and(
has('ceterms:ctid',test({x,y -> x ==~ y}, /(?i).*ce-b0f16f1d-4612-4f54-bb63-11b8584eb8d5.*/))
).union(select('main').count(),select('main').skip(0).limit(5).union(__.values('__payload').fold(),union(__.out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload')).dedup().fold()))
```

**Beta Connecting Credentials Framework**
ce-c62c336f-a76d-4d7f-a777-367e7cc72d17
Correct data in the registry: https://credentialengineregistry.org/graph/ce-c62c336f-a76d-4d7f-a777-367e7cc72d17
Incorrect data in the index (the `@id` for the framework node uses /graph/ instead of /resources/ ):
```
g.V().has('@id',test({x,y -> x ==~ y}, /(?i)http.*/)).as('main').and(
has('ceterms:ctid',test({x,y -> x ==~ y}, /(?i).*ce-c62c336f-a76d-4d7f-a777-367e7cc72d17.*/))
).union(select('main').count(),select('main').skip(0).limit(5).union(__.values('__payload').fold(),union(__.out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload')).dedup().fold()))
```

![image](https://user-images.githubusercontent.com/21346519/57092759-be689380-6cd1-11e9-91a1-59e06d4a542a.png)

**Comment by science** [comment]
@siuc-nate I might be missing some expertise and context on the current state of the CTDL structure we've settled on (ignorance warning) but it seems like there's inconsistency between the "master" @id and the interior "graph" @id for the resource?

[For example:](https://credentialengineregistry.org/graph/ce-c62c336f-a76d-4d7f-a777-367e7cc72d17)
```<snip>
"@id":"https://credentialengineregistry.org/graph/ce-c62c336f-a76d-4d7f-a777-367e7cc72d17","@graph":[{"@id":"https://credentialengineregistry.org/resources/ce-c62c336f-a76d-4d7f-a777-367e7cc72d17"
<snip>
```

Shouldn't that first @id point to /resources/ as well? Again apologies for (possibly) not being 100% current on our agreed publishing format.

**Comment by stuartasutton** [comment]
No, they should not point to the same thing since they aren’t the same thing. One is a uri of a graph (multiple resource descriptions) and the other the URI of one description in that graph.

**Comment by cwd-mparsons** [comment]
@science The /graph object contains the main object (i.e. credential), and any child components or blank nodes. The /resource object just returns the top level object. 
So the first @id/master id is the for the whole graph, and the interior @id is for just that object. 
This pattern is best seen with a competency framework. A framework can have hundreds of competencies. The framework and each competency have their own @id for the /resource endpoint. 
The @id for the /graph endpoint would return the framework and all of the competencies.

**Comment by science** [comment]
Thanks @cwd-mparsons and Stuart. Question based on Mike's comment (and for @siuc-nate too): 

So during submission to CredReg, things function correctly. When retrieving from CredReg via /graph or /resource APIs, things are returned correctly?

But when retrieving via Graph search (gremlin), the two URIs for a CTID (/graph and /resource) are being conflated somehow, and in cases where it is correct to receive a URI to /resource for a given CTID, you are incorrectly being returned a /graph URI with the CTID?

Is that a decent summary of the problem in one sentence?

**Comment by siuc-nate** [comment]
Not exactly.  In looking at my original post again, I think I may have emphasized the wrong thing accidentally, leading to your confusion.  Sorry about that.

To rephrase the issue:
There are a number of records in the registry (so far, the ones I've found have been competency frameworks) where something seems to have gone wrong with the graph search indexing process.  These problematic records have not been linked to anything else in the index, making it impossible to traverse (for example) from a framework out to its competencies (or in from its competencies to the framework).  

The common thread among these broken frameworks in the index is that, if you retrieve them directly from the index (e.g. as search results), they have a `/graph/` URI instead of a `/resources/` URI in their `@id` field.  Retrieving these same frameworks directly from the registry (not via search), however, yields data that correctly has a `/resources/` URI in its `@id` field.

My theory is that because the index looks for links that match a value in one field (like `ceasn:isPartOf`) to an `@id`, the reason these broken frameworks in the index do not link to their respective competencies in the index is because the competencies are pointing to records that do not technically exist in the index.  

In other words, if a framework is (incorrectly) identified with a `/graph/` URI, then no record in the index exists that has that same CTID at the end of a `/resources/` URI, which means the indexer has nothing to attach the competencies to (the competencies all use `/resources/` URIs in their relevant fields).

So, frameworks and competencies like this work:
```
{
  "@type": "ceasn:CompetencyFramework",
  "@id": "https://.../resources/ce-12345"
}

{
  "@type": "ceasn:Competency",
  "ceasn:isPartOf": "https://.../resources/ce-12345"
}
```

But frameworks and competencies like this do not:
```
{
  "@type": "ceasn:CompetencyFramework",
  "@id": "https://.../graph/ce-67890"
}

{
  "@type": "ceasn:Competency",
  "ceasn:isPartOf": "https://.../resources/ce-67890"
}
```
Because, my theory goes, no such record with `@id` of `https://.../resources/ce-67890` exists in the index.

My guess is that these frameworks were incorrectly published initially.  For whatever reason, republishing them does not fix the issue (perhaps the indexer thinks those `@id`s already exist?).

Again, this only applies to _some_ frameworks, seemingly at random.  You can find them in the credential finder's competency framework search (they're the frameworks that show up without any competencies).

**Comment by science** [comment]
Looks like this was an error in data: we fixed this problem but when we reindexed, it didn't fix existing records. Our current AWS indexing prototype was built from scratch and doesn't have this problem, so @excelsior is looking into why the production index is defective. I think we have a good path for resolving this..

**Comment by edgarf** [comment]
This should be fixed.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons @siuc-nate verify this and if fixed, close this issue.

**Comment by edgarf** [comment]
Greetings, just checking if we can close this issue. @jkitchensSIUC @cwd-mparsons @siuc-nate

**Comment by siuc-nate** [comment]
This was handled by the index refreshes, so yes, it should be fine to close.
