### ISSUE TITLE
Enable searching URI properties as strings or as traversals

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#228]
Currently the search index does not enable examining properties marked as `"@type": "@id"` in the context as both a raw string (e.g. a text search on the URI itself) and a traversal.  Only the traversal is enabled.

This means that properties like `ceterms:subjectWebpage` are effectively useless in the search, since their string values cannot be queried.

It also forces traversals for cases where they may not be intuitive.  For example, if someone writing a query knows the CTID for an organization and wants to do a partial text match on the value of `ceterms:ownedBy`, they won't be able to.  They will have to traverse via `ceterms:ownedBy` to the organization object and query its `ceterms:ctid` value.

**Comment by jbaird123** [comment]
@siuc-nate - I'll start investigating this.  In the meantime, if you have some example queries to help illustrate the issues that would be helpful.

**Comment by siuc-nate** [comment]
https://credreg.net/quickstart/queryhelper?showgremlin=true

Try these:
```
{
  "ceterms:subjectWebpage": "http"
}
```
```
{
  "ceterms:ownedBy": "https"
}
```

**Comment by jbaird123** [comment]
Thank you!

**Comment by siuc-nate** [comment]
Slightly more realistic examples:

Say you wanted to do a partial string match of a CTID in the ownedBy field:
```
{
  "ceterms:ownedBy": "ce-7ce4a2e7-0d1c-443b-aa95-9fd78edf7e3a"
}
```
You get nothing back.  But if you traverse via that same field and query the CTID field of the next document over, you get records that have that same ctid in their ownedBy fields, and thus should have matched the partial string:
```
{
  "ceterms:ownedBy": {
    "ceterms:ctid": "ce-7ce4a2e7-0d1c-443b-aa95-9fd78edf7e3a"
  }
}
```

And if you wanted to look for a URL (or part of a URL) in the subjectWebpage field, you are completely out of luck, since there is no "next document over" to traverse to:
```
{
  "ceterms:subjectWebpage": "https://certification.comptia.org/certifications/project"
}
```
Even though at least one record with that value in that field exists:
https://credentialengineregistry.org/resources/ce-c57948c2-6636-4ed3-9b51-bc5a9ec56d88

**Comment by siuc-nate** [comment]
Part of this is an unfortunate by-product of the JSON-LD context [not distinguishing](https://github.com/CredentialEngine/vocabularies/issues/560) between properties that are meant to be traversed and properties that are specifically intended to always be URL literals.  That might be something we could solve in the linked issue, but it would be nice to be able to query any property with a string as its value with a string query regardless of whether or not it's intended to be traversed.

One potential (and somewhat ugly?) option for that would be to inject extra properties into the indexed data to enable querying the traversal (by default) or the string data for that property.  For instance, suppose the indexed document for a given record had both a `ceterms:ownedBy` property that functioned the same way it does today, and also a `ceterms:ownedBy_rawdata` (or `rawdata:ownedBy` or `rawdata_ceterms:ownedBy` or whatever) property that was specifically intended to be queried as a string and contained the raw URLs that were originally published with that document. I can update the CTDL-to-gremlin processing to make use of that (e.g. if the property is `"@type": "@id"` and the value passed in from the client is a string rather than an object, query against the string property in the index instead of going for the traversal).

**Comment by jbaird123** [comment]
@siuc-nate - this is great context.  Give me a little time to investigate.

**Comment by jbaird123** [comment]
@siuc-nate - I think there are a variety of issues here.  Some of them I think stem from confusion around how the graph data is actually modeled (which items are vertices, which are edges, and which are properties).  I think this can be addressed in the near future as I will work on putting together a document to describe in detail how the data is modeled.  As part of that exercise, we can work through each of the issues you raised above one by one.

However... Before we dig too far into your examples, I found a problem with the Gremlin code you are generating.  This should be resolved first before we dig further.

The Gremlin code you generated based on this:
`{
  "ceterms:subjectWebpage": "http"
}`

Is this:

`g.V().has('@id',test({x,y -> x ==~ y}, /(?i)http.*/)).as('main').and(has('ceterms:subjectWebpage','test({x,y -> x ==~ y}, /(?i).*http.*/)')).union(select('main').count(),select('main').skip(0).limit(5).union(__.values('__payload').fold(),union(__.out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload')).dedup().fold()))`

Take a look specifically at this part:

`has('ceterms:subjectWebpage','test({x,y -> x ==~ y}, /(?i).*http.*/)')).`

The single quotes around the test expression need to be removed.  You're actually looking for a literal value of 'test({x,y -> x ==~ y}, /(?i).*http.*/)' which will never return any results.  If you remove those single quotes, the query works.

So I would suggest making that change, and then we should look at what issues remain after that.

**Comment by siuc-nate** [comment]
Good catch.  I will have to look into why that is getting wrapped in quotes for these fields but not for fields like name (the query generated for that looks like this):

```
g.V().has('@id',test({x,y -> x ==~ y}, /(?i)http.*/)).as('main').and(
both('ceterms:name').properties().hasValue(test({x,y -> x ==~ y}, /(?i).*degre(?:y|e|s|es|ies|er|ing|ement).*/))
).union(select('main').count(),select('main').skip(0).limit(5).union(__.values('__payload').fold(),union(__.out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload')).dedup().fold()))
```

**Comment by jbaird123** [comment]
@siuc-nate - I see 2 problems with the Gremlin code generated by this query:

`{
  "ceterms:ownedBy": "ce-"
}`

The Gremlin code generated is:

`g.V().has('@id',test({x,y -> x ==~ y}, /(?i)http.*/)).as('main').and(has('ceterms:ownedBy','test({x,y -> x ==~ y}, /(?i).*ce-.*/)')).union(select('main').count(),select('main').skip(0).limit(5).union(__.values('__payload').fold(),union(__.out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload')).dedup().fold()))`

The first problem is the same as the earlier issue: The test function is wrapped in single quotes.

The second problem is that you are treating ceterms:ownedBy as a property of the vertex, when in reality it is an edge pointing to a different vertex, so instead of using `has('ceterms:ownedBy',test....)`, you should be using `out('ceterms:ownedBy').has('@id',test(...))`.  This query works and should accomplish what you are looking for:

`g.V().has('@id',test({x,y -> x ==~ y}, /(?i)http.*/)).as('main').out('ceterms:ownedBy').has('@id',test({x,y -> x ==~ y}, /(?i).*ce-.*/)).union(select('main').count(),select('main').skip(0).limit(5).union(__.values('__payload').fold(),union(__.out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload')).dedup().fold()))`

**Comment by siuc-nate** [comment]
In the data (from the perspective of a partner developer), `ceterms:ownedBy` _is_ a property of the document (e.g. a CTDL document with an ownedBy property that has an array of URIs as its value). My thinking is that it would be more intuitive, in general, to be able to query such properties as if they contained the raw value they hold in the published document.  However, if there really is no issue (aside from the test wrapping) with queries for URI properties (like subjectWebpage), then I can probably add something to the JSON-to-gremlin translation code for known properties like ownedBy that forces them to traverse the graph and use `@id` instead.  That way other developers don't have to figure out that they need to do that.

I'll try to address these as soon as I can.

**Comment by jbaird123** [comment]
I think your suggestion to change the JSON-to-Gremlin query translation is the right one.  Even though CTDL might consider this a property, the graph database considers this a relationship between two vertices (because the entity referenced by ownedBy is an entity in it's own right).

**Comment by jbaird123** [comment]
When I get some documentation put together to describe all of this, that should make things easier for you.

**Comment by siuc-nate** [comment]
Working out how to express something whose value is either an object or a URI depending on whether you're looking at it at the schema/semantic level or the JSON level (plus the aforementioned issue with `@id` being used as a data type for both URIs to things in the schema and all other URLs) is a challenge in other areas too, so it's no surprise that it's been a monkey wrench here.

Let me take a stab at fixing things on my end first, and if there are still outstanding issues, then we can examine it in closer detail.

**Comment by jbaird123** [comment]
@siuc-nate - I looked over the other examples you provided, and I'm pretty sure the two fixes mentioned above will resolve all of those issues.  If not let me know.

In the meantime, I'll be working on some documentation to help avoid this in the future.

**Comment by jbaird123** [comment]
@siuc-nate - Can we close this issue?

**Comment by siuc-nate** [comment]
Yes, this seems to be resolved now.  Thanks for the help.
