### ISSUE TITLE
Index is not being updated, or not in a timely fashion

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#229]
We have been testing publishing data to the registry to verify the search index gets updated. 
I updated the competency framework: NOCTI 21st Century Skills for Workplace Success.
CTID: ce-d3ba13a5-9788-4aa2-a1cb-79c2a89f7545
"envelope_id": "1f49dbb8-d97c-42d0-a63f-2ec24eebf2f4"
The envelope has the following updated_at value: 2019-06-03 22:07:13 UTC
![image](https://user-images.githubusercontent.com/26332112/58841173-512c8300-862e-11e9-8785-ea319e3b5e46.png)

**The framework has:
"ceasn:dateModified": "06/03/2019 22:05:59"**
![image](https://user-images.githubusercontent.com/26332112/58841113-06ab0680-862e-11e9-921b-882c43293e8e.png)

I did a search for the framework (now over 2 hours after publishing) 
{
  "Skip":"0",
  "Take":"10",
  "Query":  {

	"@type": "ceasn:CompetencyFramework",
	"ceasn:name": "NOCTI 21st Century Skills for Workplace Success"

}
}

The ceasn:modifiedDate is still 02/15/2019

![image](https://user-images.githubusercontent.com/26332112/58841340-065f3b00-862f-11e9-881b-db79eadeaade.png)

SO it appears that the index was not updated. 
We can post more examples, but this one seems a representative example.

**Comment by cwd-mparsons** [comment]
@edgarf Also we deleted several competency frameworks and these still show in the index search. Interestingly, the deleted (from the registry) documents show first in the search results (which uses whatever the default order may be. Maybe the deleted_at date is not being checked?

![image](https://user-images.githubusercontent.com/26332112/58888646-5bda2d00-86ad-11e9-95d3-7dd4eedaa8e6.png)

**Comment by siuc-nate** [comment]
I'm not 100% sure, but I think the most recent records from the index end up getting returned first (I still haven't gotten back to working out how to control sorting).  If that's the case, then it may also be that those documents are being removed at one point and then reinserted at a later point.  

As Mike indicates, it may be due to the enevelope's `deleted_at` date not being checked (since there is no status type or other boolean indicator that a given envelope's data is meant to be interpreted as "deleted" data).

**Comment by cwd-mparsons** [comment]
@edgarf I see than the framework: "NOCTI 21st Century Skills for Workplace Success" has been updated in the index. However the deleted frameworks are still showing in the Index search:

![image](https://user-images.githubusercontent.com/26332112/58985272-907ae100-87a0-11e9-8214-041f4bbb3736.png)

**Comment by edgarf** [comment]
@cwd-mparsons @siuc-nate Greetings, we have just finished analyzing the issue, and it seems like the index is not treating the deletions correctly. During the index process only non-deleted envelopes are processed. We will need to update the function and then during next re-index that would get fixed. 
We will need tomorrow to write the update and test it, then next night that issue should get solved.

**Comment by cwd-mparsons** [comment]
@edgarf Thanks  for the update.

**Comment by cwd-mparsons** [comment]
@edgarf 
I see that the deleted frameworks no longer appear in the index search.
What is the status of the timing of updates to the Index? 
I updated a framework earlier today (11:19 CDT) and it has not been updated in the Index yet (13:00 CDT).

**Comment by edgarf** [comment]
@cwd-mparsons Yesterday, @excelsior (Alex) removed those envelopes from index manually, just so it's fixed for the time being. Also today, we released a pull request (https://github.com/CredentialEngine/CredentialRegistryGremlin/pull/1), which after review and testing would get merged into the main codebase. 

Regarding updated framework - I reached out to find out about this.

**Comment by edgarf** [comment]
@cwd-mparsons Can you tell us what changes did you do?

**Comment by cwd-mparsons** [comment]
@edgarf 
I just edited and saved the framework to force a change in the dateModified property:

![image](https://user-images.githubusercontent.com/26332112/59061875-1e6ece80-886a-11e9-8aa8-b6ba480ab9f4.png)

**Comment by edgarf** [comment]
@cwd-mparsons do you still face this issue?

**Comment by cjshawMIT** [comment]
Hi, I'm working with DXtera (NEBHE / HVCNE project), and facing a similar issue...when we publish organizations with `parentOrganization` set, the search index never seems to update and we cannot find child orgs. Example:

https://sandbox.credentialengineregistry.org/graph/ce-c5abf83d-b926-46fb-ca36-68b3a560ff92

Shows as having a `parentOrganization` as follow:

```
            "ceterms:parentOrganization": [
                "https://sandbox.credentialengineregistry.org/graph/ce-c5abf83d-b926-46fb-ca36-68b3a560ff90"
            ]
```
But running this query returns 0 results:

```
{"Query": {"@type": "ceterms:CredentialOrganization", "ceterms:parentOrganization": {"ceterms:ctid": "ce-c5abf83d-b926-46fb-ca36-68b3a560ff90"}}, "Skip": 0, "Take": 50}
```

```
{
    "data": [],
    "valid": true,
    "status": "okay",
    "extra": {
        "TotalResults": 0,
        "GremlinQuery": "g.V().has('@id',test({x,y -> x ==~ y}, /(?i)http.*/)).as('main').and(has('@type','ceterms:CredentialOrganization'),both('ceterms:parentOrganization').and(has('ceterms:ctid',test({x,y -> x ==~ y}, /(?i).*ce-c5abf83d-b926-46fb-ca36-68b3a560ff90.*/)))).union(select('main').count(),select('main').skip(0).limit(50).union(__.values('__payload').fold(),union(__.out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload'),__.out().hasNot('@id').out().hasNot('@id').out().has('@id',test({x,y -> x ==~ y}, /(?i)_:.*/)).values('__payload')).dedup().fold()))",
        "RelatedItems": []
    }
}
```
This remains true no matter how long we wait to query the system. Are we doing something wrong with regards to `parentOrganization` / queries, or making a bad assumption about how data gets indexed into the search?

If you think this is a different issue, I'm also happy to create a separate issue.

Thanks!

**Comment by cwd-mparsons** [comment]
@edgarf 
I just did a test in the **sandbox**. I updated the name of the following organization (appended a date)

https://sandbox.credentialengineregistry.org/graph/ce-e4c8e9bd-88bd-4704-9e3a-78faebdca59d

![image](https://user-images.githubusercontent.com/26332112/59886025-05464180-9383-11e9-8d5f-c01d025aff9a.png)


It has been 20 minutes and the name still has not been updated in the sandbox Index. 
![image](https://user-images.githubusercontent.com/26332112/59885983-daf48400-9382-11e9-9369-a39791fc0238.png)

**Comment by excelsior** [comment]
@cwd-mparsons 

Turns out we were notifying the indexer before the changes were actually committed, meaning that effectively, the previous data was indexed. I've fixed that, we'll let you know once the fix is deployed.

**Comment by excelsior** [comment]
@cwd-mparsons The fix has been deployed.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons if this is fixed, close this issue.

**Comment by cwd-mparsons** [comment]
@excelsior @edgarf 
I have tested both the sandbox and production, and find that the index is not being updated
Production:
I added a period to the end of the name for Credential Engine at 10:07am Central
https://credentialengineregistry.org/resources/ce-9bd8c615-9f3c-40e6-9c20-6d9f811844e6
![image](https://user-images.githubusercontent.com/26332112/60450157-d9328800-9bee-11e9-8872-e7498d3a68bc.png)

After **45 minutes**, the index record still has not been updated.

Sandbox:
I added the date to the end of the organization name at 9:43 am central
"https://sandbox.credentialengineregistry.org/resources/ce-e4c8e9bd-88bd-4704-9e3a-78faebdca59d"
![image](https://user-images.githubusercontent.com/26332112/60450201-f0717580-9bee-11e9-8b5c-908985756da6.png)

After over an hour, the name in the index record still has not been updated.

**Comment by cjshawMIT** [comment]
As another data point: I did see last week that our `parentOrganization` changes were propagating correctly to search after the fix was deployed ... but then last Thursday (June 27) it appeared that the search indexing reverted to its previous behavior somehow.

**Comment by excelsior** [comment]
@cwd-mparsons The indexer service was down on both sandbox and production. It has been put to work again yesterday. Could you give it another try?

**Comment by edgarf** [comment]
@cwd-mparsons this is completed. Closing this task.
