### ISSUE TITLE
When republishing a credential without changing any data, the envelope updated_at date doesn't change

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#231]
@rsaksida @edgarf
Scenario:
The state of Kansas published a number of credentials on May 31/2019 for Butler CC.
They republished the credentials on Jun. 12/2019. No data was changed. 
The import process on the finder didn't find any records for the Jun. 12 period. 
I checked several of the related envelopes and saw that the updated at date was still May 31. 
For example:
https://sandbox.credentialengineregistry.org/ce-registry/search?ctid=ce-2d302d1f-1dbc-dc9b-d535-82cccdbf039e

https://sandbox.credentialengineregistry.org/ce-registry/search?ctid=ce-331e27b7-84e3-48f8-f30e-f71e020f243b

https://sandbox.credentialengineregistry.org/ce-registry/search?ctid=ce-556519c3-a0f9-4d3d-318b-7e3fff6cd635

I took one example and tested republishing ce-cf9da870-a387-4346-a4bd-c3a223b67938
1. I just re-published with no changes:
  successful publish, but no change to updated_at
2. Added a period to the end of the credential name, republished:
  successful and date was updated
3. Republished immediately without any changes:
  successful publish, but no change to updated_at
4. Removed the period from the credential name and republished. 
  successful and date was updated
![image](https://user-images.githubusercontent.com/26332112/59467072-6c4c7f00-8df4-11e9-81b0-bc4fa50aca4c.png)

I then wanted to check if this issue was unique to the sandbox. I found a credential that was published this week and tried republishing it. The event was successful, but, again the updated at date didn't change. 

![image](https://user-images.githubusercontent.com/26332112/59467188-a9187600-8df4-11e9-8955-2dfdc9d5b231.png)
 
I had raised this issue previously. I was told there is no code that would essentially check for changes before changing the updated_at date. 
Is the updated_at date changed as soon as a document is saved (i.e. in code) or is it done at the system level?
For example in DotNet, using entity frameworks, we update the database object and do a check to see if there have been any state changes. If the result is true, then we do an update, otherwise we skip the update (which would set last updated dates).
![image](https://user-images.githubusercontent.com/26332112/59467597-b2eea900-8df5-11e9-84a8-9968c7e68df1.png)

Any chance there is code like the latter hidden beneath the surface?

**Comment by excelsior** [comment]
> Any chance there is code like the latter hidden beneath the surface?

@cwd-mparsons You're right, that's exactly how it works, except it's not our code, but the ORM's we use: https://github.com/rails/rails/blob/v4.2.11.1/activerecord/lib/active_record/persistence.rb#L512

So if there's a need to change `updated_at` without any other changes, we'll have to implement that explicitly.

**Comment by edgarf** [comment]
@cwd-mparsons Let us know if the change is needed.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons please reply.

**Comment by cwd-mparsons** [comment]
@edgarf We reviewed this issue and have determine that the current approach is preferred - that is, the updated_at should only be updated if there was a change to the data. 

Notification
Would it be possible for the registry to return a message, or some indicator that an update did not occur? I think this would be a useful status.
The alternative would be for use to get the envelope and check for the updated_at being changed.

**Comment by excelsior** [comment]
I think this is achievable without changing the code.

If an update completes successfully, the updated envelope is returned, and the `updated_at` property will have a new value if a change occured. Hence, before hitting the endpoint, you can memorize the current value of `updated_at`, then compare it to the one returned by the API upon successful completion.

If that doesn't work for you, we can change the response to add a flag either into the envelope entity itself or separately:

```json
{
  "envelope": "<the envelope object>",
  "changed": "<true or false>"
}
```

Alternatively, we can return an empty response with a 204 No Content status, if there was no change.

Both solutions will require some changes on the client side as well. Let me know which approach  you prefer.

**Comment by cwd-mparsons** [comment]
We don't have access to the envelope when publishing. We would have to add a separate call to get the envelope. We may not have an envelopeId, so would have to do a search by CTID. A nice to have would be an endpoint to get an envelope by CTID. Regardless, I think we would prefer to avoid this extra step. 

I think we would prefer the addition of a property like the suggested boolean of "changed".

**Comment by excelsior** [comment]
The property has been added to the successful responses of the publishing methods. Deployed on sandbox and staging: https://staging.credentialengineregistry.org/swagger/index.html

Please note that for newly published envelopes the property's value will be `true`.

**Comment by cwd-mparsons** [comment]
@excelsior I have verified this change on the sandbox and staging servers.
Please promote this change to production.

**Comment by excelsior** [comment]
@cwd-mparsons It has been deployed to production, please take a look.

**Comment by cwd-mparsons** [comment]
Validated in production
