### ISSUE TITLE
Process to clear the sandbox registry

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#233]
@rsaksida 
I would like to schedule a purge of the sandbox envelope data.
As well, I would like to know how I can do this myself. I know that we had briefly discussed this recently. I have done very little work (logged in once, or twice ) with Linux, so I am basically a beginner. 
I want to make sure to ensure the process would only delete the envelopes and retain any organizations that have been registered for keys. Although there may be times we would like to completely remove an organization from the registry.

**Comment by edgarf** [comment]
The easiest approach here, I think, is that we would create some tasks (Ruby -  `rake tasks`), which you could trigger through Cloud66 environment (the service through which we do deployments). That would be just a few clicks. It's possible to have a number of different tasks like that, for example:
1) Wipe Sandbox
2) Migrate data from Production to Sandbox
etc.

Let us know if you agree with this approach

**Comment by cwd-mparsons** [comment]
@edgarf The suggested approach sounds good. 
I look forward to the details!

**Comment by edgarf** [comment]
Great!

**Comment by excelsior** [comment]
@cwd-mparsons 

There's the `Delete All Envelopes` Rake task on sandbox's Cloud66 dashboard (under the Jobs section):

Azure: https://app.cloud66.com/jobs/jobs/26610
AWS: https://app.cloud66.com/jobs/jobs/27563

Running that task will purge all the envelopes and their dependant records (resources and transactions).

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons @edgarf this should be something that doesn't have dependence on Tapestry Team.  @cwd-mparsons how is this being set up so Engine tech team can purge whenever needed and where is this documented besides with an issue?

**Comment by cwd-mparsons** [comment]
@excelsior 
I ran the jobs on **azure** - as a quick test. The staging job was successful, and the sandbox job failed. 
I did azure first as a quick test for the process. So the failure on azure sandbox probably doesn't warrant followup. The delete worked fine on AWS sandbox.
I noticed that for the AWS staging server, there is not a Delete task. 

**No Delete Task on AWS staging**

![image](https://user-images.githubusercontent.com/26332112/62982165-fa42e700-bdf0-11e9-8b7f-def756668f8d.png)

**Comment by excelsior** [comment]
@cwd-mparsons I fixed the job: It used to delete envelopes one-by-one, I changed that to be done in one take. The AWS sandbox has a more performant DB instance, that's why the job succeeded there, but failed on Azure.

I didn't know you need that task on staging. I've just installed it on staging, too.

**Comment by cwd-mparsons** [comment]
@excelsior Thank you. 
I successfully ran the delete task on staging.
