### ISSUE TITLE
A concept scheme was unpublished, then republished successfully but is still marked as deleted. 

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#241]
@rsaksida @edgarf
re: **concept scheme: Connecting Credentials: A Beta Credentials Framework - Levels** 
https://credentialengineregistry.org/resources/ce-75a38ea0-319d-4748-8bb0-a6dc4c68feb1
This concept scheme was unpublished on July 3, 2019. 
We have tried to republish it several times. Each time it appears to publish correctly - no errors. 
A virtually deleted document should be able to made 'active' again by republishing it. 

However the above resource URL for the concept scheme returns no data. The deleted record can be found using:
https://credentialengineregistry.org/ce-registry/search?include_deleted=only&page=1&per_page=50&from=2019-07-03T01:00:12

I tried another concept scheme:
- published it
- republished it, to confirm there is not an issue with republishing - OK
- unpublished it. Did a search for deleted items and found the document
- republished it - The concept scheme was accessible again via the resource URL

There seems to be an issue with this particular concept scheme.

**Comment by cwd-mparsons** [comment]
@edgarf @excelsior 
I recreated the scenario in the sandbox environment. We have the same concept scheme, and same CTID:
- I republished the document - to confirm no issues with the republish
- Un-published the document. The history can be seen via:
 https://sandbox.credentialengineregistry.org/ce-registry/search?include_deleted=only&ctid=ce-75a38ea0-319d-4748-8bb0-a6dc4c68feb1
- Confirmed I could not access the /resource/ URL
- Then republished the document
- Verified the document is accessible from the /resource/ IRL:
 https://sandbox.credentialengineregistry.org/resources/ce-75a38ea0-319d-4748-8bb0-a6dc4c68feb1
- Doing a search shows the new publish date (as expected doesn't include the revisions prior to the unpublish
 https://sandbox.credentialengineregistry.org/ce-registry/search?ctid=ce-75a38ea0-319d-4748-8bb0-a6dc4c68feb1

So the publish - unpublish - republish seems to work properly in the sandbox. This may or may not provide useful information.

**Comment by cwd-mparsons** [comment]
@edgarf @excelsior @science 
There are competency frameworks that refer to this concept scheme.
**We need to get the problem concept scheme purged from the registry so that we can get it republished.** 
https://credentialengineregistry.org/resources/ce-75a38ea0-319d-4748-8bb0-a6dc4c68feb1

As a high priority, could this document be purged from the registry? I understand that this may affect your troubleshooting.
NOTE: We need to be able to use the same CTID, so that is why we need the document purged.

**Comment by edgarf** [comment]
@cwd-mparsons , it has been removed, you can try publishing it again.

We've been testing this issue for the last few days, it was impossible to replicate it on any other server we have. So we also were thinking about the same 'short-cut' solution as you suggested.

**Comment by cwd-mparsons** [comment]
@edgarf 
Thanks, I was able to republish the concept scheme.

**Comment by edgarf** [comment]
Thanks. We will close this issue then
