### ISSUE TITLE
Need to be able to sort search results by newest

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#247]
I think I've figured out how to get sorting working (it'll take a bit more time to be sure of it), but this only works for properties in the payload.  

One of the things I need to be able to sort by is the date that records were published - in other words, I need to be able to accommodate a "newest first" and "oldest first" sort order with the search.  

Is there a suitable property in the index I can base this on?

**Comment by cwd-mparsons** [comment]
@siuc-nate 
Relate #209

**Comment by siuc-nate** [comment]
We have enabled sorting by newest.
