### ISSUE TITLE
Request to promote production schemas from github to the sandbox and staging site s

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#248]
@edgarf 
We would like to have the Json validation schemas updated to the credential engine sandbox and staging environments. I have added three new schemas:
- conceptScheme
- poncept
- pathway

 While the publishing doesn't use the validation schemas anymore, it appears that the basic search endpoint doesn't recognize resource_type of any of the latter. 
As well the gremlin search index needs to recognize these as well. 

I have updated the Production_Schema folder with the updated schemas:
- https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/Production_Schema

I will do some testing in the sandbox site, and then submit a separate request to promote these changes to production.
Please run the script to promote the updated schemas to the registry sandbox and staging environments.
Thanks

**Comment by excelsior** [comment]
The schemas were updated on sandbox and staging. There was a typo in one of them (an extra comma) which I fixed before loading it:
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/blob/master/Production_Schema/conceptScheme.json#L90

All the schemas are in the `ce_registry` namespace. Also, `conceptScheme` was renamed to `concept_scheme` to match the other schemes' names.

**Comment by cwd-mparsons** [comment]
Thanks, I removed the extra comma.
re: Renaming the conceptScheme schema.
If the convention is to use underscores, I can rename the file in github.

**Search**
We have published many conceptSchemes, concepts, and a few pathways. 
However, I get no results from the searches like:
https://sandbox.credentialengineregistry.org/ce-registry/search?resource_type=concept_scheme&per_page=50&sort_by=updated_at&sort_order=dsc
OR
https://sandbox.credentialengineregistry.org/ce-registry/search?resource_type=pathway&per_page=50&sort_by=updated_at&sort_order=dsc

**Index Search**
I also cannot get results when using the gremlin search, for any of 
-@type": "ceasn:ConceptScheme" 
-@type": "ceterms:Pathway"

A search for @type": "ceasn:CompetencyFramework" does return results.

**Comment by excelsior** [comment]
The most recent published envelopes have empty `resource_type` properties (actually, the absolute majority of the envelopes lack this property). If those weren't published without a `resource_type` somehow, there is a bug in publishing.

Could you please share some of the envelopes you've published?

**Comment by cwd-mparsons** [comment]
We have not been using resource_type for publishing.
I don't know how the translation works for resource_type in the registry. 
The validation schema file starts with a ref to the actual CTDL type being being published:

![image](https://user-images.githubusercontent.com/26332112/62321148-98d15e80-b467-11e9-89d4-a529e3ad8498.png)

Is there code somewhere to make the connection. 

For credentials, there are about 23 subtypes:

![image](https://user-images.githubusercontent.com/26332112/62321280-e2ba4480-b467-11e9-8c22-89c6e7eacd94.png)

You can use the search to see recent envelopes:
https://credentialengineregistry.org/ce-registry/search?resource_type=credential&per_page=50&from=2019-01-01T00:00:00&sort_by=updated_at&sort_order=dsc

**Comment by siuc-nate** [comment]
Those schema files are ancient and haven't been maintained since we decided we were going to handle validation via the API like a year ago or however long it's been - I would not use them.

**Comment by excelsior** [comment]
@cwd-mparsons The lack of definitions of those schemas in the config (see #243) was the root cause of the absence of the newly published resources in the FTS index. After updating the config with the proper FTS attributes and rebuilding the index, I was able to get results.

There is yet another issue, though. Both the config and the schemas define concept schemes and concepts with the `ceasn` namespace:

- https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/blob/master/Production_Schema/concept.json#L3
- https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/blob/master/Production_Schema/conceptScheme.json#L3

Meanwhile, the published resources have types with the `skos` namespace. FTS doesn't work because of the non-matching types. But if you search Gremlin with the correct `@type`, you'll get relevant results.

The namespace of Pathway is correct, a search for that resource type produces results now both in Gremlin and the DB.

**Comment by cwd-mparsons** [comment]
I will fix these and let you know when done.

**Comment by cwd-mparsons** [comment]
@excelsior 
I updated the config to correct the namespace to be skos.

**Comment by excelsior** [comment]
Thanks, Michael. I promoted the schemas and rebuilt the FTS index on both sandbox and staging.

**Comment by cwd-mparsons** [comment]
A late thank you
