### ISSUE TITLE
Give repo access to @coffeejunk

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#25]
Please, he will be working on the RoR side

**Comment by siuc-nate** [comment]
Is that username correct?  I receive this error message:

![image](https://cloud.githubusercontent.com/assets/21346519/24105258/4c62af5e-0d52-11e7-866f-9e43e0aa275c.png)

**Comment by siuc-nate** [comment]
I checked and the username is correct, but it won't let me add that user name.  Very strange.

I'm not very well-versed in github when it comes to user management, so I must ask:
Is there another way to add a collaborator or give access? Can he post somewhere in our issues list or use some site feature to request to join?

**Comment by leolara** [comment]
@siuc-nate perhaps, try without writing the @ sign

**Comment by cwd-mparsons** [comment]
I added @coffeejunk

**Comment by siuc-nate** [comment]
It seems that not using the @ sign was the key - a strange limitation for that entry box to have.

Thanks @cwd-mparsons
