### ISSUE TITLE
Updates four frameworks and index is not updated after one hour plus

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#252]
@excelsior @edgarf 
We updated and published the four frameworks. The following credential finder pages read the data from the Index:

https://credentialfinder.com/competencyframework/ce-07c264d7-9119-11e8-b852-782bcb5df6ac/
https://credentialfinder.com/competencyframework/ce-07c27a0f-9119-11e8-b852-782bcb5df6ac/
https://credentialfinder.com/competencyframework/ce-07c25f74-9119-11e8-b852-782bcb5df6ac/
https://credentialfinder.com/competencyframework/ce-07c257d6-9119-11e8-b852-782bcb5df6ac/

After 1.5 hours, the index still has not been updated. 
Each of the frameworks had a license property and a second source URL added. 
If the related registry document is checked, the new properties exist, but when searching the Index, the data has not been updated.

**Comment by excelsior** [comment]
Unfortunately, by the time I started looking into this, the nightly full indexing process has finished. So I can't examine how things looked 1.5 hours after publishing, but right now everything seems good: Clicking on the 'Raw Metadata' button at the bottom of the page reveals the added properties and values in place.

Let me know in advance if you plan publishing something soon. I'll disable the nightly full index Cron job and check whether individual indexing commands yield correct results.

On a related note, the 'View Framework Source' link has an incorrect `href`: Its value is both sources separated by a comma, hence following that link results in a 404.

**Comment by cwd-mparsons** [comment]
@excelsior @edgarf @siuc-nate 
We again had issues with the Index today. 
For the following framework, no competencies are shown:
https://credentialfinder.org/competencyframework/ce-6f48f4bb-9d78-4947-8ab6-4722749f2733

I used the query helper (https://credreg.net/quickstart/queryhelper ), and the following query
{
	"@type": "ceterms:Certificate",
	"ceterms:name": "cybersecurity"
}
Only one framework was returned, where seven were expected:
![image](https://user-images.githubusercontent.com/26332112/64999454-76779100-d8ad-11e9-9f0a-394afd39b413.png)

I found issues with credential searches as well.  The following query only returns one record, where over 30 were expected:
{
	"@type": "ceterms:Certificate",
	"ceterms:name": "accounting"
}

**Comment by excelsior** [comment]
These issues were caused by slow indexing as well. Search results seem good to me now.
