### ISSUE TITLE
Published an organization to the navy community and found incorrect values for the envelope ctid and ctdl type

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#259]
I published an organization to the sandbox navy community. As shown below the envelope_ceterms_ctid has an incorrect value of ceterms:ctid
Also envelope_ctdl_type has a value '@type' rather than an actual ctdl type. (I created a separate issue for this as the same condition exists in production #528 ).

![image](https://user-images.githubusercontent.com/26332112/63882943-b6c3ad80-c998-11e9-9de0-b5c2fe8e67de.png)

I was getting the following error when doing other publishing:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_envelopes_on_envelope_ceterms_ctid"
DETAIL:  Key (lower(envelope_ceterms_ctid::text))=(**ceterms:ctid**) already exists.
: INSERT INTO "envelopes" ("envelope_community_id", "envelope_version", "resource", "resource_public_key", "organization_id", "publisher_id", "envelope_ceterms_ctid", "envelope_ctdl_type", "processed_resource", "top_level_object_ids", "envelope_id", "node_headers", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING "id"

It appears this is related to the issue that as envelope_ceterms_ctid has the value of ceterms:ctid, any additional publish requests will fail  because envelope_ceterms_ctid=ceterms:ctid aleady exists.

Note: this issue was not encountered when publishing to the sandbox using the default community.

**Comment by cwd-mparsons** [comment]
@excelsior 
I added a gist containing the JSON-LD for a credential that failed with the above error. 
https://gist.github.com/cwd-mparsons/2639c439d02278c086e22149329b284e

**Comment by excelsior** [comment]
Thanks, Michael.

There are two problems here actually. The first one is a bug in our code—the JSON payloads are being queried the wrong way.

The other issue is that we expect the published documents to have `@type` and `ceterms:ctid` as top-level properties. As far as I can see, all the previously published on behalf resources are comprised of the `@context`, `graph`, and `@id` properties only.

The publish on behalf feature was implemented well before graphs were introduced, and hasn't been adjusted to support them.

The CTID and CTDL type can be extracted from the first resource of the graph, of course. Could you please confirm that this is the right solution to the problem?

**Comment by cwd-mparsons** [comment]
Alex
The definition of a CTDL graph has only the above referenced three top level properties:

- @id
- @context
- graph  

The only option  you have now would be to extract the CTID and CTDL type from the graph.
An alternative would be to define two additional parameters to the API. 
&ctid=ce-...&cdtl_type=...
The latter would be straightforward for us to provide. Would this be cleaner than adding code to extract data from the graph?

**Comment by excelsior** [comment]
The former approach looks better to me as it's simpler for you (no extra work required) and lowers chances of having inconsistencies in the resulting envelopes.

The fix has been deployed to sandbox and staging. Please take a look. If everything's fine, I'll deploy prod and fix the previously published envelopes with incorrect CTIDs and CTDL types.

**Comment by cwd-mparsons** [comment]
Alex
I tried publishing a credential to the **navy community** and got a key violation. 
However now is on an actual ctid versus the literal of 'certerms:ctid'. 
The ctid does exist in the default community:
http://staging.credentialengineregistry.org/graph/ce-9fdf6277-2bfb-4783-9b37-f578cf688861
but not in the navy community (this results in a not found):
http://staging.credentialengineregistry.org/navy/graph/ce-9fdf6277-2bfb-4783-9b37-f578cf688861

Should the CTIDs be only unique to a community and not the whole environment?

**Comment by excelsior** [comment]
You're right, they're globally unique, because CER used to be assumed as the only community until lately.

I've scoped the uniqueness restriction to a community on sandbox and staging.

**Comment by cwd-mparsons** [comment]
I attempted to publish a credential to the navy community that already exists in the default community. I got a UniqueViolation error:
 "PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint \"index_envelopes_on_envelope_ceterms_ctid\"\nDETAIL:  Key (lower(envelope_ceterms_ctid::text))=(ceterms:ctid) already exists.\n: INSERT INTO \"envelopes\" (\"envelope_community_id\", \"envelope_version\", \"resource\", \"resource_public_key\", \"organization_id\", \"publisher_id\", \"envelope_ceterms_ctid\", \"envelope_ctdl_type\", \"processed_resource\", \"top_level_object_ids\", \"envelope_id\", \"node_headers\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING \"id\""

The credential that exists in the default community is: 
https://staging.credentialengineregistry.org/graph/ce-9fdf6277-2bfb-4783-9b37-f578cf688861

The latter content was used to publish to the navy community with the only difference being the addition of the navy community.
https://gist.github.com/cwd-mparsons/2639c439d02278c086e22149329b284e

**Comment by cwd-mparsons** [comment]
@excelsior @edgarf 
What is the status of this issue?
We have some major demos next week. I can work around these by not using the navy community, but would prefer not to. 
If there are some weird inconsistencies in the staging environment, we can clear it out and start over.

**Comment by excelsior** [comment]
Sorry, this fix was superseded by the Navy schemas update. I merged the two branches into one, so now both are deployed.

Let me know if you need to purge all the data from staging and not only the envelopes in order to get rid of the inconsistencies.

**Comment by cwd-mparsons** [comment]
Thanks. I have done some more publishing and so far have had no other problems.
