### ISSUE TITLE
Promote new Navy JSON schemas to the sandbox and staging

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#264]
@excelsior 
We have created a set of initial versions of new JSON valildation schemas. 
We would like these promoted to the sandbox and staging environments from:
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/NavySchema-2019-09-17

**Comment by excelsior** [comment]
The work is in progress, but I have a couple of questions about the new schemas:

1. The [navyOrganization.json](https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/blob/master/NavySchema-2019-09-17/navyOrganization.json) file has `skos:ConceptScheme` as its `$ref` and [navySystem.json](https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/blob/master/NavySchema-2019-09-17/navySystem.json)'s `$ref` is `navy:OccupationTask`.

2. The schemas should also be added into the community's [config](https://github.com/CredentialEngine/CredentialRegistry/blob/master/fixtures/configs/navy.json), I can do that myself. What I can't do is set up their FTS attributes (in the same file), which is necessary for the full-text search feature to work. Could you please provide such configuration?

3. The navy community already has all the schemas from CE/Registry associated with it. Should those stay as they are or be replaced with the new ones?

**Comment by cwd-mparsons** [comment]
I fixed the navy:Organization and System (dangers of copy and paste), and added LearnPlan.

All of the existing navy schemas will be retained.

**Comment by excelsior** [comment]
Done. BTW the `LearnPlan` schema has a duplicated closing curly brace.

**Comment by cwd-mparsons** [comment]
Thanks Alex
