### ISSUE TITLE
Duplicate results encountered from search on sandbox and navy community

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#266]
@excelsior 
I was testing publishing concept schemes on the sandbox and navy community on the staging server.
If a search  is done, the same concept scheme is displayed 10 times:
https://staging.credentialengineregistry.org/navy/search
Example:
The same envelopeId and CTID are displayed for each entry
![image](https://user-images.githubusercontent.com/26332112/65843609-23173100-e2f8-11e9-9fb4-deee16dce932.png)

**Comment by excelsior** [comment]
Search returns envelope resources, not envelopes. An envelope can contain more than one resource, thus duplicated envelope IDs is a normal thing. It just so happened that the last envelope published to the Navy community has exactly 10 resources.

**Comment by cwd-mparsons** [comment]
Interesting. I guess I never noticed before with documents like a credential that typically only contain one resource. 
Thanks
