### ISSUE TITLE
Published 5000 OccupationalTask records, and only 356 show in the search

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#267]
I have published 5000 OccupationalTask records to the staging navy community.
Only 365 are returned by the graph search.

There were probably 2-3 trx per second. Is there an issue with handling larger number of transactions?
NOTE: we are attending a Navy demo to prototype effectiveness of these searches!

**Comment by excelsior** [comment]
@cwd-mparsons Could you please confirm that search works as expected after the typo was fixed? 

As I can see, the number of occupational tasks in the database matches the number of those in the graph.

**Comment by cwd-mparsons** [comment]
All 15,100+ occupational tasks are shown in the index now.
