### ISSUE TITLE
Update configs/navy.json - please promote to sandbox and staging

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#269]
@excelsior 
I have updated configs/navy.json:
https://github.com/CredentialEngine/CredentialRegistry/blob/master/fixtures/configs/navy.json

Please update this file to the sandbox and staging servers.

**Comment by excelsior** [comment]
There is a problem with the new config: `ceterms:CredentialOrganization` et al and `navy:Organization` both have the same alias (`organization`), despite being different schemas. I've changed the former's alias to `credential_organization` and kept `organization` for the latter.

The updated config has been promoted to sandbox and staging and the existing envelopes have been reindexed, so full-text search should work for the Navy content.

**Comment by siuc-nate** [comment]
It would be nice to not need these aliases, or to have the aliases more closely align to their schema names.  The namespacing afforded by the part of the schema name before the `:` exists for exactly this reason - to avoid name collisions.

e.g.
ceterms_credential_organization
navy_organization
etc.

**Comment by cwd-mparsons** [comment]
Would there be a huge impact if instead the organization in the navy community be renamed to navy_organization, and credential_organization be changed back to organization?
We use the search in multiple environments. I could make the search configurable.
Per Nate's point, I could add the navy prefix as an alias in the config file. That would make the relationship clearer. Also we could soon have another source of a job class.

I can add the prefixes, and let you know. Do you see an issue with this approach?

**Comment by excelsior** [comment]
It should be fine, no downsides I can think of. 

I like Nate's idea of simply putting namespaces into the aliases in order to ensure uniqueness. But renaming the newer schemas and keeping the old ones intact for the sake of compatibility will work, too.

**Comment by cwd-mparsons** [comment]
I have updated the config file - by adding the navy_ prefix.

**Comment by excelsior** [comment]
The updated config has been promoted to sandbox and staging.

**Comment by cwd-mparsons** [comment]
Thanks

**Comment by excelsior** [comment]
Hey @cwd-mparsons,

I've just noticed that the latest config lacks the `navy:LearnPlan` schema. Its entry should look like this, right?

```json
"navy_learn_plan": {
    "fts": {
      "full": [
        "$.schema:name.en-us",
        "$.schema:description.en-us"
      ],
      "partial": ["$.schema:name.en-us"]
    }
  }
```

**Comment by cwd-mparsons** [comment]
@excelsior 
The LearnPlan is just a placeholder, I don't have all the details. 
But, yes for now name and description should be fine.
