### ISSUE TITLE
How do we activate logging?

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#27]

**Comment by leolara** [comment]
by request of @coffeejunk

**Comment by andersoncardoso** [comment]
Hi @coffeejunk ,
For now we have 2 simple ways of logging stuff. 
Via the default app server output, and another app specific here:  here: https://github.com/CredentialEngine/CredentialRegistry/blob/master/config/application.rb#L27-L29
(this one is very simple. `stdout` for now, but easily configurable)
On the server the project run on phusion passenger, so we just use their default settings. We didn't tweak much of this so far

**Comment by leolara** [comment]
@andersoncardoso he mentioned he doesn't see any logs on the screen. The question is not about how to send logs somewhere or how to write logs, but how to see the logs that there is already

**Comment by andersoncardoso** [comment]
Sorry, maybe I'm missing something, but if you just run the app `bin/rackup` (or `rerun bin/rackup` if you want auto-reloads when you change code), you should see the logs on `STDOUT`.
It's a simple default Rack app log. 

<img width="1440" alt="screen shot 2017-03-22 at 2 51 08 pm" src="https://cloud.githubusercontent.com/assets/597026/24213060/09f17cf8-0f10-11e7-9250-25516fd2ff75.png">

**Comment by leolara** [comment]
@coffeejunk should we close this?

**Comment by coffeejunk** [comment]
that's the same output I'm seeing, but if for example I execute this code:

<img width="1680" alt="screenshot 2017-03-23 17 56 00" src="https://cloud.githubusercontent.com/assets/205556/24242283/45154d18-0ff2-11e7-8b93-82c9e123e636.png">

While I see the message of the exception in the HTTP response and that the request resulted in an internal server error (`500`), the stack trace is lost.

**Comment by andersoncardoso** [comment]
We capture failures on Grape to return a proper response [0], but it was lacking log messages. 
I added a commit to handle this [1].
Anywhere you see it's lacking messages that can be useful, or better handled, feel free to change.
Thanks for pointing this issue :+1: 

[0] https://github.com/CredentialEngine/CredentialRegistry/blob/master/app/api/v1/defaults.rb
[1] https://github.com/CredentialEngine/CredentialRegistry/commit/6e0bdec5fdcac3fb80d54ea2aa88d0f2f42e7940

**Comment by coffeejunk** [comment]
👍
