### ISSUE TITLE
Issue with staging server

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#271]
I was able to publish the following document to the sandbox and navy community.

	 "Rating": {
	    "CodedNotation": "ABE",
	    "CTID": "ce-d0cd9d5e-cc1c-44c3-8d14-7ea24c055d9e",
	    "DatePublished": "JUL 2015",
	    "Description": "Operate, maintain, and perform maintenance on steam catapults, barricades, arresting gear, and associated equipment ashore and afloat; operate catapult hydraulic systems, retraction engines, water brakes, jet blast deflectors, deckedge and ICCS, and jet blast deflector control panels; arresting gear engines, sheave dampers, deckedge control station, and associated equipment; perform aircraft handling duties related to the operation of aircraft launching and recovery equipment.",
	    "HasDoDOccupationType": [
	      "https://staging.credentialengineregistry.org/navy/resources/ce-fac82c3e-573f-4f14-b017-444ec7b55553"
	    ],
	    "HasOccupationType": [
	      "https://staging.credentialengineregistry.org/navy/resources/ce-453c089a-694d-4f37-97e9-19887b83bc92"
	    ],
	    "InLanguage": [],
	    "Name": "Aviation Boatswain's Mate (Launching and Recovery Equipment)",
	    "UploadDate": "12/30/2014 12:24 PM",
	    "Version": "1"
	  }

When I try to publish the same document to the staging server or to staging/navy community, I get the following error:
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

I then tried to do a graph/gremlin search for any navy:Rating, and I get the same error.  The same error occurs for other document types!
This is very unexpected for the search. 
Is there some bad data in the staging server, or how to find what the bad data may be?

ALSO, the same error occurs when I attempt to publish OccupationalTasks that have been previously successfully published.

**Comment by siuc-nate** [comment]
If I had to guess from that error, something is receiving an XML or HTML response (hence the opening`<` in some tag) and trying to parse it as if it were JSON, and then throwing the error that you're seeing.  Could be a 500 error somewhere in the chain.

**Comment by cwd-mparsons** [comment]
I have seen errors like that when the wrong set of keys are used, but never for the search. 
By wrong set of keys, the scenario is:
- a document gets published originally with, say the CE keys
- a subsequent publish tries to use the registry managed keys
- while the error can be something like trying to publish with a different owner

In this case, I encountered the error and then tried to republish a document that was successfully published earlier - definitely with the same keys, and got the error.

**Comment by cwd-mparsons** [comment]
@excelsior Publishing to the staging server is now working again. 
There are still issues with the graph search. 
I tried a simple search of: 
"@type": "navy:OccupationalTask"
I get: 
{
    "data": null,
    "valid": false,
    "status": "Internal Server Error",
    "extra": {
        "Status": 500
    }
}
There are over 15100 occupationalTask documents. I was retrieving two ( to check the count of total records).

I did a search for: navy:EnlistedClassification, and it is successful. Same for other smaller tables.

**Comment by excelsior** [comment]
Michael, the two issues are unrelated.

The problem with publishing was caused by the server returning an HTML response instead of JSON, as Nathan correctly pointed out. I'll deploy the fix soon. Normally, the API responds with JSON even if an error occurs, but if the API fails to handle an exception, it'll be wrapped up by the web server, and the latter responds with HTML. I'd suggest checking the content type and status of the response before processing its body, that'd help troubleshooting such issues.

The graph search problem appears to be a Neo4j bug, it's hardly reproducible, but re-indexing the problematic resources seems to solve it.
