### ISSUE TITLE
Exploring conversion of JSON to RDF Triples (and using Neptune as a Triple Store)

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#272]
Since it came up in our meeting today, I put together some sample code to show how to convert JSON into RDF triples:
https://github.com/CredentialEngine/vocabularies/blob/master/Code-Samples/JSON%20to%20Triples.js

I put it in the vocabularies repository to avoid any potential confusion/conflict with the registry-related code in this repository.

The code sample above contains a few pieces of sample data and some javascript functions to turn it from JSON into a flat JSON list, then into RDF triples, injecting some extra identifiers along the way (things we've also discussed) to make it easier to retrieve and manage the data later on.

I included a lot of comments to explain the what and why of the code, and tried to write the code in a way that facilitates using the same or similar approach in other programming languages (though strongly typed ones will probably give you all kinds of trouble).

You should be able to copy and paste the whole file into your browser console and then play around with it by calling the JSONtoTriples method like so:

![image](https://user-images.githubusercontent.com/21346519/66603946-cd9e1800-eb72-11e9-91af-213ec3a8b5ae.png)

This all relates to the potential exploration of using AWS Neptune as a triple store to see how it compares performance-wise to our other stuff.

**Comment by siuc-nate** [comment]
FYI, I tried this with a [NOCTI credential](https://credentialfinder.org/credential/10010/Culinary_Arts_Cook_NOCTI-ACF) and it appeared to work:
![image](https://user-images.githubusercontent.com/21346519/66604578-0985ad00-eb74-11e9-8840-f40dff73216b.png)
It certainly does away with any semblance of being compact, but in exchange the data ends up being quite simple (just...very large).

**Comment by siuc-nate** [comment]
A couple of lines of code makes a big difference while retaining the essence of the triple structure...
```
var compact = {};
triples.forEach(function(triple){
	compact[triple["rdf:subject"]] = compact[triple["rdf:subject"]] || [];
	compact[triple["rdf:subject"]].push({ "rdf:predicate": triple["rdf:predicate"], "rdf:object": triple["rdf:object"] });
})
```
![image](https://user-images.githubusercontent.com/21346519/66605157-25d61980-eb75-11e9-80d5-d9e935664854.png)

@stuartasutton do you know of anywhere something like that might be useful? Sort of a JSON-triple hybrid approach?

Anyway, I digress...

**Comment by stuartasutton** [comment]
Nate, the first encoding is close to the serialization called n-triples, what the machinery of a triple- or quad-store (named graph store) actually sees. If you compact the subjects, you basically have turtle (and the fundamentals of SPARQL). BUT, n-triples don't include **anything** but the data of the triples with each triple terminated with a period.

What do you care about the size of the file if all you are doing is using it to load a triple-store. That said, in terms of line count, the n-triples are far, far less than a json-ld encoding.

**Comment by stuartasutton** [comment]
And "yes" the data viewed as native triples is quite, quite simple and invariate in form...that's what supports harmonization :-)

**Comment by science** [comment]
@siuc-nate @stuartasutton - thanks for this, and nice work Nate! I think if we go this route, we are abandoning the Gremlin language at least as it is currently formulated for queries (with a fairly high level and rich vocab) and we'd be digging in the data at the triple level to get results, which might be more technically challenging?

If that is not a problem (or worth the trade off), I'd be very interested in "exploding" the data into triples, and trying out native triple stores for performance and reliability.

To be clear we might still use Gremlin but the data structures we'd be querying would be more fine-grained and therefore require new Gremlin nomenclature. (Please correct me if I'm off-base here).

Thoughts?

Secondarily, Stuart would you mind sharing (again) the names of the triple stores that have, in your experience, the best reputation for production-quality readiness (performance, stability).

cc @excelsior @edgarf

**Comment by siuc-nate** [comment]
AWS Neptune apparently has triple store functionality, though I don't know enough about it to know how you'd go about making use of it (maybe it's the default for data created with SPARQL?).

I think it would be worth investigating the performance differences.  If it proves to be notably faster to put things into the database as triples (solving the indexing problem) then it would be worth rewriting the layer that translates the CTDL JSON queries to instead output SPARQL if needed.

**Comment by science** [comment]
Thanks @siuc-nate -- if you are open to rewriting the Gremlin layer, then that would open up a lot of possibilities for us, including Cypher and SPARQL. It may just be that Gremlin is too new, and the underlying databases haven't optimized for it yet? We'll take that forward, and update as we go.

**Comment by siuc-nate** [comment]
I'm not particularly fond of gremlin anyway, so don't think of it as something we absolutely need to stick to.  Finding the system that gives us the best reliability/performance should be the top priority.

**Comment by stuartasutton** [comment]
Neptune accepts json-ld without conversion to n-triples. https://docs.aws.amazon.com/neptune/latest/userguide/sparql-media-type-support.html

**Comment by siuc-nate** [comment]
That would certainly be worth exploring.

**Comment by science** [comment]
Basically if we switch to SPARQL it seems like a world of options opens up in terms of bulk loading and indexing..

**Comment by jkitchensSIUC** [comment]
@science @siuc-nate @stuartasutton @cwd-mparsons @edgarf please put this on the agenda for the next Registry meeting and include @stuartasutton with that meeting invite.

**Comment by siuc-nate** [comment]
This was implemented a long time ago. Closing this issue.
