### ISSUE TITLE
Steps to configure gremlin search for communities

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#273]
This issue was part of #243 . Moved the gremlin related question to this separate issue, and closed 243.

Summary moved from #243 .

Aug.21, 2019 mparsons
Quick question: how does the gremlin search work with communities?
That is, is additional work required to configure gremlin searches for communities, or will the following be all that is needed:
https://staging.credentialengineregistry.org/navy/gremlin/

Aug. 22, 2019 Alex
Communities are not supported in Gremlin. Associating vertices with communities is rather simple, but the problem is, the indexer assumes CE/Registry is the only community (namely by using CER-specific IDs). The navy community is pretty much identical to CER, so no changes are needed, but that might not be the case for additional communities in future.

We can scope the /gremlin endpoint (so that way, /ce-registry/gremlin will only search for CER resources and /navy/gremlin will only search for navy resources), but I think it would be easier if a community restriction is added to queries themselves. I think we should consult with @siuc-nate about that

Nate:
Which way would yield the best performance?

Aug. 23, 2019 Alex
Both are the same performance-wise.

Once we add a property for associating vertices with communities (let's call it __community), we'll be able to limit traversals to a specific community like this: g.V().has('__community', 'navy').<rest of the query>. Then, if a query is sent to the /navy/gremlin endpoint, we'll parse the query and add the .has('__community', 'navy') to it.

Alternatively, we may leave the single unscoped endpoint, and adding a community condition to the queries would be the API client's responsibility.

**Comment by excelsior** [comment]
@cwd-mparsons The majority of the Navy envelopes' `@context` is https://credreg.net/navy/schema/context/json. This value is absent in the `json_contexts` table. The available values are:

1. http://credreg.net/ctdl/schema/context/json
2. https://credreg.net/ctdl/schema/context/json
3. http://credreg.net/ctdlasn/schema/context/json
4. https://credreg.net/ctdlasn/schema/context/json

This issue prevents successful indexing of the Navy resources.

**Comment by cwd-mparsons** [comment]
@excelsior 
Sorry, I didn't know about the  json_contexts table.
Please add: **https://credreg.net/navy/schema/context/json** to both the sandbox and staging server
Thanks

**Comment by cwd-mparsons** [comment]
@excelsior Have you been able to add these new schema references?

**Comment by excelsior** [comment]
@cwd-mparsons When I was about to add the missing context, I've found out that it was already there, on both servers. Somebody outran me 😼 I've reindexed everything with the new context, though.

**Comment by excelsior** [comment]
@cwd-mparsons @siuc-nate 

Community support was implemented for Gremlin searches: Every vertex has a `__community` property which contains the name of a community to which the related envelope belongs. Both sandbox and staging have been reindexed that way.

Now, we need to decide whether we need to namespace the `/gremlin` endpoint and inject a step with a condition on community to supplied queries.

**Comment by siuc-nate** [comment]
I think we need to either do that or stop offering direct access to a gremlin search API endpoint (have all queries be generated by our system) - which is something we'll probably need to do anyway if we switch from gremlin to another query language under the hood.
