### ISSUE TITLE
Timeout issues for a competency framework with ~8000 competencies

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#282]
We have received a competency framework from O*Net with almost **8000** competencies. 
I have been testing calls to publish the framework to the registry.   I was able to publish 1000 competencies, but attempts to publish more fail. The publish request times out after 100 seconds.
The complete payload is around 7mb. 
There was a previous issue related to a large concept scheme: #242 
The latter (with ~1500 concepts) was addressed by processing content with a 'background' process, and returning to the client after uploading the payload. In this case it would seem to be necessary to increase the timeout parameters for the server.

**Comment by excelsior** [comment]
The asynchronous resource extraction feature isn't deployed to production, it's only available on staging. Could you please try publishing the large framework to staging first and see whether the issue persists (if you haven't done so yet). If it works on staging, I'll set up background processing on prod.

**Comment by cwd-mparsons** [comment]
@excelsior I tried publishing the large framework to staging. 
I first tried with **5000 competencies, and was successful, with an elapsed time of about 75 seconds.** 
I then tried all the competencies, again **about 8000, and the publish failed after 100 seconds.** 
We need to get this framework published as soon as possible. 
Could you just increase the timeout setting (> 150 seconds?) on staging and I can try again? 

When successful, we will then want to do the publish in production. In order for the latter to be successful, it appears that you would first have to **add the asynchronous resource extraction feature to production**.

**Comment by cwd-mparsons** [comment]
Update
There is some strange things happening on staging. I tried publishing 5010 competencies - failed. 
I tried 4000 - failed, as did 2000. 
I then went back to 1000 and that worked. 
Tried 2000 again, it worked, but took 75 sec. 

I then found that search for the CTID would now fail:
https://staging.credentialengineregistry.org/ce-registry/search?ctid=ce-9fab4187-0903-11e9-8250-782bcb5df6ac
But I could get by envelopeId:
https://staging.credentialengineregistry.org/envelopes/49fb2058-1e53-48e9-a0b8-3d837b28301d


Also (yes there is more), the Changed property returned on the enveloped would always be false even though I was changing the number of competencies being published. Does the latter value only relate to the top level object, rather than the whole transaction? So since the competency framework itself didn't change, the Changed value is false?

**Comment by excelsior** [comment]
@cwd-mparsons The timeout has been increased to 300s. Search by CTID works for me.

I need more time to find out why the `changed` flag isn't `true` when the number of competencies is different. It is supposed to indicate a change, because the envelope itself changes.

**Comment by cwd-mparsons** [comment]
@excelsior Thanks, I was able to publish the full framework. 

As noted earlier, we will now want to able to do the publish in production. 
In order for the latter to be successful, it appears that you would first have to add the asynchronous resource extraction feature to production.

**Comment by excelsior** [comment]
Backround resource extraction is available on production, the server's timeout is set to 300s, too.

**Comment by cwd-mparsons** [comment]
@excelsior 
Thank you Sir, have a good weekend.
