### ISSUE TITLE
Add ability to transfer ownership of a document

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#283]
This issue was split out from #232 .
We need a function to allow transferring the 'owner' of a document. 
Scenario:
Organization 'A' publishes a document - which gets signed by their keys. Often Org 'A" might be the credential engine admin org. 
The document is really owned by Org 'B', which now has a Registry key.

Currently if Org 'B' tries to republish the document (retaining the original CTID), the request would be rejected with an error on mismatched keys. 

We want the ability for an administration user to be able to transfer ownership of a document.

**Comment by cwd-mparsons** [comment]
For reference, I copied the comments from @aspino regarding transferring an owner (#232) 

@science I think I get what you mean, but when you talk about "change the owner", I guess that actually means changing the publisher, right?

From what I remember, every envelope that gets uploaded is signed with the publisher's key, and then stored. By looking at the code I also see you've added the option to "impersonate" an organization and sign on its behalf, but I'm not sure if that's too relevant here, because the organization stays the same, doesn't it?

I think the process could involve 2 steps:

Current publisher of the envelope (or an admin) invokes an API endpoint that accepts an envelope ID and a publisher ID that will be the new owner. When executed it would prepare the transfer by marking the envelope as ready to be transferred (with a flag or something of the sort).
New publisher can then invoke an API endpoint (perhaps it can be the same one that updates a resource) sending the envelope ID. The signature is then verified and, if valid, the envelope record is updated and re-signed to reflect the new publisher. The ownership transfer could be reflected as another update to the envelope, so previous history would be kept.
This is just a preliminary idea about the implementation, so feedback is welcome, but I'd like to know if you think this approach is aligned with what you had in mind for this feature or not.

**Comment by excelsior** [comment]
@cwd-mparsons 

The ownership transfer feature is available on sandbox. Changing the publishing organization of a document can be done by executing a request like this:

`PATCH /resources/organizations/{orgA}/documents/{ctid}/transfer?new_organization_id={orgB}`

This changes the organization and re-encodes the resource with the new organization's key. The change is reflected in the document's version history.

[Swagger](https://sandbox.credentialengineregistry.org/swagger/index.html) contains documentation for the new endpoint.

Currently, only superpublishers have this ability. An attempt to transfer a document into the same organization will trigger no change, equivalent to republishing a document without changes (the `changed` flag will be `false`).

**Comment by excelsior** [comment]
@cwd-mparsons 

The API has been simplified:

```
PATCH /resources/documents/{ctid}/transfer?organization_id={newOrgId}
```

Other changes:

- Correct community is assumed when looking the envelope up.
- Superpublishers can transfer someone else's documents.

**Comment by mparsons-ce** [comment]
@excelsior 
As noted in the last meeting:
- I changed the owner of a credential
- the request was successful
- I then published the credential with the old owner - and it worked. I should have got an error now that the credential has a different owner.

**Comment by excelsior** [comment]
@mparsons-ce 

This is an interesting scenario: The current implementation allows updating an existing envelope disregarding the owner (at the same time, the `update_if_exists` flag gets ignored, so it's not really flexible).

BTW this bug/feature effectively makes it possible to change ownership without the need of a dedicated API.

Anyway, I fixed that—now, republishing an existing document under another owner will raise a `CTID not unique` error.

**Comment by excelsior** [comment]
@mparsons-ce Could you please confirm the fixes are good?

**Comment by jeannekitchens** [comment]
@mparsons-ce please respond

**Comment by mparsons-ce** [comment]
@excelsior I have completed testing this feature. Please promote the feature to production.
Thx

**Comment by excelsior** [comment]
Done.
