### ISSUE TITLE
CRITICAL All requests to the navy community resources, graphs, envelopes, and search return an error.

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#284]
@excelsior @edgarf  @science 
There seems be a major issue with the navy community.
I first did a graph search that returned:
![image](https://user-images.githubusercontent.com/26332112/68910761-89c1a400-0718-11ea-9529-6cdf3854cf00.png)

I clicked/followed one of the links to an existing resource like: 
https://staging.credentialengineregistry.org/navy/resources/ce-2520f6e2-e1ea-4d62-a419-fb84af906b92
and got the following error:
![image](https://user-images.githubusercontent.com/26332112/68910723-626ad700-0718-11ea-9044-995eed9cd582.png)

The same  error occurs if I attempt a search
https://staging.credentialengineregistry.org/navy/search?resource_type=credential

https://staging.credentialengineregistry.org/navy/search?resource_type=navy_rating

I just tried to publish two records to the navy community (that had been previously been published) and these also fail with the oblique error of **navy**!

**Comment by science** [comment]
@cwd-mparsons - noted, and I'll post this for @excelsior @rsaksida and a few other engineers to examine internally.

**Comment by excelsior** [comment]
@cwd-mparsons The issue has been fixed, it was basically a regression in configuration after enabling backround publishing.
