### ISSUE TITLE
CRITICAL: Production search/resources/envelopes request fails with "undefined method `secured?' ... "

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#286]
@excelsior @edgarf @science 
All direct requests to the production registry are failing. 
It appears that a recent update resulted in the addition of a security check (**_and an incomplete version of the latter_**) like that should only be used for the navy community.

https://credentialengineregistry.org/ce-registry/search?resource_type=credential
https://credentialengineregistry.org/resources/ce-9fab4187-d8e7-11e9-8250-782bcb5df6ac

![image](https://user-images.githubusercontent.com/26332112/69069306-ddb7db80-09eb-11ea-956d-7d9df3d75116.png)

**NOTE: this prevents the process that runs on the credential finder to import updates from the registry!**

**Comment by excelsior** [comment]
@cwd-mparsons 

Apparently, there's a bug in our deployment setup causing database changes not being applied during a deployment. I've fixed that issue manually and will investigate why it happens in the first place

**Comment by cwd-mparsons** [comment]
Issue occurred during migration from Azure.
The configuration has been updated to automatically use the correct values.
