### ISSUE TITLE
Updates to the CTDL schema for updates to price and duration related properties

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#290]
@excelsior @edgarf 
The CTDL schema is being updated **Nov. 29, 2019**. 
https://credreg.net/ctdl/release?releaseid=20191129
Key Updates
- Price is being changed from int to decimal
- Duration related properties (exactDuration, minimumDuration, maximumDuration, and renewalDuration) are being changed from xsd:duration to schema:Duration as the latter supports weeks. 

This update should resolve the issues that Alex was encountering with the related data while loading Neptune.

**Comment by excelsior** [comment]
Can confirm: The data gets indexed correctly now, with no workarounds needed.
