### ISSUE TITLE
Integrate better stability monitoring services

### ISSUE THREAD

**Issue by edgarf** [CredentialEngine/CredentialRegistry#296]
1. Set up proper monitoring - integrate CW for now.

2. Determine the best strategy to make the whole site more reliable  (e.g. two servers load balanced, auto-reset strategies at various levels including restarting the server)

**Comment by jeannekitchens** [comment]
@edgarf @science @excelsior @mparsons-ce this had been identified as high priority in January but still can't tell what's going on.  Provdie a clear status update please.

**Comment by edgarf** [comment]
We can always improve (so I will put this task to "In Progress" column). We are already using monitis for uptime tracking both for staging and production. We are also using https://www.skylight.io/, and @excelsior will implement Airbrake.io for error analysis this week.

**Comment by edgarf** [comment]
Production deployed
