### ISSUE TITLE
Addressing identify definitions

### ISSUE THREAD

**Issue by mparsons1953** [CredentialEngine/CredentialRegistry#3]
per: @leolara

Of the three buckets: entities, sub-entities and literals (perhaps you have better terms, I made these up) I see that you have identified the literals as they have now JSON types on them. I think a basic step forward on this is to add them some validation rules, as for example if one is an url add some regex to it.

I see there are 41 classes that have ctid property, and that they are referenced from other schemas using meta:identifier. I guess these are what I called the entities. And the rest that are not either literals nor entities, are the sub-entities. See #1 

One thing I can say is that 41 entity types perhaps are too many and will be confusing for developers. But of course, for the Registry technical work this does not matter.

I think the way you did it, will validate correctly.  A problem, perhaps, is that perhaps for the developer that reads the schema will have the impression that meta:identifier in each case can point to anything. For example we lose the information that ceterms:approvedBy can point to any of ceterms:CredentialOrganization, ceterms:CredentialPerson or ceterms:QACredentialOrganization.

For solving that I would propose to create indentity defintions for each of the entities, for example, we would have meta:approvedByID, meta:CredentialPersonID and meta:QACredentialOrganizationID. Then we would got:

"ceterms:approvedBy": {
   anyOf: [
      { "$ref": "#/definitions/meta:approvedByID"},
      { "$ref": "#/definitions/meta:CredentialPersonID"},
      { "$ref": "#/definitions/meta:QACredentialOrganizationID"} 
   ]

**Comment by stuartasutton** [comment]
I am probably speaking beyond my expertise because I make no claims of knowing much of anything about json schema; but, it seems to me that the example encoding would be:

```
"ceterms:approvedBy": {
anyOf: [
{ "$ref": "#/definitions/meta:CredentialOrganizationID"},
{ "$ref": "#/definitions/meta:CredentialPersonID"},
{ "$ref": "#/definitions/meta:QACredentialOrganizationID"}
]
```
I'm making this guess because these are the only three types (classes) in the example that can be values for `ceterms:approvedBy`.  That would rule out `{ "$ref": "#/definitions/meta:approvedByID"}` because `approvedBy` is a property and not a class.

**Comment by leolara** [comment]
@stuartasutton good catch, it was a copy/paste error from my part

**Comment by siuc-nate** [comment]
What would the definitions for those ID properties look like?  They are all just URIs in the data that would be published, so I don't think we'd need individual identifiers for each.  This is why I used the same reference to the same identifier structure:

Note that I made up "meta:identifier" and placed it at the top of the document to handle the JSON-LD style of handling `{ "@id": "{some url}" }` style objects:
![image](https://cloud.githubusercontent.com/assets/21346519/23757006/27289384-04ab-11e7-9144-bb04e9b5bfcd.png)

**Comment by leolara** [comment]
@siuc-nate we do not need that, I just think that it is better for the developer as it will be clear the type of the pointed object. But the validation would work the same.

**Comment by siuc-nate** [comment]
Is there anything further with this issue, or can it be closed?

**Comment by leolara** [comment]
I think https://github.com/CredentialEngine/CredentialRegistry/issues/11

Addresses which are the top-level entities.
