### ISSUE TITLE
Staging server should track this repo

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#30]

**Comment by leolara** [comment]
https://github.com/CredentialEngine/CredentialRegistry -> Cloud66 -> lr-staging.learningtapestry.com

**Comment by andersoncardoso** [comment]
Done, 
The codeship CI is the only piece we had before and it's not here. Not sure if that's needed, but 
if we want that too we need to register a deploy key, so I would need to have admin rights, or some admin to help me to solve this.

**Comment by leolara** [comment]
@andersoncardoso ok

I created an issue for codeship: https://github.com/CredentialEngine/CredentialRegistry/issues/39
