### ISSUE TITLE
Combine Neptune instances into one box. This involves API/code work to ensure graph isolation.

### ISSUE THREAD

**Issue by edgarf** [CredentialEngine/CredentialRegistry#300]

**Comment by jeannekitchens** [comment]
@edgarf @mparsons-ce is this still open?  Status update please.

**Comment by edgarf** [comment]
This task can't be started while we are working out the approach with SPARQL.

**Comment by siuc-nate** [comment]
Due to needing to make sure the navy index is locked down, I think that will need to remain as a separate SPARQL instance, unless the LT team has figured out a way to ensure separation of data.

**Comment by edgarf** [comment]
This task is needed to decrease monthly spending on AWS, we will get on it after having the stability of the rest of the system improved
