### ISSUE TITLE
Updated ce_registry.json to remove the language strings from the fts definitions. 

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#302]
@excelsior 
re: 

> There is an another issue with FTS indexing, though: in the config, all the paths specifying indexed properties feature the 'en-us' language. However, the actual data contain a mix of ‘en' and ‘en-us.’ For example, all of the concepts’ properties have ‘en’ as their language, meaning that none of them get indexed property. This doesn’t affect Gremlin indexing, of course.

AS we discussed, removing the lang strings from the fts definitions was a preferred fix for the latter describe issues.
I updated the ce_registry.json file to remove the language strings and checked it the updates.

For example, changed:
"$.ceasn:name.en-us"
to
"$.ceasn:name"

**Comment by excelsior** [comment]
Thanks @mparsons-ce 

The change has been deployed.
