### ISSUE TITLE
Missing connection between organization and competency framework

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#303]
I've stumbled across a missing connection in the SPARQL index:

```
{
    "query": "PREFIX credreg: <https://credreg.net/> PREFIX ceterms: <https://purl.org/ctdl/terms/> PREFIX ceasn: <https://purl.org/ctdlasn/terms/> SELECT * WHERE { ?id  ( ceasn:creator ) <https://credentialengineregistry.org/resources/ce-058262c6-472b-415c-8448-51e0cbc32776> }"
}
```

That should find this competency framework:
https://credentialengineregistry.org/resources/ce-d6a4cefe-fa6e-406a-97bd-afff2753b8d3

which has a ceasn:creator of this organization:
https://credentialengineregistry.org/resources/ce-058262c6-472b-415c-8448-51e0cbc32776

The connection works in the gremlin index, but not the SPARQL one - also the URIs appear to be normal (lowercase, using /resources/) so I'm not sure why this is missing.

Any ideas?

**Comment by siuc-nate** [comment]
When was the last time the index was built?  We did have an issue the other day with the CTDL terms not getting correctly factored into the JSON-LD context for CTDL-ASN (which probably means that `ceasn:creator` and `ceasn:publisher` might not have shown up as having `"@type": "@id"`), however, this was fixed a few days ago.

Since this is a case of data in one schema pointing to data in another schema (the ceasn:creator property references a ceterms:CredentialOrganization or ceterms:QACredentialOrganization), I suspect the gap here has something to do with that.

**Comment by siuc-nate** [comment]
Also experiencing this with organization `ce-dab7aeae-d843-4c46-a013-9cbdc8e1cc44`. I suspect it'll be the same across all of them.

**Comment by excelsior** [comment]
Yep, the context does matter. I refreshed the index, and now the query producec the expected results.

I haven't turned automatic index updates back on yet (because of the `CLEAR ALL` issues in 1.0.1), so please ping me when you make fixes or just need the latest and greatest data in Neptune.

**Comment by siuc-nate** [comment]
This seems to be working now.

Thanks.
