### ISSUE TITLE
Mystery blank nodes in the index

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#305]
The following certification shows in both the registry and the search index:
https://credentialengineregistry.org/resources/ce-fde870d6-4689-456a-8e84-79d27a885098

According to that record, it requires one assessment. However, the following query returns a link to that assessment as well as over a hundred bnodes:

```
PREFIX credreg: <https://credreg.net/> PREFIX ceterms: <https://purl.org/ctdl/terms/> SELECT * WHERE { ?s ceterms:ctid 'ce-fde870d6-4689-456a-8e84-79d27a885098' . ?s ( ceterms:requires/ceterms:targetAssessment/^credreg:__graph? ) ?o . }
```

These bnodes all have the integer-based IDs rather than the newer /bnodes/ based IDs - they also do not appear if you leave off the ^credreg:__graph part of the predicate path.

They may be tied to the assessment that appears alongside them. If I run the following query (using that assessment's graph URI), I get a bunch of nodes that appear to be fragments of a record:

```
PREFIX credreg: <https://credreg.net/> PREFIX ceterms: <https://purl.org/ctdl/terms/> SELECT * WHERE { ?s credreg:__graph <https://credentialengineregistry.org/graph/ce-5ed9190b-f97f-45fa-813a-4a50dbdeb263> . ?s ?p ?o . }
```

Are these bnodes orphan data that wasn't cleared out of the index somehow? How did they end up connected to this record?

**Comment by excelsior** [comment]
I limited the use of the `__graph` property to top-level resources only. Now the above queries return both the graph URI and the top-level resource URI for each property path like that.

**Comment by siuc-nate** [comment]
It looks like the bnodes are the credential alignment objects?
![image](https://user-images.githubusercontent.com/21346519/75993693-80269c80-5ebf-11ea-8ae6-23467a69435b.png)

![image](https://user-images.githubusercontent.com/21346519/75993725-8b79c800-5ebf-11ea-9531-a074c1428956.png)

But I'm not able to retrieve the bnodes themselves - is it possible that the assessment record needs to be reprocessed to remove the bnode references?

**Comment by excelsior** [comment]
Yes, mainly credential alignment objects. And all those bnode resources lack an `@id`, even a blank one. Is that the way it should be?

The following query retrieves each ID-less resource's values:

```sparql
PREFIX credreg: <https://credreg.net/>
PREFIX ceterms: <https://purl.org/ctdl/terms/>
SELECT ?bnode ?bnode_property ?bnode_value WHERE
{
  ?s credreg:__graph <https://credentialengineregistry.org/graph/ce-5ed9190b-f97f-45fa-813a-4a50dbdeb263> .
  ?s ?p ?bnode .
  ?bnode ?bnode_property ?bnode_value
  FILTER(ISBLANK(?bnode))
}
```

**Comment by siuc-nate** [comment]
Thanks.  I haven't seen this kind of thing pop up since it was initially reported, so I'll go ahead and close this for now.
