### ISSUE TITLE
Data size/scaling/performance issue

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#306]
We have a particularly large competency framework in our registry (many thousands of competencies) that we have been wrestling with for some time.  It's the O*NET Technology Skills competency framework:
https://credentialengineregistry.org/resources/ce-9fab4187-d8e7-11e9-8250-782bcb5df6ac

I have attached the description set query for competency frameworks.  This query works fine for other frameworks, but so far I haven't gotten it to work with this one.  Queries tend to time out or return so much data that they crash Postman (which has happened at least twice now).

Previously, we were just getting the `@graph` for this data and doing the description set processing client-side or server-side - and this worked, but it often took a while to happen.  My hope with offloading this processing to the database was that it would be more efficient, since the data could be collected while it was being queried instead of needing to be calculated after being loaded.  This may still technically be true depending on how much processing power our SPARQL instance has.

Is this simply a matter of needing to throw more hardware at the problem? This likely won't be the only massive framework we have to deal with in the future, but they will hopefully be rare.  It may be possible to scale back the extent of the query (most likely starting points would be skipping concept schemes and organization QA), but the majority of it is what @jeannekitchens  wants to see in the DSP search results.

Note that the query (intentionally) does not select the payloads, just the connections - again, this was done with the intent of making things run more smoothly, but even this seems to fail.

Any suggestions?

[ONET technology skills DSP.txt](https://github.com/CredentialEngine/CredentialRegistry/files/4262010/ONET.technology.skills.DSP.txt)

**Comment by siuc-nate** [comment]
To do:
Try this query with smaller frameworks to see if there is extra data coming back in the initial result set that can be filtered out before any further processing.

**Comment by siuc-nate** [comment]
Progress!

The search was indeed (as we discussed in today's meeting) retrieving way more bindings than it needed to. I updated my code to automatically determine which variables were relevant and select only those (instead of a blanket select all).  That caused this framework to go from server-crashingly slow to taking about 45-75 seconds depending on whether or not I have it bring back the competency nodes or just the related items map.  The bindings went from nearly 400,000 to around 19,000 (though there are only about 9,000 competencies in the framework, so there is clearly more optimization to be had).

After that, I tried to make the query process itself go a bit faster, but didn't have much luck there. I tried first do a query to get the count of total bindings, then divide those up into chunks (ranging between 1000 and 10000 depending on the test) and retrieve them via pagination (both synchronously and asynchronously).  This approach actually took more time, since the query had to run twice or more (even if the times after the first were running in parallel).  So this actually goes faster if you just blindly query it single-threaded like I was originally - at least that's simpler, I suppose.

But the main thing is that this framework is now within the realm of something that may be solvable with caching.  I want to try to get that total binding count down further, though.

Thanks for pointing me in the right direction.  I'll update this again if I find some more enhancements.

**Comment by siuc-nate** [comment]
Actually, I think I found the reason why the bindings are double - I forgot that every single competency in that framework has a `ceasn:exactAlignment` with the competency that lives at the official ONET URI - so the 19,000 bindings number is probably pretty close to accurate.

**Comment by jeannekitchens** [comment]
@siuc-nate is this still an open issue?

**Comment by siuc-nate** [comment]
The major problem here was the way SPARQL was selecting duplicate bindings for every credential type - that part was fixed.  However, I recently updated the DSP queries to try to capture more stuff and I think I'll have to back that change off a bit since this query is now timing out (specifically, it's responding with just
```
null
```
after about a minute and a half:
![image](https://user-images.githubusercontent.com/21346519/75995254-c41aa100-5ec1-11ea-884d-8d001654ab21.png)

Probably related to #312 since it also includes an attempt to grab references to condition manifests and whatnot. I'll try it without those.

**Comment by excelsior** [comment]
Could you please attach the fixed query? I couldn't reproduce this exact error, the original query fails because the response is too big, but it never times out, neither does it return `null` with a 201.

**Comment by siuc-nate** [comment]
The handling has changed completely since my last post and it now runs as a series of separate queries for different parts of the description set.  In particular, the processing for competencies is now also "chunked" into queries that process competencies 250 at a time.  So far so good in terms of not getting errors, but it still takes a long time to process everything, even with it running in parallel.  I'm not sure we can do anything about that given there's ~9,000 competencies to grind through.

**Comment by jeannekitchens** [comment]
@siuc-nate is this a Registry issue that the Learning Tapestry team needs to address?  What is the status?

**Comment by siuc-nate** [comment]
I updated the debugging/logging mechanism so that the Registry team can get at the queries and sent them instructions this morning. 

Closing this.
