### ISSUE TITLE
Critical error: getting error: "key must be 32 bytes" when trying to register an organization

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#315]
@excelsior 
Today in  our production environment I saw the following error when trying to register a new organization in the credential registry:
**key must be 32 bytes**

I tried to replicate this/debug using the staging and sandbox environments. 
I got the same error in both. 
I verified that the api token was being passed, and is 32 bytes/characters.

**Comment by mparsons-ce** [comment]
@excelsior @edgarf 
This is critical. This means that any new organizations cannot be registered to publish data to the registry.

**Comment by excelsior** [comment]
@mparsons-ce Could you please send me a sample request for me to test on sandbox or staging, just to make sure we're on the same page?

**Comment by mparsons-ce** [comment]
@excelsior 
Using postman
Url:
https://staging.credentialengineregistry.org/metadata/organizations
request:
{
    "id": null,
    "name": "Lumaway",
    "_ctid": "ce-4aa94bfc-129d-4d13-be77-f52f73324379",
    "description": null
}
token:
![image](https://user-images.githubusercontent.com/58825866/76116303-63699200-5faf-11ea-90b1-9c7db4bf7b8f.png)

![image](https://user-images.githubusercontent.com/58825866/76116116-05d54580-5faf-11ea-8928-23225f5b307c.png)

**Comment by excelsior** [comment]
Thanks, Michael. I pushed the fix onto sandbox and staging. Could you please confirm it's working for you. If it is, I'll deploy it to prod.

**Comment by mparsons-ce** [comment]
@excelsior 
OK, I verified that the registration works in both the sandbox and staging.
