### ISSUE TITLE
Issues with Search index in sandbox

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#319]
@excelsior 
We are still having issues with the search index in the sandbox. Michigan is heavily using the sandbox for publishing and need to be able to find stuff via the index. 

On Feb 26, 2020 based on the question:

> How often is the search index updated in the sandbox?
> A partner from Michigan published an organization almost two hours ago, and we still can't find it via the graph search. 

Alex replied:

> The background process responsible for resource indexing was down on sandbox and won’t start up. I’m investigating what might be wrong with, but in the meantime I’ve indexed all of the pending resources manually. We could run a full reindexing process daily just in case (in addition to the background process).

On Feb. 27, Michael replied:

> I still can't find 'Northern Michigan University' in the sandbox search:
> https://sandbox.credentialengineregistry.org/ce-registry/resources/ce-c7e359c3-a2e6-452e-9d1b-5addebaf838f
> 
> I can find it with the fts search:
> https://sandbox.credentialengineregistry.org/ce-registry/search?fts=Northern%20Michigan%20University

On Mar 19, 2020 Suneetha Chandanam from michigan.gov wrote:
 I just published an organization with the below details but could not find them through Search API by CTID or Name in next moment, can you please let us know how long we will have to wait for the data to be updated in CE and to be able to searched through API ? 

- Name of the organization: Olivet College
- CTID: ce-37ed1ff0-c916-4d05-9530-855c94117169

I checked and cannot find the organization either by ctid or by name, buy can find it via the fts search:
https://sandbox.credentialengineregistry.org/ce-registry/search?fts=Olivet%20college

**Comment by excelsior** [comment]
@mparsons-ce 

The indexing process is up and running again (it was an internal Cloud66 issue that prevented it from being alive). This organization was indexed almost instantly.

Could you please enlighten me on how to look resources up CTID and name?

Hitting https://sandbox.credentialengineregistry.org/ce-registry/resources/ce-37ed1ff0-c916-4d05-9530-855c94117169 returns the expected resource. And I don't know another way of searching by name except the FTS API.

**Comment by mparsons-ce** [comment]
@excelsior 
I tried to search for the org using both ctid and name and didn't get results.
I republished the organization, and then could find the record with ctid or:
{
		"@type": "ceterms:CredentialOrganization",
		"ceterms:name": "Olivet College"
}

**re: Could you please enlighten me on how to look resources up CTID and name?**
The latter is an example of searching by name. Including the type will limit the search to organizations only.

**Comment by jeannekitchens** [comment]
@mparsons-ce @excelsior @siuc-nate 

All, it is critical that any registry issues that are getting in the way of our state partners publishing need to be prioritized and addressed quickly.  This has been open for over a week.  Provide an update and make sure that all things to do with the search include Nate as he is the one spending the most time on search issues.

**Comment by jeannekitchens** [comment]
@mparsons-ce is this resolved for MI?

**Comment by jeannekitchens** [comment]
@mparsons-ce @excelsior @siuc-nate respond and update this status.

**Comment by excelsior** [comment]
Both indexing process (graph and full-text) run smoothly on sandbox.

**Comment by edgarf** [comment]
This issue has been resolved in sandbox, moving this card to "Production" (as it's the last state of the task process pipeline).
