### ISSUE TITLE
Site under Heavy Load error (SPARQL index)

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#320]
When I try to query the SPARQL index, I get the following message:
![image](https://user-images.githubusercontent.com/21346519/77666283-c61ad180-6f4e-11ea-8e56-f228a8858a7f.png)

Since it isn't JSON-encoded, it causes other issues - but what is the source of this error? Is it coming from AWS or the Registry's server?

**Comment by siuc-nate** [comment]
Actually, it might be related to whatever's causing this:
![image](https://user-images.githubusercontent.com/21346519/77666614-29a4ff00-6f4f-11ea-989d-53f358490005.png)

**Comment by siuc-nate** [comment]
I suspect the above is the issue, as I just got this:
![image](https://user-images.githubusercontent.com/21346519/77668597-9a4d1b00-6f51-11ea-9ae3-9c597ec326dc.png)

However, both the AWS and Azure status dashboards show no issues:
https://status.aws.amazon.com/
https://status.azure.com/en-us/status

Are these errors being generated by the Registry's server?

**Comment by edgarf** [comment]
@siuc-nate do you still have this issue?

**Comment by siuc-nate** [comment]
Not at this time.  However, I am still curious about the origin of those HTML-encoded errors.  Shouldn't everything that comes back from the server's API endpoint be in JSON?

**Comment by excelsior** [comment]
@siuc-nate Our app server, Passenger, has a default limit on the number of requests it allows to queue up. We can either increase this number or get rid of the limit entirely. The latter would worsen the timeout problem.

Speaking about timeouts: Although we disabled those for SPARQL queries on our backend, the web server in front of the API (Nginx) has its own timeout limit (currently it's 5 minutes). And when Nginx throws an error, it sends it in the HTML format. We can configure it to respond with our custom error messages in the JSON format, of course. Just let me know if that's important for you.

**Comment by jeannekitchens** [comment]
@siuc-nate @excelsior what's the status of this issue.  Please update for this Thursday's status update.

**Comment by excelsior** [comment]
Last week, we disabled the queue size limit, so this exact error stopped being a thing. However, Steve suggested to increase the limit tenfold instead of getting rid of it completely. Thus the error might still occur in rare cases.

**Comment by siuc-nate** [comment]
This appears to have been fixed.  We haven't seen this error in quite some time, and have fixed our queries so they don't take 5+ minutes.
