### ISSUE TITLE
SPARQL API returning plaintext response

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#321]
Is something being changed/tested?  I keep getting a plaintext formatted result that looks like something that's meant to be translated into JSON, but isn't.

![image](https://user-images.githubusercontent.com/21346519/79388762-8898db00-7f33-11ea-86b9-df07ada18715.png)

![image](https://user-images.githubusercontent.com/21346519/79388911-c8f85900-7f33-11ea-91a3-fa66c18f4400.png)

**Comment by excelsior** [comment]
Good catch, I've just fixed that.

**Comment by siuc-nate** [comment]
Thanks.  It seems to be working again.
