### ISSUE TITLE
Precalculate description sets and store them

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#322]
Based on our meeting earlier this week, I had some ideas for how to handle adding some indexing shortcuts for description set queries.  I think the approach that would be the most useful is to generate the actual data that I'm building anyway, and store it, instead of trying to get it on-demand.

The following example shows the kind of pattern I would be looking for.  I have tried to keep this as simple as possible, in hopes that it's something that could be implemented, maintained, and changed as needed over time.

JSON representation of the data I'm looking for, since that's sometimes easier to visualize (the wrapper credential is just there for context):
```
{
	"@type": "ceterms:Certificate",
	"@id": "https://.../resources/ce-12345...",
	"credreg:__descriptionSet": {
		"@id": "_:12345",
		"credreg:__relatedItemsMap": [
			{
				"@id":"_:abcdefg...",
				"credreg:__dspPath": "> ceterms:requires > ceterms:ConditionProfile > ceterms:targetLearningOpportunity > ceterms:LearningOpportunityProfile",
				"credreg:__dspQuery": "?subject ( ceterms:requires/ceterms:targetLearningOpportunity/^credreg:__graph? ) ?target .",
				"credreg:__dspURI": [
					"https://.../resources/ce-abc...",
					"https://.../resources/ce-def...",
					"https://.../resources/ce-ghi..."			
				]
			},
			{
				"@id":"_:hijklm...",
				"credreg:__dspPath": "< ceterms:targetCredential < ceterms:ConditionProfile < ceterms:isRequiredFor < ceterms:LearningOpportunityProfile",
				"credreg:__dspQuery": "?subject ( credreg:__graph?/^ceterms:targetCredential/^ceterms:isRequiredFor ) ?target . ?target a ceterms:LearningOpportunityProfile .",
				"credreg:__dspURI": [
					"https://.../resources/ce-abc...",
					"https://.../resources/ce-ghi..."
				]
			},
			{
				"@id":"_:nopqrst...",
				"credreg:__dspPath": "> ceterms:requires > ceterms:ConditionProfile > ceterms:targetLearningOpportunity > ceterms:LearningOpportunityProfile > ceterms:teaches > ceterms:CredentialAlignmentObject > ceterms:targetNode > ceasn:Competency",
				"credreg:__dspQuery": "?subject ( ceterms:requires/ceterms:targetLearningOpportunity/^credreg:__graph?/ceterms:teaches/ceterms:targetNode ) ?target .",
				"credreg:__dspURI": [
					"https://.../resources/ce-jkl...",
					"https://.../resources/ce-mno...",
					"https://.../resources/ce-pqr...",
					"https://.../resources/ce-stu...",
					"https://.../resources/ce-vwx..."		
				]
			}
		]
	}
}
```

A Turtle representation of the data would look like this, and is likely what would be stored in the SPARQL database directly:
```
<https://.../resources/ce-12345...> credreg:__descriptionSet <_:12345> .
<_:12345> credreg:__relatedItemsMap <_:abcdefg...> .
<_:12345> credreg:__relatedItemsMap <_:hijklm...> .
<_:12345> credreg:__relatedItemsMap <_:nopqrst...> .
<_:abcdefg...> credreg:__dspPath '> ceterms:requires > ceterms:ConditionProfile > ceterms:targetLearningOpportunity > ceterms:LearningOpportunityProfile' .
<_:abcdefg...> credreg:__dspQuery '?subject ( ceterms:requires/ceterms:targetLearningOpportunity/^credreg:__graph? ) ?target .' .
<_:abcdefg...> credreg:__dspURI <https://.../resources/ce-abc...> .
<_:abcdefg...> credreg:__dspURI <https://.../resources/ce-def...> .
<_:abcdefg...> credreg:__dspURI <https://.../resources/ce-ghi...> .
<_:hijklm...> credreg:__dspPath '< ceterms:targetCredential < ceterms:ConditionProfile < ceterms:isRequiredFor < ceterms:LearningOpportunityProfile' .
<_:hijklm...> credreg:__dspQuery '?subject ( credreg:__graph?/^ceterms:targetCredential/^ceterms:isRequiredFor ) ?target . ?target a ceterms:LearningOpportunityProfile .' .
<_:hijklm...> credreg:__dspURI <https://.../resources/ce-abc...> .
<_:hijklm...> credreg:__dspURI <https://.../resources/ce-ghi...> .
<_:nopqrst...> credreg:__dspPath '> ceterms:requires > ceterms:ConditionProfile > ceterms:targetLearningOpportunity > ceterms:LearningOpportunityProfile > ceterms:teaches > ceterms:CredentialAlignmentObject > ceterms:targetNode > ceasn:Competency' .
<_:nopqrst...> credreg:__dspQuery '?subject ( ceterms:requires/ceterms:targetLearningOpportunity/^credreg:__graph?/ceterms:teaches/ceterms:targetNode ) ?target .' .
<_:nopqrst...> credreg:__dspURI <https://.../resources/ce-jkl...> .
<_:nopqrst...> credreg:__dspURI <https://.../resources/ce-mno...> .
<_:nopqrst...> credreg:__dspURI <https://.../resources/ce-pqr...> .
<_:nopqrst...> credreg:__dspURI <https://.../resources/ce-stu...> .
<_:nopqrst...> credreg:__dspURI <https://.../resources/ce-vwx...> .
```

The `credreg:__dspPath` property contains the verbose path that I use as part of my output for the search API. Its purpose is to give the API consumer a very specific idea of exactly where the data came from.

The `credreg:__dspQuery` property contains the equivalent SPARQL query that would be needed to get data for that path.

The `credreg:__dspURI` property is a list of 1-n URIs that match that query (in other words, the URIs for the value of `?target`).

If there aren't any URI matches for a given path, then the path and query don't need to be included/stored.

I also encapsulate all of this as a value for the `credreg:__descriptionSet` property at the root level of the relevant objects so that these don't get scattered all over the index.  The idea is that I would just select this alongside the payload match in the initial search and effectively bypass the need to do a real-time description set query all together - it doesn't get much faster than that, in theory.

Hopefully this setup is something that can be handled via configuration so that more can be added to it if needed.  

The one thing I'm not sure about is how to go about maintaining it when something gets added or deleted to the index.  The use of reverse properties for a lot of connections means that any record could potentially need to be updated when any other record is added, modified, or deleted.

This obviously isn't a complete set of terms/paths/queries/etc. - but does this kind of approach seem practical?

**Comment by jeannekitchens** [comment]
@siuc-nate who is this information for?  Who needs to act on it?

**Comment by siuc-nate** [comment]
No action at this time.  I was looking for feedback from the LT team on the viability of this as a concept.

**Comment by siuc-nate** [comment]
Per our meeting today, this seems like a viable approach if we can solve the issues related to keeping the description sets up to date.

**Comment by excelsior** [comment]
@siuc-nate 

I updated the indexer to precalculate the above description sets the way you described it. It's available on production for testing.

Below is the INSERT statement used for handling the description sets for certificates. It only takes 7s to complete, so chances are we probably wouldn't need some sophisticated approach for incremental description set updates, since we can always prepare them from scratch.

```sparql
PREFIX ceterms: <https://purl.org/ctdl/terms/>
PREFIX credreg: <https://credreg.net/>

INSERT
{
  ?subject credreg:__descriptionSet [
    credreg:__relatedItemsMap [
      credreg:__dspPath '> ceterms:requires > ceterms:ConditionProfile > ceterms:targetLearningOpportunity > ceterms:LearningOpportunityProfile';
      credreg:__dspQuery '?subject ( ceterms:requires/ceterms:targetLearningOpportunity/^credreg:__graph? ) ?target';
      credreg:__dspURI ?target1
    ];
    credreg:__relatedItemsMap [
      credreg:__dspPath '< ceterms:targetCredential < ceterms:ConditionProfile < ceterms:isRequiredFor < ceterms:LearningOpportunityProfile';
      credreg:__dspQuery '?subject ( credreg:__graph?/^ceterms:targetCredential/^ceterms:isRequiredFor ) ?target . ?target a ceterms:LearningOpportunityProfile';
      credreg:__dspURI ?target2
    ];
    credreg:__relatedItemsMap [
      credreg:__dspPath '> ceterms:requires > ceterms:ConditionProfile > ceterms:targetLearningOpportunity > ceterms:LearningOpportunityProfile > ceterms:teaches > ceterms:CredentialAlignmentObject > ceterms:targetNode > ceasn:Competency';
      credreg:__dspQuery '?subject ( ceterms:requires/ceterms:targetLearningOpportunity/^credreg:__graph?/ceterms:teaches/ceterms:targetNode ) ?target';
      credreg:__dspURI ?target3
    ]
  ]
}
WHERE
{
  {
    ?subject a ceterms:Certificate .
  }
  UNION
  {
    ?subject ceterms:requires/ceterms:targetLearningOpportunity/^credreg:__graph? ?target1
  }
  UNION
  {
    ?subject credreg:__graph?/^ceterms:targetCredential/^ceterms:isRequiredFor ?target2 .
    ?target2 a ceterms:LearningOpportunityProfile
  }
  UNION
  {
    ?subject ceterms:requires/ceterms:targetLearningOpportunity/^credreg:__graph?/ceterms:teaches/ceterms:targetNode ?target3
  }
}
```

**Comment by siuc-nate** [comment]
Thanks, this may be good for some initial testing.  Of course the real description sets are far, far more complex - I will try to get you a comprehensive list of connections for those as soon as time allows.

**Comment by siuc-nate** [comment]
Okay, I _think_ this has everything:
https://docs.google.com/spreadsheets/d/1VNgJ7qu_zydCB3UQMzEuHbYKczr_Q9nkRRxzoUWYLuk/edit#gid=0

I'm going to look back through the code that generates the current description sets and see if I can spot any missed routes.

- The "Starting Point Type" column contains a list of entity types that that row applies to.  If needed, I can expand "Credential" to the full list of credential types.
- The "Name" column doesn't need to be stored anywhere; that's just to make it easier to identify what's what on this spreadsheet
- The "Path" column contains the `credreg:__dspPath` value for an item map object
- The "Query" column contains the `credreg:__dspQuery` value for an item map object

I haven't tested all of the paths yet - I'll try to find some time to do that.  I'm curious whether the SPARQL somehow runs faster if each path is crawled separately rather than as one big branching tree of paths like how we currently do it.

Note that if this approach does work, it will need to be expanded upon to handle the navy schema terms as well.  And it's likely that some of these will be added, removed, or adjusted in the future.  So the more flexible/configurable this is, the better.

**Comment by siuc-nate** [comment]
We still need to address the problem of keeping data maintained when something changes.  I suspect the most reliable workflow will be:

1. Something gets published to the registry
2.a. If it is a new record (not an update)...
2.a.1. Build the description set for that object
2.a.2. Keep track of any record that gets referenced in the process of building that description set
2.a.3. For each record that was referenced, if it is associated with a description set of its own, rebuild its description set
2.b. If it is an update to an existing object, or a delete/purge/removal...
2.b.1. Keep track of every record that was referenced by the old version's description set
2.b.2. Remove the updated record entirely from the index, as though it were never there
2.b.3. For each record that was in the old version's description set, if it is associated with a description set of its own, rebuild its description set
2.b.4. Add the updated record to the index
2.b.5. Build the description set for the updated record
2.b.6. Keep track of any record that gets referenced in the process of building the updated record's description set
2.b.7. For each record that was referenced, if it is associated with a description set of its own, rebuild its description set

It may be possible to merge 2.b.1 and 2.b.6 to simplify the update process - I'm just trying to be very careful to avoid any chance of "straggler" references from being left behind in the event of an update, deletion, and/or purge of a record.

I don't _think_ it would be necessary to rebuild description sets that aren't directly associated with the new/updated record (i.e. A references B and B references C, we don't need to rebuild C's description set) because I don't see how any of that data would change, but that's something to keep an eye out for just in case.

**Comment by excelsior** [comment]
@siuc-nate Pre-calculated description sets are available on staging.

I've included all of the credential types (not only `ceterms:Credential`, but also `ceterms:Badge`, `ceterms:Certificate`, `ceterms:Degree`, etc—22 types in total).

Description sets are inserted on a per resource basis. Processing 18,490 subjects takes just under an hour.
