### ISSUE TITLE
Archive.org backup is not active

### ISSUE THREAD

**Issue by science** [CredentialEngine/CredentialRegistry#323]
The archive.org backup is not active. It appears to have stopped in late Dec 2019. 

1. We need to restart this function.
2. We should add a status check to verify backups are active, if possible
3. We should consider multiple exports to archive.org: the original envelopes, and possibly some kind of triple export.

**Comment by edgarf** [comment]
@excelsior - the account on archive.org is ready. 

1) Let's put all of the older archives into this account from here https://archive.org/details/ce-registry
2) Make the archival function work again (it's broken now).

**Comment by excelsior** [comment]
This is what I've done:

1. Set up the archival function on the new server with the proper credentials
2. Moved all the old dumps into the new bucket.
3. Generated and uploaded dumps for each day since Dec 30, 2019.

**Comment by mparsons-ce** [comment]
@science @excelsior 
We are documenting our disaster recovery plan. 
The URL referenced above (https://archive.org/details/ce-registry) shows no data available.
![image](https://user-images.githubusercontent.com/58825866/113617672-407b3880-961c-11eb-9b7d-be6e7eea8561.png)

Is the latter supposed to be the main URL to be used to see/verify credential registry backups?
We will want to reference the appropriate URL in the recovery plan.

**Comment by excelsior** [comment]
@mparsons-ce About a year ago, we found out that we'd lost access to that account at some point, so your team created a new one: https://archive.org/details/credential-engine

There is the same message on that page, too. It basically says that Archive.org can't _display_ the contents of the uploaded files (I guess they only able to preview a handful of common formats, and gzip isn't among those). There is a `Show all files` link under that message that leads directly to the list of our backups: https://archive.org/download/credential-engine

**Comment by jeannekitchens** [comment]
@mparsons-ce seems the only issue here is having two accounts.   Can the one that isn't actively used be closed?  May be a silly question since it is an archive but if it was never used, we need to eliminate any confusion.  Otherwise, @excelsior isn't this this fully operational?

**Comment by lucianopanaro** [comment]
@jeannekitchens the process is active and backing up at https://archive.org/download/credential-engine

#469 updates the README with the correct URL. @edgarf perhaps this issue can be closed when merged.
