### ISSUE TITLE
Using the gremlin query shows there are 449 competency frameworks, while the sparql query returns 421. 

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#327]
Using simple query for a type of competency framework:
  "Query":  {
	"@type": "ceasn:CompetencyFramework"
}
The gremlin endpoint returns a total of **449** 
The sparql endpoint returns **421**. 

The correct amount is 449.

**Comment by excelsior** [comment]
I've updated the SPARQL index from scratch, and now the SPARQL query shows **429** competency frameworks.

Here's the query I used to calculate the number of competency frameworks in the registry:

```sql
SELECT COUNT(*)
FROM envelopes
CROSS JOIN LATERAL jsonb_array_elements(processed_resource->'@graph') AS graph(resource) 
WHERE envelopes.deleted_at IS NULL
AND graph.resource->>'@type' = 'ceasn:CompetencyFramework'
```

It, too, returns **429**.

@mparsons-ce Could you please confirm whether my analysis is correct? If so, then the Gremlin index might still contain some of deleted resources.

**Comment by mparsons-ce** [comment]
@excelsior Yes, I believe that 429 is now correct as I did purge 20 competency frameworks over the weekend. 
The Gremlin index is now incorrect, as it still shows 449.

**Comment by excelsior** [comment]
I've rebuilt the Gremlin index, and now it also returns **429** competency frameworks. Fixing #328 will resolve this issue for good.
