### ISSUE TITLE
Documents that were purged are still showing in SparQL and gremlin indices

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#328]
@excelsior @edgarf 
We used the new **Purge** endpoint to remove a number of documents last week. 
I noticed that the totals returned from the sparql query were not changing. 
I did a sparql search for one of these:
	"@type": "ceasn:CompetencyFramework",
	"ceterms:ctid":"ce-c79dac02-ff1f-4932-99f4-7663e5a9d943"
And data was returned. 
Following the returned @id will get no matching resource found. 
I tried the above using the gremlin search and got the same unexpected result. 
I also tried some credentials that were purged, and again got results even though the document no longer exists in the registry. 
For example, a query on the following would return a record:
"ceterms:ctid":"ce-9c2e30f8-5b06-4d5d-828b-4fc65d351a56"
Even though the URL is invalid:
https://credentialengineregistry.org/resources/ce-9c2e30f8-5b06-4d5d-828b-4fc65d351a56

You can use the query helper to verify the issue:
https://credreg.net/quickstart/queryhelper

Other purged documents include:
ce-c38cc08a-147d-4e84-a492-43a72431767b
ce-db775fe0-2273-461a-87ff-c54369b35fe6
ce-fa53b80a-798c-4201-a174-029816568660
ce-bffa4144-6997-496d-a2ee-ff2a47e753c5
ce-27c6567d-2947-484d-a85c-41922565b9d9

**Comment by excelsior** [comment]
Good catch @mparsons-ce 

Physically deleted documents aren't handled correctly during indexing. I'll make the necessary adjustments.

**Comment by edgarf** [comment]
Done for SPARQL. Pending for GREMLIN.
