### ISSUE TITLE
Document how to startup new API users

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#33]
Think if we are implementing it the right way

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
Currently, for the staging server, there is no requirement to set up an account of any sort. Anyone can set up the necessary public/private keys, and publish to the registry. Generally this is fine for the staging server. 
The approach for production has not been fully defined. 
Steve (@science ) had a suggested a mechanism something like the following:

- a registration url would be identified
- a new user/organization would visit the registration page, and fill out the necessary information (TBD)
- the latter could include credentials like a URI for the org, and password
- the request would be submitted to a private google group
- administrators for the group would be notified of a new registration
- an administrator would review the request, and approve or deny
- if denied, the organization would be contacted with the reason

**Approval**
**We need to document what happens on approval.**

- Could the registry generate the public/private keys for the organization? (see #59) 
- a future service would be determine which publishing model the user will use. 
 -- for example, direct publishing (push), or one of the proposed pull models


**Accessing the Registry in Production**
Once a person has the necessary credentials, how will the publishing workflow differ from the current staging environment.

**Prototyping Production-Like Authorization**
As the process for production registration and authentication is documented, we will want test the process. How would this be best accomplished?
- We could implement a similar process for the staging server
- Or, we could have a separate community that mirrors the process for production

**Comment by siuc-nate** [comment]
On approval, would it be possible to generate/issue a UUID to the organization (to address part of the problem brought up in #37)?

**Comment by leolara** [comment]
@siuc-nate I think it is more complex. Because several users may be managing the same organisation, a user might manage more than one, etc.

So I guess there could be a process of registering organisation similar to the one registering users that would generate an UUID.

@siuc-nate @cwd-mparsons 

in both things you are mentioning, there are elements that I would not implement perhaps all of them as part of the Registy API, they sound like a layer on top. Or perhaps another layer in the registry.

I think first it has to be decided things about the real world, on how a person proofs that should given access, etc, and then work on how to implemetn this technically.

**Comment by leolara** [comment]
@cwd-mparsons @siuc-nate so basically, I think we need to have more clear idea about #37 in an abstract sense before thinking about how to implement it on this system.

When I created this issue, I meant to document how to add an user in a technical sense for an Administrator user. It results that currently, there is no need to add an user, any user can publish, I think we should document that until in changes.

**Comment by leolara** [comment]
@coffeejunk please document that to publish it is not necessary to add the user, that any user with a public key can publish, and that document the few actions (perhaps only changing schema?) for which to add the public key in the code is necessary
