### ISSUE TITLE
Updated fixtures/configs/ce_registry.json to add TransferValueProfile

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#332]
@excelsior 
I updated the fixtures/configs/ce_registry.json:

- Added new top level class of TransferValueProfile
- Added some additional fts properties to some of the classes

Please update the sandbox. 
Thanks

**Comment by excelsior** [comment]
@mparsons-ce The changes have been deployed to sandbox.

**Comment by jeannekitchens** [comment]
@mparsons-ce per ACE, they're ready to test next week.  We'll need to have a search in place when they publish to production.  Why is this relying on Tapestry team to make updates every time there's a new class added or errors are found with existing classes?

**Comment by mparsons-ce** [comment]
@jeannekitchens 
The change is for the full text search. No updates are necessary for the graph search.

**Comment by excelsior** [comment]
@mparsons-ce Are these changes good to be merged into master and deployed to prod?

**Comment by mparsons-ce** [comment]
@excelsior yes, the changes can be promoted to production

**Comment by mparsons-ce** [comment]
@excelsior Have these changes been promoted to production?

**Comment by excelsior** [comment]
@mparsons-ce Yes, they have. Please take a look.
