### ISSUE TITLE
Count of Competency frameworks differs between the gremlin and sparql endpoints

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#339]
- Ctdl: 434, 
- Sparql: 430

**Comment by mparsons-ce** [comment]
The plot thickens, I just did a fts search for competency frameworks, and I get **436** with the latter!
https://credentialengineregistry.org/ce-registry/search?resource_type=competency_framework&page=1&per_page=10

**Comment by mparsons-ce** [comment]
July 9, 2020 
- gremlin: 434
- sparQL: 435
-fts: 437

**Comment by excelsior** [comment]
I fixed the discrepancy, now all the indices contain ~470 frameworks.

There are a couple of issues with the data preventing the perfect match:

1. SPARQL doesn't support non-ASCII characters in URIs, one of the frameworks are missing from the index for that reason.
2. Another framework fails to get indexed in Gremlin for some vague reason. Am still debugging it.

**Comment by edgarf** [comment]
@excelsior will review this once he's back from va
cation next week.

**Comment by siuc-nate** [comment]
We're no longer using gremlin. Closing this.
