### ISSUE TITLE
Adding requirement that an Api Key be required to use the full text search

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#341]
We currently have no idea if there are partners using the full text search in general, or for downloading most if not all of the data for off line usage. 
We would like to implement that an API key be required when using the full text search - primarily in production. 

We would use a similar approach as was used when the navy community was locked down. #270 
However there will **not** be any API key required for the /resources/, /graph, or /envelopes endpoints. 
We will need to notify partners before implementing this update in production, and so will want to prototype in staging first.
Are there any statistics/logging available now for the use of the search?

**Comment by excelsior** [comment]
I suggest to add a `secured_search` flag to communities, which will work exactly as the `secured` flag, but effective for the search API only.

Also, there are two search endpoints:

1. GET /search
2. GET /{community}/search

How should we the former work in this scenario? Should it be gone or just search across all of the non-secured communities (if there will be any)?

According to the logs, we had 106 search requests for the past two weeks.

**Comment by mparsons-ce** [comment]
We want to be able to log when the searches are called as well.
The existing API is:
https://apps.credentialengine.org/accountsAPI/Organization/ValidateApiKey?apikey=b13924b5-5583-4756-b176-77f707d06f57

**Comment by siuc-nate** [comment]
Wouldn't it make more sense to just require those kinds of searches to go through our server the same way that we do for publishing and SPARQL API searches?

**Comment by edgarf** [comment]
@excelsior is there a way to get logs to see what are the API requests that are coming?

**Comment by siuc-nate** [comment]
Implementation delayed pending notifications of consumers of this API

**Comment by siuc-nate** [comment]
CE has made progress on this, but has some more adjustments and testing to do.  Namely, the CE side needs to handle communities.

**Comment by siuc-nate** [comment]
Communities are now handled. @cwd-mparsons is there anything else we need to setup/do before enacting this change?

**Comment by siuc-nate** [comment]
@mparsons-ce may have found an error with our implementation - when he gets a chance, he will test and confirm.

**Comment by edgarf** [comment]
@mparsons-ce will let @excelsior know when to deploy it on sandbox

**Comment by mparsons-ce** [comment]
@excelsior Please deploy this to staging and sandbox.

**Comment by mparsons-ce** [comment]
@excelsior 
Sorry make that deploy to staging and production. A key will not be required for the sandbox.

**Comment by excelsior** [comment]
@mparsons-ce The feature has been deployed to production and staging. And it's enabled for the Navy community on staging. Let me know if it should be enabled for CER as well.

**Comment by mparsons-ce** [comment]
@excelsior 
I was able to do a production registry search from a browser:
https://credentialengineregistry.org/ce-registry/search?resource_type=credential&per_page=25

This should have failed as an API key was not provided.

**Comment by excelsior** [comment]
@mparsons-ce I was hesitant to enable it on production right away, thought it'd be safer to try it on staging first. But now it's turned on prod as well, please give it another try.

**Comment by excelsior** [comment]
@mparsons-ce BTW, we don't have the API key validation endpoint set up on prod. What should it be?

**Comment by mparsons-ce** [comment]
The endpoint is: 
https://apps.credentialengine.org/accountsAPI/Organization/ValidateApiKey?apikey=**[apikey]**

**Comment by excelsior** [comment]
Done, it should work now.

**Comment by mparsons-ce** [comment]
Great. I was able to validate that a request failed with an invalid or missing API key and was successful with it.

**Comment by mparsons-ce** [comment]
Verified complete.
