### ISSUE TITLE
Added new class of pathwaySet to fixtures

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#343]
I added the class ceterms:PathwaySet to ce_registry.json and navy.json in the fixtures/configs file:
https://github.com/CredentialEngine/CredentialRegistry/tree/master/fixtures/configs

Please promote these changes to the sandbox and staging environments.

**Comment by excelsior** [comment]
Done.

I also had to fix a missing comma in the Navy schema: https://github.com/CredentialEngine/CredentialRegistry/pull/344/commits/2eaa21decbce0281b4cb8b4ba1c8ff32ff2a31c7

**Comment by jeannekitchens** [comment]
@mparsons-ce there is still an open issue for making this promotion available so it's not dependent on requests.  Verify this one can be closed but the issue of a dependence every time there's a class

**Comment by mparsons-ce** [comment]
Thanks Alex. I updated navy.json for the missing period.

**Comment by mparsons-ce** [comment]
@excelsior 
There is one pathwaySet in the sandbox:
https://sandbox.credentialengineregistry.org/envelopes/ce-bf3f4eb2-d687-41b8-bd4d-bfff21d0cec4

When I issue a search for resource type of pathway_set, I don't get any results:
https://sandbox.credentialengineregistry.org/ce-registry/search?resource_type=pathway_set

**Comment by mparsons-ce** [comment]
@excelsior 
I checked the schemas/info endpoint and **pathway_set** is not shown. 
https://sandbox.credentialengineregistry.org/schemas/info

Actually **pathway_component** is not showing either, and it was added some time ago:
![image](https://user-images.githubusercontent.com/58825866/88549367-d36fc780-cfe5-11ea-9fc7-8ebf96f05cc9.png)

We will also need production updated this week. 
Thanks.

**Comment by excelsior** [comment]
The PathwaySet resource was published on July 16, but the schema was updated a week later. So the FTS indexer couldn't index the resource due to the lack of its definition. I reindexed everything, and now the resource is show in search results. Republishing would've worked, too.

The `/schemas/info` endpoint lists all of the available schemas. We don't have schemas for PathwaySet and PathwayComponent, only config entries.

**Comment by mparsons-ce** [comment]
Thanks for the reminder. 
I updated the fixture configs to include aliases for pathway_component as is being done for credential:
		"ceterms:AssessmentComponent":"pathway_component",
		"ceterms:BasicComponent":"pathway_component",
		"ceterms:CocurricularComponent":"pathway_component",
		"ceterms:CompetencyComponent":"pathway_component",
		"ceterms:CourseComponent":"pathway_component",
		"ceterms:CredentialComponent":"pathway_component",
		"ceterms:ExtracurricularComponent":"pathway_component",
		"ceterms:JobComponent":"pathway_component",
		"ceterms:SelectionComponent":"pathway_component",
		"ceterms:WorkExperienceComponent":"pathway_component",

**Comment by mparsons-ce** [comment]
TODO: I will need to add json-ld schemas for all of the pathway component classes.
I will start with a subset of the properties to determine if that is all that is necessary for use pathway_component in the fts search.
