### ISSUE TITLE
Need a way to download all current Registry resources in bulk

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#347]
We have a pressing need to be able to get all of the Registry resources in a single download (or at least a small number of downloads).  These resources would only be the current/active versions, not all of the archival data/previous versions.

For the first run of this, it can just be a single zip file of JSON documents (specifically, the JSON-LD payloads - we can leave out the envelopes).  We'll probably want some options and features as well, but those can come later.

I need this ASAP for the ARTT project and we have a very similar request from one of our partners as well.

What would it take to enable this, preferably this week or early next week if possible?  It would need to require an API key like our search does, of course, but that can come after we've provided the data to our partner for ARTT as well.

For this immediate need, it could even just be a zip file sitting in AWS so I can give the link to our partner for ARTT.  But we will definitely need this functionality going forward as well.

**Comment by stuartasutton** [comment]
Nate, when you say "all of the Registry resources", do you mean the entire registry?

**Comment by siuc-nate** [comment]
For ARTT: Yes, the partner wants all of the resources we can throw at them for their AI processor.

For the API/etc. going forwards: We can/should discuss that. Mike suggested breaking things down by `@type`. I think that may make sense (perhaps as categories of `@type` so that all credentials can be packaged together)

**Comment by stuartasutton** [comment]
Ah, yes. If yesterday afternoon's ARTT call was with Tanjo, I should probably been on the call. If it was a calendar invite, I was not on the list.

**Comment by jeannekitchens** [comment]
@siuc-nate in this case, just get a download via file transfer to Tanjo.  This bulk upload cannot be open without a key via the account system.

**Comment by siuc-nate** [comment]
Yes, any implementation of this for partners that we'd offer as an API would be secured like any other - I mentioned this in the first post.

**Comment by jeannekitchens** [comment]
I don't want Registry team to do anything at this time unless it's for our internal use only.

**Comment by siuc-nate** [comment]
We do have at least one other outstanding request from a partner for the same kind of functionality (just downloading files instead of setting up the whole import process).  What should we tell them?

**Comment by excelsior** [comment]
@siuc-nate I put an archive with all of the registry payloads into S3: https://cer-graph-uploads.s3.us-east-2.amazonaws.com/ce_registry.zip

It contains one file per envelope named after the corresponding envelope's ID. Let me know if you rather have a file per resource instead.

**Comment by siuc-nate** [comment]
Thanks.  The envelopes themselves have extra data and don't use CTDL, and we don't want to confuse the AI, so it would be preferable I think to have the payloads instead.

**Comment by siuc-nate** [comment]
Thanks for jumping right on this - I'll send it to them immediately.

**Comment by mparsons-ce** [comment]
The import has a download only option. 
The graphs are downloaded and stored in a folder.

**Comment by siuc-nate** [comment]
Delaying further implementation here pending further internal discussions.

**Comment by jeannekitchens** [comment]
@edgarf @excelsior let's look at if this is something you can do on your side.  Provide a time estimate.  Requirements are users have to be issued a key by our account system to get this access, they can download the JSON.  Need to determine if it's at the envelope or payload levels or offer an option to do one or the other.  The users would not need to, for example, install visual studio as is currently required.

**Comment by mparsons-ce** [comment]
@edgarf @excelsior 
Have had an opportunity to formulate an estimate for this request?

**Comment by excelsior** [comment]
@mparsons-ce Looks like we don't have to care about making this API asynchronous, b/c archiving the current amount of data is fairly quick. My estimate is 2—3 hours.

**Comment by excelsior** [comment]
@mparsons-ce @siuc-nate

It's possible now to an archive with all of the current data on production: `GET /envelopes/download`. 

That archive takes a few minutes to generate. It's also possible to download resources of a specific community: `GET {community}/envelopes/download`.

**Comment by mparsons-ce** [comment]
@excelsior Thanks
Would it be possible to use the CTID in the file name instead of the envelope identifier? The latter will be more useful and the CTID is the main identifier people would be interested in.

**Comment by excelsior** [comment]
@mparsons-ce Done!

**Comment by mparsons-ce** [comment]
@excelsior Also, please make this available in the sandbox (I see it is on staging) as well. 
This could be useful for partners to test consuming a download, as well as for my testing.

**Comment by excelsior** [comment]
@mparsons-ce Deployed to sandbox.

**Comment by mparsons-ce** [comment]
@excelsior 
Thank you sir

**Comment by mparsons-ce** [comment]
Thank you
