### ISSUE TITLE
Access resources by @id in /resources/{@id}

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#35]

**Comment by leolara** [comment]
We have

/{community}/resources/{@id}

and 

/resources/{@id} that uses default community

Implement CRUD acctions on this resource

**Comment by leolara** [comment]
Note that the read (GET) operation returns the resource itself without envelope, while the other operations require envelope

**Comment by leolara** [comment]
Note that although non-GET operations use envelopes, the @id url param always refers to the resource @id, never to the envelop id.

**Comment by coffeejunk** [comment]
Should the operations (other than `GET`) return the resource or the envelope?

**Comment by leolara** [comment]
I think they should return the same as in the /envelop/ calls.

This is like the envelope calls but:
 + Using the resource @id as url param instead of the envelope id
 + GET retruns the resource, wihtout the envelope
 + The default community thing and the prefix thing

The rest should be like the /envelopes/ API call

**Comment by coffeejunk** [comment]
Having both `/resources/{id}` and `/resource/{id}` is possible and somewhat simple, however the implementation is not the pretties as grape doesn't support alias routes. 

If it is deemed necessary to have both we can do it (see 4633ad08f293d8ffe5c8ee6366d539017f8c350a) but I personally would prefer an executive decision to go for one route and not allow the other (or as a friendly alternative redirect).

**Comment by leolara** [comment]
@coffeejunk 
 + index route at the moment not a requirement
 + route decision about /resources or /resource must be done by @jkitchensSIUC @cwd-mparsons @siuc-nate I asked here: #1
