### ISSUE TITLE
Enable FTS search for all pathway components using alias of pathway_component

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#350]
We will want to be able to have the fts search return all types of pathway components, by using resource_type=pathway_component

I updated the fixture configs to include aliases for pathway_component as is being done for credential:
"ceterms:AssessmentComponent":"pathway_component",
"ceterms:BasicComponent":"pathway_component",
"ceterms:CocurricularComponent":"pathway_component",
"ceterms:CompetencyComponent":"pathway_component",
"ceterms:CourseComponent":"pathway_component",
"ceterms:CredentialComponent":"pathway_component",
"ceterms:ExtracurricularComponent":"pathway_component",
"ceterms:JobComponent":"pathway_component",
"ceterms:SelectionComponent":"pathway_component",
"ceterms:WorkExperienceComponent":"pathway_component",

Next Steps
CE team :
- nothing yet

Michael 
- will need to format the JSON-LD schemas for all of the pathway component classes.
- upload to Github
- notify the CE team

**Comment by jeannekitchens** [comment]
@mparsons-ce is this your task or does this need to be assigned?  We are going to be moving some of the Badgr pathways to production.

**Comment by mparsons-ce** [comment]
@excelsior This seems to be working in the sandbox.

Please promote this to staging and production.

**Comment by siuc-nate** [comment]
@excelsior What is the status of this?

**Comment by mparsons-ce** [comment]
This has been verified as working in production.
