### ISSUE TITLE
Enable getting bnodes in bulk

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#352]
It would be very useful if the existing search feature that allows getting multiple CTIDs at once was expanded to handle bnode URIs as well.  This would save multiple round-trips to the Registry downloading `@graph` data that is mostly not needed.

I recommend a POST body structure for `https://credentialengineregistry.org/resources/search` like this (but am open to feedback):
```
{
  "ctids": [ "ce-00d41001-76b3-4fae-9508-0212b0cad347", "ce-03dc1c17-0a0e-47e7-b3d9-878f7ec03dfe", "ce-16ade8f0-16ee-4525-8964-1a87366c035c" ],
  "bnodes": [ "_:d4ff14cf-4a76-48bf-9250-f0df3fe3d278" ]
}
```

**Comment by excelsior** [comment]
Does that also mean that resources with bnode IDs should be retrievable directly, i.e. `GET /resources/_:123` should return the resource with the matching ID?

**Comment by siuc-nate** [comment]
If that makes it easier to implement, sure, but strictly speaking, bnodes aren't supposed to be retrievable without getting their parent `@graph`.  The problem is that getting a bunch of graph payloads only to get the bnodes (and more or less throwing away the rest) isn't very efficient.  So this would be something meant to be used internally alongside our process for getting the first x items from each branch of a description set.

If it's faster/easier/simpler to alter _that_ process to enable returning the records (and bnodes) and not just the URIs, that is an alternative we can discuss - I just figured it might overcomplicate that process to try fetching the data.  But I'm not familiar enough with your internal architecture to say for sure.

Anyway, making it possible to retrieve bnodes directly wouldn't technically be a problem, but it wouldn't be something we would want to promote or rely on, as it's technically "wrong" in terms of how RDF is supposed to work.

**Comment by excelsior** [comment]
I added this functionality without changing the way bnodes were treated. The change is available on staging.

**Comment by siuc-nate** [comment]
Thanks.  What does the syntax look like? For example, if I receive a bnode URI from a description set via #342, the data looks like this:
```
{
  "path": "> ceterms:accreditedBy > ceterms:Agent",
  "total": 1,
  "uris": [
      "https://credreg.net/bnodes/d4ff14cf-4a76-48bf-9250-f0df3fe3d278"
  ]
}
```
Then which of the following placements/formats is correct?:
```
{
	"ctids": [ "https://credreg.net/bnodes/d4ff14cf-4a76-48bf-9250-f0df3fe3d278", "_:d4ff14cf-4a76-48bf-9250-f0df3fe3d278", "d4ff14cf-4a76-48bf-9250-f0df3fe3d278" ],
	"bnodes": [ "https://credreg.net/bnodes/d4ff14cf-4a76-48bf-9250-f0df3fe3d278", "_:d4ff14cf-4a76-48bf-9250-f0df3fe3d278", "d4ff14cf-4a76-48bf-9250-f0df3fe3d278" ]
}
```

**Comment by siuc-nate** [comment]
Note: If I do this query on staging to find the NOCTI organization:
```
{
    "query": "PREFIX ceasn: <https://purl.org/ctdlasn/terms/> PREFIX ceterms: <https://purl.org/ctdl/terms/> PREFIX credreg: <https://credreg.net/> SELECT ?uri WHERE { ?uri ceterms:name ?name FILTER(REGEX(STR(?name), 'nocti', 'i')) } LIMIT 10"
}
```
The result that contains it has a URI of
```
https://credentialengineregistry.org/resources/ce-6a62b250-a1a2-4d31-a702-cdc2437efd31
```
which appears to be its production URI rather than a staging URI.  This means that I get no results when I try to get the description set for it on staging:
```
https://staging.credentialengineregistry.org/description_sets/ce-6a62b250-a1a2-4d31-a702-cdc2437efd31?limit=10
```
which in turn means that I don't have access to a staging bnode ID to try out with the question in my above post.

**Comment by siuc-nate** [comment]
This is now working on production:
```
{
	"ctids": [ "ce-82a854b6-1e17-4cd4-845d-0b9b6df2fb5c" ],
	"bnodes": [ "_:d4ff14cf-4a76-48bf-9250-f0df3fe3d278" ]
}
```

**Comment by jeannekitchens** [comment]
@siuc-nate is this still an open issue?

**Comment by siuc-nate** [comment]
This can now be closed.
