### ISSUE TITLE
Determine best setup of Navy Registry

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#354]
Short-Term:
- We know there is a Navy ARTT partition of the Staging CE Registry
- We need to know if there is an existing SPARQL instance for the Navy ARTT partition, or if it is currently sharing the CE Staging SPARQL instance
- Confirm whether there are exist a "production", "sandbox", and a "staging" SPARQL instance or just a "production" and "staging" SPARQL instance
![image](https://user-images.githubusercontent.com/21346519/90659023-d7b88a80-e209-11ea-83c4-08c2d2e82b69.png)

Longer-Term:
There is some upcoming Navy work that may involve setting up a separate partition for Ready Relevant Learning (RRL) that would be separate from the ARTT partition at both the Registry and SPARQL level.  We will be meeting with their team to determine whether this is necessary, or if it would be better for them to use the existing ARTT partition and SPARQL instance.
![image](https://user-images.githubusercontent.com/21346519/90659230-0d5d7380-e20a-11ea-9423-e44519d93d52.png)

Alternative Longer-Term:
Depending on the above, it may make more sense to create a completely separate environment for all Navy work. Such an environment _may_ also entail a standalone instance of the CE Accounts system, organization account management, CaSS, publishing/consuming tools, etc., to be 100% separate from CE's public-facing registry and related services/systems.
![image](https://user-images.githubusercontent.com/21346519/90659325-282fe800-e20a-11ea-8512-57133d47c524.png)

**Comment by siuc-nate** [comment]
The ARTT project is currently is currently using the staging SPARQL index (meaning there are a total of two SPARQL indexes currently: one for production and one for staging).

**Comment by jeannekitchens** [comment]
@siuc-nate can this be closed?

**Comment by siuc-nate** [comment]
I think so, yes.
