### ISSUE TITLE
Update description set data to include Pathways

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#357]
I have updated the [description set data spreadsheet](https://docs.google.com/spreadsheets/d/1VNgJ7qu_zydCB3UQMzEuHbYKczr_Q9nkRRxzoUWYLuk/edit#gid=0) from row 334 onwards to include description set items for the [`ceterms:Pathway`](https://credreg.net/ctdl/terms/Pathway) class.  Most of this is the usual ownedBy/offeredBy stuff but there are several rows dealing with connections to the progression model/level and to various flavors of source data.

Just in case it is relevant for the implementation, the use of `ceterms:PathwayComponent` operates the same way as the use of `ceterms:Credential` and `ceterms:Agent` elsewhere in that spreadsheet in the sense that it is basically an alias for a group of related classes (in this case, the [subclasses of ceterms:PathwayComponent](https://credreg.net/ctdl/terms#groups)).  Since everything here has `ceterms:Pathway` (not PathwayComponent) as a starting point, though, there should be no need to expand any of those rows out to the actual set of subclasses.

CE is currently prioritizing pathways work, so the sooner this gets added, the better.  However, I believe we only have a handful of pathways published at the moment, and only to the sandbox.

**Comment by excelsior** [comment]
The config has been updated. There are no Pathways in the registry yet, right? So the actual description set data shouldn't have changed, when recalculated with the new config?

**Comment by siuc-nate** [comment]
Thanks.

And right, no pathways on production yet, unless @cwd-mparsons knows of any.  Just a handful on sandbox right now.

**Comment by siuc-nate** [comment]
The description set appears to be missing in the sandbox.

For example, this pathway:
`https://sandbox.credentialengineregistry.org/graph/ce-cc62e516-f95d-4306-a11a-c0ecc39d835f`
![image](https://user-images.githubusercontent.com/21346519/92013007-d1023b00-ed12-11ea-9c24-7e02a76d279d.png)

**Comment by excelsior** [comment]
@siuc-nate I made RDF data and description sets available on sandbox.

**Comment by siuc-nate** [comment]
Thanks. However, the progression model/progression level data seems to be missing (rows 370-373 in [the spreadsheet](https://docs.google.com/spreadsheets/d/1VNgJ7qu_zydCB3UQMzEuHbYKczr_Q9nkRRxzoUWYLuk/edit#gid=0)).

The only example pathway we have right now that has data for this is here:
[https://sandbox.credentialengineregistry.org/graph/ce-cc62e516-f95d-4306-a11a-c0ecc39d835f](https://sandbox.credentialengineregistry.org/graph/ce-cc62e516-f95d-4306-a11a-c0ecc39d835f)

**Comment by excelsior** [comment]
@siuc-nate The ASN namespace's prefix wasn't defined in the SPARQL queries used for DS precalculation. I fixed that.

**Comment by siuc-nate** [comment]
Thanks.  Tested and working.
