### ISSUE TITLE
Description set data includes duplicate URIs

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#358]
The description set data does not appear to be removing duplicate URIs:
`https://credentialengineregistry.org/description_sets/ce-ee8c01f1-05fe-4d09-99ff-7dd4ec12a571`
![image](https://user-images.githubusercontent.com/21346519/91882831-28d46f80-ec49-11ea-89cc-2aaf80bf6fd2.png)

The intended assertion of the above path would be "This framework has competencies that are aligned to competencies in 1 other framework" but the current value would instead be interpreted as "This framework has competencies that are aligned to competencies in 187 other frameworks".

The fact that there are 187 _competencies_ with alignments to competencies in another framework (which happens to be the same framework in all cases) is already **correctly** asserted by one of the other paths:
![image](https://user-images.githubusercontent.com/21346519/91883082-8799e900-ec49-11ea-8dd3-4ac251ae67f2.png)

Anyway, duplicate URIs should not be stored or counted (for the "total") for any of the description set queries. Apologies for not making that clear to begin with.

**Comment by excelsior** [comment]
I removed the duplicates (they used to comprise ~11.5% of the description set URIs).

**Comment by siuc-nate** [comment]
Great, thanks!
