### ISSUE TITLE
Default community

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#36]

**Comment by leolara** [comment]
@coffeejunk We have in the configuration a list of domains and their default communities. Then we have a general default community. The list of domain-communities pair can be empty, but the general default community should trigger an error if not set.

When calling the API /resources/{@id}  we first check if the domain has a default community, if not we use the general default community.

**Comment by coffeejunk** [comment]
Where exactly is this list of domains/configurations?

**Comment by leolara** [comment]
@coffeejunk 

when I am talking in present tense here, I am meaning the result of the task. Kind of like the invariant of the task.

We currently do not have anything of this implemented. I guess this configuration should be put where the rest of the configuration is.

**Comment by leolara** [comment]
@coffeejunk 

Let me clarify how the community of a "resources API" call is decided:

 + If there is a community is in the URL, that is the community.
 + If the domain name in the request is in the domain->community mapping in the configuration, use that community
+ Otherwise, use the "default community" in the configuration.

Do no use the community in the envelop to select the community. But return an error if the community in the envelope does not match the community selected following the previous rules.

**Comment by coffeejunk** [comment]
@leolara any reason in particular why we should ignore the `:envelope_community` embedded in the envelope?

**Comment by leolara** [comment]
@coffeejunk very quickly in some use cases the users do not need to know that "communities" exists, they will use /resource with the default community and for that case it is better to do not mention envelope

Also, think it is confusing that it is allowed to have a community in the url path and a different one in the envelope, and that the envelope one has priority. What would be the reason for that design decision, a part that the how the framework works.
