### ISSUE TITLE
Added new credential type of CertificateOfCompletion to schemas

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#360]
I made a few updates to the ce-registry schema. 
The currently most important one is to add a new credential type of CertificateOfCompletion. 
https://github.com/CredentialEngine/CredentialRegistry/blob/master/fixtures/schemas/ce_registry/credential.json

Also added the CertificateOfCompletion alias for credential in the fixture configs:
https://github.com/CredentialEngine/CredentialRegistry/blob/master/fixtures/configs/ce_registry.json

This is needed to ensure the counts from the FTS search reflect the total in the registry. 
Please promote these updates to the sandbox where I will verify the search.

**Comment by excelsior** [comment]
@mparsons-ce The updates have been promoted to sandbox.

**Comment by mparsons-ce** [comment]
@excelsior The new CertificateOfCompletion was added here:

![image](https://user-images.githubusercontent.com/58825866/92002286-50890d80-ed05-11ea-870e-1141a8a94087.png)

However it doesn't show in the schemas list
https://sandbox.credentialengineregistry.org/schemas/ce_registry/credential

![image](https://user-images.githubusercontent.com/58825866/92002600-a3fb5b80-ed05-11ea-972e-4c72ece558a5.png)

**Comment by mparsons-ce** [comment]
@excelsior 
I also added the json schema for pathway components.
https://github.com/CredentialEngine/CredentialRegistry/blob/master/fixtures/schemas/ce_registry/pathway_component.json

**Comment by edgarf** [comment]
@excelsior will review this once he is back from vacation on Monday-Tuesday

**Comment by excelsior** [comment]
@mparsons-ce I added the schemas for both CertificateOfCompletion and PathwayComponent on sandbox, please take a look.

**Comment by mparsons-ce** [comment]
@excelsior 
There must be something missing. The following is a CertificateOfCompletion
https://sandbox.credentialengineregistry.org/resources/ce-8d0ead8a-bff9-4231-be30-6db0b262bc44

ceterms:CertificateOfCompletion exists in:
https://sandbox.credentialengineregistry.org/schemas/ce_registry/credential

And the alias is present in
https://github.com/CredentialEngine/CredentialRegistry/blob/master/fixtures/configs/ce_registry.json
![image](https://user-images.githubusercontent.com/58825866/93229062-cb0d5080-f73b-11ea-9296-783f1fca9781.png)

Yet a search for credentials shows no results:
https://sandbox.credentialengineregistry.org/ce-registry/search?resource_type=credential&per_page=50&sort_by=updated_at&sort_order=dsc

**Comment by mparsons-ce** [comment]
This appears to be working in the sandbox, please promote the updates to production
