### ISSUE TITLE
SPARQL/Elasticsearch integration

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#361]
I have implemented the Elasticsearch query stuff into the SPARQL API, and while it does work, I am very concerned about its limitations.  Specifically:
- There is a limit of 1000 matches per query (though this may(?) be something that can be changed via `index.max_result_window`)
- There is no way to control how strict or fuzzy a query is (right now it seems to be a bit too strict)
- There is no way to control the tokenization of terms in a query (presumably this also applies to tokenization of the data(?))
- There is no way to weight or boost results based on certain fields (e.g. no way to make matches in the title have more importance than matches deep in the data)
- There is no way to access the "score" data that elasticsearch uses internally to sort based on relevance
- There is no way to sort based on overall score since each elasticsearch service call is scored/sorted independently (this means that there's no way to make something with a lot of matches in competencies float above something with a single match in a name/description)

Given that the current regex-based search does not have the above limitations and is only slightly slower (~5-6 seconds vs. ~4-5 seconds for a roughly equivalent competency framework query), I currently do not think it is worth the added cost or complexity of keeping the elasticsearch integration.  That money would be better spent on a faster SPARQL instance instead.

Is there anything we can do to address the above problems? If not, we should do a cost comparison of our current setup vs. the next step/tier upwards without elasticsearch (and extra AWS support unless we are still using that).

[Amazon AWS Documentation](https://docs.aws.amazon.com/neptune/latest/userguide/full-text-search-sparql-examples.html)

**Comment by jeannekitchens** [comment]
@science @siuc-nate what confirmations are in place concerning these limitations? ElasticSearch supports all of the issues listed.  This needs a thorough conversation this week to nail down the best solution and not have the entirety of the search work in @siuc-nate hands.

**Comment by siuc-nate** [comment]
ElasticSearch on its own does support most if not all of the above, but the way it's integrated into SPARQL heavily limits which features you can actually access in a SPARQL query.

**Comment by siuc-nate** [comment]
Per @jeannekitchens :
We need to reach out to AWS support to find out if there are solutions to these issues that exist or will soon exist, but are not currently documented/supported.  If AWS can solve these problems for us, then it would make sense to keep the elastic index.

**Comment by siuc-nate** [comment]
I have submitted a request to AWS support.

**Comment by siuc-nate** [comment]
AWS is looking into it as of the 13th.

**Comment by siuc-nate** [comment]
AWS responded with the following (emphasis mine):

---

Hi again,

I have just spoken to our teams who have provided the following updates:

1. Our Neptune team provides a handy solution[1] which can be referenced or used for Replicating data from Neptune Streams to Elastic search.
Though the current replication solution has few limitations around how data is been indexed, still one can write there own replication solution as per this blog post:
https://aws.amazon.com/blogs/database/capture-graph-changes-using-neptune-streams/

Custom analyzer for field indexing and querying:
Neptune data is converted to appropriate ES document as per this doc:
https://docs.aws.amazon.com/neptune/latest/userguide/full-text-search-model.html

In order to use custom analyzer for indexing data and querying data one can pre-define custom analyzers directly in ES and attach these analyzers to respective ES document field through index mapping. Note: currently there is no direct way for passing analyzer with FTS query but one can define "search_analyzer" mapping in field indexing to pickup right analyzer with query.

How strict or fuzzy a query is??
Neptune FTS support different queries:
https://docs.aws.amazon.com/neptune/latest/userguide/full-text-search-parameters.html 

through "query_type" parameter. Depending on query_type one can control whether a query needs to be a fuzzy match or a prefix match or a term match or simple_query_string.
Also, for fuzzy search one can pass "Levenshtein edit distance" in query like ""neptune-fts:config neptune-fts:query 'mikael~2'"" here the Levenshtein edit distance is 2.

A way to access the "score" for a given match -
Score for a query result is **currently not been returned to the users** but still one can use "score" value to sort the results. (Refer sortBy, sortOrder from this doc:
https://docs.aws.amazon.com/neptune/latest/userguide/full-text-search-parameters.html 

"sortBy, sortOrder" parameters can be used to sort result by any field present in document.

[1] https://docs.aws.amazon.com/neptune/latest/userguide/full-text-search-cfn-create.html 

2. The main reason of the result difference of the two queries is because of FTS services return the Subject of the triples, but the query expects Objects to be returned. So advise to revise query like this:

From
```
?id ((ceasn:publisher / ^ credreg:__graph ?) | (credreg:__graph ? / ^ ceasn:publisher)) ?064274c62c434542937c83e468b53d73 .
{
        {
                ?064274c62c434542937c83e468b53d73 (ceterms:name) ?tokens_4784b74b3a7c4ef68f51be56a0161ce5 .
                {
                        {
                                SERVICE neptune-fts:search
                                {
                                        neptune-fts:config neptune-fts:endpoint 'https://vpc-cer-l6tiqwxvh2pcn5zurr36nkyzve.us-east-2.es.amazonaws.com ' .
                                        neptune-fts:config neptune-fts:queryType 'query_string' .
                                        neptune-fts:config neptune-fts:field ceterms:name .
                                        neptune-fts:config neptune-fts:query 'nice OR cyber OR security' .
                                        neptune-fts:config neptune-fts:return ?tokens_4784b74b3a7c4ef68f51be56a0161ce5 .
                                }
                        }
                }
        }
}
```

To
```
?id ((ceasn:publisher / ^ credreg:__graph ?) | (credreg:__graph ? / ^ ceasn:publisher)) ?064274c62c434542937c83e468b53d73 .
{
        {
                {
                        SERVICE neptune-fts:search
                        {
                                neptune-fts:config neptune-fts:endpoint 'https://vpc-cer-l6tiqwxvh2pcn5zurr36nkyzve.us-east-2.es.amazonaws.com ' .
                                neptune-fts:config neptune-fts:queryType 'query_string' .
                                neptune-fts:config neptune-fts:field ceterms:name .
                                neptune-fts:config neptune-fts:query 'nice OR cyber OR security' .
                                neptune-fts:config neptune-fts:return ?064274c62c434542937c83e468b53d73 .
                        }
                }
        }
}
```

3. Regarding relavance score, you can use `minScore` described in [2] to filter out unwanted results (to replace the FILTER in the REGEX query). And then use `sortBy`-`score` to sort all results by the score (also described in [2]). You may even assign an auto-incremented counter to each entry of the sorted results, and use the counter value as the "score" if the score only means the relative order.  

[2] https://docs.aws.amazon.com/neptune/latest/userguide/full-text-search-parameters.html 

I trust you will find these details useful, please let us know if you have any other questions or concerns herein and we will gladly assist you further therein.

---

I thanked them for the thorough response and let them know we'd reply with any issues we run into after updating our query to work in the manner they described. There are some things we can probably tweak here to improve the tokenization during indexing, too, but ultimately we're still dead in the water without access to the score.  I asked if AWS has any plans to update the integration to include the ability to return the score. I will post again with their response.

**Comment by siuc-nate** [comment]
Earlier this week the AWS team responded. The relevant portion of the response is as follows:

---

I have just gotten word from the teams that we are planning to have the feature which allows the Elasticsearch integration to return the score from Elasticsearch.

However, they cannot provide an ETA for this functionality.

I will continue to monitor this feature from my end and I will let you know once there is any positive news in this regard. 

---

I asked if they can give us a rough estimate since an exact ETA isn't available (in other words, are we anticipating waiting weeks or months)?

**Comment by siuc-nate** [comment]
We received a response, the relevant portion of which is:

---

I have taken a look around the details on the feature request, and it looks to me on the long term road map.

While there is no defined ETA on the feature request, I have asked them to possibly provide one in a hope to gain traction on this. If they do provide one or if there is any positive progress on this feature I will reach out to you.

---

So it sounds like we won't be able to really use the elasticsearch integration for a while.  Unless we have further questions for AWS, I recommend we turn off the elasticsearch service so we're not paying for it until this feature is enabled. @jeannekitchens @cwd-mparsons @science what do you think?

**Comment by siuc-nate** [comment]
Per our 11/5/2020 meeting:
We will turn off the elasticsearch service until Neptune supports, minimally, returning the score from records.
