### ISSUE TITLE
Token normalization issue: Plain Strings

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#365]
In the process of comparing [Gremlin results](https://credreg.net/quickstart/queryhelper) to [SPARQL results](https://credreg.net/quickstart/queryhelper?usesparql=true&showdescriptionsets=true), I noticed that the query for "Credentials that reference occupations with a notation code beginning: 13-20" fails in the SPARQL version.  If you remove out the credential type check, that CTDL query boils down to:
```
{
	"ceterms:occupationType": {
		"ceterms:codedNotation": "13-20"
	}
}
```
This ultimately gets turned into a bunch of `REGEX`s that look at the `credreg:__tokenFullNormalized` for `ceterms:codedNotation__tokenData`.  I dug into why this was failing and discovered that those tokens are represented as a stringified JSON array:
![image](https://user-images.githubusercontent.com/21346519/94867042-0b402480-0406-11eb-83b0-a1f477f64987.png)

Which means that searching for "13-20" fails but breaking that out into an array works since the individual tokens match:
```
{
	"ceterms:occupationType": {
		"ceterms:codedNotation": ["13", "20"]
	}
}
```

I don't immediately remember the specific normalization rules for plain string properties like `ceterms:codedNotation`, but the value of `credreg:__tokenFullNormalized` shouldn't be an array in this case (letalone a stringified JSON array).  Since the [original data for one of the records that should match](https://credentialengineregistry.org/resources/ce-c57948c2-6636-4ed3-9b51-bc5a9ec56d88) has the relevant value as "13-2099.00":
![image](https://user-images.githubusercontent.com/21346519/94867216-696d0780-0406-11eb-96d9-319278586d0b.png)

If I had to guess, there may be a missing string.join (or equivalent) somewhere in the tokenization code - can you verify whether or not I'm on the right track?

**Comment by excelsior** [comment]
Good guess: `split` was called a second time instead of `join`. I fixed that and reindexed the data. The full normalized version of `13-2099.00` is `13 2099 00` now.

**Comment by siuc-nate** [comment]
This seems to be working now. Thanks.
