### ISSUE TITLE
publisher_id is null on many envelopes and seems to result in "Resource can only be updated by the original user"

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#368]
I was notified that the following error occurred when publishing an organization:
`Resource can only be updated by the original user. There is a public key or key locations mismatch`

This organization had been previously published using the old process using the CE signed keys. 
There should have been no change in owner. I checked the envelope and found that **publisher_id** was null.
Just in case, I did a transfer of ownership and was then able to do the publish. 

Then the same error started to occur when attempting to publish credentials for the latter organization. Of the roughly 80 credentials, two were successful and the rest failed with the latter error. 
First why is this property null?
Since there is only one publisher (CE), can all envelopes with publisher_id nulll be set to **e8aa2734-5f6d-473a-9cf7-bc184439a1ac**

**Comment by excelsior** [comment]
@mparsons-ce Only the envelopes published on behalf of an organization have `publisher_id` populated. I believe it should stay this way, so we can tell how an envelope was published (the old way or the new way).

The real problem here is that existing envelopes don't get properly updated when republished, i.e. the publisher doesn't get assigned to them (unless a transfer of ownership takes place). I'm still investigating why this is happenning. In the meantime, as a quick fix, I've disabled validation of the original user.

This may be related to the issue: Do you use the `update_if_exists` flag when republishing envelopes?

**Comment by mparsons-ce** [comment]
We have **not** been populating publisher_id in any of our code. The latter is set by the registry endpoint. 

Yes we do use update_if_exists=true when publishing the 'old way'. 
https://sandbox.credentialengineregistry.org/ce-registry/envelopes?update_if_exists=true
But not with the 'new' way:
https://sandbox.credentialengineregistry.org/resources/organizations/{0}/documents?skip_validation=true

**Comment by mparsons-ce** [comment]
@excelsior 
I had started adding documentOwnedBy and documentPublishedBy when publishing the _old_ way. 
Could this have been a factor?

**Comment by excelsior** [comment]
@mparsons-ce 

I couldn't reproduce the reported issue. When I republish an envelope published the old way (i.e. with no owner and with an empty `publisher_id`), I get the `Resource CTID must be unique` response, not the one you experience.

Could you please point out a specific envelope on sandbox or staging for me to try?

> Could this have been a factor?

Nope, that's highly unlikely. The validator only looks at the public key, not the owner or publisher.

**Comment by mparsons-ce** [comment]
The following have publisher_id = null

republished 20-10-16
https://credentialengineregistry.org/envelopes/ce-edc5179d-fe90-4b4e-b818-be74587399a5
https://credentialengineregistry.org/envelopes/ce-5dab2264-d4d3-4bc9-926e-58fffe775185

https://credentialengineregistry.org/envelopes/ce-cab21b2c-c003-4391-bbc3-dcc0fe80b578

**Comment by mparsons-ce** [comment]
Following is a payload to test using Postman. 
https://staging.credentialengine.org/assistant/credential/publish
You will need an apiKey which I can send separately. 

{
"DefaultLanguage": "en-US",
  "PublishForOrganizationIdentifier": "ce-91d58cc1-be37-42f5-bb5c-88913b13b3fb",
  "RegistryEnvelopeId": "08ccb106-17b1-4ae6-a6ed-a340bdf8ccb4",
  "Credential": {
    "Name": "ELL: Modification for ELLs",
    "Description": "ELL: Modify content to meet the needs of English Language Learners with a variety of needs and abilities.",
    "OwnedBy": [
      {
        "Type": "CredentialOrganization",
        "CTID": "ce-91d58cc1-be37-42f5-bb5c-88913b13b3fb"
      }
    ],
    "CredentialType": "ceterms:OpenBadge",
    "CredentialStatusType": "Active",
    "Ctid": "ce-310708ea-6581-4086-a9d8-cec1d944054b",
    "SubjectWebpage": "https://www.participate.com/badges/Modifications-for-ELLs/a99cf4bb-bf4c-46f8-b98b-786e3f88c06d",
    "InLanguage": [
      "en"
    ],
    "AvailableOnlineAt": "https://www.participate.com/products/ell-modifications-for-ells/299fa27e-bebb-4288-9ca4-cfdee16543af",
    "CopyrightHolder": {
      "Type": "CredentialOrganization",
      "CTID": "ce-91d58cc1-be37-42f5-bb5c-88913b13b3fb"
    },
    "ApprovedBy": [
      {
        "Type": "QACredentialOrganization",
        "Name": "International Society for Technology in Education (ISTE)",
        "SubjectWebpage": "https://www.iste.org"
      }
    ],
    "OfferedBy": [
      {
        "Type": "CredentialOrganization",
        "CTID": "ce-91d58cc1-be37-42f5-bb5c-88913b13b3fb"
      }
    ],
    "BaseSalary": {},
    "EstimatedDuration": [
      {
        "MinimumDuration": {},
        "MaximumDuration": {},
        "ExactDuration": {
          "Hours": 10
        }
      }
    ],
    "Image": "https://s3.amazonaws.com/com.appolearning.files/production/uploads/badge/a99cf4bb-bf4c-46f8-b98b-786e3f88c06d/ESL-K12-Y4-M2.png",
    "Keyword": [
      "global learning",
      "language learners",
      "modify"
    ],
    "OccupationType": [
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-1081.00",
        "Name": "Education Teachers, Postsecondary",
        "Description": "Teach courses pertaining to education, such as counseling, curriculum, guidance, instruction, teacher education, and teaching English as a second language. Includes both teachers primarily engaged in teaching and those who do a combination of teaching and research.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-1081.00"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-2012.00",
        "Name": "Kindergarten Teachers, Except Special Education",
        "Description": "Teach elemental natural and social science, personal hygiene, music, art, and literature to kindergarten students. Promote physical, mental, and social development. May be required to hold State certification.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-2012.00"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-2021.00",
        "Name": "Elementary School Teachers, Except Special Education",
        "Description": "Teach students basic academic, social, and other formative skills in public or private schools at the elementary level.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-2021.00"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-2022.00",
        "Name": "Middle School Teachers, Except Special and Career/Technical Education",
        "Description": "Teach students in one or more subjects in public or private schools at the middle, intermediate, or junior high level, which falls between elementary and senior high school as defined by applicable laws and regulations.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-2022.00"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-2031.00",
        "Name": "Secondary School Teachers, Except Special and Career/Technical Education",
        "Description": "Teach students in one or more subjects, such as English, mathematics, or social studies at the secondary level in public or private schools. May be designated according to subject matter specialty.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-2031.00"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-3099.00",
        "Name": "Teachers and Instructors, All Other",
        "Description": "All teachers and instructors not listed separately.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-3099.00"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-3099.02",
        "Name": "Tutors",
        "Description": "Provide non-classroom, academic instruction to students on an individual or small-group basis for proactive or remedial purposes.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-3099.02"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-4021.00",
        "Name": "Librarians",
        "Description": "Administer libraries and perform related library services. Work in a variety of settings, including public libraries, educational institutions, museums, corporations, government agencies, law firms, non-profit organizations, and healthcare providers. Tasks may include selecting, acquiring, cataloguing, classifying, circulating, and maintaining library materials; and furnishing reference, bibliographical, and readers' advisory services. May perform in-depth, strategic research, and synthesize, analyze, edit, and filter information. May set up or work with databases and information systems to catalogue and access information.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-4021.00"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-9031.00",
        "Name": "Instructional Coordinators",
        "Description": "Develop instructional material, coordinate educational content, and incorporate current technology in specialized fields that provide guidelines to educators and instructors for developing curricula and conducting courses. Includes educational consultants and specialists, and instructional material directors.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-9031.00"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-9031.01",
        "Name": "Instructional Designers and Technologists",
        "Description": "Develop instructional materials and products and assist in the technology-based redesign of courses. Assist faculty in learning about, becoming proficient in, and applying instructional technology.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-9031.01"
      },
      {
        "Framework": "https://www.bls.gov/soc/",
        "FrameworkName": "Standard Occupational Classification",
        "CodedNotation": "25-9099.00",
        "Name": "Education, Training, and Library Workers, All Other",
        "Description": "All education, training, and library workers not listed separately.",
        "TargetNode": "https://www.onetonline.org/link/summary/25-9099.00"
      }
    ],
    "IndustryType": [
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "61",
        "Name": "Educational Services",
        "Description": "Educational Services",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "611",
        "Name": "Educational Services",
        "Description": "Educational Services",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "6111",
        "Name": "Elementary and Secondary Schools",
        "Description": "Elementary and Secondary Schools",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=6111&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "61111",
        "Name": "Elementary and Secondary Schools ",
        "Description": "Elementary and Secondary Schools ",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61111&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "611110",
        "Name": "Elementary and Secondary Schools ",
        "Description": "Elementary and Secondary Schools ",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611110&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "61143",
        "Name": "Professional and Management Development Training",
        "Description": "Professional and Management Development Training",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61143&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "611430",
        "Name": "Professional and Management Development Training ",
        "Description": "Professional and Management Development Training ",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611430&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "61169",
        "Name": "All Other Schools and Instruction",
        "Description": "All Other Schools and Instruction",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61169&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "611699",
        "Name": "All Other Miscellaneous Schools and Instruction ",
        "Description": "All Other Miscellaneous Schools and Instruction ",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611699&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "6117",
        "Name": "Educational Support Services",
        "Description": "Educational Support Services",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=6117&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "61171",
        "Name": "Educational Support Services",
        "Description": "Educational Support Services",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61171&search=2017"
      },
      {
        "Framework": "https://www.census.gov/eos/www/naics/",
        "FrameworkName": "NAICS",
        "CodedNotation": "611710",
        "Name": "Educational Support Services",
        "Description": "Educational Support Services",
        "TargetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611710&search=2017"
      }
    ],
    "Naics": [
      "61",
      "611",
      "6111",
      "61111",
      "611110",
      "61143",
      "611430",
      "61169",
      "611699",
      "6117",
      "61171",
      "611710"
    ],
    "RenewalFrequency": {},
    "Requires": [
      {
        "Name": "Conditions for ELL: Modification for ELLs",
        "Description": "Requirements for this artifact include: meeting the listed submission requirements",
        "SubjectWebpage": "https://www.participate.com/badges/Modifications-for-ELLs/a99cf4bb-bf4c-46f8-b98b-786e3f88c06d",
        "SubmissionOf": [
          "http://example.com"
        ],
        "SubmissionOfDescription": "In order to earn the badge, you will submit the following pieces of evidence for peer review at the end of this course: Teacher Learning: Portfolio Collection, Classroom Practice: Lesson Plan, Student Learning: Student Artifact.",
        "AssertedBy": {
          "Address": [],
          "AvailabilityListing": [],
          "CTID": "ce-91d58cc1-be37-42f5-bb5c-88913b13b3fb",
          "Email": [],
          "Type": "CredentialOrganization"
        },
        "CreditValue": {}
      }
    ]
  }
}

**Comment by siuc-nate** [comment]
@mparsons-ce and @excelsior will test this.

**Comment by jeannekitchens** [comment]
@mparsons-ce did you and @excelsior test this per the meeting last week?

**Comment by mparsons-ce** [comment]
{
  "@context": "https://credreg.net/ctdl/schema/context/json",
  "@id": "https://staging.credentialengineregistry.org/graph/ce-310708ea-6581-4086-a9d8-cec1d944054b",
  "@graph": [
    {
      "@id": "https://staging.credentialengineregistry.org/resources/ce-310708ea-6581-4086-a9d8-cec1d944054b",
      "@type": "ceterms:OpenBadge",
      "ceterms:name": {
        "en-US": "ELL: Modification for ELLs"
      },
      "ceterms:description": {
        "en-US": "ELL: Modify content to meet the needs of English Language Learners with a variety of needs and abilities."
      },
      "ceterms:ctid": "ce-310708ea-6581-4086-a9d8-cec1d944054b",
      "ceterms:image": "https://s3.amazonaws.com/com.appolearning.files/production/uploads/badge/a99cf4bb-bf4c-46f8-b98b-786e3f88c06d/ESL-K12-Y4-M2.png",
      "ceterms:subjectWebpage": "https://www.participate.com/badges/Modifications-for-ELLs/a99cf4bb-bf4c-46f8-b98b-786e3f88c06d",
      "ceterms:availableOnlineAt": [
        "https://www.participate.com/products/ell-modifications-for-ells/299fa27e-bebb-4288-9ca4-cfdee16543af"
      ],
      "ceterms:inLanguage": [
        "en"
      ],
      "ceterms:occupationType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-1081.00",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Teach courses pertaining to education, such as counseling, curriculum, guidance, instruction, teacher education, and teaching English as a second language. Includes both teachers primarily engaged in teaching and those who do a combination of teaching and research."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-1081.00",
          "ceterms:targetNodeName": {
            "en-US": "Education Teachers, Postsecondary"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-2012.00",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Teach elemental natural and social science, personal hygiene, music, art, and literature to kindergarten students. Promote physical, mental, and social development. May be required to hold State certification."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-2012.00",
          "ceterms:targetNodeName": {
            "en-US": "Kindergarten Teachers, Except Special Education"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-2021.00",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Teach students basic academic, social, and other formative skills in public or private schools at the elementary level."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-2021.00",
          "ceterms:targetNodeName": {
            "en-US": "Elementary School Teachers, Except Special Education"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-2022.00",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Teach students in one or more subjects in public or private schools at the middle, intermediate, or junior high level, which falls between elementary and senior high school as defined by applicable laws and regulations."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-2022.00",
          "ceterms:targetNodeName": {
            "en-US": "Middle School Teachers, Except Special and Career/Technical Education"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-2031.00",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Teach students in one or more subjects, such as English, mathematics, or social studies at the secondary level in public or private schools. May be designated according to subject matter specialty."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-2031.00",
          "ceterms:targetNodeName": {
            "en-US": "Secondary School Teachers, Except Special and Career/Technical Education"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-3099.00",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "All teachers and instructors not listed separately."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-3099.00",
          "ceterms:targetNodeName": {
            "en-US": "Teachers and Instructors, All Other"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-3099.02",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Provide non-classroom, academic instruction to students on an individual or small-group basis for proactive or remedial purposes."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-3099.02",
          "ceterms:targetNodeName": {
            "en-US": "Tutors"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-4021.00",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Administer libraries and perform related library services. Work in a variety of settings, including public libraries, educational institutions, museums, corporations, government agencies, law firms, non-profit organizations, and healthcare providers. Tasks may include selecting, acquiring, cataloguing, classifying, circulating, and maintaining library materials; and furnishing reference, bibliographical, and readers' advisory services. May perform in-depth, strategic research, and synthesize, analyze, edit, and filter information. May set up or work with databases and information systems to catalogue and access information."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-4021.00",
          "ceterms:targetNodeName": {
            "en-US": "Librarians"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-9031.00",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Develop instructional material, coordinate educational content, and incorporate current technology in specialized fields that provide guidelines to educators and instructors for developing curricula and conducting courses. Includes educational consultants and specialists, and instructional material directors."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-9031.00",
          "ceterms:targetNodeName": {
            "en-US": "Instructional Coordinators"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-9031.01",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Develop instructional materials and products and assist in the technology-based redesign of courses. Assist faculty in learning about, becoming proficient in, and applying instructional technology."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-9031.01",
          "ceterms:targetNodeName": {
            "en-US": "Instructional Designers and Technologists"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "25-9099.00",
          "ceterms:framework": "https://www.bls.gov/soc/",
          "ceterms:frameworkName": {
            "en-US": "Standard Occupational Classification"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "All education, training, and library workers not listed separately."
          },
          "ceterms:targetNode": "https://www.onetonline.org/link/summary/25-9099.00",
          "ceterms:targetNodeName": {
            "en-US": "Education, Training, and Library Workers, All Other"
          }
        }
      ],
      "ceterms:industryType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "61",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Educational Services"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Educational Services"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "611",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Educational Services"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Educational Services"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "6111",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Elementary and Secondary Schools"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=6111&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Elementary and Secondary Schools"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "61111",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Elementary and Secondary Schools"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61111&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Elementary and Secondary Schools "
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "611110",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Elementary and Secondary Schools"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611110&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Elementary and Secondary Schools "
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "61143",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Professional and Management Development Training"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61143&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Professional and Management Development Training"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "611430",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Professional and Management Development Training"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611430&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Professional and Management Development Training "
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "61169",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "All Other Schools and Instruction"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61169&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "All Other Schools and Instruction"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "611699",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "All Other Miscellaneous Schools and Instruction"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611699&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "All Other Miscellaneous Schools and Instruction "
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "6117",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Educational Support Services"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=6117&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Educational Support Services"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "61171",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Educational Support Services"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=61171&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Educational Support Services"
          }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:codedNotation": "611710",
          "ceterms:framework": "https://www.census.gov/eos/www/naics/",
          "ceterms:frameworkName": {
            "en-US": "NAICS"
          },
          "ceterms:targetNodeDescription": {
            "en-US": "Educational Support Services"
          },
          "ceterms:targetNode": "https://www.census.gov/cgi-bin/sssd/naics/naicsrch?code=611710&search=2017",
          "ceterms:targetNodeName": {
            "en-US": "Educational Support Services"
          }
        }
      ],
      "ceterms:naics": [
        "61",
        "611",
        "6111",
        "61111",
        "611110",
        "61143",
        "611430",
        "61169",
        "611699",
        "6117",
        "61171",
        "611710"
      ],
      "ceterms:keyword": {
        "en-US": [
          "global learning",
          "language learners",
          "modify"
        ]
      },
      "ceterms:copyrightHolder": [
        "https://staging.credentialengineregistry.org/resources/ce-91d58cc1-be37-42f5-bb5c-88913b13b3fb"
      ],
      "ceterms:estimatedDuration": [
        {
          "@type": "ceterms:DurationProfile",
          "ceterms:exactDuration": "PT10H"
        }
      ],
      "ceterms:requires": [
        {
          "@type": "ceterms:ConditionProfile",
          "ceterms:name": {
            "en-US": "Conditions for ELL: Modification for ELLs"
          },
          "ceterms:description": {
            "en-US": "Requirements for this artifact include: meeting the listed submission requirements"
          },
          "ceterms:subjectWebpage": "https://www.participate.com/badges/Modifications-for-ELLs/a99cf4bb-bf4c-46f8-b98b-786e3f88c06d",
          "ceterms:submissionOf": [
            "http://example.com"
          ],
          "ceterms:submissionOfDescription": {
            "en-US": "In order to earn the badge, you will submit the following pieces of evidence for peer review at the end of this course: Teacher Learning: Portfolio Collection, Classroom Practice: Lesson Plan, Student Learning: Student Artifact."
          },
          "ceterms:assertedBy": [
            "https://staging.credentialengineregistry.org/resources/ce-91d58cc1-be37-42f5-bb5c-88913b13b3fb"
          ]
        }
      ],
      "ceterms:credentialStatusType": {
        "@type": "ceterms:CredentialAlignmentObject",
        "ceterms:framework": "http://credreg.net/ctdl/terms/CredentialStatus",
        "ceterms:frameworkName": {
          "en-US": "CredentialStatus"
        },
        "ceterms:targetNode": "credentialStat:Active",
        "ceterms:targetNodeName": {
          "en-US": "Active"
        }
      },
      "ceterms:ownedBy": [
        "https://staging.credentialengineregistry.org/resources/ce-91d58cc1-be37-42f5-bb5c-88913b13b3fb"
      ],
      "ceterms:approvedBy": [
        "_:5882f577-e6b8-4532-b9ff-c13036e9b8af"
      ],
      "ceterms:offeredBy": [
        "https://staging.credentialengineregistry.org/resources/ce-91d58cc1-be37-42f5-bb5c-88913b13b3fb"
      ]
    },
    {
      "@id": "_:5882f577-e6b8-4532-b9ff-c13036e9b8af",
      "@type": "ceterms:QACredentialOrganization",
      "ceterms:name": {
        "en-US": "International Society for Technology in Education (ISTE)"
      },
      "ceterms:subjectWebpage": "https://www.iste.org"
    }
  ]
}

**Comment by mparsons-ce** [comment]
This issue is being addressed (we believe) by converting the CTID for all registered organizations to lower case, and converting older envelopes to registry managed keys. 
Keeping open until latter is complete.

**Comment by mparsons-ce** [comment]
We have started the conversion of all envelopes published the old way. As we believe the latter will address this issue, closing.
