### ISSUE TITLE
Missing data from SPARQL index

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#369]
This competency framework is missing from production SPARQL:
https://credentialengineregistry.org/resources/ce-ece7cefa-3c0f-42fe-9e51-f24e5489aa0c

```
PREFIX credreg: <https://credreg.net/> PREFIX asn: <http://purl.org/ASN/schema/core/> PREFIX ceasn: <https://purl.org/ctdlasn/terms/> PREFIX ceterms: <https://purl.org/ctdl/terms/> SELECT * WHERE { <https://credentialengineregistry.org/resources/ce-ece7cefa-3c0f-42fe-9e51-f24e5489aa0c> ?p ?o }
```

![image](https://user-images.githubusercontent.com/21346519/96776571-d133c400-13ae-11eb-8ac1-2e04f5586e60.png)

Additionally, there are several other recently-published competency frameworks that are also missing from production:
https://credentialengineregistry.org/resources/ce-8d359552-f6d6-4c43-a6bc-bbd6dee213cb
https://credentialengineregistry.org/resources/ce-b63598f5-da4c-4752-b0ce-2e9bedc95c78
https://credentialengineregistry.org/resources/ce-c991ea0e-3606-4a88-acaa-0a4d21f5173d
https://credentialengineregistry.org/resources/ce-63127c22-8bd2-4816-8df1-b26633fb6ff7
https://credentialengineregistry.org/resources/ce-fab53ae6-895c-449e-a761-cef6bf7de58b
https://credentialengineregistry.org/resources/ce-c2239a6a-396e-4a95-b834-24f86eb031e6

Did the SPARQL indexer fall over again?

When something is missing from the SPARQL index, we don't have a good way to know that it's missing or to search for what's missing aside from comparing our own local copy of the data to what shows up in the search.  This means we don't usually find out that something went wrong until it's too late (or someone outside CE notices and reports it to us).  We must keep a better eye on the SPARQL indexing.

Is there any logging of errors happening so that we know when something gets published but doesn't get indexed, so we can immediately check on it?

**Comment by excelsior** [comment]
@siuc-nate Uploading data into Neptune started failing sometimes recently (their API responds with `400 Bad Request` to our attempt to import a file, but a subsequent very same request may succeed). Also, there is a bug in the indexer's error handling mechanism, that's why this issue went under the radar.

I've rebuild the index from scratch, all of the missing resources should be available in Neptune.

**Comment by siuc-nate** [comment]
Does this seem like an issue on AWS's side that we should contact their support about?  If so, do we have any information to give them to describe/reproduce the error (since it sounds like it's inconsistent)?

**Comment by excelsior** [comment]
It's hard to reproduce, so I doubt their support can do much about it. I'm changing the code to retry a failed request a few times. If it still fails after multiple attempts, we'll have to contact AWS for sure.

**Comment by jeannekitchens** [comment]
@siuc-nate was AWS contacted about this?  Please do so ahead of this Thursday.

**Comment by siuc-nate** [comment]
Have we had more failures? Do we have anything to give them? "Sometimes it doesn't work" isn't a very useful bug report on our part.

**Comment by siuc-nate** [comment]
@excelsior @edgarf @science  Last week we discussed having the LT team add some more logging and escalation to catch cases where things fail to get into the SPARQL index.  Has that been implemented?  It appears that we have another framework that has failed to get into the index (I will update this post to confirm when I have more info on that).

**Comment by siuc-nate** [comment]
The missing framework is:
https://credentialengineregistry.org/envelopes/74dfcf5b-3744-4cdd-958d-ede2b4202a43
The problem is the URL for ceasn:derivedFrom:
https://www.agacgfm.org/cgfm-certification/candidates/cgfm-process/examination-requirements/examination-one-%E2%80%94-governmental-environment.aspx
It contains a long dash character, which SPARQL does not accept.

Do we need to report this to AWS or should we explore some kind of solution for working around it on our side? I'm concerned that if we encode URLs that will create issues when querying later since the published data won't match the indexed data which may or may not match the queried data.

**Comment by excelsior** [comment]
@siuc-nate Appartently, URIs cannot contain non-ASCII characters: https://tools.ietf.org/html/rfc3986#page-49

I changed the indexer to escape those. However, since we have a custom tokenizer for URI parts, nothing stops us from leaving non-ASCII characters unescaped in the tokens. How does that sound to you?

**Comment by siuc-nate** [comment]
Ideally whatever solution we settle on should have the same URI strings in both the registry document and the index so that the two records match up.  If URIs should always escape non-ASCII characters, then we should probably do something with that in the registry records. It should probably be baked into our code that publishes to the registry so that everything we send over is normalized in that fashion.  I can also update the code that translates the queries to escape non-ASCII characters in URI fields as well.
I am open to alternatives, though, as I am not entirely sure what all of the implications would be for modifying data in this manner.  I assume we would need to do it in order to maintain the integrity of the signatures used in the envelopes as well.

@cwd-mparsons @stuartasutton what do you think?

**Comment by siuc-nate** [comment]
We will update our workflow to escape URLs before sending them to the Registry as part of both publishing and search queries.

**Comment by siuc-nate** [comment]
Actually, upon checking this morning, that record is in the SPARQL index - with the long-dash URL and everything:
![image](https://user-images.githubusercontent.com/21346519/99268972-6e85ea80-27eb-11eb-8899-5560f7155f43.png)

Is it possible that something else caused the problem?  Did AWS update SPARQL to allow non-ASCII characters in URLs?

```
PREFIX credreg: <https://credreg.net/> PREFIX asn: <http://purl.org/ASN/schema/core/> PREFIX ceasn: <https://purl.org/ctdlasn/terms/> PREFIX ceterms: <https://purl.org/ctdl/terms/> SELECT * WHERE { ?id ceterms:ctid 'ce-984f03b9-b9a5-4b68-817f-26ede832e215' . ?id ?p ?o }
```

**Comment by siuc-nate** [comment]
This is working now.
