### ISSUE TITLE
Determine how to manage ownership/creation of third-party organizations

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#37]
@stuartasutton @science @jkitchensSIUC @mparsons1953 @leolara 
It's not 100% clear whether this belongs in the Registry repository or the Vocabulary repository; this sort of overlaps both areas.  It came up on our call today, and I said I would make a post about it - so here we go. This actually ended up being much lengthier than I expected, so skip to the summary at the bottom if you're in a hurry.

The scenario in question is along the following lines:

Part One: 1 + 0 = 2
---
1. Organization A is creating the data for a credential they own or control.
2. The organization wishes to express some relationship between their credential and a third-party organization that they do not own or control (or have any other rights to)
3. The other organization (call it Organization B) does not have any metadata in the registry, and may not be aware that the registry exists
4. The user is faced with a choice:
   **A)** Arbitrarily create a ceterms:CredentialOrganization (or ceterms:QACredentialOrganization) in the registry to represent Organization B
   **B)** Do not include the relationship between their credential and Organization B, because there is no entity in the registry to point to

Option A results in the following:
- Organization A has made arbitrary, unconfirmed assertions about Organization B
- Organization A holds the "keys" to controlling the metadata documents in the registry for Organization B

Option B results in the following:
- No information about the connection between the credential and Organization B is included in the registry

This on its own is a problem.  But it gets worse if Organization A chooses Option A...

Part Two: Reverse Doppelganger
---
1. Some time passes.
2. Organization B discovers the registry and decides to join in and publish metadata
3. Organization B publishes metadata about itself in the registry
4. Organization B may or may not become aware of the existing metadata about them that was previously published by Organization A

Result: There are now two non-identical instances of metadata about Organization B in the registry

This, too, is on its own a problem.  Furthermore there is the potential that more than one instance of metadata about Organization B could be published to the registry by more than one additional parties, both **before _and_ after** Organization B publishes data about itself.

I'm sure you can imagine what might happen if Organization B were to discover the unauthorized metadata about it in the registry, and then discover that it has no power to remove or change it. In the best case scenario they might report it or ignore it; in the worst case they might attempt to take some sort of legal action against it.

But we've only discussed publishing.  It gets even worse if someone tries to consume the data...

Part Three: Metadata bumper cars
---
1. Organization C comes along and decides to consume metadata from the registry. This can happen a few ways:
   **A)** Organization C downloads data about organizations directly, and discovers multiple different versions of data about Organization B
   **B)** Organization C downloads data about credentials, and may (or may not!) notice that different credentials point to different "versions" of Organization B
2. Organization C has **no way** of knowing which, if _any_, of the versions of metadata about Organization B are authentic
3. Organization C may decide to:
   **A)** Attempt to reach out to one or more publishers to try to determine which version of the data is correct, and develop a means to force that data to display instead of whatever data comes in with a Credential (such a means would have to be regularly checked and updated to ensure that everything that should point to the correct org does indeed do so - this creates a code and maintenance headache)
   **B)** Decide that option A is too much work, and use or display (presumably to end users) the data as-is, regardless of inconsistencies
   **C)** Decide that option B makes their website look bad in the eyes of their customers (or funders, or administrators, etc) and drop or ignore any data that claims to point to Organization B (which is essentially the same process as option A in terms of the code and maintenance required)
   **D)** Decide that the registry is not reliable and stop using it, and mention the inconsistency to their peers

None of the things described above are things we want to deal with, so I think it will be crucial that we figure out how to avoid this problem.  

Ideas
---
One way, I suppose, is to begin at the account level - when someone signs up to be a part of the registry, we can (hopefully) validate that their organization is who and what it claims to be - and at **that** time, issue some identifier to them (or have them create one), and associate that identifier with their publishing keys.  

From then on, any published metadata we receive from them that describes an organization **must** use that identifier as its UUID (for example, at the end of the URL in the `@id` field).  This should prevent any organization from publishing data about any other organization (note that it does not disallow them from pointing to other organizations, provided those exist in the registry).

This could _potentially_ extend to some service that allows third parties to check UUIDs they find in the metadata against the registry's accounts to make sure that data about an organization came from that organization.  In essence this would mirror the credential verification services offered by parties that actually issue credentials (which is basically what the registry does when it authorizes someone to publish).

It does not, however, solve the problem faced by Organization A in Option B in Part One.  If an organization does not exist in the registry, but needs to be referenced, then some, looser means of pointing at that organization needs to exist.  This could possibly be accomplished via [CredentialAlignmentObject](http://credreg.net/ctdl/terms/CredentialAlignmentObject) (or some subclass thereof - perhaps an "OrganizationAlignmentObject") that allows:
- Naming and describing an organization 
- Providing a target URL to that organization's website (or one of their websites in the case of organizations that have more than one)
- Providing a reference to a framework (like FEIN or IPEDS) and "coded notation" for that organization's unique identifier within that framework
This would likely be the next best thing to a true UUID identifier used in/by the registry.

Summary
---
The problem is three-fold: 
1. **Problem:** How do we allow organizations to reference organizations that do not exist in the registry?
   **Suggestion:** Use an AlignmentObject (see Ideas section above)
2. **Problem:** How do we prevent organizations from publishing metadata data that describes other organizations?
   **Suggestion:** Tie an org UUID to the org's publishing credentials and only allow that org to publish organization data about itself
3. **Problem:** How do we provide proof or assurance that an organization's metadata came from that organization when someone consumes the data?
   **Suggestion:** This one _should_ be solved by default by solving the first two problems

**Comment by leolara** [comment]
This seems like a very big sub-project. Designing it is not trivial. I think someone should drive this

**Comment by siuc-nate** [comment]
Here are some diagrams based on conversations I've had with Mike.  In essence, he suggested an index or directory of sorts that would host records that could be pointed to from things in the registry. The records in this index would initially return non-official records until such time as official records existed, at which point they would instead return those ( @cwd-mparsons correct me if I'm wrong ).

What I show in the diagrams below is a concept based on that conversation.  It's fundamentally the same idea, except that it uses the envelopes for records instead of using an external index.  This relies on the idea that the envelope can be updated and changed, unlike the payload, which is essentially set in stone.  If this is not true, then we'll need to come up with something else.

@stuartasutton I would also like to get your feedback on this, as it is definitely a point of friction between the world of RDF and the world of implementation. The implementation below is analogous to PURL URLs in the sense that the envelope for the non-canonical record "redirects" to the non-canonical record until such time as the canonical record exists, at which point it "redirects" to that.

This is by no means a final proposal and I'm sure there are things I have missed, so I am open to feedback.

![image](https://cloud.githubusercontent.com/assets/21346519/26013580/bbaed766-371e-11e7-9a67-6c3489120757.png)

![image](https://cloud.githubusercontent.com/assets/21346519/26013595/cd5b2582-371e-11e7-93ff-36a17a9c9eee.png)

![image](https://cloud.githubusercontent.com/assets/21346519/26013617/daecbe40-371e-11e7-8521-3737e9348e86.png)

![image](https://cloud.githubusercontent.com/assets/21346519/26013641/f5c672ce-371e-11e7-83a9-29c442094f02.png)

**Comment by siuc-nate** [comment]
Regarding the above approach, see comment here: https://github.com/CredentialEngine/vocabularies/issues/394#issuecomment-301833128

**Comment by siuc-nate** [comment]
Issue #107 is intended to solve this.
