### ISSUE TITLE
Updates for fixtures\configs\ce_registry.json and fixtures\schemas\ce_registry

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#370]
I made a few updates to the ce-registry schema to add HoldersProfile, EarningsProfile and EmploymentOutcomeProfile'

I also added several entries to fixtures\schemas\ce_registry

- qdata_data_profile.json
- qdata_dataset_profile.json
- employment_outcome_profile.json
- earning_profile.json
- holders_profile.json

**Comment by excelsior** [comment]
@mparsons-ce It looks like there's a typo in the updated config:

`"ceterms:EmplomentOutcomeProfile": "emploment_outcome_profile"`

should be

`"ceterms:EmploymentOutcomeProfile": "employment_outcome_profile"`

**Comment by mparsons-ce** [comment]
Thanks Alex, I made the correction.

**Comment by excelsior** [comment]
@mparsons-ce The changes are on sandbox. It doesn't look like there are any resources of the new types, though. So I couldn't check whether those config changes are enough for search to work.

**Comment by jeannekitchens** [comment]
@mparsons-ce why is there dependence on Tapestry team to make updates whenever there's significant schema updates?  Where's the documentation on what all must be updated as it is going to impact several updates being made to CTDL this week.

**Comment by mparsons-ce** [comment]
I tried the search:
https://sandbox.credentialengineregistry.org/ce-registry/search?resource_type=holders_profile&per_page=50&from=2019-11-01T00:00:00&sort_by=updated_at&sort_order=dsc
A single credential result is returned that has a holdersProfile in the graph:
https://sandbox.credentialengineregistry.org/resources/ce-80f07b38-0dc0-4886-8252-ed2cab8cedb6
A graph request for the holders profile returns the credential graph:
https://sandbox.credentialengineregistry.org/graph/ce-80f07b38-0dc0-4886-8252-ed2cab8cedb6

First
Shouldn't we be able to get just the holders profile graph?
Our publishing approach may change so this is just a question for now. 

Second
I tried to do a graph search for a type of ceterms:HoldersProfile and I don't get any results.

**Comment by excelsior** [comment]
@mparsons-ce 
1. That's just how the search works: It returns the envelope's whole graph, not the resource's graph. We can change it, of course.
2. By the graph search you mean Gremlin or SPARQL or something else?

**Comment by mparsons-ce** [comment]
I am referring to the SparQL search

**Comment by siuc-nate** [comment]
See also #379 

Todo: Once sandbox is up and running, I will test to see if I can:
- Access any records with a Holders Profile
- Access any DataSetProfile records

**Comment by siuc-nate** [comment]
I was able to find:
- 6 records with a Holders Profile
- 3 Data Set Profiles

**Comment by mparsons-ce** [comment]
@excelsior  
This can be promoted to staging and production.

**Comment by excelsior** [comment]
@mparsons-ce Promoted to both staging and production
