### ISSUE TITLE
Enable getting the envelope data without the payload

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#378]
There are cases where it would be useful to download the metadata from an envelope without the overhead of redownloading the payload (or its encoded form).  For instance, getting metadata about search results, such as the revision history - the consumer already has the payload data and doesn't need to redownload it.  This is important for cases where some results (like the tech skills framework) are several megabytes or more in size (which is roughly doubled by the encoded version being in the envelope).

What is the feasibility of enabling some kind of endpoint or parameter that enables getting an "empty" envelope? By "empty" I mean it has no `resource` or `decoded_resource` data, just the other meta information.

Something like one of these (I have no particular preference, but @mparsons-ce or @stuartasutton might):
```
https://credentialengineregistry.org/envelopes/ce-517e5336-af1a-41e7-94f5-27637915a164/empty
https://credentialengineregistry.org/envelopes/ce-517e5336-af1a-41e7-94f5-27637915a164?includeresource=false
https://credentialengineregistry.org/envelopedata/ce-517e5336-af1a-41e7-94f5-27637915a164
etc.
```

**Comment by jeannekitchens** [comment]
@excelsior can you provide a time estimate for this? We'll review your time estimate and determine if this should or should not be priortized.

**Comment by mparsons-ce** [comment]
@excelsior has provided an estimate of a couple of hours.

**Comment by excelsior** [comment]
@mparsons-ce @siuc-nate 

This feature is now available on staging and production:

- https://credentialengineregistry.org/envelopes?metadata_only=true
- https://credentialengineregistry.org/metadata/organizations/ce-5e443bd4-f685-4242-86af-1d2d597c6827/envelopes?metadata_only=true
- https://credentialengineregistry.org/search?metadata_only=true

**Comment by siuc-nate** [comment]
Nice, thank you.
