### ISSUE TITLE
Unable to query sandbox SPARQL

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#379]
Was the change made to turn off Sandbox SPARQL by chance?  When I try to query it, I get this message:

```
{
    "errors": [
        "Failed to open TCP connection to credential-registry-graph.cazemjodbmne.us-east-2.neptune.amazonaws.com:8182 (getaddrinfo: Name or service not known)"
    ]
}
```

**Comment by excelsior** [comment]
@siuc-nate The endpoint had changed, but sandbox's settings were not updated to reflect that. It's fixed.

**Comment by siuc-nate** [comment]
This is working now.
