### ISSUE TITLE
Documentation for credreg.net Registry pages

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#38]
@jkitchensSIUC @science @cwd-mparsons 
Please provide a list of what documentation is needed for the credreg.net site's Registry pages (which don't exist yet), so that we can point our various partners to those pages when they want to know how to start using the registry (publishing and/or consuming).  This list will make it easier to determine what existing documentation can be used and what, if any, needs to be (re)written.

**Comment by cwd-mparsons** [comment]
@jkitchensSIUC @science @leolara 
I have created a google doc to serve as a table of contents for Registry related documentation. The initially organization will be arbitrary. We want to identify all the topics of interest. The initial contents for a topic could be a link to an existing document, a summary of potential content, or detailed content. 

https://docs.google.com/document/d/1rVBGVnZ0c7vxfVPC8LQMuWm2W4h2vItY5nSbk26lFvE/edit#heading=h.x8q2x24somcn

This document is not expected to be a final source of all documentation. It may remain as a roadmap, where the the majority of the content is links to other locations. Some topics may be better presented as summary and use the equivalent of an appendix for more detailed or technical information. 

We could use this thread to assign responsibility to a topic, and possibly to notify where a topic is ready to be reviewed. 
As noted, we are starting with multiple sources: github, google, and perhaps external websites
The documentation presented on the credReg site will need to be well formed Html.
