### ISSUE TITLE
The sandbox registry is brutally slow

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#383]
@excelsior @edgarf @science 
Activities like a resource url take a long time to respond. Stopped checking after one minute. 
https://sandbox.credentialengineregistry.org/ce-registry/envelopes/ce-8c0497aa-c1bf-42ba-ade6-ca0234d0b35f

Note that the staging environment is fine.

**Comment by excelsior** [comment]
@mparsons-ce I restarted the instance, now it feels as snappy as before.

**Comment by mparsons-ce** [comment]
@excelsior thanks

**Comment by siuc-nate** [comment]
Any idea what may have caused this?
