### ISSUE TITLE
Enable mathematical comparisons on durations

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#385]
We have a use case where a client wants to be able to find all credentials that will take less than 5 days to complete.  This led me down something of a rabbit hole in trying to figure out how to write a query for it. There are a few problems in play:

- **1.** Values using either xsd:duration or schema:Duration do not lend themselves to math comparisons, since they are formatted as strings with no clear numeric representation (e.g. how do you get a computer to answer `P3Y6M2W4D >= P30M2W1D`?)
- **2.** Accurately normalizing the values to some common denominator (e.g. convert everything to a total number of hours and index that value) is not possible, both because:
    - **(a)** Durations can mean different things: A "5 month course" may take 5 real-world months but only a few hours a week in a classroom, while a 40-hour course may be 40 hours stretched across an undefined number of months
    - **(b)** [It is not possible to accurately answer the question](https://www.w3.org/TR/swbp-xsch-datatypes/#section-duration), "How many days does P3M take?" because there are an inconsistent number of days per month, per year (due to leap years), and the starting month (and year) is undefined. In other words, we don't know how many days P3M is because we don't know if it's P3M starting in February or starting in October and whether or not it's a leap year.

I don't have a solution for 2.a. above but it may be possible to ignore it and hope users will be able to tell the difference.  For 2.b. the best I can think of is to normalize the duration in a way that is not _technically_ accurate but should be close enough (and is better than nothing).  Something like one of the following:
1 month = 30 days
1 year = 52 weeks
1 month = 4 weeks
etc.

The trouble with that is, while they can be made to work well enough on their own, I haven't found a good way to enable unit conversion where the math doesn't break down and introduce repeating decimals and such along the way when converting between days, months, weeks, and years.

For example:
1 year = 12 months = 366 days (at 30 days per month) = ~52.2857142857 weeks per year
1 year = 52 weeks = ~4.33333333333 weeks per month
1 year = 366 days (at 30 days per month) = ~7.03846153846 days per week

And so on.  Questions like `P3Y6M2W4D >= P30M2W1D` can probably be answered in a "close enough" fashion when we assume (force) a 30 day month and a 366 day year, but not so much when we start having to change the number of days in a week to make the unit conversion work.

Maybe if we normalize every duration into some total number of seconds using some arbitrary "close enough on average" unit conversion assumptions like those above (but going directly to seconds without converting from one unit to another to another to another), the direct nature of the conversion will allow us to gloss over the imprecision.  For example, `P1Y3M2W` = `( 31556952 * 1 ) + ( 2592000 * 3 ) + ( 604800 * 2 )` = `31556952 + 7776000 + 1209600` = `40542552`.  That level of (im)precision should be good enough to answer the kinds of questions we're trying to answer.

I'm open to suggestions.

**Comment by mparsons-ce** [comment]
I think this is more like a sink hole than a rabbit hole.
A person may be fine with results for effort versus duration. They can afford a few hours a week and so don't mind an elapsed duration of 10 weeks versus a single week.
