### ISSUE TITLE
Codeship should track this repo

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#39]

**Comment by leolara** [comment]
@cwd-mparsons please give @coffeejunk deploy keys of this repo to implement this

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
How do I give deploy keys? Sorry I am not terribly familiar with github features like this!

**Comment by coffeejunk** [comment]
https://app.codeship.com/projects/210254 exists but the builds are failing (misconfiguration) can someone give me access to [metadataregistry's codeship](https://codeship.com/projects/136545) project so I can mirror the settings?

**Comment by coffeejunk** [comment]
CodeShip now tracks this repo and master will automatically be deployed
