### ISSUE TITLE
Convert all CTIDs to lower case

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#391]
We have encountered issues due to case differences for, especially metadata organizations.
Request
All CTIDs for the metadata organizations should be converted to lowercase.

Start with the sandbox to assess impact and then progress to other environments.

**Comment by excelsior** [comment]
@mparsons-ce All of the sandbox's organization CTIDs were converted to lowercase.

**Comment by mparsons-ce** [comment]
@excelsior 
Please change all organization CTIDs to lower case in both staging and production.

**Comment by mparsons-ce** [comment]
@excelsior Thanks, I have been able to verify related issues have been solved.
