### ISSUE TITLE
Create a faceted search to enable filtering by metadata like 

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#392]
The search mechanism only allows to perform full-text queries against the indexed attributes (those defined in the config). We need a faceted search following is a list of properties for searching .

envelope_ceterms_ctid
envelope_id
envelope_ctdl_type
publisher_id
published_by

**Comment by excelsior** [comment]
@mparsons-ce Should the faceted search allow filtering by multiple values (e.g. by several CTIDs)? If yes, then how'd you prefer to specify them:

1. by providing a comma separated list (`?envelope_ceterms_ctid=foo,bar`),
2. or by using the bracket syntax (`?envelope_ceterms_ctid[]=foo&envelope_ceterms_ctid[]=bar`)?

**Comment by mparsons-ce** [comment]
@excelsior While I don't think that multi-value will be a major usage, I suppose it would be useful to enable this feature. 
I would suggest using the first option of a comma separated list

**Comment by excelsior** [comment]
@mparsons-ce This feature is available on production now.

**Comment by mparsons-ce** [comment]
Thanks closing this issue.
