### ISSUE TITLE
Status of upgrade to use the newest version of PostgreSQL

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#394]
TBD

**Comment by excelsior** [comment]
What has been done:

1. Launched a separate RDS instance to accomodate the sandbox and staging databases.
2. Upgraded both production and non-production instances to Postgres 12.4., the latest available on AWS.
3. Tested the app with Postgres 13.0. locally, works just fine, meaning we can upgrade to it once RDS becomes offering it.
