### ISSUE TITLE
Not found definitions on JSON Schema

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#40]
When testing on http://www.jsonschemavalidator.net/

> http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true
> Error: Could not resolve schema reference '#/definitions/schema:Image'
>
> http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true
> Error: Could not resolve schema reference '#/definitions/schema:ContactPoint'
>
> http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?asGroup=true
> Error: 
Could not resolve schema reference '#/definitions/ceterms:IdentifierVaueSet'.
>
> http://credreg.net/ctdl/schema/validation/LearningOpportunityProfile/json?asGroup=true
> Error: Could not resolve schema reference '#/definitions/asn:LearningResource'.

This stops at the first error, so there can be more. All references need to be in the definitions. Please, fix this and test with the validator, just pasting the code on the left panel should show any errors.

**Comment by siuc-nate** [comment]
Unfortunately these are all problems with the source data itself that the schema is generated from - they have all been fixed in the next version of CTDL, but that doesn't release until late april.  I can add some temporary workarounds into the generation code to target these specific things, however.

**Comment by siuc-nate** [comment]
Which validator(s) are you using? I spotted two additional problems and added some workarounds for them as well, but I'd like to use your validator to check.

**Comment by leolara** [comment]
@siuc-nate We have used this http://www.jsonschemavalidator.net/ ; just paste the JSON schema on the left panel, if there is an error it will show below, even if you do not try to validate a document.

The workarrounds are necessary, the JSON schema should validate in order to use it in our system.

**Comment by leolara** [comment]
@siuc-nate I have to check more but it seems it is ok now
