### ISSUE TITLE
Sandbox registry response time very slow

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#403]
@excelsior @edgarf @science 
Publishing a competency framework is taking over 90 seconds. 

I tried a credential full text search. No response after 2 minutes:
https://sandbox.credentialengineregistry.org/ce-registry/search?resource_type=credential

A production FTS search for competency frameworks took 15 seconds, where in the past it was much faster.

**Comment by edgarf** [comment]
I know that @excelsior was working today with sandbox, doing some texts. Maybe it's related, @excelsior ?

**Comment by excelsior** [comment]
@mparsons-ce There is a huge envelope on sandbox (`ce-24e2260c-1d14-11ea-8239-782bcb5df6ac`), attempting to index it results in consumption of a lot of RAM, which slows the server down dramatically. Hopefully, we don't ever publish that big envelopes in production.

**Comment by mparsons-ce** [comment]
@excelsior @edgarf 
I am getting timeouts doing sandbox resources and searches

- https://sandbox.credentialengineregistry.org/resources/ce-bd8d187f-a734-4cc0-800f-0f8cc0bc3dd9- 
- https://sandbox.credentialengineregistry.org/ce-registry/search?resource_type=credential&per_page=50&from=2020-11-01T00:00:00&sort_by=updated_at&sort_order=dsc

**Comment by mparsons-ce** [comment]
FYI, Illlinois trying to publish to the sandbox, and all requests are timing out.

**Comment by mparsons-ce** [comment]
@excelsior @edgarf
I am getting timeouts again doing sandbox resources and searches

**Comment by excelsior** [comment]
@mparsons-ce This time, it's an indexing problem. Nearly 5,000 envelopes  with more than 15.000 resources were published recently. The sandbox server and its Neptune instance aren't that fast, so indexing such a large chunk of data slows them both down considerably. The solution would be either throttling the indexer or indexing newly published envelopes in batches (and not individually). I'll research which way is better.

**Comment by mparsons-ce** [comment]
@excelsior Thanks for the update.

**Comment by mparsons-ce** [comment]
@jeannekitchens @siuc-nate @edgarf @excelsior 
Updates
The issues are due to having only one server to server the API and indexing. If a lot of data is published, and lots of jobs are running, there will be high demand for CPU and ram. 
We discussed a possible approaches: 
- Throttle jobs
- Process envelopes together rather than individually. Wait and batch.
- More hardware
- Next step: get costs of changing staging server to a tiny instance (to reduce costs) and adding a separate server for indexing (to reduce the load)

**Batch Processing**
The second option of processing envelopes in batch does have a lot of merit and should be considered regardless. The process would be configurable, and could say run every 5, or 10 minutes. We will defer this for now.

**More Hardware**
The load on the sandbox is high now due to testing by partners. As soon as these partners complete their testing, load will be reduced again. A second server just for indexing would reduce the impact on the registry APIs (publishing, GETs).
To minimize the costs, a suggestion was to change the staging instance to be very small, and then add a new server for indexing. 

**Next steps**: 
Get cost of a tiny instance to be used for staging (to reduce costs) 
Confirm that the configuration of the current staging server would be adequate to be used for the indexing server.
If not, what would be the cost for an appropriately sized server. Note this would be appropriate for the sandbox, not production sized.

**Comment by jeannekitchens** [comment]
All, it is clear that testing on the sandbox will increase not decrease.  We must anticipate every state that will use the API publishing hundreds even thousands of credentials to the sandbox.  We actually require testing in the sandbox before providing the Registry keys.  Where are things with the next steps?

Next steps:
Get cost of a tiny instance to be used for staging (to reduce costs)
Confirm that the configuration of the current staging server would be adequate to be used for the indexing server.
If not, what would be the cost for an appropriately sized server. Note this would be appropriate for the sandbox, not production sized.

**Comment by jeannekitchens** [comment]
@edgarf @excelsior @mparsons-ce where are thing with ensuring sandbox remains responsive?

**Comment by excelsior** [comment]
We added a separate process server to the stack, meaning that the web server doesn't get affected if indexing goes awry.
