### ISSUE TITLE
AWS TLS Requirement Deadling March 15, 2021

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/CredentialRegistry#404]
@edgarf @excelsior @mparsons-ce @siuc-nate 

Hello,

You are running Neptune clusters on older engine versions that do not support TLS 1.2. You should update the following Neptune clusters in the us-east-2 Region to at least engine version 1.0.4.1 [1] prior to March 31, 2021, which is the date when TLS 1.2 will become the minimum required to use AWS FIPS endpoints [2].

credential-registry-production
credential-registry-graph-staging-cluster

Please upgrade to an engine version of at least 1.0.4.1 to enable TLS 1.2 and require encrypted client connections. There are also product updates included in this version. We recommend you perform a manual upgrade before March 15, 2021 by cloning your existing cluster with engine version 1.0.4.1, and test the upgraded cluster for any client incompatibilities. Be sure to validate the support Gremlin and SPARQL client versions listed on the release page [1]. To clone a cluster for testing follow the steps outlined in the Neptune documentation [3]. To upgrade your cluster manually refer to the steps on the 1.0.4.1 engine release page [1].

*About Engine Release 1.0.4.1*
Engine release 1.0.4.1 enforces encryption-in-transit with TLS v1.2 in all regions. Clients must use SSL with TLS v1.2 for both REST and WebSocket connections to the cluster. This removes the need to author IAM policies or change settings to enforce SSL client connections. In addition, the release improves performance of bulk loading data and SPARQL and Gremlin query execution. The latest engine release also introduces Neptune ML [4], a new capability of Neptune that uses machine learning technique purpose-built for graphs to make easy, fast, and more accurate predictions using graph data.

For a complete list of product changes, please refer to the release notes on the engine release page [1]. For any questions, please contact us through AWS Support [5] or the AWS Developer Forums [6].

[1] https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases-1.0.4.1.html
[2] https://aws.amazon.com/blogs/security/tls-1-2-to-become-the-minimum-for-all-aws-fips-endpoints/
[3] https://docs.aws.amazon.com/neptune/latest/userguide/manage-console-cloning.html
[4] https://docs.aws.amazon.com/neptune/latest/userguide/machine-learning.html
[5] https://aws.amazon.com/support
[6] https://forums.aws.amazon.com/forum.jspa?forumID=253

Sincerely,
Amazon Web Services

**Comment by excelsior** [comment]
@jeannekitchens All of our Neptune instances have been upgraded to the latest version (1.0.4.1) more than a week ago.
