### ISSUE TITLE
Give codeship access to Max @coffeejunk

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#41]
He needs to change that reads from this repo

**Comment by cwd-mparsons** [comment]
@leolara @andersoncardoso 
I added CodeShip to third party access. However, I am not familiar with this tool, so am not sure of how to provide the necessary permissions.

**Comment by coffeejunk** [comment]
@cwd-mparsons you can add collaborators via the [Manage Teams view](https://documentation.codeship.com/general/account/organizations/#managing-teams); you can add me by entering my email address (`max@holmes-iv.com`) into the form

**Comment by cwd-mparsons** [comment]
@coffeejunk 
I created an initial project, with some defaults (like Ruby), then added Max and Anderson as team members.
Let me know if there are any project attributes to add or change.

**Comment by coffeejunk** [comment]
Got access thanks!
