### ISSUE TITLE
Resources missing from SPARQL

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#410]
We have discovered that the following resources do not exist in SPARQL:
https://credentialengineregistry.org/resources/ce-2f9c0e33-10cc-47fe-8236-eafc42e1730c
https://credentialengineregistry.org/resources/ce-3e3fe009-9f1f-48af-80d1-6295e6fefbf7
https://credentialengineregistry.org/resources/ce-361ffacf-7c38-4049-b2be-40681092ddde
https://credentialengineregistry.org/resources/ce-768155dd-64ef-4bd5-8ebf-70b79bfb2696
https://credentialengineregistry.org/resources/ce-a74b55c0-88fa-4039-ba31-d0e2ede4f089
https://credentialengineregistry.org/resources/ce-83d5b674-65b9-4982-8678-327bdcae0a17
https://credentialengineregistry.org/resources/ce-1018d9df-a36f-4c7e-8fc9-52006fa56aaa
https://credentialengineregistry.org/resources/ce-4295dbe9-426b-497c-b285-5e112e723237
https://credentialengineregistry.org/resources/ce-44fc8a24-bcca-476a-b8ac-50f18fd047ed
https://credentialengineregistry.org/resources/ce-76c404bb-d38b-489e-9aa1-54e64125841c
https://credentialengineregistry.org/resources/ce-890b8559-4acf-4123-9835-6557069ed930

No results when looking by CTID:
![image](https://user-images.githubusercontent.com/21346519/109719388-31f9b700-7b6e-11eb-9090-bc7932cbd24c.png)

Nor by `@id`:
![image](https://user-images.githubusercontent.com/21346519/109719830-d7ad2600-7b6e-11eb-906e-17cb82a3f14d.png)

It's possible that there are others as well.

Any idea what would have caused this, and how to prevent it in the future?

**Comment by excelsior** [comment]
@siuc-nate After a full reindex, the missing resources are available in Neptune. TBF, I couldn't find why those where missing in the first place, will continue my investigation.

**Comment by siuc-nate** [comment]
Thanks.  Good luck.

**Comment by siuc-nate** [comment]
@excelsior will look into this again when time allows.
