### ISSUE TITLE
Missing description set for Competency Framework

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#411]
https://sandbox.credentialengineregistry.org/graph/ce-cf8c0f27-230c-4ed9-8d99-30f6bdec4252

Looking for the description set for this framework yields no data.  It was published a few hours ago. Is the sandbox still working through something else? Or did the indexer fall over?

![image](https://user-images.githubusercontent.com/21346519/110024340-ce999180-7cf3-11eb-90e9-99851f1ea3d0.png)

**Comment by excelsior** [comment]
@siuc-nate No, no failovers this time. More than 3,200 envelopes were published yesterday, so it took quite some time to index them all (and pre-calculate their description sets).

**Comment by siuc-nate** [comment]
Thanks. I see the data now.
