### ISSUE TITLE
Add new Purge process using Publisher id, optional resource type and date range

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#412]
We recently had to purge 5000+ records from production. The current process is to do one at time. 
The ability to be able to do bulk purges would be very helpful. 

This would be an especially useful feature for the sandbox. A publisher could then easily purge all of their documents as needed. 

Properties;
published_by: required
resource_type: optional
from datetime: optional
until datetime: optional

**Comment by excelsior** [comment]
@mparsons-ce The new purged API is available on sandbox. A few notes:

```
DELETE /envelopes?published_by=ce-abc-123&resource_type=credential&from=2020-04-20T16:20:00Z
```

- `resource_type` is supposed to be an alias (e.g. `credential` instead of `ceterms:Credential`),
- `from` and `until` should be in the ISO 8601 format.

**Comment by siuc-nate** [comment]
This is awaiting @mparsons-ce's testing.

**Comment by mparsons-ce** [comment]
@excelsior If the request is for a community, will the URL be:
DELETE /**{community}/**envelopes?published_by=ce-abc-123&resource_type=credential&from=2020-04-20T16:20:00Z
OR using a parameter
DELETE /{envelopes?published_by=ce-abc-123&resource_type=credential&from=2020-04-20T16:20:00Z**&community={community}**

**Comment by excelsior** [comment]
@mparsons-ce This API doesn't support filtering by a community. If you need it to, I'd rather implement in the former manner.

**Comment by mparsons-ce** [comment]
@excelsior 
I tried doing a purge all request, and get back zero results.
https://sandbox.credentialengineregistry.org/envelopes?published_by=ce-a0c0984a-1153-4244-b510-dbb0a805fa35&resource_type=learning_opportunity_profile

**Comment by mparsons-ce** [comment]
@excelsior 
re: communities
Yes, we would like the ability to just purge data in a community.

As you suggested the format of the endpoint would be: 
DELETE /{community}/envelopes?published_by=ce-abc-123&resource_type=credential&from=2020-04-20T16:20:00Z

**Comment by excelsior** [comment]
@mparsons-ce Turns out, the `resource_type` column didn't get populated for envelopes published the new way (only for envelope resources). So that filter didn't work on sandbox where 100% of data was published the new way. That bug is fixed and all of the envelopes' resource types are populated correctly.

**Comment by mparsons-ce** [comment]
@excelsior 
I tried again and was able to **successfully** do purges for learning opps, credentials, and all.
NOTE: the latter two returned the total of records purged, but **zero** was returned after the learning opportunity purge.

**Comment by mparsons-ce** [comment]
@excelsior I recently did a purge all without specifying an entity type. I did get a total records returned. 
Later today I will probably do more purges. I will do one at a time to check if total records are returned for learning opps.

**Comment by mparsons-ce** [comment]
Completed testing for just assessments and just credentials, and totals were properly returned.

**Comment by mparsons-ce** [comment]
@excelsior 
I tried to do purges in the sandbox today for published_by=ce-89bd0d16-6492-4ae1-8059-deabc3d89c15.
All attempts would seem to hang and then time out. I tried both credentials and learning opportunities.

**Comment by excelsior** [comment]
@mparsons-ce One of your requests timed out because of a deadlock, not sure why the other one failed as well. Looks like bulk purging can conflict with resource extraction.

 I don't see any envelopes from this publisher on sandbox. I assume you did succeed at purging them after all?

**Comment by mparsons-ce** [comment]
@excelsior Yes, I was able to purge all of the documents for this publisher.
