### ISSUE TITLE
Use prefix for @id in some resource types/communities

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#42]

**Comment by leolara** [comment]
@coffeejunk 

Each community could have a "@id prefix" configured. If it is not set, it should be considered an empty string.

When calling the APIs end points /{community}/resources/{@id} and /resources/{@id} ; the url parameter should be added this prefix before using it.

Also, we should check when inserting or updating a json documents via these API endpoints, that the @id field if present does actually contains the prefix and gives an error otherwise.

**Comment by leolara** [comment]
Where I said json documents, I meant the resources

**Comment by coffeejunk** [comment]
Do these "prefix"es adhere a certain format or are they just some string?

**Comment by leolara** [comment]
@coffeejunk the prefix should be any string. For the credential registry community is going to be an url, but I do not think it is useful to restrict it to a url.

In the CredReg, the `@id` is going to be something like http://domain.com/resources/{UUID} and the idea is that the GET of the /resources/ API is the same url in the end as the `@id`; the problem of course is that the url parameter cannot be the url because that would be recursive. The problem is solved by this prefix.

**Comment by leolara** [comment]
@coffeejunk 

Example:

in https://gist.github.com/cwd-mparsons/4fa334d51ddf308ed09bc2f0d096a65c

we have the ID:  
`“@id”: “http://credentialengine.org/resource/urn:ctid:E04B6368-3587-45C9-8B9C-AA1DC0A761FD“`

in the API the @id url param we have urn:ctid:E04B6368-3587-45C9-8B9C-AA1DC0A761FD which is only the last part of the actual resource url, so we say that for this community we have the @id prefix http://credentialengine.org/resource/

Then, in the API code, before using the @id url param, we prepend http://credentialengine.org/resource/
