### ISSUE TITLE
Critical unable to search or retrieve resources in the sandbox or staging environment

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#424]
@excelsior @edgarf @science 
The FTS search or any attempt to view a /resources/, /graph/ or /envelopes/ endpoint fails with no connection to the server.

![image](https://user-images.githubusercontent.com/58825866/113889083-81905b80-9788-11eb-87f1-e354d7454e5c.png)

In case this is related, I was testing the PurgeAll endpoint. I had got a result of zero purged. I then used the search to see if there was a change in the number of a learning opps for a publisher.

**Comment by edgarf** [comment]
@mparsons-ce, Alex (@excelsior) is updating Postgres on Sandbox, we will update this thread.

**Comment by mparsons-ce** [comment]
@edgarf Thanks

**Comment by excelsior** [comment]
@mparsons-ce Both are up and running again, sorry for the inconvenience.

**Comment by mparsons-ce** [comment]
@excelsior thanks.

**Comment by edgarf** [comment]
@mparsons-ce - can you check if it's fine now?
