### ISSUE TITLE
Framework removed from the registry, but still exists in the SPARQL index

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#430]
In the **sandbox** environment:

https://sandbox.credentialengineregistry.org/resources/ce-cf8c0f27-230c-4ed9-8d99-30f6bdec4252 does not exist in the sandbox registry, but it does still exist in the sandbox SPARQL index:
```
SELECT * WHERE { <https://sandbox.credentialengineregistry.org/resources/ce-cf8c0f27-230c-4ed9-8d99-30f6bdec4252> ?p ?o }
```
![image](https://user-images.githubusercontent.com/21346519/115251679-5f83cb00-a0f0-11eb-84a5-f3410c33408b.png)

It's possible the same issue applies to other resources.

**Comment by excelsior** [comment]
@siuc-nate I'm rebuilding the sandbox SPARQL index, will update you once it's ready.

**Comment by excelsior** [comment]
@siuc-nate The index is up-to-date.

**Comment by siuc-nate** [comment]
Thanks.  Any idea what caused the resources to not get removed from the index when they were deleted from the registry?

**Comment by excelsior** [comment]
Unfortunately, I can't check, because the envelope was deleted on March 3, and the logs has gotten rotated already.
