### ISSUE TITLE
Many SPARQL resources do not have credreg:__recordPublishedBy data

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#431]
When I do the following query:
```
https://staging.credentialengineregistry.org/sparql/
```
```
PREFIX credreg: <https://credreg.net/> PREFIX ceasn: <https://purl.org/ctdlasn/terms/> PREFIX ceterms: <https://purl.org/ctdl/terms/> SELECT * WHERE {  ?id (credreg:__recordPublishedBy) ?recordPublishedBy . } LIMIT 100
```

I get no results.  Running the same query against sandbox or production produces results.  Using `credreg:__recordOwnedBy` instead of `credreg:__recordPublishedBy` also produces results.

I thought we didn't have a staging instance of SPARQL(?) - What is this actually querying against?

**Comment by siuc-nate** [comment]
This is also affecting production SPARQL.  When I look for competency frameworks, I get 763 results (vanilla) but only 437 frameworks that have `credreg:__recordPublishedBy`

Compare:
```
PREFIX credreg: <https://credreg.net/> PREFIX ceasn: <https://purl.org/ctdlasn/terms/> PREFIX ceterms: <https://purl.org/ctdl/terms/> SELECT (COUNT(?id) AS ?count) WHERE { ?id a ceasn:CompetencyFramework . ?id (credreg:__recordPublishedBy) ?recordPublishedBy . } LIMIT 100
```
```
PREFIX credreg: <https://credreg.net/> PREFIX ceasn: <https://purl.org/ctdlasn/terms/> PREFIX ceterms: <https://purl.org/ctdl/terms/> SELECT (COUNT(?id) AS ?count) WHERE { ?id a ceasn:CompetencyFramework . } LIMIT 100
```

**Comment by mparsons-ce** [comment]
@siuc-nate The data in the staging registry was probably published before we adding published_by when publishing. 

@excelsior All staging envelopes can have the published_by set to owned_by.

**Comment by excelsior** [comment]
@mparsons-ce The problem is, only 11 envelopeshave a non-blank `owned_by` on staging . On production, ~4,800 envelopes  don't have a publisher.

**Comment by excelsior** [comment]
@mparsons-ce [envelopes_without_publisher_on_prod.csv](https://github.com/CredentialEngine/CredentialRegistry/files/6468363/envelopes_without_publisher_on_prod.csv)

**Comment by mparsons-ce** [comment]
@excelsior 
I updated the file with the publisherCTID. I was not where to upload the file, so put it here:
https://gist.github.com/mparsons-ce/5d0c7b9af6d6c7e8b8e51791e6636624#file-envelopes_without_publisher_on_prod_updated-csv

**Comment by excelsior** [comment]
Thank you, I promoted those changes to production.
