### ISSUE TITLE
Missing organization in sandbox SPARQL

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#432]
This organization does not appear in the sandbox SPARQL index:
https://sandbox.credentialengineregistry.org/resources/ce-bd8d187f-a734-4cc0-800f-0f8cc0bc3dd9
```
PREFIX credreg: <https://credreg.net/> PREFIX ceasn: <https://purl.org/ctdlasn/terms/> PREFIX ceterms: <https://purl.org/ctdl/terms/> SELECT * WHERE {  <https://sandbox.credentialengineregistry.org/resources/ce-a4041983-b1ae-4ad4-a43d-284a5b4b2d73> ?p ?o . } LIMIT 100
```
![image](https://user-images.githubusercontent.com/21346519/115782870-ca980080-a381-11eb-86ae-a40067a60000.png)

It's possible there are others.

How can we best figure out why/how the SPARQL index seems to keep slipping out of sync with the registry?

**Comment by excelsior** [comment]
@siuc-nate This organization was deleted from the registry long time ago. It was also supposed to be physically removed, but we don't have the purge mechanism enabled on sandbox. Should I enable it?

**Comment by siuc-nate** [comment]
I would defer that question to @mparsons-ce.

What's available in SPARQL should match what's available in the registry.  Is there a way to make that happen regardless of whether or not the "purge mechanism" is enabled?

**Comment by mparsons-ce** [comment]
@siuc-nate @excelsior 
I would guess the "purge mechanism" is something related to SPARQL as we can currently have purge and purge all endpoints already operational in the sandbox?

**Comment by excelsior** [comment]
Actually, all is good with the index in this case.

@siuc-nate You're looking at an organization with the `ce-bd8d187f-a734-4cc0-800f-0f8cc0bc3dd9` ID. But in your SPARQL query you're using a completely difference resource with the `ce-a4041983-b1ae-4ad4-a43d-284a5b4b2d73` ID. The latter did get deleted from the registry and from the index as well, so the query returns nothing. The former does exist, and looking it up in Neptune produces the expected result:

```sparql
PREFIX credreg: <https://credreg.net/> PREFIX ceasn: <https://purl.org/ctdlasn/terms/> PREFIX ceterms: <https://purl.org/ctdl/terms/> SELECT * WHERE {  <https://sandbox.credentialengineregistry.org/resources/ce-bd8d187f-a734-4cc0-800f-0f8cc0bc3dd9> ?p ?o . } LIMIT 100
```

Sorry, I didn't notice the ID mismatch at first 🥺

**Comment by siuc-nate** [comment]
This is resolved
