### ISSUE TITLE
Organization (NOCTI) gets 'Organization not found' error trying to republish credentials and assessments

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#435]
Attempts by NOCTI to republish credentials and assessments result in the error:

> Error - Couldn't find Organization

Typically the latter occurs because the organization was not registered properly in the credential registry. However, the NOCTI organization can be seen in metadata/organizations:
![image](https://user-images.githubusercontent.com/58825866/116159833-90e33480-a6b6-11eb-8884-45ae26a97201.png)

The organization NOCTI (ce-6a62b250-a1a2-4d31-a702-cdc2437efd31) was one that previously had the CTID registered in /meta/organizations as upper case (ce-6A62B250-A1A2-4D31-A702-CDC2437EFD31).
Some time ago, all of the CTIDs were set to lowercase. 

I tried doing a transfer of owner on one of the credentials and assessments that could not be published. 
After the latter, I was able to publish the documents. 

Could it be that changing the ctid in metadata/organizations 'broke' the registered organization?

**Comment by excelsior** [comment]
@mparsons-ce I see a handful of publishing requests with the upper-case ID (`ce-6A62B250-A1A2-4D31-A702-CDC2437EFD31`) in the logs. Those 100% won't work, because IDs are case-sensitive, and NOCTI's ID is all lower-case.

There are also proper requests, those using `ce-6a62b250-a1a2-4d31-a702-cdc2437efd31`. All of those worked out just fine, according to the logs. I guess the proper ones were issued by you?

**Comment by mparsons-ce** [comment]
@excelsior 
My testing was to:
- try publishing with the input document provided by NOCTI
- the publish would fail with the organization not found error
- I checked the NOCTI record in /metadata/organizations and saw that the CTID for NOCTI was all lowercase
- The API already was forcing all CTIDs to lower case including PublishForOrganizationIdentifier (I found that the latter was not happening for assessments - I fixed this)
- On fail, the only change I had to do was to do a _transfer of owner_ to NOCTI (even though the latter was already the owner)
- then I could publish both the credential and assessment

I just completed a transfer of owner on all of the credentials and assessments for NOCTI. I am going to notify NOCTI to try publishing again. 

My concern is that will a similar problem occur for all orgs that used to have upper case letters in the CTID that was used when registering an organization.

**Comment by mparsons-ce** [comment]
TODO for @mparsons-ce 
Find another organization to test that may have previously had an upper case CTID as a registered organization.

**Comment by jeannekitchens** [comment]
@mparsons-ce NOCTI and some states are the only publishing API users, How would it be possible, unless it was via the manual publisher or bulk upload.  Is this still open?

**Comment by jeannekitchens** [comment]
@mparsons-ce is keeping this open.  It is currently not an issue for Tapestry team.

**Comment by mparsons-ce** [comment]
Closing this issue as have not run into a similar scenario.
