### ISSUE TITLE
Sandbox has been unresponsive a lot today 

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#441]
@excelsior @edgarf 
The sandbox server is not responding.

**Comment by mparsons-ce** [comment]
![image](https://user-images.githubusercontent.com/58825866/116504319-a060aa00-a87d-11eb-972a-a5822baf8b6e.png)

**Comment by excelsior** [comment]
According to the syslog, the most likely cause of the outage was exausted memory:

```
Apr 28 20:04:46 alligator kernel: [303559.070821] Out of memory: Killed process 29201 (ruby) total-vm:2193580kB, anon-rss:1145228kB, file-rss:0kB, shmem-rss:0kB, UID:60125 pgtables:3116kB oom_score_adj:0
```

However, the server became unresponsive more than an hour earlier, so maybe there was a separate network problem in place as well.

Fewer than 300 envelopes were published yesterday, each with two resources at most. Hence the server shouldn't have been overwhelmed. Maybe the app server or job scheduler leak memory. We're working on enhancing our monitoring setup to avoid situations like this.

Anyway, we have an API for restarting an unresponsive instance: https://github.com/CredentialEngine/CredentialRegistry/issues/244#issuecomment-779115481
