### ISSUE TITLE
Query Speed Issue Examples 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/CredentialRegistry#443]
**This query looks for credentials that are availableAt an Indiana address or offered by an organization in Indiana. It takes 14-15 seconds.  This is a typical query that Registry users are interested in.  14-15 seconds is too slow.  See the second example below that takes longer**  
{
	"@type": [
		"ceterms:ApprenticeshipCertificate",
		"ceterms:AssociateDegree",
		"ceterms:BachelorDegree",
		"ceterms:Badge",
		"ceterms:Certificate",
		"ceterms:CertificateOfCompletion",
		"ceterms:Certification",
		"ceterms:Degree",
		"ceterms:DigitalBadge",
		"ceterms:Diploma",
		"ceterms:DoctoralDegree",
		"ceterms:GeneralEducationDevelopment",
		"ceterms:JourneymanCertificate",
		"ceterms:License",
		"ceterms:MasterCertificate",
		"ceterms:MasterDegree",
		"ceterms:MicroCredential",
		"ceterms:OpenBadge",
		"ceterms:ProfessionalDoctorate",
		"ceterms:QualityAssuranceCredential",
		"ceterms:ResearchDoctorate",
		"ceterms:SecondarySchoolDiploma"
	],
	"search:termGroup": {
		"search:operator": "search:orTerms",
		"ceterms:availableAt": {
			"ceterms:addressRegion": [
				{ "search:value": "indiana" },
				{ "search:value": "in", "search:matchType": "search:exactMatch" }
			]
		},
		"ceterms:offeredBy": {
			"ceterms:address": {
				"ceterms:addressRegion": [
					{ "search:value": "indiana" },
					{ "search:value": "in", "search:matchType": "search:exactMatch" }
				]
			}
		}
	}
}

 **This querly looks for credentials that have either a specified SOC code or any description of an occupation, and which meet at least one of the location criteria (availableAt an Indiana address, offered by an organization with an Indiana address, or approved by an organization with an Indiana address).  It takes 16-19 seconds.**  
{
	"@type": [
		"ceterms:ApprenticeshipCertificate",
		"ceterms:AssociateDegree",
		"ceterms:BachelorDegree",
		"ceterms:Badge",
		"ceterms:Certificate",
		"ceterms:CertificateOfCompletion",
		"ceterms:Certification",
		"ceterms:Degree",
		"ceterms:DigitalBadge",
		"ceterms:Diploma",
		"ceterms:DoctoralDegree",
		"ceterms:GeneralEducationDevelopment",
		"ceterms:JourneymanCertificate",
		"ceterms:License",
		"ceterms:MasterCertificate",
		"ceterms:MasterDegree",
		"ceterms:MicroCredential",
		"ceterms:OpenBadge",
		"ceterms:ProfessionalDoctorate",
		"ceterms:QualityAssuranceCredential",
		"ceterms:ResearchDoctorate",
		"ceterms:SecondarySchoolDiploma"
	],
	"ceterms:occupationType": {
		"ceterms:targetNodeDescription": "search:anyValue",
		"ceterms:codedNotation": {
			"search:value": "23-2011.00",
			"search:matchType": "search:exactMatch"
		},
		"search:operator": "search:orTerms"
	},
	"search:termGroup": {
		"search:operator": "search:orTerms",
		"ceterms:availableAt": {
			"ceterms:addressRegion": [
				{ "search:value": "indiana" },
				{ "search:value": "in", "search:matchType": "search:exactMatch" }
			]
		},
		"ceterms:offeredBy": {
			"ceterms:address": {
				"ceterms:addressRegion": [
					{ "search:value": "indiana" },
					{ "search:value": "in", "search:matchType": "search:exactMatch" }
				]
			}
		}
	}
}

**Comment by excelsior** [comment]
I haven't succeeded at optimizing the queries yet, but I've tried them with the alternative query engine enabled and the execution time was reduced from 15–20s to 8–10s.

This engine has been enabled on sandbox for a couple of weeks already, and we haven't run into any issues there, have we? @siuc-nate 

I'll leave enabled on production for a few hours for you guys to give it a try…

**Comment by siuc-nate** [comment]
Note: In our meeting today, we decided to leave this enabled unless/until something comes up that indicates we should disable it.

**Comment by siuc-nate** [comment]
See #449
