### ISSUE TITLE
Erroneous/extra data in description sets

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#445]
I was working on some stuff with description sets today and I noticed that the description set for [this competency framework](https://sandbox.credentialengineregistry.org/resources/ce-3e7df7ec-1a9b-4503-9ff3-21256022b515) included a reference to Pathway Component items that didn't belong there:
![image](https://user-images.githubusercontent.com/21346519/117739999-17bf0380-b1c5-11eb-87c5-ead0a68405e2.png)

If I had to guess, I would guess this is caused by a missing type filter on the starting point for the description set queries that were based on [the tracking spreadsheet](https://docs.google.com/spreadsheets/d/1VNgJ7qu_zydCB3UQMzEuHbYKczr_Q9nkRRxzoUWYLuk/edit#gid=0).

Both rows 265 ("Has Competency") and 371 ("Has Component") use the same SPARQL, but the `?subject` for each should be of a different type (`ceasn:CompetencyFramework` for the former and `ceterms:Pathway` for the latter).  This problem may also be affecting other places where the SPARQL query overlaps but the starting points are different types.

It's not currently an urgent matter, but this does need to be fixed the next time description sets are rebuilt.

**Comment by excelsior** [comment]
@siuc-nate Your assumption was correct: the subject's type wasn't taken into account when reverse mappings were processed. Fixed that.

**Comment by siuc-nate** [comment]
Great, thanks.
