### ISSUE TITLE
Occasionally 

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#450]
@excelsior 
I had noted last week that occasionally an error like the following can occur while doing publishing:
**The remote name could not be resolved: 'sandbox.credentialengine.org'**

This occurred today. I immediately retried the request and it was successful. 
The possible symptoms:
- mostly have noticed this while in the development environment
- sometime it occurs on a /resources/ url, sometimes on an /envelopes/ url
- I think it is often the first time a URL request is made. That is, I could be importing several documents. The first document transaction may result in this kind of error, and then not occur for the rest of the transactions

I understand that this could be difficult to debug given the infrequent occurrence.

**Comment by excelsior** [comment]
@mparsons-ce Our API is hosted at sandbox.credentialengine**registry**.org

The domain whose name sometimes fails to resolve (sandbox.credentialengine.org') is different, I don't think we have access to its settings. It appears to be configured correctly, according to nslookup.

How exactly do you make the requests mentioned above? Do you do that locally, e.g. via Postman? In this case, try flushing your DSN cache for starters (`ipconfig /flushdns` on Windows).

**Comment by mparsons-ce** [comment]
The error message specifies the IP address of 18.221.137.177, which is the sandbox server
InnerException3: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond **18.221.137.177**:443;

![image](https://user-images.githubusercontent.com/58825866/118988583-f1c4fc00-b946-11eb-8552-a0b503967290.png)

**Comment by excelsior** [comment]
Yeah, the `connection attempt failed` exception is a different issue. The previous one is about name resolution failures. The fact that the IP address is specified in the error message indicates that name resolution was successful.

**Comment by jeannekitchens** [comment]
@mparsons-ce please review and clarify if this issue is not resolved.
