### ISSUE TITLE
Sandbox SPARQL is broken

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#458]
I'm not able to retrieve data using any of the normal queries:
![image](https://user-images.githubusercontent.com/21346519/121228766-c309b980-c852-11eb-9f30-152490f5f239.png)

I get the error with a vanilla query too:
![image](https://user-images.githubusercontent.com/21346519/121228828-d87ee380-c852-11eb-939e-5131b579ddb1.png)

But data does show if I limit it enough (LIMIT 10 instead of LIMIT 100 in the above query):
![image](https://user-images.githubusercontent.com/21346519/121228899-f1879480-c852-11eb-8732-8e44d17088ad.png)

Any idea what's going on?

**Comment by excelsior** [comment]
@siuc-nate There was a problem with query logging. We disabled it for now, sorry about that.

**Comment by jeannekitchens** [comment]
@excelsior is the query logging still disabled?

**Comment by excelsior** [comment]
@jeannekitchens The issue was fixed, the logging is enabled and works as expected.
