### ISSUE TITLE
Alignments present in description set but not in competency data

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#459]
The tech skills framework is here:
https://credentialengineregistry.org/graph/ce-9fab4187-d8e7-11e9-8250-782bcb5df6ac

It used to have 9000+ alignments to external URIs, but it was republished at some point and those alignments were removed:
![image](https://user-images.githubusercontent.com/21346519/121406131-6aeeb800-c923-11eb-9162-9bfd28b67611.png)

However, those alignments still show up in the description set for it:
![image](https://user-images.githubusercontent.com/21346519/121406229-82c63c00-c923-11eb-9ef9-1ebaa6d766ac.png)

It seems that there is something missing in the description set handling code(?)

**Comment by siuc-nate** [comment]
For what it's worth, those alignments _are_ supposed to be present in the registry - we're working on fixing that on our end. Nonetheless, if the data was published without them, then the description set shouldn't have retained them.

**Comment by excelsior** [comment]
@siuc-nate I'm re-calculating the description sets.

**Comment by jeannekitchens** [comment]
@excelsior is this completed?

**Comment by excelsior** [comment]
@jeannekitchens It is ✅
