### ISSUE TITLE
Description set missing concept scheme data for a framework

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#460]
This concept framework:
https://credentialengineregistry.org/graph/ce-eca0a0de-6cce-4d68-ae87-94b4831e8776

Has a reference from nearly every competency to concepts in this concept scheme:
https://credentialengineregistry.org/graph/ce-29cdb1b5-5714-4bcf-a0ca-75274f50820a

However, the description set for that framework is missing the concepts and their scheme:
![image](https://user-images.githubusercontent.com/21346519/121930507-11620100-cd08-11eb-9ef8-b08d2e960799.png)

It looks like this is due to [the description set item map spreadsheet](https://docs.google.com/spreadsheets/d/1VNgJ7qu_zydCB3UQMzEuHbYKczr_Q9nkRRxzoUWYLuk/edit#gid=0) missing rows for ceasn:conceptTerm.  I have updated the spreadsheet (rows 270 and 271) with the appropriate paths.

**Comment by excelsior** [comment]
@siuc-nate I updated the config and re-calculated the sets, now the framework's DS looks good.

**Comment by jeannekitchens** [comment]
@siuc-nate can this be closed?

**Comment by siuc-nate** [comment]
Yes, it is working now.
