### ISSUE TITLE
Differences in credential counts in production

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#472]
@excelsior @edgarf 
While Nate was doing the demo of the search updates in the query helper, I noticed discrepancies in the credential counts
Production
Full text search for credential:	**28680**
SearchAPI current: 27622 
SearchAPI beta: 28690
Credential Finder: **28600**

We need to resolve why these counts vary. I would think that the full text search should be the most accurate. 
re: Finder
Could I get a list of the CTIDs for all credentials? This will allow be to determine what is missing. 
Actually, could I get a list of all top level entities, with the CTID. That is a file for each of credential, organization, assessment, learning opportunity, and competency framework.

**Comment by mparsons-ce** [comment]
Next steps: Alex will look into how we can query and exclude the blank nodes.

**Comment by excelsior** [comment]
@mparsons-ce You can now control presence of bnodes in search results via the `with_bnodes` parameter. The allowed values are `true` and `false` (by default it's `true` ). It's available on sandbox. I'll deploy to prod once you confirm it's working as expected.

**Comment by mparsons-ce** [comment]
@excelsior Thanks. I did some quick testing and need to do bit more checking.
One more request, could `with_bnodes` default to false? 
I think the most common expectation is to NOT want bnodes.

**Comment by excelsior** [comment]
@mparsons-ce The default for `with_bnodes` has been changed to `false` per your request. Also, there's another option called `only` in case you'd like to look for bnodes only.
