### ISSUE TITLE
Explore efficient ways to look for data that references a known starting point

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#480]
For concept schemes, one of the difficulties we have on our plate is constructing their description sets.  Because concepts are used in a very large number of places across CTDL, the current way we handle description sets would require determining every possible path (within reason) by which a concept from any scheme gets referenced by any top-level object, either directly or indirectly (ie via condition profile).

Is there a more efficient way to do this? If not as a real-time query, then perhaps a way to generate description sets without needing to define every possible path? Something like:
```
skos:Concept < [some property] < [some top-level object]
skos:Concept < ceterms:targetNode < ceterms:CredentialAlignmentObject < [some property] < [some top-level object]
skos:Concept < [some property] < [some non-top-level object] < [some property] < [some top-level object]
skos:Concept < ceterms:targetNode < ceterms:CredentialAlignmentObject < [some property] < [some non-top-level object] < [some property] < [some top-level object]
```
We would catch a lot of paths with that, but there are a lot of places where the tree goes deeper, so it would also miss a lot as well.  We would need to retain the properties/object types along the way so that the description set that gets generated would still be able to provide explicit paths as it does now.

Maybe we need some way to crawl `0..n` combinations of non-top-level object and some property, e.g.
```
skos:Concept < [(0..n sets of [some property] < [some non-top-level object])] < [some property] < [some top-level object]
```
I can attempt to create/generate all of the possible paths via the schema's domains and ranges if we can't determine something here, but I was hoping to avoid the overhead of needing to maintain that list as the schema evolves over time.

I'm not even sure SPARQL could do what I'm trying to do, here. Any clever ideas? Bonus points if the approach can also be used for competencies and other things that get referenced from a lot of potential places.

**Comment by excelsior** [comment]
@siuc-nate I started exploring ways of constructing all possible paths in real time. It seems to be feasible with Postgres' recursive queries. The big question is what would be the termination condition in such a query?

- Should we stop as soon as we hit a top-level resource?
- Or should the `n` value from your examples be simply set to some reasonable number?

**Comment by siuc-nate** [comment]
I think stopping at the first top-level resource is reasonable, yeah. Can the object/property path be preserved/returned along the way with that approach?

**Comment by excelsior** [comment]
> Can the object/property path be preserved/returned with that approach?

It should be possible, the only problem is you use aliases in your mappings (e.g. `ceterms:Agent`, which isn't a real type, it's an umbrella category for various organizations). Thus I'll need a list of such aliases in order to construct the paths when building the sets dynamicaly.

Speaking about the paths, all the connections in your examples are 'incoming':

```
skos:Concept < [property] < [top-level resource]
```

Should we look for 'outgoing' ones as well? E.g.

 ```
skos:Concept > [property] > [top-level resource]
```

**Comment by excelsior** [comment]
@siuc-nate I wrote a recursive query for generating description sets. Using concepts as starting points, then following incoming connections until a top-level resource is reached the following paths were constructed:

```
skos:Concept < ceasn:complexityLevel < ceasn:Competency
skos:Concept < ceasn:conceptTerm < ceasn:Competency
skos:Concept < ceasn:educationLevelType < ceasn:Competency
skos:Concept < skos:hasTopConcept < skos:ConceptScheme
```

So, there are only four paths, each only one step long. There are no `ceterms:targetNode` connections from your examples nor any alignments involved. Am I missing something?

I tried looking at outgoing connections using the same algo, and I got these paths:

```
skos:Concept > skos:inScheme > skos:ConceptScheme
skos:Concept > skos:topConceptOf > skos:ConceptScheme
```

I also tried generating one-step long paths from the SPARQL data and got the same results.

**Comment by siuc-nate** [comment]
>Thus I'll need a list of such aliases in order to construct the paths when building the sets dynamicaly.

I can probably provide that, but can the `@type` values be captured as part of recursing through the paths? Maybe I'm misunderstanding.

>Am I missing something?

Actually, I missed something: Those are probably the only connections you'd see in the actual data at this point. It just occurred to me that you wouldn't see the other types of connections I was talking about in the registry because we use the "official" schema references from credreg.net instead of the copies of those that exist in the registry for the URIs for terms like the following:
https://credentialengineregistry.org/ce-registry/resources/ce-9fdf6277-2bfb-4783-9b37-f578cf688861
From the credential's perspective:
`ceterms:Credential > ceterms:audienceLevelType > ceterms:CredentialAlignmentObject > ceterms:targetNode > audLevel:BeginnerLevel`
`ceterms:Credential > ceterms:estimatedCost > ceterms:CostProfile > ceterms:directCostType > ceterms:CredentialAlignmentObject > ceterms:targetNode > costType:StandaloneAssessment`

Naturally those wouldn't show up in the registry data, since they aren't technically using the registry data. I can figure out another solution for those if/when we need them, so for now let's just focus on the paths you were able to find.  Those are the ones that will matter the most anyhow, since the major goal of enabling this is to be able to show what links to a given concept scheme from its detail page in the finder, and the schemes that will show up in the finder will be the ones people upload rather than the ones from credreg.net.  (The registry copies of the credreg.net schemes won't show any connections because, technically, none exist - but I can work around that, I think).

**Comment by neaf** [comment]
@siuc-nate @excelsior 

Can we close this issue?

**Comment by siuc-nate** [comment]
This will be covered by the dynamically generated description set mechanism
