### ISSUE TITLE
Attempt to publish an organization to the snhupr community results error: @type is required

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#489]
@excelsior I tried to publish an organization to the snhupr community and received the following error:

`{"errors":["Cannot load json-schema. @type is required"]}`

I then tried to publish the same info to the public sandbox and it was successful. 

following is the payload:
{
  "@context": "https://credreg.net/ctdl/schema/context/json",
  "@id": "https://sandbox.credentialengineregistry.org/snhupr/graph/ce-0f0d84f5-5c32-4526-ad39-1db0adbdbe93",
  "@graph": [
    {
      "@id": "https://sandbox.credentialengineregistry.org/snhupr/resources/ce-0f0d84f5-5c32-4526-ad39-1db0adbdbe93",
      "@type": "ceterms:CredentialOrganization",
      "ceterms:name": {
        "en-US": "Southern New Hampshire University"
      },
      "ceterms:description": {
        "en-US": "Southern New Hampshire University is accredited by the New England Commission of Higher Education (NECHE). All Programs offered by SNHU are encompassed by this regional accreditation."
      },
      "ceterms:ctid": "ce-0f0d84f5-5c32-4526-ad39-1db0adbdbe93",
      "ceterms:subjectWebpage": "http://www.snhu.edu",
      "ceterms:lifecycleStatus": {
        "@type": "ceterms:CredentialAlignmentObject",
        "ceterms:framework": "https://credreg.net/ctdl/terms/Active",
        "ceterms:targetNode": "lifecycle:Active",
        "ceterms:targetNodeName": {
          "en-US": "Active"
        }
      },
      "ceterms:agentType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:framework": "https://credreg.net/ctdl/terms/OrganizationType",
          "ceterms:frameworkName": {
            "en-US": "OrganizationType"
          },
          "ceterms:targetNode": "orgType:FourYear",
          "ceterms:targetNodeName": {
            "en-US": "Four-Year College"
          }
        }
      ],
      "ceterms:agentSectorType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:framework": "https://credreg.net/ctdl/terms/AgentSector",
          "ceterms:frameworkName": {
            "en-US": "AgentSector"
          },
          "ceterms:targetNode": "agentSector:PrivateNonProfit",
          "ceterms:targetNodeName": {
            "en-US": "Private Not-For-Profit"
          }
        }
      ],
      "ceterms:fein": "02-0274509",
      "ceterms:opeID": "002580",
      "ceterms:address": [
        {
          "@type": "ceterms:Place",
          "ceterms:name": {
            "en-US": "Southern New Hampshire University"
          },
          "ceterms:streetAddress": {
            "en-US": "2500 North River Road"
          },
          "ceterms:addressLocality": {
            "en-US": "Manchester"
          },
          "ceterms:addressRegion": {
            "en-US": "New Hampshire"
          },
          "ceterms:postalCode": "03106",
          "ceterms:addressCountry": {
            "en-US": "United States"
          },
          "ceterms:latitude": 43.041308699999988,
          "ceterms:longitude": -71.452199400000012
        }
      ]
    }
  ]
}

**Comment by mparsons-ce** [comment]
@excelsior have you had an opportunity to look into this? 
SNHU will want to start publishing to this community soon.

**Comment by excelsior** [comment]
@mparsons-ce I fixed this error, please try again.

In many places throughout the codebase, CER is treated as the only community, thus problems like this one happen. I'm curious why publishing into Navy worked well so far. Do you publish Navy documents differently?
