### ISSUE TITLE
ceterms:foundingDate' must be a valid RFC3339 date/time

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#50]
The organization founding date can be entered as one of:
- year only (yyyy)
- year and month (yyyy-mm)
- year, month, and day (yyyy-mm-dd)
Given the latter, a full date will not always be available. For this reason, the founding date should published in the ISO8601 format. The schema currently validates the property as RFC3399. 
We need to have a custom validation that uses the ISO8601 format

**Comment by coffeejunk** [comment]
In that case shouldn't the definition of `ceterms:foundingDate` be something like this:

```json
{
  "type": "object",
  "required": [
    "ceterms:foundingDate"
  ],
  "properties": {
    "ceterms:foundingDate": {
      "anyOf": [
        {
          "type": "string",
          "format": "date"
        },
        {
          "type": "string",
          "format": "date-time"
        }
      ]
    }
  }
}
```

[A quick test run:](https://gist.github.com/coffeejunk/9f0a6edc85ca8dc83d586fad44c5fed3)
```
{"ceterms:foundingDate":"2017"} valid? true
{"ceterms:foundingDate":"2017-03"} valid? true
{"ceterms:foundingDate":"2017-03-31"} valid? true
{"ceterms:foundingDate":"2017-03-31T01:37:59Z"} valid? true
{"ceterms:foundingDate":"20170331T013759Z"} valid? true
{"ceterms:foundingDate":"2017-03-31T01:37:59+00:00"} valid? true
```

**Comment by siuc-nate** [comment]
I did some more research on this - the schema we use for foundingDate doesn't specify ISO 8901, but it _does_ specify a range of xsd:DateTime (as do some other properties). I looked that up, and found this:
http://books.xmlschemata.org/relaxng/ch19-77049.html

xsd:DateTime is _based on_ ISO 8901, but with additional restrictions I wasn't aware of until just now - among them, _all_ of the parts of the date must be specified (which sounds identical to RFC3399, as far as I can tell).

The following is copied directly from the page linked above (emphasis added):

> Valid values for xsd:dateTime include: `2001-10-26T21:32:52`, `2001-10-26T21:32:52+02:00`, `2001-10-26T19:32:52Z`, `2001-10-26T19:32:52+00:00`, `-2001-10-26T21:32:52`, or `2001-10-26T21:32:52.12679`.
> 
> The following values are **invalid**: `2001-10-26` (all the parts must be specified), `2001-10-26T21:32` (all the parts must be specified), `2001-10-26T25:32:52+02:00` (the hours part—25—is out of range), or `01-10-26T21:32` (all the parts must be specified).

To me, this says that we **cannot** permit entry of partial dates (it is probably okay to assume a time of 00:00 on all dates).  So our options are either:
1) Revise the interface to only allow full dates
2) Change the range of ceterms:foundingDate to just be a string
3) Deprecate ceterms:foundingDate in favor of something like ceterms:foundingYear (founding month and founding day are probably not relevant in any realistic use case)

@stuartasutton @jkitchensSIUC please chime in on this.

**Comment by stuartasutton** [comment]
Nate, we should use xsd:date instead. You are correct that none of the properties currently with xsd:dateTime use the time aspect.

**Comment by leolara** [comment]
@cwd-mparsons @siuc-nate 

Here I think we should analyse the impendance between what JSON schema format="date", format="date-time" are and what xsd:dateTime and xsd:date mean in RDF world.

If they are different we will have to implement our own validator in the registry. You could put now:

```js
type="string", format="xsd:date" 
```

in the JSON schema. I believe the format will be ignored until we implement the custom format in the registry.

It would be very practical to find a Ruby library that validates exactly xsd:date, or at least an algorithm to do so based on ISO date formats.

**Comment by siuc-nate** [comment]
@leolara Since all we really need is the date, I believe we can use xsd:date in the RDF and format="date" in the validation - the two (as far as I can tell) conform to the same standards, so it should validate.

The main issue here is that in our interface we currently attempt to allow entry of a partial date (e.g., the year an organization was founded, leaving out the month and date).  This is something we cannot do if we are to follow our own schema (because both xsd:date and xsd:dateTime require a full date). Alternatively we can make "foundingDate" a string.  I outlined the options in my post above.

@stuartasutton Thanks, I agree.  But the main issue is the data we are entering - do you have a preference in regards to forcing entry of a full date vs using a string for foundingDate (or some other solution; perhaps a foundingYear property)?
I would also like input from @jkitchensSIUC

**Comment by jkitchensSIUC** [comment]
Founding dates range from just a year to a month/year to month/day/year.  Validation needs to allow all three of these examples.

**Comment by siuc-nate** [comment]
In that case, making foundingDate a string solves all of the problems without creating additional complications.

**Comment by leolara** [comment]
@siuc-nate @jkitchensSIUC @stuartasutton @cwd-mparsons 

Please note that making it just a string in JSON schema, will make valid any string.

If we want to validate the format you are describing we will have to implement a custom format validator. The good thing is that we can add that format to the JSON schema, and it will be ignored until we implement it.

So I would put, `"type"="string", "format"="ceterms:foundingDate"` for example, and at some point implement ceterms:foundingDate validation.

But, in my opinion and experience the most future proof solution would be to implement `foundingDate` as an object with fields for year, month, etc.

**Comment by siuc-nate** [comment]
This has been taken care of.
