### ISSUE TITLE
Staging: Receiving 401 Unauthorized errors attempting to publish

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#501]
@excelsior 
We have been unable to publish to the staging server. 
All attempts result in a  401 Unauthorized error. 

This has occurs if we attempt to register an organization (to enable publishing by the org).

**Comment by excelsior** [comment]
@mparsons-ce We restored a sandbox DB snapshot onto staging in order to run some tests. Hence you should use the sandbox auth token in order to perform those actions. We didn't know you were going to use staging again, thus didn't give you a heads up about the change. Sorry for the inconvenience.

**Comment by neaf** [comment]
@mparsons-ce We left copies of staging data and can switch back at any point.

Let's discuss the overall topic of test environments on our weekly meetings to come up with a strategy that will allow us to avoid stepping on each other's parade. :)

**Comment by neaf** [comment]
@mparsons-ce I restored staging to the old state. Let me know if there are any issues.

**Comment by mparsons-ce** [comment]
Thank you.
