### ISSUE TITLE
Handling Primary and Secondary Records in the Registry

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/CredentialRegistry#502]
@science @edgarf @neaf @siuc-nate @mparsons-ce @philbarker @stuartasutton 

The CTDL team including @philbarker @stuartasutton, Mike, Nate, and me just concluded a  Credential Approval Lists Task Group and development of this [CAL proposal ] for new CTDL terms (https://docs.google.com/document/d/1xmEm7llzPaRuBmBM9U16oS4MA_1vJvE9vfeuTXULYLk/edit#heading=h.xz0tuq9but9n).  We're in the process now of additional vetting this proposal with several state agency partners who will publish Lists (i.e. Collections) using the model, CTDL terms, and Registry solution proposed in the above linked proposa.  To support the primary use cases, listed in the proposal, we're proposing that the Registry  support flagging primary and secondary records, the Registry envelope will include either  "from_primary_source": false or "from_primary_source": true and potentially a "in_context_of"  which includes the URI to the related collection.  

See the [real world Registry envelope data examples] (https://credreg.net/page/credentialapprovallists) 
and [additional examples of record envelopes](https://drive.google.com/file/d/1NBCLl2UejwBPru0ZHKHUUiB7MIaqWLJW/view?usp=sharing) in the Registry both created by Nate.    

You can see this is an indepth CTDL proposal that overlaps with a new Registry envelope requirements that we need to discuss this week during our weekly meeting rather than trying to do explain more here:)

**Comment by neaf** [comment]
Well, in the end it's your decision.

I'd stay closer to my initial recommendation which is to come up with a namespace that represents a category of attributes which this one will be member of.

```
{
		"envelope_community": "ce_registry",
		"envelope_id": "8fdd0f64-da1f-4c2a-abed-d13691ebe122",
		"envelope_ceterms_ctid": "ce-8797e9c3-0847-4282-840c-c7ce04a5afac",
		"envelope_ctdl_type": "ceterms:Course",
		"envelope_type": "resource_data",
		"envelope_version": "1.0.0",
		"resource": "...",
               [...]
               "publishing_context": {
                              "source_type": "primary" | "secondary"
               }
}
```

Also note using strings instead of boolean. The type of source, while currently has only two values we can think of, isn't really strictly binary state and thus, I believe, is better represented that way.

Also it might be worth considering even a bit different approach like `document_source: "internal" | "external"`.

In the end, it doesn't really matter to us on technical level. I'm just trying to nudge you a bit into coming up with the best describing terminology you can think of within your business domain. We'll need to stick to that vocabulary for years to come.

**Comment by philbarker** [comment]
Any "container object" would be a distraction in RDF terms, but could be ignored by using [`@nest`](https://www.w3.org/TR/json-ld11/#nested-properties) in the context, so long as it is merely a convenient way of grouping properties and has no semantic significance.

**Comment by neaf** [comment]
Allow searching/fitlering by `source_type`

**Comment by neaf** [comment]
Apply the information to every resource in the envelope.

**Comment by neaf** [comment]
@siuc-nate @mparsons-ce @jeannekitchens 

Hello! Naming and stuff part 2. ;)

I need a one sentence description of the `resource_publish_type` field.

We provide those to all envelope attributes: https://github.com/CredentialEngine/CredentialRegistry/blob/master/app/api/entities/envelope.rb#L16

**Comment by siuc-nate** [comment]
Do you need one for the values too or do the descriptions of the values need to be incorporated into the description of the property?

**Comment by neaf** [comment]
Just the field description is fine. It's not suuuuper important here but that would help me to finally understand what we're actually determining here.

**Comment by neaf** [comment]
@siuc-nate 

Changes deployed to **sandbox**.

Publishing action now accepts `resource_publish_type: "primary" | "secondary"` attribute.

You can now search for this attribute with the following:
```
{
  "@type": "ceasn:CompetencyFramework",
  "search:resourcePublishType": "primary"
}
```

The attribute will be returned with envelopes as well as with metadata in descriptions set query.

**Comment by mparsons-ce** [comment]
@neaf 
Should this filter be available for the full text search? I tried:
https://sandbox.credentialengineregistry.org/search?resource_publish_type=primary
and get:
![image](https://user-images.githubusercontent.com/58825866/159059841-2386d24c-2405-4e37-a820-7ccbabe35ad3.png)

**Comment by neaf** [comment]
@mparsons-ce Oh, no. I added it only to CTDL search.

Do we need it somewhere else?

**Comment by mparsons-ce** [comment]
@neaf We still use the full text search for downloading data. I checked and saw that all of the other envelope properties are available to the FT search. 
So yes it would be useful to enable filtering by resource_publish_type.

**Comment by mparsons-ce** [comment]
@neaf 
I tried to publish a credential and included the parameter: resource_publish_type=primary (as shown below). 

https://sandbox.credentialengineregistry.org/resources/organizations/ce-f739fb95-88e8-45a8-84f3-d1df5fbaaacd/documents?skip_validation=true&published_by=ce-a4041983-b1ae-4ad4-a43d-284a5b4b2d73&resource_publish_type=primary

However, the envelope was not updated to include **resource_publish_type**.

https://sandbox.credentialengineregistry.org/envelopes/ce-284c0e7c-6926-4900-b91b-52c76422882a

**Comment by neaf** [comment]
@mparsons-ce I'm sorry. I restored `master` branch to sandbox for some testing and forgot this one is not yet merged.

Now you should be able to publish as well as do a full text search specifying `resource_publish_type.

**Comment by neaf** [comment]
@neaf Pending production deploy

**Comment by mparsons-ce** [comment]
I did a publish as a secondary resource
https://sandbox.credentialengineregistry.org/envelopes/ce-284c0e7c-6926-4900-b91b-52c76422882a
I was able to search by resource_publish_type =secondary and find the resource. 

However. When I get the envelope directly, the envelope shows **resource_publish_type** just above the node_headers.

![image](https://user-images.githubusercontent.com/58825866/163235747-08ef9660-de6a-49eb-becb-757df65a1ba0.png)

In the search results I don't see resource_publish_type . Instead I see **envelope_resource_publish_type** .

![image](https://user-images.githubusercontent.com/58825866/163236470-68f0c221-ce31-4827-bf75-2f778138c5a7.png)

**Comment by neaf** [comment]
@mparsons-ce I renamed the `envelope_resource_publish_type` to `resource_publish_type`.
