### ISSUE TITLE
Added a new Collection  to the sandbox and 'changed' was set to false

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#508]
Sandbox
- Added collection
- checked envelope and saw that the property: **changed** had a value of false (being new, it should be true)

![image](https://user-images.githubusercontent.com/58825866/152469253-59534baf-c995-4467-bc17-3c9bc230a9bb.png)

**Comment by excelsior** [comment]
@mparsons-ce Was this a one-off issue or do you experience this behavior consistently?

**Comment by mparsons-ce** [comment]
I just republished a collection with an update:
https://sandbox.credentialengineregistry.org/envelopes/ce-ed72a572-3069-46d0-aa05-ec85ae875c9c
![image](https://user-images.githubusercontent.com/58825866/155620712-2e10c3d8-239b-423c-9f98-ab87aed3c8d9.png)

There was an update and changed is still false. However the value in the envelope returned after publishing is true.

Actually what would be the purpose of **changed** when displayed on the envelope?
By definition, the envelope is only updated when the new data differs from the existing data.

**Comment by mparsons-ce** [comment]
@neaf Yes, it makes sense to remove the flag.

**Comment by neaf** [comment]
@mparsons-ce Flag removed on sandbox and production.

Again, if we need it let's put another item on the roadmap. This issue I'd treat as ready to close.
