### ISSUE TITLE
Clear out old data from the credential registry

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#51]
@leolara 
Registry entries prior to this week (that use the old Ctdl schema), are obsolete. 
Can all of the old entries be purged from the cer community?
I would then reset all the credential Ids in our system, and start publishing with only the new schema.

**Comment by coffeejunk** [comment]
There is a task for this: `rake envelopes:clear_community\['ce_registry'\]`. I can execute this on the server if you wish?

**Comment by cwd-mparsons** [comment]
@coffeejunk
Yes, please clear out the ce_registry community

**Comment by coffeejunk** [comment]
http://lr-staging.learningtapestry.com/api/ce-registry/envelopes is cleared.
