### ISSUE TITLE
Timeout trying to query

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#512]
This query:
```
{
	"@type": "ceasn:Competency",
	"ceterms:occupationType": "search:anyValue"
}
```
Resulted in a timeout:
![image](https://user-images.githubusercontent.com/21346519/153447320-0a6a41fd-ade0-4c99-8035-872e35d71803.png)

**Comment by siuc-nate** [comment]
We tested this briefly today and were able to confirm that it is still an issue.  It didn't time out this time, but it did take quite a while:
![image](https://user-images.githubusercontent.com/21346519/155576655-e0930ad4-b143-406b-bb08-05b522990dce.png)

**Comment by neaf** [comment]
@siuc-nate I deployed a fix to sandbox and production that optimizes how we handle querying on referenced resources.

This reduced execution time of the query you pasted from ~2.5minutes to 1.5seconds. Hence, I believe this change should positively affect the general performance of both our environments.

If you encounter other slow queries (not necessarily that extreme), let me know, I'll investigate and maybe find more things we can improve.

Cheers!

**Comment by siuc-nate** [comment]
Very nice! Thank you.

**Comment by mparsons-ce** [comment]
@neaf 
On the sandbox were are currently getting: 
**This website is under heavy load**

This will occur just getting a resource or envelope.

**Comment by neaf** [comment]
For now I just decreased the process count on sandbox machine. It might keep it in check better. If we still run out of memory I'll upgrade the machine itself.

Let's keep it open.

**Comment by neaf** [comment]
@mparsons-ce I see it's down again.

Are you doing something that involves massive amount of requests now?

**Comment by mparsons-ce** [comment]
@neaf I have not been running anything. Some of partners may have been trying to publish. I had heard from one who not able to publish due to errors.

**Comment by neaf** [comment]
@mparsons-ce There's something super weird happening and I'm trying to figure it out.

We have to consider sandbox down even if it goes back up for a bit from time to time. Please notify partners so they don't get frustrated trying to use it.

I'll post an update before I finish today.

**Comment by neaf** [comment]
@mparsons-ce I think we're good.

The Neptune instance stopped responding. That, combined with the fact that we had disabled timeout for Neptune calls made our workers wait endlessly and requests started pilling up.

Tomorrow I'll try to educate myself more on Neptune and add a timeout and reporting so we don't block our server workers.

**Comment by mparsons-ce** [comment]
@neaf 
Thank you.

**Comment by siuc-nate** [comment]
This query is working now. Thanks.
