### ISSUE TITLE
Is the "OLD" Json schema validation still operational, specifically in the sandbox?

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#515]
re: ceterms:subjectWebpage
In the early days the property ceterms:subjectWebpage was defined as a single string in many of our top level objects. 
In those same early days a JSON validation scheme had been defined for the registry objects. We eventually stopped using the JSON Validation process, instead having the publishing API be responsible for validation. 

Recently the new class **Collection** was defined with ceterms:subjectWebpage as a **List of strings**. 
Whenever I try to publish a collection with a subjectWebpage, I get errors like the following:

` Unexpected character encountered while parsing value: [. Path 'ceterms:subjectWebpage', line 116, position 29.`

The position references the  bracket where perhaps a quote was expected.
There was another error (which I didn't capture) that did specifically reference a JSON validation error. 
So I was wondering some vestige of the JSON schema validation is still operational.

**Comment by excelsior** [comment]
@mparsons-ce The old validation will be enforced unless you provide the `skip_validation` parameter. But I assume you always specify it when publishing things? Could you please share a sample payload which fails to get published?

**Comment by mparsons-ce** [comment]
@excelsior I found the issue was related to an intermediate process - closing.
