### ISSUE TITLE
Full text search exhibits odd behavior with partial matches

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#517]
If I want to find a resource, such as [this framework](https://credentialengineregistry.org/resources/ce-e49dcaf3-5885-46e8-bd3c-cdbe765a8f1b) ("Education Design Lab 21st Century Skills"), the search exhibits some odd behavior when it comes to partial field matches.

For example, I find it if I search for "Education Design Lab":
![image](https://user-images.githubusercontent.com/21346519/153934428-9dcff7f2-0842-4062-864a-e5928bd3201a.png)

---

But not for "Education Design La" or "Education Design L":
![image](https://user-images.githubusercontent.com/21346519/153934468-37f21ac1-250a-43bd-bef5-8f1ef39cbc7a.png)
![image](https://user-images.githubusercontent.com/21346519/153934498-3264de61-1116-4a40-b50f-69421273fc6a.png)

---

But I do find it for "Education Design"
![image](https://user-images.githubusercontent.com/21346519/153934535-cc1c92f0-097c-465f-9e88-59144091d2d2.png)

---

I can also find it via "Education Design Lab 21st Century Skills" and "Education Design Lab 21st Century Skill":
![image](https://user-images.githubusercontent.com/21346519/153934633-ead18b96-75f3-4c9e-b6f5-3067270efb45.png)

---

But not via "Education Design Lab 21st Century Skil", "Education Design Lab 21st Century Ski", or "Education Design Lab 21st Century Sk":
![image](https://user-images.githubusercontent.com/21346519/153934689-83569fa6-d696-4658-89b6-99faef094e3d.png)

---

But I _do_ find it via "Education Design Lab 21st Century S" and "Education Design Lab 21st Century":
![image](https://user-images.githubusercontent.com/21346519/153934797-0a5c3970-ef54-44df-aaf9-bec4785656b7.png)

---

But not via "Education Design Lab 21st Centur":
![image](https://user-images.githubusercontent.com/21346519/153934970-d60d2d65-d3c2-42de-ae23-56acd067602a.png)

---

This is kind of odd.  I think we had discussed tokenizing strings using groups of every 3 characters or so, at one point. Is it possible that that has something to do with it?  It isn't a big priority for now, but it's something to look into when time allows.

**Comment by edgarf** [comment]
Thanks @siuc-nate , adding to the list for @neaf for when he comes back

**Comment by neaf** [comment]
@siuc-nate 

I deployed an update to sandbox which does two things:

1. Accepts searched word as prefixes.  `Design La` should return results for `Design Lab` and `Design Land`. It **will not** accept words as suffixes, meaning: `ation` won't match `education`.
2. Returns results that don't contain all of the searched words.

The second part makes it behave more like other search engines we know. Searching for `Design Lab` will return results with `Design Principles`, `Chemistry Labolatory` and `Designer Land`. In such case, unless different sort was explicitly requested, the last item should appear first as it contains both of search keywords. Play around with it and let me know if that's something we want to keep.

At some point we might find the search speed to be unsatisfactory. Currently we're generating a datatype postgres uses for the search on the fly while querying. Having it generated and stored on record update would be much better option and that will be a first thing to do once we encounter any trouble.

**Comment by neaf** [comment]
@siuc-nate I went ahead and deployed it to production. Please let me know if the behavior described above is ok.

If so, the issue is ready to be closed.

**Comment by siuc-nate** [comment]
Thanks, but I think we're not quite there yet:
![image](https://user-images.githubusercontent.com/21346519/156210810-a93f075a-674f-48cb-97c1-d390bc81db74.png)

**Comment by neaf** [comment]
@siuc-nate Ohh, sorry. I merge in the changes but missed final production deployment among other things.

It should be ok now.

**Comment by siuc-nate** [comment]
Thanks - it appears to be working now.
