### ISSUE TITLE
re: Purge ALL. Currently the only option is published_by. We also need an option for owned_by.

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#518]
We have a scenario where Florida as a third party publisher, published over 5000 credentials to the sandbox. 
Now they want to purge all of the credentials for just one of their organizations (Florida State University). 
I cannot use the Purge all since the published _by is Florida and the owned_by is FSU. 

We would like the option to use either published_by or owned_by.

**Comment by excelsior** [comment]
@mparsons-ce The bulk purge API has been extended to support the `owned_by` filter. You can even use both `owned_by` and `published_by` parameters, at least one of the two are required.

**Comment by mparsons-ce** [comment]
@excelsior Thank you. I have confirmed the new feature.
