### ISSUE TITLE
Description sets for Collections

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#519]
We need to enable the description sets for the ceterms:Collection class.  Specifically, we need to be able to get the data that references inwards to the Collection (e.g. credentials that point to it).  The collection's data contains the outgoing connections, so we don't need to (manually) generate description set data for that.

This would also include updating the description sets for credentials, competencies, etc., that are members of a collection, to show the connection back to that collection.

Is this something that can be generated given current processes or do I need to set this up manually?

**Comment by jeannekitchens** [comment]
@siuc-nate @mparsons-ce is publishing two collections now that need to show the credentials and LOs referencing the WGU Collection.  Needs to show correctly today as soon as possible.

**Comment by siuc-nate** [comment]
Why was this closed?

**Comment by excelsior** [comment]
@siuc-nate  We don't have any mappings for the `ceterms:Collection` class. In order to generate the description sets, we need to update the config first. Could you update the [spreadsheet](https://docs.google.com/spreadsheets/d/1VNgJ7qu_zydCB3UQMzEuHbYKczr_Q9nkRRxzoUWYLuk/edit#gid=0) with the new mappings?

**Comment by siuc-nate** [comment]
Do you still need the SPARQL portion of the data, or will the path part be sufficient?

**Comment by excelsior** [comment]
@siuc-nate I do since we still rely on the SPARQL data when pre-calculating description sets.

**Comment by siuc-nate** [comment]
I have updated the sheet: https://docs.google.com/spreadsheets/d/1VNgJ7qu_zydCB3UQMzEuHbYKczr_Q9nkRRxzoUWYLuk/edit#gid=0

The new rows start on row 382.

It's been a long time since I've written SPARQL, so please double-check it to make sure it makes sense and meshes with the intent of the Path column.

By the way, there are some expansions to groups of classes brought about by CTDL changes that have happened since the last time we made updates to the description set sheet.  These changes apply across the board, so they would likely affect some existing description set queries. Namely:
- ceterms:Agent also includes ceterms:Organization, ceterms:CredentialOrganization, and ceterms:QACredentialOrganization (I don't think we had ceterms:Organization last time this came up)
- ceterms:LearningOpportunityProfile also includes ceterms:Course and ceterms:LearningProgram

Should those be made into a separate github issue?

**Comment by siuc-nate** [comment]
I would need to go back and add the stuff from the last two bullet points to the spreadsheet if we wanted to do that. Or is that something that can be programmatically done?

**Comment by siuc-nate** [comment]
I have updated the spreadsheet. It seems 49 rows throughout it were affected. Rows where the SPARQL used to end with:
```?target a ceterms:LearningOpportunityProfile .```
Now end with:
```?target a ?learningType . VALUES ?learningType { ceterms:LearningOpportunityProfile ceterms:Course ceterms:LearningProgram } .```
