### ISSUE TITLE
Inconsistent sort order behavior

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#520]
These two queries return results in a different order even though the CTDL part of the query, and the `order_by` parameter, are the same:

```
https://credentialengineregistry.org/ce-registry/ctdl?skip=0&take=5&order_by=^search:recordUpdated
```
![image](https://user-images.githubusercontent.com/21346519/155169182-3fbed0f6-d489-4b50-acd8-614122dc8a86.png)

```
https://credentialengineregistry.org/ce-registry/ctdl?skip=0&take=20&include_description_sets=1&include_description_set_resources=1&per_branch_limit=10&include_results_metadata=1&order_by=^search:recordUpdated
```
![image](https://user-images.githubusercontent.com/21346519/155169271-0a3d0d8c-95cf-4339-8dd6-1c3377f64f33.png)

-----

After trying different combinations of parameters, the difference seems to be a bug with the `take` parameter. Using different numbers for that yields a different result set for the first few numbers after 1:

`take=1` yields this:
![image](https://user-images.githubusercontent.com/21346519/155170027-e254b634-6b8c-4a05-93f9-af09c19279cc.png)

`take=2` and `take=3` yield this result:
![image](https://user-images.githubusercontent.com/21346519/155170285-24862e30-962e-44a7-b8a1-5a562671991e.png)
![image](https://user-images.githubusercontent.com/21346519/155170332-1448757d-3910-4dd5-b910-1e89b9a4d65e.png)

`take=4` and `take=5` yield this result:
![image](https://user-images.githubusercontent.com/21346519/155170549-e487942a-b00b-416a-b221-4d9020706f52.png)
![image](https://user-images.githubusercontent.com/21346519/155170590-fef4e30a-7340-4adb-b62d-f16f57b7d1ca.png)

`take=6` through `take=13` yield this result:
![image](https://user-images.githubusercontent.com/21346519/155170685-764c6b9a-8ab7-4bf8-8e95-fa7bb122cfd3.png)
![image](https://user-images.githubusercontent.com/21346519/155170741-868e2593-d4fe-4bf5-b2d1-4b3538aad029.png)
![image](https://user-images.githubusercontent.com/21346519/155170830-e48261e1-b45e-4e43-95be-5e75607fd187.png)
![image](https://user-images.githubusercontent.com/21346519/155171137-65d8e7b7-6b48-4ae7-97c0-9ec23e276555.png)

`take=14` through `take=42` yield this result:
![image](https://user-images.githubusercontent.com/21346519/155171322-818d4851-cfd1-44eb-8240-e57348e22d18.png)
![image](https://user-images.githubusercontent.com/21346519/155171520-0755aacb-cea7-4e7b-8f48-5876f9d95d6f.png)

`take=43` yields this:
![image](https://user-images.githubusercontent.com/21346519/155171610-b21b6bde-242a-4514-a032-e21249bff184.png)

And so on.  It seems like the threshold changes exponentially or something. Very odd.

-----

The `skip` parameter seems to play into it as well, up to the thresholds described above.  For instance:
`skip=1` or `skip=2` and `take=40` yields the "Knowledge" framework:
![image](https://user-images.githubusercontent.com/21346519/155172339-344ce9d0-ffef-445f-aecf-366f936afcd6.png)
![image](https://user-images.githubusercontent.com/21346519/155172390-388f5e97-d2af-4378-8d6d-71f89ce4b90f.png)

But `skip=3` pushes the results over the "42" threshold described above, and yields the "Basic Skills" framework:
![image](https://user-images.githubusercontent.com/21346519/155172458-686802e6-0b38-47d8-b704-209738957fa2.png)

Any idea what might be causing this?

**Comment by edgarf** [comment]
@siuc-nate we are on it.

**Comment by neaf** [comment]
@siuc-nate I believe I mentioned it on last meeting but to be sure:

This is fixed on production and issue should be ready to close.

**Comment by siuc-nate** [comment]
Great. Thank you.
