### ISSUE TITLE
Optimize bulk purge requests

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#526]
I am not able to do searches or even gets of resources/envelopes, etc.

**Comment by edgarf** [comment]
We see that the sandbox was not responsive for 20 minutes around that time, @neaf will investigate the logs to see what made it that way.

**Comment by neaf** [comment]
I looked wherever I could and to my astonishment couldn't really find anything. The requests from Pingdom, our monitoring tool seemed to be coming over that period and the server returned proper responses. I don't see any slow weird requests in our QueryLog.

As I noted here: https://github.com/CredentialEngine/CredentialRegistry/issues/513#issuecomment-1055696269

I've deployed a fix that should significantly reduce load on our machines. I've also setup some some additional host machine metrics gathering in CloudWatch so we can see better if, for instance, we're running out of memory. I'll also setup slow queries logging on our Postgres database.

I'm going to close this issue and more closely monitor stability of both our environments.

**Comment by mparsons-ce** [comment]
@neaf 
I reopened this issue just to add some additional information, that may or may not be helpful.
I was doing some Purge All requests.
I had done a request for DataSetProfiles earlier (about 16000 records) and then issue a request to purge organizations published by ce-89bd0d16-6492-4ae1-8059-deabc3d89c15. 
I got the following error.


> Error: PurgeAll failed for: Organization Publisher: 'Credential Engine Administration - Sandbox', CTID: 'ce-89bd0d16-6492-4ae1-8059-deabc3d89c15', type: 'organization', 
> reason:  This website is under heavy load (queue full) 
> We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

**The Purge All process probably had not finished, which could be a factor.**

I think I may have done some Purge Alls the last time there was this time out issue!

**Comment by neaf** [comment]
Thank you. The purge all lead is what we needed. I don't immediately see why but it seems like this action clogs our memory, makes the machine fallback into SWAP which basically brings it to a halt.

That's definitely something that needs to be a background job instead of happening directly in the HTTP request.

**Comment by neaf** [comment]
@mparsons-ce It was a long investigation to arrive at very little changes but on my local machine I cut down the bulk purge request from 19 hours to 1 minute.

It's still a long running thing to do directly in HTTP request, however, until it actually causes some trouble I'd rather avoid the complexity of making it a background job. It is an administrative task so should be fine.

If it works fine for you next time, please close the issue.

Cheers!

**Comment by mparsons-ce** [comment]
I don't have any large purges planned in the near future. 
I will close this issue for now.

**Comment by mparsons-ce** [comment]
@neaf 
FYI: I did a few purges today of 3000 credentials and 3900 learning opps, and both took only a few seconds. 
Thanks
