### ISSUE TITLE
Enable searching for "no value"

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#539]
There are occasionally cases where it would be useful to find all items for a given query where there is no value for a given property (or the value is empty).  It would be nice to be able to support this in the search API (likely via a custom property like `search:noValue` as the opposite of `search:anyValue`).

This would return cases where:
- There is no value for the specified property (i.e. the property isn't there in the JSON even if it's there in the schema for a given class)
- There is a value, but it is empty (e.g. empty array, empty string)
- There is a value, but it is `null` (I don't think we allow this anyway?)

For boolean properties, it would only match if there is no value assigned (both `true` and `false` would be considered having a value).

For numeric properties, it's a little fuzzier. `0` may be a valid value in _some_ cases, but it is often also a default value that may be published (unintentionally?) in others.  We should probably only match `search:noValue` on cases where there is no value assigned, and query separately for cases where `0` is assigned if we want to capture those, too.

Example usage:
```
{
  "@type": "ceterms:License",
  "ceterms:financialAssistance": "search:noValue"
}
```
Would return all of the licenses that have no financial assistance.

This isn't an urgent need, but if it's something that would be reasonably quick to implement, we do run into cases now and then where it would be useful.

I thought we might have had something like this at one point, but if we did, I can't find the documentation for it.

**Comment by neaf** [comment]
@siuc-nate I've merged in @excelsior 's changes to sandbox.

Can you confirm it works to your liking so we can deploy to production?

**Comment by neaf** [comment]
Deployed to production.

Should be ready to close.
