### ISSUE TITLE
Competency framework indexing

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#549]
Suddenly, we are having trouble finding this framework in the search index:
https://credentialengineregistry.org/resources/ce-e49dcaf3-5885-46e8-bd3c-cdbe765a8f1b

Looking for an exact match on the name ("Education Design Lab 21st Century Skills") yields the result:
![image](https://user-images.githubusercontent.com/21346519/166475945-8ca48f35-f6e8-4148-9300-2b51bf779530.png)

But the query used by the Finder does not, at least not as the first result:
```
{
    "@type": "ceasn:CompetencyFramework",
    "search:termGroup": {
        "search:operator": "search:orTerms",
        "ceasn:creator": {
            "ceterms:name": "education design lab 21st century skills",
            "ceterms:subjectWebpage": "education design lab 21st century skills",
            "search:operator": "search:orTerms"
        },
        "ceasn:publisher": {
            "ceterms:name": "education design lab 21st century skills",
            "ceterms:subjectWebpage": "education design lab 21st century skills",
            "search:operator": "search:orTerms"
        },
        "^ceasn:isPartOf": {
            "ceasn:competencyLabel": "education design lab 21st century skills",
            "ceasn:competencyText": "education design lab 21st century skills",
            "ceasn:comment": "education design lab 21st century skills",
            "ceasn:conceptKeyword": "education design lab 21st century skills",
            "search:operator": "search:orTerms"
        },
        "ceasn:name": "education design lab 21st century skills",
        "ceasn:description": "education design lab 21st century skills",
        "ceasn:source": "education design lab 21st century skills",
        "ceasn:conceptKeyword": "education design lab 21st century skills"
    }
}
```
![image](https://user-images.githubusercontent.com/21346519/166476504-1debe7df-ba58-489e-805e-06aeed8e85bb.png)

It worked before. Did something change with the way frameworks are indexed?

**Comment by excelsior** [comment]
@siuc-nate There was a bug in relevancy calculation. When multiple properties are queried against using full-text search, we calculate a rank for each of them, then order the results by the combined rank. However, if one of the properties is `NULL`, its rank will be `NULL` as well, causing the combined rank to be `NULL`, too. And those `NULL`s mess up the order of the results.

I fixed it by coalescing such ranks to zero.

**Comment by excelsior** [comment]
BTW, this isn't relevant to the issue, but `ceasn:source` is a reference, not a string property. The  `"ceasn:source": "education design lab 21st century skills"` condition above doesn't make sense.

**Comment by siuc-nate** [comment]
Thanks, looks like it's fixed now.

As for source, I think there was a case at some point where we wanted to be able to find frameworks based on their source URL(s) (maybe just the domains, I don't remember).  So the search checks against that property as well as the others just in case.
