### ISSUE TITLE
Data missing from description set

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#552]
For this framework: https://credentialengineregistry.org/resources/ce-1214d94f-2c1e-48f6-8d66-f252f5d014e8

The connection from this assessment is missing:
https://credentialengineregistry.org/resources/ce-f0866bed-9b6c-45d6-9def-8f405a630ff5

The connection to the framework is also missing from the description set for the assessment.

It looks like the indexer for the description sets might have fallen over again.

**Comment by excelsior** [comment]
@siuc-nate I tried re-calculating both envelopes' description sets, but it didn't seem to help. There must be a deeper problem, I'll let you know once I find it.

**Comment by siuc-nate** [comment]
I found another case.  This one is in the sandbox.

This learning opportunity: https://sandbox.credentialengineregistry.org/ce-registry/resources/ce-d49ec29a-6960-4898-b9fa-3c9516552986
teaches this competency (among others): https://sandbox.credentialengineregistry.org/resources/ce-e7c31ca7-b951-40db-b46d-35d24fb19c2a

However, neither one appears in the description set for the other:
![image](https://user-images.githubusercontent.com/21346519/169575850-0b555fbd-54c2-47ae-a728-f76577ecd9f7.png)
![image](https://user-images.githubusercontent.com/21346519/169576091-793ae6cb-01ce-4553-bf69-c0ec1c745295.png)

**Comment by siuc-nate** [comment]
Another case, also from sandbox. This one is a little different.
This framework: https://sandbox.credentialengineregistry.org/resources/ce-6c2306e1-e39c-4a34-aacd-84a83eef4e17
does not show up at all in the data for its own description set, but does list its competencies in the related resources (probably because of the `include_graph_data` flag):
![image](https://user-images.githubusercontent.com/21346519/169578057-493adea7-b648-474e-85d1-0749f7b51e31.png)

**Comment by excelsior** [comment]
@siuc-nate I'm going to rebuild both indices on both servers over the weekend. That might take some time, because the new description set generator doesn't support bulk pre-calculation yet.

**Comment by excelsior** [comment]
@siuc-nate I think the problem is caused by the [config](https://docs.google.com/spreadsheets/d/1VNgJ7qu_zydCB3UQMzEuHbYKczr_Q9nkRRxzoUWYLuk/edit#gid=0) we're using.

The `ce-f0866bed-9b6c-45d6-9def-8f405a630ff5` assessment profile assesses the `ce-1214d94f-2c1e-48f6-8d66-f252f5d014e8` competency framework (via a bunch of credential alignment objects). But the above config doesn't have any paths that start with `> ceterms:assesses`.

On sandbox, there's the same problem: There are no paths starting with `> ceterms:teaches`.

The description set profile [page](https://credreg.net/page/descriptionsetprofiles) does have such paths, but we haven't integrated those mappings into the app yet.

**Comment by siuc-nate** [comment]
I do see that the file is missing paths that start with an assessment or learning opportunity and end in a competency (strange, I'm not sure how we never noticed those were missing, given how long those have been in place).  But there are some paths with the reverse (namely rows 598 and 599), so the assessment/learning opportunity should at least be appearing in the competency's description set.
![image](https://user-images.githubusercontent.com/21346519/169842204-3551f51e-b0c2-40f9-92f5-05fe306b3d71.png)

I can add the paths from the assessment/learning opportunity to the competency if needed.

**Comment by siuc-nate** [comment]
I have added these rows:
![image](https://user-images.githubusercontent.com/21346519/171653223-e18271c7-7dd4-4d42-b967-12fd4492ab11.png)

These rows were already present in the sheet, and I think were related to the original issue:
![image](https://user-images.githubusercontent.com/21346519/171653514-542acdae-f207-4701-bcdb-f76cbc9cfbdd.png)

The sooner we can upgrade to the auto-generated paths, the better, I think.

**Comment by excelsior** [comment]
The config has been upgraded and deployed to production. The description sets have been re-calculated with the latest config.

**Comment by mparsons-ce** [comment]
deployed to production
