### ISSUE TITLE
PostgreSQL search index issue

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#554]
This morning, this query:
```
{
	"@type": "qdata:DataSetProfile",
	"schema:about": {
		"ceterms:ctid": "ce-15990a06-b328-4051-bfaf-0c319b551062"
	}
}
```
Would correctly return this result:
https://credentialengineregistry.org/resources/ce-b2d2664b-aa5f-4502-96ef-c7d2557d303e

However, a few hours later (now), when I run the query, that result no longer shows.
![image](https://user-images.githubusercontent.com/21346519/170316681-6467c943-8102-4b20-a184-bb6f91040e8c.png)

Is something going on with the PostgreSQL search index?

Note that this result does still show with the old index:
![image](https://user-images.githubusercontent.com/21346519/170316800-3c081338-a5ae-42e3-bfcb-d215375b1b38.png)

**Comment by excelsior** [comment]
@siuc-nate When an existing envelope gets republished, its resources get removed from the index immediately and new ones get created later. The problem, is this happens asynchronously, and also envolves ingesting data into Neptune and pre-calculating description sets, so the queue of those jobs get processed slowly. Thus, when a lot of envelopes get published, their resources appear in the index with a delay.

I fixed a couple of bugs slowing down the indexing process. And of course once we get rid of Neptune, it'll naturally become faster.

**Comment by siuc-nate** [comment]
Is there a way to avoid removing the old one until just before the new one is inserted, so that things don't appear to vanish for a while?

**Comment by excelsior** [comment]
@siuc-nate The resource extraction improvement has been deployed on sandbox. Let me know if you notice any problems. If everything's fine, I'll promote these changes to production.

**Comment by mparsons-ce** [comment]
Has been  deployed to production.
