### ISSUE TITLE
There is a trailing space on financialAssistanceType

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#565]
Alex noted that there are many records in the registry with trailing space on financialAssistanceType

Michael checked and found the trailing space in the Json property:
[JsonProperty(PropertyName = "ceterms:financial**AssistanceType "**)]
public List<CredentialAlignmentObject> FinancialAssistanceType { get; set; }

Michael corrected the issue and updated the API. 
Alex will create a process to remove the space from the database.

**Comment by siuc-nate** [comment]
This has been fixed.
