### ISSUE TITLE
Framework description set missing competencies

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#566]
This framework:
https://sandbox.credentialengineregistry.org/graph/ce-c958bc3e-27e3-44ea-8e9d-e487389345ee

had its description set generated:
![image](https://user-images.githubusercontent.com/21346519/178587310-1daf1af3-8a6c-4bcd-a2e5-bce2faff908b.png)

But, as you can see in the above screenshot, the connections to its competencies are missing.

**Comment by siuc-nate** [comment]
Strange.  How are those competencies in the `@graph` for that Framework?

**Comment by excelsior** [comment]
I believe the envelope was published that way.

**Comment by mparsons-ce** [comment]
@jeannekitchens You added this framework to sandbox CaSS: Home Energy Professional – Evaluation and Inspection
Was this exported from production and then imported into the sandbox?
It appears the competency URIs all had registry production URIs. 
In CaSS the Canonical URL shows as the production URI but the registry URL appears like it is correct. There may be a CaSS issue here. 

![image](https://user-images.githubusercontent.com/58825866/182883632-1c2d8aaa-75ec-46ba-a8ff-d9ae69909598.png)

**Comment by jeannekitchens** [comment]
@mparsons-ce imports of the DOL industry competency models were done directly from the JSON URIs provided to us.  It wouldn't have made sense to copy anything from sandbox to production.  Sneha finalized the uploads of all frameworks to production.

**Comment by mparsons-ce** [comment]
Closing the issue as it relates to CaSS not the registry
