### ISSUE TITLE
Description set missing for Collection

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#567]
I'm getting an empty array when looking for description set data for this Collection:
https://credentialengineregistry.org/graph/ce-d5726b12-7a7a-4001-a154-71e40dc18d14

![image](https://user-images.githubusercontent.com/21346519/178800636-8d0357f1-e756-4b48-b6d5-00cef0ead0af.png)

**Comment by excelsior** [comment]
@siuc-nate I re-indexed the envelope and re-calculated its description set.

**Comment by siuc-nate** [comment]
Thanks. Do you have any leads on what caused this?
