### ISSUE TITLE
Empty description sets for Competency Frameworks

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#569]
The following Competency Frameworks have no data in/for their description sets:
https://credentialengineregistry.org/resources/ce-fd3e874f-f1d3-4895-8c46-dfed04da9336
https://credentialengineregistry.org/resources/ce-f204c85c-1a3e-4ac7-8a3c-705e5833ac9d
https://credentialengineregistry.org/resources/ce-0ac2068b-55df-4b3c-9d21-1f77ac34c327
https://credentialengineregistry.org/resources/ce-0c780d22-2195-46e2-85ee-9acdffd67a2c
https://credentialengineregistry.org/resources/ce-cf0efb79-427d-424d-983f-a17fc7714db6
https://credentialengineregistry.org/resources/ce-d9b45ce9-6906-4b6e-a40a-5bee394b5d53
![image](https://user-images.githubusercontent.com/21346519/181101641-312ebe3c-5462-40e4-a364-d5e2f6ba01f4.png)

I believe @jeannekitchens plans to present some of these in a meeting in the near future. Any idea what caused the description sets to not be generated?

**Comment by excelsior** [comment]
@siuc-nate The only reason they failed to get indexed properly is their size: there are almost 1,000 resources in some of those envelopes. I pre-calculated their description sets in the console, and it took between 2 and 4 hours per each. Our background processor is better suited for small jobs, time-consuming operations like these may fail silently.

I haven't tested performance of our new, PG-based description set generator yet, but I expect it to be faster.

**Comment by siuc-nate** [comment]
These are working now, thanks
