### ISSUE TITLE
Exact Match searches are not strict enough

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#572]
While testing the exact match functionality as it applies to addresses, I encountered a number of false positive matches. For example, looking for credentials available in Indiana, I wanted to find records where the ceterms:addressRegion was "IN" (the official abbreviation for Indiana).  However, the matchType/exactMatch seems to not be getting applied, since I was also able to find results where the ceterms:addressRegion contained the text "in", but in "north carol**in**a".
![image](https://user-images.githubusercontent.com/21346519/181791170-1609f7bb-5596-4cfd-9635-63801adf9ad6.png)

The exact match should, in this case, only bring back results where ceterms:addressRegion is "IN" (case-insensitive, so "in" would also match).

**Comment by excelsior** [comment]
@siuc-nate I deployed a change to make it strict.

Just a heads up: it's not a bug, it was implemented this way intentionally. The thing about the full-text search is that it's fuzzy and at the same values like `in` are stopwords in certain dictionaries (they're too short and common and thus get ignored). So contrary to the FTS, the exact match type was meant to find exact substring occurrences.

Now that I made the above change, do you need the old behavior still supported? By introducing a `search:contains` match type or something like that.

**Comment by siuc-nate** [comment]
Thank you. It looks like it's working.

I wasn't aware of the nuance you described. I can see potential use for `search:contains`, so if that's something fairly easy to add, it sounds worthwhile. I don't have any pressing need for that, though, so it doesn't need to be a priority.  I appreciate the insight though.
