### ISSUE TITLE
Missing bnodes in graph data for description set

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#575]
I'm trying to get the description set data for this Collection and include its graph data, which includes a few bnodes:
https://sandbox.credentialengineregistry.org/ce-registry/graph/ce-3bc3d4a3-c2de-4c16-8d7b-caca771b12f4

The following request:
```
{
    "ctids": [
		"ce-3bc3d4a3-c2de-4c16-8d7b-caca771b12f4"
	],
	"include_resources": false,
	"include_graph_data": true,
	"per_branch_limit": 5,
	"include_results_metadata": true
}
```
Sent to the `https://sandbox.credentialengineregistry.org/description_sets` endpoint should include the bnodes from the Collection's `@graph`, but they are not returned in the response (in fact, the entire `description_set_resources` array property is missing):
![image](https://user-images.githubusercontent.com/21346519/182658196-5f2fac63-d30a-410e-b4fd-4d8d4551b74f.png)

If I set `include_resources` to true, I still don't get the bnodes in the response (the item in the `description_set_resources` array is the Organization that owns the Collection):
![image](https://user-images.githubusercontent.com/21346519/182658472-600b8871-6546-4e0c-a8f4-2be75cc0e5bd.png)

**Comment by excelsior** [comment]
@siuc-nate This bug has been resolved.

When fetching graph resources, we ignore the ones having the given CTIDs. But since bnodes don't have a CTID to begin with, this condition wasn't working correctly for them, made them filtered out, too.

**Comment by siuc-nate** [comment]
Thanks, this is working now.
