### ISSUE TITLE
Search API returning resources other than top-level resources

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#579]
The following query:
```
{
	"Query": {
		"ceterms:name": "Ivy Tech Community College"
	},
	"Skip": 0,
	"Take": 5
}
```
Returns results where the `@type` is something other than a top-level class (e.g. ceterms:Place, ceterms:ConditionProfile, etc).  This shouldn't be allowed.
![image](https://user-images.githubusercontent.com/21346519/184231561-23947fe0-e783-47b5-b11c-681f4df4a827.png)

A top-level class is any class that has a ceterms:ctid property.

**Comment by excelsior** [comment]
@siuc-nate I'm a little bit confused. Those resources get returned because they match the given condition. If I'm getting you right, we shouldn't apply the above condition to them. The question is, when _should_ we query non-top-level resources?

**Comment by siuc-nate** [comment]
Those objects are parts of resources; the search API is intended to return only complete/entire resources (basically anything whose class has a CTID property).  It may be a useful feature at some point to be able to return parts of resources, but it shouldn't be on by default.

**Comment by excelsior** [comment]
Just to be clear: bnodes shoudn't be returned in the response, but they still need to be queried (e.g. if a condition has a connection through/to them)?

**Comment by siuc-nate** [comment]
Correct, I'm talking only about the actual results that get returned.

**Comment by excelsior** [comment]
Thanks, it's an easy fix then. Both production and sandbox have been updated.

**Comment by siuc-nate** [comment]
Great, thanks.
