### ISSUE TITLE
"anyValue" query for CTID not working

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#581]
I stumbled across this one while trying to diagnose something else.  This query, strangely, returns 0 results:
![image](https://user-images.githubusercontent.com/21346519/186920326-d66797ed-64cb-4936-89e5-b6a4ef3e759e.png)

**Comment by excelsior** [comment]
@siuc-nate This bug has been fixed.

**Comment by siuc-nate** [comment]
Great, thanks.
