### ISSUE TITLE
Description set data missing for competency

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#583]
In the sandbox:

This competency is used for various forms of testing:
https://sandbox.credentialengineregistry.org/resources/ce-eef18dfb-d6ed-4f47-b290-501066fd0a19

It has several references to this competency:
https://sandbox.credentialengineregistry.org/resources/ce-7bfce2b5-7f84-4e60-bc57-416aae8d47e8

However, the description set for the second competency doesn't contain any references to the first competency. There should be several due to the reverse connections:
![image](https://user-images.githubusercontent.com/21346519/187330516-473a3129-0099-452e-8a39-50fc63ca67ae.png)

**Comment by excelsior** [comment]
@siuc-nate I reindexed both envelopes, now there's data returned. The former competency was published later than the latter, looks like the reverse connections not handled correctly in a scenario like this.

**Comment by siuc-nate** [comment]
Thanks. This is working now.
