### ISSUE TITLE
The Florida staging registry (FDEO) doesn't seem to be operational

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#585]
@science @excelsior @edgarf 
We thought the Florida staging registry (FDEO) was set up in June. 
I did some checks today and the community is not recognized.

![image](https://user-images.githubusercontent.com/58825866/188165965-5b471557-19d2-4ccd-b97c-4a228a9495a5.png)

![image](https://user-images.githubusercontent.com/58825866/188166811-41a96bab-3fc3-458a-888d-e28a27b93b0e.png)

The production schemas endpoint only shows the ce-registry 
https://credentialengineregistry.org/schemas/info
![image](https://user-images.githubusercontent.com/58825866/188166900-bffc2ea3-ce45-440b-bd1c-9a79a8c0e1c4.png)

We need this to be operational to prove to Florida that it is ready to use. Or I am missing something?

**Comment by excelsior** [comment]
@mparsons-ce I think there's a typo in the URLs you're trying, it's `FDOE`, not `FDEO`.

The issue with the available schemas is a different thing, though. I'll take a look and let you know.

**Comment by mparsons-ce** [comment]
I will check, I had a previous example via Postman that had worked.

**Comment by mparsons-ce** [comment]
Yes, just a matter of using the correct spelling and I can publish. 
re: schemas
I had compared the list the one shown from the sandbox and saw that the navy community was included. 
I then realized that snhupr was not in the list. 
Another DUH - we are not using the schemas anymore for JSON-LD validation.
Have a great day.
