### ISSUE TITLE
When publishing a large collection, the process can take a long time checking the existence of collection members. Can an internal process be developed to improve checks?

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#586]
@excelsior  We have a partner that is testing publishing a collection with 1700+ members. 
The API has a step to validate that each collection member ProxyFor property refers to an existing resource in the registry. 
The process for the latter takes over 6 minutes.  This partner has over 3000 members in production. 
Would it be more efficient if there was an internal registry endpoint for validating the existence of a resource, via the CTID?
Or perhaps a list of CTIDs?

**Comment by excelsior** [comment]
@mparsons-ce I added an endpoint for this: `POST /{community_name}/resources/check_existence`. It accepts an array of CTIDs (just like the search endpoint): `{ ctids: […] }` and returns an array of the CTIDs of not deleted resources from the given community (CER by default).

It's available on sandbox, documented here: https://sandbox.credentialengineregistry.org/swagger/index.html

Let me know if this solves your problem.

**Comment by mparsons-ce** [comment]
@excelsior 
Thank you, I tested the endpoint and works as needed. 
You can promote this change to staging and production.
