### ISSUE TITLE
Request to remove an organization returns message that has published resources but none found.

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#587]
@excelsior 
I have been trying to do some clean up of obsolete organizations from the sandbox. Every org that I have been trying returns a message that: 
{"errors":["Organization has published resources, can't be removed"]}
However I have checked, and these organizations don't seem to have published resources.

Example: ce-a8ec0ca9-3dad-488e-b83b-e1f47f501f2c
https://sandbox.credentialengineregistry.org/metadata/organizations/ce-a8ec0ca9-3dad-488e-b83b-e1f47f501f2c

There is no envelope:
https://sandbox.credentialengineregistry.org/ce-registry/envelopes/ce-a8ec0ca9-3dad-488e-b83b-e1f47f501f2c

A search by owned_by shows zero results:
https://sandbox.credentialengineregistry.org/ce-registry/search?per_page=50&owned_by=ce-a8ec0ca9-3dad-488e-b83b-e1f47f501f2c

**Also, is there a GET endpoint for metadata organizations?** I tried a GET of the above metadata URL and got a 405 Not Allowed response.

**Comment by excelsior** [comment]
@mparsons-ce The above organization has envelopes marked as deleted, those, too, prevent it from being deleted. To see the soft-deleted envelopes, add a `include_deleted=true` param:

https://sandbox.credentialengineregistry.org/ce-registry/search?per_page=50&owned_by=ce-a8ec0ca9-3dad-488e-b83b-e1f47f501f2c&include_deleted=true

Or `include_deleted=only` to see only such ones:

https://sandbox.credentialengineregistry.org/ce-registry/search?per_page=50&owned_by=ce-a8ec0ca9-3dad-488e-b83b-e1f47f501f2c&include_deleted=only

I think we should physically remove soft-deleted envelopes when an attempt to delete an organization is made. What do you think?

There's no `GET /metadata/organizations/:id` endpoint. We can add it, just let me know what data it should return.

Here's the list of all available endpoints:

https://sandbox.credentialengineregistry.org/swagger/index.html

**Comment by excelsior** [comment]
@mparsons-ce The organization deletion functionality has been fixed on sandbox, i.e. soft-deleted resources get physically removed alongside their organization. Please give it a try.

**Comment by mparsons-ce** [comment]
@excelsior Thanks I have verified this update addresses the issue.
