### ISSUE TITLE
Is it feasible to have the registry generate the private/public keys necessary for publishing

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#59]
@science @leolara 
Depending on the platform, creating the private/public used for publishing can be simple or a little complicated (as I found under windows).
Would it be feasible to create a registry service to create these keys?
If possible, the latter could be done once a user successfully registers with CER.
Or would this be a security risk?

**Comment by leolara** [comment]
@cwd-mparsons @jkitchensSIUC @siuc-nate 

If what you mean is that the server generates a private/public key pair, and return it to the API user. This is technically possible, but a big beyond-security-risk, I think it would be fair to call it a "faux pas" of asymmetric key cryptography. The idea is that the private key will never travel around the internet, in some cases will not even leave the computer that generates it. For example, if you publish from two different computers you ideally would generate key pairs in each, and publish both public keys as part of your identity.

However, whatever is your use case/problem, I am sure we can find a solution:

 + Is it problematic to generate the key pairs in windows?
 + Would you like the API user to be able to publish using a different authentication method, like for example API PSK?
 + Are you developing a API client that has many users, and would like the users to do not have to handle the creation of management of theses keys?

All these problems and more, they all have several solutions and we can discuss them.

**Comment by cwd-mparsons** [comment]
@leolara 
Part of the issue is the steps to create the pair of keys on windows. This is not a huge issue given that we have a documented process - for technical users. 
The primary use case we have or are exploring now, is to enable publishing without the user requiring detailed knowledge of either CTDL or the formatting the Json-LD payload, and publishing. This initial case is for an organization with structured data that can be extracted from a database.
The scenario:

- An API is developed that uses CTDL classes, but is populated as key-value pairs. 
- The user requests the data from a datastore and the transport class is populated:
  - CredApi api = new CredApi();
  - api.Name = source.Name;
  - api.Description = source.Description;
  - etc
- A call is made to the API - not directly to the registry.
- The input is mapped to the CTDL Json-LD format - that is as a payload ready to be published
- The input is minimally validated (will leave the main validation to the registry call)
- If there are issues, errors are returned
- Otherwise, the payload is published
- Error handling and success handling are similar to a regular publish

**Advantages**:
- the user needs no actual knowledge of CTDL or the Json-LD format
- the user would not even have to format a Json document, just simply mapping
- the user would be insulated from changes to CTDL

**Disadvantages**
- the parameter classes for the API could be large
- the process could be a little longer with the extra step

In this scenario, the user would not be  signing the envelope. The API step would be responsible. 
A related possibility could be:
- this option still requires being registered
- the registration process could include generating keys and storing on the server (as securely as possible)

If the generation and storage of keys on the API server is considered too risky, the API could have a method to only format a request as Ctdl Json-LD, and return the payload to the caller. The caller could then save the payload for later or publish the payload to the registry. 
An org with a large number of credentials could run batch processes to format the payload documents, and then publish at a later time.

**Comment by leolara** [comment]
@cwd-mparsons 

Re windows key generation, probably the easiest method is using a program called "putty". We could document about generating the keys on windows using "putty".

the generation and storage of the private key on the API server, I do not think it is too risky. What we couldn't do is for the API server to give the private key to the user.

I see in your design you have another API as client of the registry API. Let's call this other API the editor API. This editor API has some clients itself that authenticate in a different way that is not asymetric key.

I can think of several possible solutions, very briefly:
 + We add to the registry the concept of signing on behalf of another user. then the editor API has its own key pair with which sings on behalf of its users.
 + The editor API generates key pairs for its users, **but the private key never leaves the editor API systems***. When the editor API creates envelopes for its users, it uses the user private key to sign.
 + Another alternative, that complicates more the registry, is this: the registry have a different form of authentication, and generates key pair for the users, , **but the private key never leaves the editor API systems***. Then the registry can sign using the private key of the user that it stores.

We can explore more in depth these possibilities or others.

**Comment by cwd-mparsons** [comment]
@leolara 
I did struggle finding the 'correct' approach for creating the keys. Steve had one of his developer's point me in the right direction. Following is  link the section in our (draft) developer guide on the steps for a windows developer. If you know of less complex process, please let me know.

https://docs.google.com/document/d/1rVBGVnZ0c7vxfVPC8LQMuWm2W4h2vItY5nSbk26lFvE/edit#heading=h.3zx4pib92oen

**Comment by leolara** [comment]
@cwd-mparsons I think this is a more windows friendly approach:

https://www.youtube.com/watch?v=olL39dHRpYg

**Comment by siuc-nate** [comment]
My understanding is that we have an API approach in development in which the registry will handle the keys.  Is this correct?

**Comment by cwd-mparsons** [comment]
@leolara @science 
As we have already committed to a publishing model where the registry will manage the key pairs, I am closing this issue. I am opening a new issue to specifically track how the process of managing the keys will be designed/implemented. 
See #108
