### ISSUE TITLE
Search API: matching on URL isn't quite fuzzy enough

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#597]
For this record:
https://credentialengineregistry.org/ce-registry/resources/ce-1c6322d8-1869-42bb-bdda-9af2908c61f4

The following query will find it:
```
{
	"ceterms:name": "Tech Elevator",
	"ceterms:subjectWebpage": "https://www.techelevator.com"
}
```

But this query will not:
```
{
	"ceterms:name": "Tech Elevator",
	"ceterms:subjectWebpage": "https://www.techelevator.com/"
}
```

Can the matching for URLs be made a little bit looser so that trailing slashes (or the lack thereof) don't break the default matching?

**Comment by excelsior** [comment]
@siuc-nate I made the necessary updates, so the latter query does return proper results now.

**Comment by siuc-nate** [comment]
Cool, thank you.
