### ISSUE TITLE
17-03-08_WithDefinitions.json is not a valid JSON

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#6]
All keys should be with double quotes.

**Comment by leolara** [comment]
moved to another branch: https://github.com/CredentialEngine/CredentialRegistry/blob/master-old/SchemaValidation/17-03-08_WithDefinitions.json

**Comment by cwd-mparsons** [comment]
Ahh - the problem was that I copied the JSON from the browser 'friendly' view. The actual output should be correct.
