### ISSUE TITLE
Single-character queries return 0 results

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#600]
A query like this:
```
{
	"ceterms:name": "a"
}
```
returns 0 results. However, queries that are at least two characters seem to behave as expected:
```
{
	"ceterms:name": "ab"
}
```
returns ~70 results.

Does something in the full text index search process fall over if the user provides a single letter as a query string?

**Comment by mparsons-ce** [comment]
NOTE: most single letter queries do work successfully, but not 
- a
- i
- s 
- t

**Comment by excelsior** [comment]
It's not a bug. The above values are stop words in PG's built-in English dictionary, meaning they are ignored when used in a search term.

Documentation: https://www.postgresql.org/docs/9.1/textsearch-dictionaries.html#TEXTSEARCH-STOPWORDS

Here's the full list of English stop words:

```
i
me
my
myself
we
our
ours
ourselves
you
your
yours
yourself
yourselves
he
him
his
himself
she
her
hers
herself
it
its
itself
they
them
their
theirs
themselves
what
which
who
whom
this
that
these
those
am
is
are
was
were
be
been
being
have
has
had
having
do
does
did
doing
a
an
the
and
but
if
or
because
as
until
while
of
at
by
for
with
about
against
between
into
through
during
before
after
above
below
to
from
up
down
in
out
on
off
over
under
again
further
then
once
here
there
when
where
why
how
all
any
both
each
few
more
most
other
some
such
no
nor
not
only
own
same
so
than
too
very
s
t
can
will
just
don
should
now
```

**Comment by excelsior** [comment]
Just to be clear: Stop words are only taken into account in full-text search conditions, which are used for string properties by default.

You guys can execute single-letter queries using another match type, e.g.:

```json
{
  "ceterms:name": {
     "search:matchType": "search:contains",
     "search:value": "a"
  }
}
```

**Comment by excelsior** [comment]
In this case, disabling stop words entirely would be the best solution, I believe.

@science What do you think?

**Comment by jeannekitchens** [comment]
@siuc-nate is this moved over to CE internal Trello so you can close it here if there's nothing for Tapestry team to handle?

**Comment by siuc-nate** [comment]
I have updated the code/servers on our side and it appears to work.  We can close this.
