### ISSUE TITLE
This website is under heavy load (queue full)

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#604]
There have been many alerts today regarding the registry. 
I tried doing searches and get

> This website is under heavy load (queue full)
> We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

I get the same message if I tried to access a single resource. 

This issue affects publishing as well. The last successful publish was at 22-12-11 16:46 CST. So far there are 4 attempts to publish that failed after the latter time.

**Comment by edgarf** [comment]
We are going to address it as soon as somebody from engineering is around

**Comment by edgarf** [comment]
This has been resolved and I will email about the cause later today
