### ISSUE TITLE
Getting inconsistent 403 errors from sandbox

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#615]
Today, while testing some code changes, I started getting `403 Forbidden` errors from the sandbox Registry for normal URIs like these:

https://sandbox.credentialengineregistry.org/resources/ce-17fcb5b2-7339-9b93-aa93-9741556e1481
https://sandbox.credentialengineregistry.org/resources/ce-a4041983-b1ae-4ad4-a43d-284a5b4b2d73

However, @mparsons-ce can load them just fine.  Is there a particular reason why requests would fail for some users and not others?

I had been testing some code changes that were making a lot of requests in short succession - did I accidentally trip some kind of anti-request-flooding protection perhaps?

**Comment by excelsior** [comment]
@siuc-nate I see no indication of 403 responses in our logs. Those most likely didn't originate from our backend. An anti-flooding mechanism sounds like a plausible explanation indeed.

How exactly do you perform those requests? A 403 status code usually implies authentication. I want to try and replicate this problem.

**Comment by siuc-nate** [comment]
It was an accidental infinite loop on a page that was making a lot of GET requests for the same few resources in a very short time.  The 403 errors persisted for a few minutes after I fixed that, but then things started working again.  The response I got was a generic NGINX error rather than something in JSON, if that helps.

**Comment by siuc-nate** [comment]
Closing this since we can't replicate it. Will reopen if it happens again.
