### ISSUE TITLE
Sandbox server 

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#617]
@excelsior @edgarf 
Unable to view resources/envelopes, or search the sandbox registry:

![image](https://user-images.githubusercontent.com/58825866/217116067-f69d1ff2-72a7-45db-83b8-ad6828f326ea.png)

**Comment by excelsior** [comment]
@mparsons-ce For some reason, the app server was trying to load an older version of one of the libraries. I replaced the faulty instance with a brand new one.
