### ISSUE TITLE
Strange error: the URI for the resource can be resolved, but not the envelope

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#618]
@excelsior 
I encountered a very strange situation. 
The resource for this dataSetProfile can be found:
https://sandbox.credentialengineregistry.org/ce-registry/resources/ce-13e36d12-5d9b-4f56-a885-319a46302e29

But the envelope cannot be resolved:
https://sandbox.credentialengineregistry.org/ce-registry/envelopes/ce-13e36d12-5d9b-4f56-a885-319a46302e29

**Comment by excelsior** [comment]
@mparsons-ce The resource belongs to this envelope:

https://sandbox.credentialengineregistry.org/ce-registry/envelopes/ce-343120e2-c068-4630-bb39-0a09e56d5613

In gerenal, if an envelope contains multiple resources, it can be resolved by the the CTID of its first resource.

**Comment by mparsons-ce** [comment]
@excelsior Thanks. 
This must have been related to some early publishing where the dataSetProfile was included with the credential envelope.
