### ISSUE TITLE
Framework description sets missing Competencies

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#619]
Several of our competency framework description sets appear to be missing some or all of their competencies.  For example:
https://credentialengineregistry.org/graph/ce-6acb6c6e-1769-40bf-bb89-1a7b9281aef4

That framework has a number of competencies, but the description set only shows 1, and the `related_resources` array is also missing the other competencies:
![image](https://user-images.githubusercontent.com/21346519/221008012-37e5042c-71c2-4583-b8a5-46149593085d.png)

**Comment by excelsior** [comment]
@siuc-nate There was a bug with how reverse mappings were handled. Basically, the URIs used to be overriden by each processed resource (hence, there was only one value present in such cases). I deployed the fix and am re-calculating the affected description sets. Will let you know once that's done.

**Comment by excelsior** [comment]
@siuc-nate Done. Both production and sandbox DS have been re-calculated.

I found one more bug causing DS pre-calculation to fail. I'm still investigating it, only two envelopes are affected by it, so it's not that big of a blocker.

**Comment by siuc-nate** [comment]
Looks good, thanks.  Should we keep this issue open for tracking that last bug?

**Comment by excelsior** [comment]
Yes, let's keep it open until the last one is resolved.

**Comment by siuc-nate** [comment]
Thanks
