### ISSUE TITLE
Error on staging server: Could not translate host name "credential-registry.cazemjodbmne.us-east-2.rds.amazonaws.com" to address: Name or service not known

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#620]
@excelsior 
Attempts to access a resource on the staging server or publish to the staging registry result in the following error:
https://staging.credentialengineregistry.org/resources/ce-ff6f1d1e-2389-4652-97a1-cfc31942a623 

![image](https://user-images.githubusercontent.com/58825866/222589769-07473565-abef-4995-8e19-ec0a2ce30abe.png)

**Comment by mparsons-ce** [comment]
@excelsior What is the status of this issue?
I checked today, and get a different error. 
for any resources or a search:
https://staging.credentialengineregistry.org/ce-registry/search?
I get 
![image](https://user-images.githubusercontent.com/58825866/225455197-c630f626-7f62-415f-aeec-0b8204567a68.png)

**Comment by excelsior** [comment]
@mparsons-ce Sorry, I fixed, then broke it again. Now it's up and running, all the data is intact.

**Comment by mparsons-ce** [comment]
@excelsior thx Alex
