### ISSUE TITLE
Request: add a GET endpoint for a registered organization (in metadata/organizations)

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#625]
@excelsior @edgarf 
In our account system, once a new organization is approved, we 'register' it in the credential registry. 
I know there is the following endpoint to get all organizations:
`/metadata/organizations`

I want to be able to do a Get like the following in order to determine if a organization CTID has been registered.  
`/metadata/organizations/{organization_id}`
As well, being able to get by the id might be useful.

**Comment by excelsior** [comment]
@mparsons-ce The requested endpoint is available on both production and sandbox.

**Comment by mparsons-ce** [comment]
Thanks, closing this issue.
