### ISSUE TITLE
Fix Swagger host

### ISSUE THREAD

**Issue by coffeejunk** [CredentialEngine/CredentialRegistry#64]
As mentioned in #63 (https://github.com/CredentialEngine/CredentialRegistry/pull/63#issuecomment-293616155):

> something that needs a fix on the swagger definition is the host,
> currently is always set to localhost. (I guess that's a reason for a couple of warnings on the deployed swagger docs on staging)
> maybe we can get somehow from /etc/host or simply get from a env var on the server.

**Comment by leolara** [comment]
@coffeejunk is it possible to get it from where rack/ruby gets its hostname? If the swagger.json is a template I guess it could be regenerated on every rack startup.

I think we are using rack, right? Not sure If I am right on the tech details, but you get what I mean?
