### ISSUE TITLE
If possible, we would like a mass change for an incorrect @type with the ceterms:teaches property

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#654]
@excelsior 
@siuc-nate noticed that the learningopportunity teaches property has an incorrect @type of ceasn:Competency, where it should be ceterms:CredentialAlignmentObject. 
The error occurred for learning opps published in the last few months. 
Would it be possible to change all of the incorrect types?

![image](https://github.com/CredentialEngine/CredentialRegistry/assets/58825866/d457f9b2-2ef9-49a3-98e0-8e3d8f3b77fd)

**Comment by mparsons-ce** [comment]
@excelsior Yes, that list appears to be the correct targets to change the type to **ceterms:CredentialAlignmentObject**.
Thank you.

**Comment by jeannekitchens** [comment]
@mparsons-ce this change had been made. Please verify so we can close this issue.
