### ISSUE TITLE
CTID RFC URN Syntax

### ISSUE THREAD

**Issue by rehak** [CredentialEngine/CredentialRegistry#66]
I've been working on the draft of the RFC for the Credential ID URN
namespace.  I have an issue for discussion.

As background, I've only found 2 URN namespace RFCs that have been
updated after initial publication.  I've also only found a handful
that have errata.  The updates have been about the registration
authority and ancillary information.  The RFC guidelines are clear,
updates should not change the syntax of the namespace string.

Thus, we need to get the syntax right on the first submission.

The RFC guidelines are also clear; a new URN should not replicate an
existing URN and include justification for the new URN.  There are no
other URNs that look like the CTID or look like a UUID URN.  I am
concerned that a submission that mirrors the UUID syntax will be
rejected.

urn:uuid:E7F50CD6-392A-46AD-87D6-FA3BAD293FC9 and
urn:ctid:E7F50CD6-392A-46AD-87D6-FA3BAD293FC9 are too similar.

Since we are not planning global direct resolution, i.e., not adding
"ctid" to the Resolution Discovery System, IETF could argue that UUID
URNs and private resolution via the Credential Registry (the user needs
to know to use the CR for resolution) are sufficient and reject the
RFC.

I also understand that while IDs are only applied to credential, there
may be a need to assign IDs for other top-level entities in the model.
This suggest that a broader syntax may be appropriate and given the
inability to update the URN scheme, this should be done now if
the need is anticipated.

There are several options to consider in defining the URN.

0) Stick with urn:ctid:<UUID> and see what happens.

- Risky in terms of IETF process.
+ No change to anything in the registry.

1) Add a top-level resource type and follow that by a UUID string

urn:ctid:<resource type>:<UUID>

E.g.,
  urn:ctid:credential:E7F50CD6-392A-46AD-87D6-FA3BAD293FC9 
  urn:ctid:organization:2C448478-D5EE-44D0-ACFA-0EB468E39CD6

The list of resource types would NOT be specified in the RFC, but is
described as a managed process of defining types undertaken by the
community.  The resource type is just a string.

+ Less risky.  
+ Supports extensibility.
- Required changes in the current implementation and documents.
- Exposes semantics in IDs by having a resource type (which might be
  good or bad).  
- Most complex RFC.

2) Same as #1 but do not specify the form of what follows the
type, just call it a "resource specific string" and again make it a
string.

urn:ctid:<resource type>:<resource specific string>

+ Less risky.
+ More extensibility as it supports the ability to have different syntax
  for different resource types.
- Required changes.
- Requires a list of resource types be added to the CTDL.
- Exposes semantics in IDs by having a resource type (which might be
good or bad).
+ Significanlty simplier RFC (all the rules about UUIDs disappear).

3) Be completely opaque in the RFC and not expose types.

urn:ctid:<resource specific string>

The string can be anything: a simple UUID, or a hierarchy of types and
type specific values, something else if needed.  Provides the most
flexibility and extensibility.

- Less risky.
+ Most flexibility.
-  Required changes in documentation to describe how the strings are
   generated and used.
+ Can support either the current model without resource types or a model
  with resource types
+ Simplist RFC.

Options #1), #2) and #3) also permit a hierarchy of resource types, e.g.,

urn:ctid:<resource type>:<subtype>:<resource specific string>

This would need to be included in the RFC for #1), but can be defined
in the registry documentation for #2) and #3)

Recommendation:

My ranking of the approaches (best to worst) is #2), #3), #1), #0) 

While #3) is the most flexible it may appear to be overly simplistic.

Option #2) shows that we have thought about the need for different
types and understand the requirements to manage and maintain an
internal registry of these types.  I believe this increases
credibility and the justification for a new URN namespace.

We need to reach consensus on approach to be able to complete and
submit the draft RFC.

**Comment by siuc-nate** [comment]
Wow, that's a lot to take in.  Very thorough, too.  Thank you for all the hard work.

Given all of this, and the fact that we're not currently using (or needing, apparently) CTIDs or a CTID-like mechanism with any other top level entity, my initial impression is that perhaps we don't _need_ a URN at all. A UUID should be sufficient.  We can keep the CTID property itself (definition modified as needed) as a way of specifying "the UUID for this credential goes here".  Then our top level entities would look like:

```
{ 
   "@type": "ceterms:Certificate",
   "@id": "http://credentialengineregistry.com/resources/EE694546-E7E1-43AD-AE0F-A27AFF5C6F4F",
   "ceterms:ctid": "EE694546-E7E1-43AD-AE0F-A27AFF5C6F4F"
}
```
```
{ 
   "@type": "ceterms:CredentialOrganization",
   "@id": "http://credentialengineregistry.com/resources/8BE95289-F75C-4D25-A6A8-FAFA37DA5690"
}
```
```
{ 
   "@type": "ceterms:AssessmentProfile",
   "@id": "http://credentialengineregistry.com/resources/8F739475-1EF0-4E04-85B8-4AB3B1A06E66"
}
```
```
{ 
   "@type": "ceterms:LearningOpportunityProfile",
   "@id": "http://credentialengineregistry.com/resources/7B81434D-53B9-4FCB-A39B-504F23AF9B09"
}
```

If I remember correctly, one of the original justifications for a URN had to do with resolving it (i.e., "people will see this URN and know it should be resolved in the CER" or something along those lines).  However, that was before we had determined what would go in the `@id` fields -- If the official identifier is always going to be a resolvable URL (with "credentialengineregistry.com" in it, no less) _anyway_, then the URN almost seems redundant.

This would also make it dramatically easier to implement identifiers specific to the other entities.  For example, if some day we decided to create an official "organizationID" property, we could do so without having to go jump through the hoops of creating a URN for that as well.

Not using a URN means no : characters, which means no worrying about URL encoding interfering with the string literal of the ID.  Then we never have to worry about confusion between
```
http://credentialengineregistry.com/resources/urn:ctid:EE694546-E7E1-43AD-AE0F-A27AFF5C6F4F
```
and
```
http://credentialengineregistry.com/resources/urn%3Actid%3AEE694546-E7E1-43AD-AE0F-A27AFF5C6F4F
```

**Comment by stuartasutton** [comment]
@siuc-nate , we need to have this on next Tuesday's agenda. I'm going to argue to drop the use of URN for CTID.

**Comment by leolara** [comment]
@rehak why we are not going to use Resolution Discovery System? wouldn't be a good idea for this case?

**Comment by rehak** [comment]
Why not DDNS - short reasoning.
1) I believe almost all of the existing URN schemes do not use it and most explicitly state that they use "private" resolution.  
2) The only operational DDNS system is DNS; I have no idea how difficult it is to get a new NAPTR record for URN resolution rolled out across the internet.
3) I've never seen URN resolution used in real life,
4) IEFT and W3C recommend against URNs.

I think the effort to make DDNS work could be very cumbersome.
Operational examples would be helpful to really evaluate.

**Comment by siuc-nate** [comment]
In my opinion, there is no need for it if the published identifier is a resolvable URI (i.e. it includes the http://credentialengineregistry/resources/ part), which does the URN's job better than the URN.

**Comment by stuartasutton** [comment]
In the history of our discussions around the CTID, it began with an explicit statement by me that there was no need for the CTID to be resolvable **because** of the presence of the credential resource URI. In the TAC discussion, the conversation shifted to using a URN as opposed to a plain UUID; I guess to make it resolvable outside the context of RDF and Linked Data. That meant the there would be two ways to resolve for credential entities--the resource URI and the CTID. 

So, to the extent there are issues with registering a URN, I'm with @siuc-nate that this double resolution is not worth the effort it's turning out to require. In any debate as to the 'best approach', resolution by means of the credential resource URI wins hands down. Thus, in my opinion, the credential's CTID should be a plain UUID that is concatenated on the /resources/ namespace to create the credential resource URI.

**Comment by rehak** [comment]
Since I won't be available for the call on IDs and URNs I wanted to
send along my thoughts.  You'll excuse my lack on prior history with the
project here.

I'll start with the assumption that the Credential Registry is
designed to be a long-lived service, and that data will be around for
a very long time.  As such the core data needs to outlast technology
changes (like encodings and protocols) and it the services will evolve
over time.

This leads to some questions:

-- 1) is the credential the only (forever) thing that needs a
   persistent ID, or will other resources need persistent IDs.

-- 2) should IDs for different classes of resources look the same or
   can they be different, e.g., can/should they all be UUIDs.

-- 3) does the class of resource need to "human readable" by looking
   at an ID without having to resolve it to get the class of resource.

-- 4) does the ID need to be useful without being associated with a
      locator or resolution service, i.e., can ID can be exposed to
      the outside world without embedding in a query or path string in
      http.

-- 5) does the ID scheme need to confirm to an existing standard or spec,
   e.g., URI, URN

-- 6) do you need to use IETF standards (with the associated costs) or
   will other's suffice.

-- 7) do you need public, external, internet-wide (non project, e.g.,
   DNS like) resolution, or will project specific resolution do

For any long-lived project, my general design and recommendations for
the above would be 1) multiple entities, 2) same form, 3) maybe 4)
yes, 5) yes (some scheme), 6) non IETF OK, 7) non public internet
resolution

My recommendation would be either

1) use the URI syntax, e.g., CTID:<string>, and not bother to register
    this URI with IANA (getting a standard URI like HTTP is very
    difficult and there no guarantee of uniqness or ownership for
    provisional URIs. For internal documention, do write the 15 line
    URI description following IETF guidelines).

2) or use a widely accepted 3rd party scheme, like DOI and assign
these to the resources

In either case you can embed these IDs in http locators or use them as
naked IDs.

**Comment by science** [comment]
I'm fine with @siuc-nate's proposal of using only URI/URL as the resolution and ID persistence schema AS LONG AS we are all comfortable with that domain name being long-lived. We went down this whole rabbit hole at the start because we discussed discomfort with dependency on a domain name. If we are comfortable with that, then I think we can use a UUID attached to a URI for IDs. Seems fine to me.

**Comment by siuc-nate** [comment]
Conclusions from our 4/27/2017 call:
- We will not register or use a URN
- We will define a CTID for every entity that is assigned a URI (instead of a blank node) described by CTDL
   - Includes Credential, Organization, AssessmentProfile, LearningOpportunityProfile, CostManifest, ConditionManifest
   - Example: ce-[UUID]
- We will provide a URI identifier that resolves those abstract IDs for CER
   - Example: http://credentialengineregistry.com/resources/ce-[UUID]
- The abstract identifier applies to the entity; the URI applies to the record in the CER
- We will update the definition of CTID to accomodate these changes.

**Comment by Lomilar** [comment]
Note that ce-<UUID> may have some effects on URL parts parsing that match UUIDs as a regex.

This is small peanuts, but if resources from the CE are copied into other repositories, aggregated into search engines or transmuted into other LD objects outside of the CE, the presence of an undecorated UUID is a valuable discriminator.

**Comment by rehak** [comment]
I wanted to verify my understanding of the conclusions from the call using an example, i.e., a URI independent from a http locator was not desired.

Selected choice:
1) the ID is ce-[UUID]
2) this is not a URI
3) the URI and locator uses the http URI scheme: http://credentialengineregistry.com/resources/ce-[UUID]

vs a change in syntax

1) the ID is ce:[UUID]
2) this is a URI using the unregistered ce URI scheme, it is not a locator
3) the locator (and also a URI) is http://credentialengineregistry.com/resources/ce:[UUID]

**Comment by leolara** [comment]
@siuc-nate @rehak 

Could we consider using http**s** for the URI.

 + Many systems/institutions are deprecating http because it is unsecure. For example Google penallize you in their algorithm
 + To use other authentication other than asymmetric key as it is being spec'd we will need to use https, otherwise it would be insecure. Hence, keeping http in the URI would mean that the API would have to make mandatory https in all the endpoints except the URI one

**Comment by siuc-nate** [comment]
I agree this is something we need to settle on.  It's unfortunate that the protocol needs to be a part of the identifier at all; it would be nice to say that `credentialengineregistry.com/resources/ce-[uuid]` was the identifier and let people use whatever protocol was best/convenient, but that would be inconsistent with how other systems work, I guess.

Anyway, the http/https issue and how it relates to the validity of a given identifier has come up before. @stuartasutton can elaborate on that.  Stuart, has there been any news on that front? I recall you said there were some other discussions on it that you were keeping track of.

**Comment by stuartasutton** [comment]
Discussions in DCMI and schema.org regarding preferred protocol (http / https) have gone no further. Schema.org recognizes both in markup (http://schema.org/docs/faq.html#19). It is without doubt that the movement is toward https.

**Comment by rehak** [comment]
Using TLS for all transport is reasonable.  Best practice is to use it; the network costs are now acceptable.  The only real "cost" is that of the certificates and their management.

I'm going to nit pick on terminology (since this is what can lead to difficulty).

credentialengineregistry.com/resources/ce-[uuid] is a valid identifier (especially since there is not formal definition of what an ID is).
ce-[uuid} is also an ID

ce:[uuid} is an ID and a valid URI -- the URI syntax starts with a string followed by a colon.

credentialengineregistry.com/resources/ce_[uuid] is and ID but not a URI

http://credentialengineregistry.com/resources/ce-[uuid] is a URI using the URI scheme
ftp://credentialengineregistry.com/resources/ce-[uuid] is a URI using the FTP scheme
both http and ftp are the protocols, so in this case the URI includes the protocol.

My main argument for considering ce:[uuid] is to have an id that follows an accepted syntax and avoids having to have a URI that overloads the URI scheme with the access protocol.    I suspect that most people don't care about the distinction, but I've fought too many "id wars" to not bring it up just to make sure everyone is clear on their decisions.

**Comment by leolara** [comment]
@rehak is the underscore in credentialengineregistry.com/resources/ce_[uuid] a mistype?

**Comment by science** [comment]
To re-iterate and try to organize some of the above discussion as well as some phone calls we've had recently on this subject. 
First off, there are two identifiers that we are trying to manage, as @siuc-nate points out:
* 1- "ce-[uuid]" is the ID of the abstract entity being described. 
  * The easiest example of an abstract entity is a credential. While metadata about the credential might be available from many places (including CER), the credential itself is intangible/abstract and needs an ID.
  * @Lomilar you mention that a naked UUID is valuable? I was thinking just the opposite. By pre-pending "ce-" to the UUID, we give someone hope of distinguishing our IDs from the bigger world of UUIDs. It's a poor man's URN. Also for parsing via regex, having the "ce-" seems nice (to me). I'm open to naked UUIDs but they seem less good than an ID which can be pattern matched uniquely.
* 2- `http://credentialengine.org/resource/ce-[uuid]` is the ID of metadata known about the abstract entity, as available from CER. 
  * These URIs are supposed to be long-lived and resolvable. They should be suitable for use in RDF/semantic web references, and should return metadata that is usable in semantic statements.
  * I think it's important to underline that these URIs are *not* just part of a resolver service for the abstract entity ID. These URIs are distinct IDs themselves (as IDs to metadata about the abstract IDs). The fact that these URIs contain the abstract entity ID is a mnemonic convenience to everyone. (@stuartasutton let me know if these URIs can be called resolvers at all or if we should only talk about them as metadata IDs?)
* 3- HTTP/S Proposal: IMO we should declare http and https IDs to be equivalent or "same-as" to each other: either is fine as an ID, and they mean 100% the same thing. Either can be used interchangeably by any party, depending on their use-case. 
  * I hate to prohibit HTTP entirely b/c clear-text is so easy to debug and get started using, and these are public identifiers anyway, so encryption isn't really required (though it seems great to have it as an option).
  * Does this approach cause more problems than it solves?

**Comment by Lomilar** [comment]
For compatibility purposes:
URN > UUID > prefixed-UUID

Prefixed UUIDs can be parsed if you're looking for them, but `url.split(/\//g).match("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")` would not work, nor would a URN parser. 

ce-[uuid] ends up being (yet) another unique identifier format.

Probably more importantly, consider that the ID of a credential may come from other sources that want their own canonical identifiers. Having a default generation method is great, but relying on an ID to carry any information can be dangerous.

**Comment by Lomilar** [comment]
I agree that IDs, if possible, should try to provide some readable information. Here's how I parse this:

`http://credentialengine.reg/resource/ce-8baad47a-395f-402a-8af9-d12bce152138`

credentialengine.reg and ce- are saying the same thing. 'ce-' additionally doesn't mean anything unless I know what the credential engine is.

`http://credentialengine.reg/resource/ce/8baad47a-395f-402a-8af9-d12bce152138`

This one is saying that the CE stores resources for other organizations, but this one is a credential engine resource. I'd expect to see /resource/mit.edu/... and /resource/dol.gov/ there as well. Obviously mit.credentialengine.reg or dol.credentialengine.reg would be better, but that'd require sharding and whatnot.

`http://credentialengine.reg/resource/8baad47a-395f-402a-8af9-d12bce152138`

This one is saying the exact same thing as the first one, but with something that can be a 128 bit number or a string on the end.

I'll stop now, as I imagine this is becoming tedious. :-)

**Comment by rehak** [comment]
Bunch of stuff:
-----
@rehak is the underscore in credentialengineregistry.com/resources/ce_[uuid] a mistype? 
Yes, should have been "-"

----
On http vs https

The issue isn't the form of the URI, both http and https as the NIS can be considered to be equivalent.  Nor is it an issue of encryption.  Once the NIS means the protocol, then you have to deal with some organization that by policy blocks port 80.  Using https exclusively circumvents this; the "cost" to deal with debugging, ... are offset by picking the single approach.

----
On opaque ID

Opaque IDs are good.  Naked IDs can be good.
"ce-" makes it possible to look at string and infer that it could be a credential entity; make it human readable.  This is especially useful if the ID is just the abstract ID "ce-[UUID]", a naked UUID isn't too useful.

http://credentialengine.org/resource/ce-[UUID} and http://credentialengine.org/UUID are saying the same thing.

But what is the full abstract ID syntax? If the "ce-[UUID]" component as a path element of the NSS can appear anywhere, then the "ce-" could be useful to a parse to find the entity ID in the overall metadata ID.   Can you document the ABNF for the metadata ID to identify the entity ID component without it containing "ce-", or without making it very difficult to write a parser?  Maybe using "ce-" makes life easier.

**Comment by Lomilar** [comment]
If you're using UUIDv4 (Random UUIDs) for generation:

Perhaps make UUIDs where the first letters are always 'ce' or 'ce0'. If you want to avoid random chance, 'ce000000'. You'd be able to encode additional type data in there as well, if desired.

`ce-8baad47a-395f-402a-8af9-d12bce152138` becomes `ce000000-395f-402a-8af9-d12bce152138`

**Comment by science** [comment]
@rehak ABNF is not a strength of mine, but here's my attempt to define the two kinds of IDs were defining, per your request:
```
CTDL-ID = ce-prefix ce-uuid
CER-ID = cer-resources-uri ce-prefix ce-uuid
cer-resources-uri = "http" ["s"] "://credentialengine.org/resources/"
ce-prefix = "ce-"
ce-uuid = {ABNF for a UUID per https://www.ietf.org/rfc/rfc4122.txt or similar}
```
Your help in de-fubaring the above is welcome.

@Lomilar Forcing part of the UUID itself to reflect the CE prefix worries me more than naked UUIDs. It implies that anyone using a UUID library has the ability to force the library to reflect this prefix, which isn't a standard feature that I've noticed in UUID libs I've used in the past. I'm open to having missed this whole aspect of UUIDs.

From my perspective, if people internally decide to store our CTDL-IDs as naked UUIDs, and then re-present them to the world by prefixing a static string of "ce-" that seems fine. Regarding the parsing, if someone wants to just parse for naked UUIDs, they are welcome to do so with regex or otherwise. The `ce-` prefix shouldn't impact them at all. But for other people, if they want to parse a doc and know they are pulling on CTDL-IDs, they can modify their UUID regex with the static prefix and it'll work.

This is imperfect regex (false positives) but the general idea is:
`/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/` #is fine, but so is:
`/ce-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/`

If everyone but me thinks this is a bad idea, let's not do it this way! :)

**Comment by Lomilar** [comment]
`/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/` only works in `.find()`, not in `.match()` against `ce-8baad47a-395f-402a-8af9-d12bce152138`.

Unless someone codes in a special case, there's at best a 50/50 chance they will not parse the resource identifier.

[There's ample proof people use `.match()`](https://github.com/search?utf8=%E2%9C%93&q=%22function+isUUID%22&type=Code).

Forcing the UUID to have `ce000000-` is not great, but at least it parses with standard tools! Admittedly, there's a rather high chance though someone would unwittingly use a UUIDv1 and replace the timestamp portion of the ID with the tag.

**Comment by science** [comment]
Weird - I can't see why match wouldn't work. I tried it in Google Chrome JS console, and it does work for me. What am I missing?

![image](https://cloud.githubusercontent.com/assets/67948/25871688/3e692b84-34bd-11e7-9a16-0473281ec167.png)

**Comment by Lomilar** [comment]
Huh. You're absolutely right.

I was under the impression `.match()` was similar to Java [matches()](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#matches())

Looks like my understanding is completely in the minority here among languages. My bad!

I was seeing in my head `/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/` (which still tends to be common in the code examples)

**Comment by science** [comment]
NP - pinning to begin/end line would definitely break it, but of course that would break many possible uses of UUIDs in documents.

Are we at a reasonable consensus? 
```
CTDL-ID = ce-prefix ce-uuid; Where CTDL-ID is the ID for the abstract "top level" entities such as a credential.
CER-ID = cer-resources-uri ce-prefix ce-uuid; Where CER-ID is the ID for the metadata available about a top level entity as it is available in CER
cer-resources-uri = "http" ["s"] "://credentialengine.org/resources/"
ce-prefix = "ce-"
ce-uuid = {ABNF for a UUID per https://www.ietf.org/rfc/rfc4122.txt or similar}
```

(@rehak or others please fix whatever I've borked in the ABNF above - hopefully I've at least got the idea across)

**Comment by rehak** [comment]
The correct ABNF for the URI and UUID are in the respective RFC.  URI permits a UUID (with most prefix characters) in any segment of the URI.  As long as it is *always* just one segment that is "resource" and one following and final segment that is the UUID based ID, then might be better/easier to just write those as constraints on the ABNF rather than  do a special ABNF, but it looks OK,  Or that the generic URI syntax and make the restrictions, like the scheme must be http/https, there are 2 segments, one must be "resource", ...  [I'm old school and don't know the fine points of ABNF, I learned BNF from Alan Perlis who worked with Backus and Naur on Algol 60].

I would not mess with the UUID syntax and would not presume to constrain someone to use only one of the types of UUID generation.  I think it is too subtle of a point that can easily be ignored by someone not reading all the details resulting in a potential for errors.

**Comment by science** [comment]
@rehak I edited the above ABNF to reflect your input, I think. LMK if you (or anyone!) has additional thoughts. Hopefully this is (finally) settled!

**Comment by rehak** [comment]
Closing this.
