### ISSUE TITLE
Checking if there was a temporary registry outage around 2:55am central on 11/14/23

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#663]
@excelsior 
We had a partner running a registry import (which uses the registry full text search) starting Nov. 13, 2023.
Around  11/14/2023 2:55:28 AM central (11/14/2023 8:55AM GMT) there were some InternalServerError messages.
This lasted about 10 seconds, and then the search started to work properly again,

I didn't see any outages in our servers, and I didn't getting any alerts about registry server outages. 

Could you check if there were any issues with the registry servers around this time?
It could have been too short to be caught by the Azure monitors, and others.

**Comment by excelsior** [comment]
@mparsons-ce I don't see any search-related errors either. There only were were a handful of search requests around the specified time frame, all of those successful.
