### ISSUE TITLE
Credential Engine DESM Emails

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/CredentialRegistry#666]
Should we have a separate CE DESM Repo?  I don't expect there to be much and the enhancement project is via the existing t3 DESM repo.  Anyhow, rather than bother with another repo until it's really necessary, this is to request the following updates to the DESM emails sent via the Credential Engine instance using our mailgun account/API.

1. Rather than using desm@credentialengine.org, use [donotreply@credentialengine.org](mailto:donotreply@credentialengine.org)?

2. Change the below referenced CE/DESMemail text to the following. 

Subject: CTDL DESM Account Confirmation - Action Needed

Remove the T3 logo.  We don't need to include a logo but if you want to swap a logo out. Use the same Credential Engine logo we provided for the CE DESM site. 

[Name of person capitalize first and last name] you're invited to participate with a CTDL mapping project.  By joining you wil be able to participate in the mapping of your schema(s).  Click the linke below to set up your password and log in. [Set up your password!] Contact info@credentialengine.org if you have any questions. 

![image](https://github.com/CredentialEngine/CredentialRegistry/assets/20917206/2223d130-deeb-4aef-92f0-5cad59fd4680)

**Comment by excelsior** [comment]
@jeannekitchens The email template has been updated.

Having a separate repo is a great idea. I created a new repo. Could you team fork the T3 repo by clicking the following link under the @credentialengine account:

https://github.com/t3-innovation-network/desm/fork

That'd made it easier to sync changes from the main repo.

Add me to the new repo as a contributor and I'll push my changes.

**Comment by jeannekitchens** [comment]
@excelsior Thank you!  The updates look great. And, sure, we can take care of  getting the repo set up under CE.

**Comment by jeannekitchens** [comment]
@excelsior Repo is set up https://github.com/CredentialEngine/desm.  I added you and @edgarf.  Let us know if anything else is needed.

**Comment by excelsior** [comment]
Thanks @jeannekitchens! The forked repo has been updated and is now used for deployment.
