### ISSUE TITLE
Unsupported property error in Search API

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#667]
The following query:
```
{
	"ceterms:supportServiceStatementDescription": "search:anyValue"
}
```
returns this error:
```
{
	"error": "Unsupported property: `ceterms:supportServiceStatementDescription`"
}
```

https://credreg.net/ctdl/terms/supportServiceStatementDescription is a valid CTDL property, added in the September 2023 release.

Is there a cached version of the schema somewhere that needs to be updated (or some similar issue)?

**Comment by excelsior** [comment]
You're right, the context sync job wasn't working for quite some time. I fixed it, but rebuilding the index will take some time. I'll keep you posted.

**Comment by excelsior** [comment]
@siuc-nate The context has been updated, but I can't find any resources having this property. Hence the error persists.

Currently, the search engine expects a property to be present in the data in order to use it in a query. Should it be changed to not care about it?

**Comment by jeannekitchens** [comment]
Per @excelsior this is ready to test.

**Comment by siuc-nate** [comment]
The property now works, but it took a strangely long amount of time:
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/021f4eee-e7b2-446e-a35e-b10d0c51bfde)

**Comment by siuc-nate** [comment]
Getting the same error with ceterms:registeredBy on **sandbox** (no error on production):
```
{
	"ceterms:registeredBy": "search:anyValue"
}
```
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/5b8a30e0-eb5e-4391-aaf4-f5c1fda4016c)

**Comment by excelsior** [comment]
@siuc-nate The JSON context cache sometimes doesn't get invalidated. I'll fix it manually, will work on a proper fix later.

**Comment by siuc-nate** [comment]
Fixed, thanks.
