### ISSUE TITLE
Queries for resources based on CTIDs not working

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#669]
The following resource exists:
https://credentialengineregistry.org/resources/ce-bb97054a-401b-4b2c-9db2-4fb9e621440a

However, attempting to find it by querying for its CTID returns no results:
```
{
	"ceterms:ctid": "ce-bb97054a-401b-4b2c-9db2-4fb9e621440a"
}
```

![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/e3655fa5-293f-4799-8832-e3800c1468b8)

While it is possible to just get the resource directly via its URI, the above query should also still work (and may be indicative of some other issue in the system?).

**Comment by jeannekitchens** [comment]
Per @excelsior this is ready to retest.

**Comment by siuc-nate** [comment]
Thanks, this appears to be fixed now.
