### ISSUE TITLE
Potential issue with description sets

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#671]
@excelsior Nate is out of the office this week. 
We have encountered an issue that seems related to description sets, but I am not very familiar with the latter. 
The following framework exists in the sandbox:
https://sandbox.credentialengineregistry.org/envelopes/ce-9b96bb43-62cc-47e4-b2ec-1857f2e4700d

The finder detail page process is calling: 
https://sandbox.credentialengineregistry.org/description_sets/
with a request of:
{"ctids":["ce-9b4be37f-8cc6-4e5d-be7c-fddb00f816af"],"include_resources":true}

But no data is returned. 

I also tried:
https://[sandbox.credentialengineregistry.org/resources/ce-5c286542-c455-4e78-b4e2-b90f2e25b0e2](https://sandbox.credentialengineregistry.org/resources/ce-5c286542-c455-4e78-b4e2-b90f2e25b0e2)
And it does return a description set with the competencies.

I noticed that the key" results_metadata has no data. I don't if that causes a later issue with the detail page not being displayed. 

OR, perhaps related, competency frameworks published today don't show in the registry graph search.

**Comment by excelsior** [comment]
@mparsons-ce The indexer was lagging behind on processing newly published data. It did catch up eventually. The framework's description set and related subresources look good to me now. Could you please confirm?

**Comment by mparsons-ce** [comment]
@excelsior 
I checked several frameworks and they all look good now.  
Thanks.

**Comment by jeannekitchens** [comment]
@excelsior were any changes made to alleviate lag time going forward?

**Comment by excelsior** [comment]
@jeannekitchens I'm working on it, but nothing has been deployed yet.

**Comment by jeannekitchens** [comment]
Fix has been deployed.
