### ISSUE TITLE
Blank node ids are generated so a graph with no real changes now appear changed 

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#672]
@excelsior 
We have a partner publishing thousands of transfer values daily. Often or usually there is no change to the data but the envelope gets marked as changed. 
I think the issue is the blank node ids. These are always generated new so the graph will appear changed.
I would guess there is little you could do about this, other than a major hack, but thought I would check. 
Another possibility would depend on whether blank node ids have to be globally unique or only unique within a graph?

**Comment by excelsior** [comment]
@mparsons-ce Blank nodes need to be unique within a graph, not necessarily globally. I think we can diff two versions of a graph and see whether they only differ by blank node IDs, but it may be tricky indeed…

**Comment by mparsons-ce** [comment]
@excelsior Thanks for your response.
