### ISSUE TITLE
Call to  resources/check_existence returns duplicate CTIDs

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#674]
@excelsior 
We have a collection of course CTIDs being uploaded. Part of the upload step is to check if the CTIDs exist in the registry using 
**.../resources/check_existence**
A list of **6573** CTIDs were sent, but **6575** were returned!
I checked the list and found duplicates for the following CTIDs:

- ce-1ee35d87-9194-4c44-89b4-e7a169f3e1d5
- ce-6fca72e1-f283-4a7f-9f0b-c6796f04a652

I am not sure how this can happen. 
Is it possible that somehow there are actual duplicate resources for these CTIDs?

**Comment by excelsior** [comment]
@mparsons-ce Yes, I found 8 duplicates in total.

```
               resource                 |                                     envelopes
----------------------------------------+---------------------------------------------------------------------------------
ce-0310ef55-3763-4bab-b542-c9482b81b95f | ce-0310ef55-3763-4bab-b542-c9482b81b95f, ce-0310ef55-3763-4bab-b542-c9482b81b95f
ce-17d99fc5-ca8a-45b3-b4ef-b3d78efb625f | ce-17d99fc5-ca8a-45b3-b4ef-b3d78efb625f, ce-17d99fc5-ca8a-45b3-b4ef-b3d78efb625f
ce-1ee35d87-9194-4c44-89b4-e7a169f3e1d5 | ce-1ee35d87-9194-4c44-89b4-e7a169f3e1d5, ce-1ee35d87-9194-4c44-89b4-e7a169f3e1d5
ce-660e8df6-3699-4a3d-a3df-ef0d1f983ceb | ce-660e8df6-3699-4a3d-a3df-ef0d1f983ceb, ce-660e8df6-3699-4a3d-a3df-ef0d1f983ceb
ce-6fca72e1-f283-4a7f-9f0b-c6796f04a652 | ce-6fca72e1-f283-4a7f-9f0b-c6796f04a652, ce-6fca72e1-f283-4a7f-9f0b-c6796f04a652
ce-a2e9c853-d068-4fcb-b5bc-0233bd2dbce5 | ce-a2e9c853-d068-4fcb-b5bc-0233bd2dbce5, ce-a2e9c853-d068-4fcb-b5bc-0233bd2dbce5
ce-a9c3c797-cb67-4148-af8e-8aa3eee05d5e | ce-a9c3c797-cb67-4148-af8e-8aa3eee05d5e, ce-a9c3c797-cb67-4148-af8e-8aa3eee05d5e
ce-ed12a61b-f82a-4962-bf36-aeb0a12bbea8 | ce-ed12a61b-f82a-4962-bf36-aeb0a12bbea8, ce-ed12a61b-f82a-4962-bf36-aeb0a12bbea8
```

**Comment by mparsons-ce** [comment]
As previously noted, the CTIDs were not duplicated in different resources, the same resource was published a few times. 
https://docs.google.com/spreadsheets/d/1pqZUBfwP9ZIYcrvFUbGXwbx-z5vlNCowBnTcUyd_7_Y/edit#gid=0

**Comment by mparsons-ce** [comment]
We have not had this issue reoccur, and Alex has implemented a process to do deduplication.
