### ISSUE TITLE
Concept schemes missing from search index and description sets on Sandbox

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#677]
These concept schemes (and likely a few others):
https://sandbox.credentialengineregistry.org/resources/ce-61151031-c455-483b-8ce7-609415aec2e5
https://sandbox.credentialengineregistry.org/resources/ce-4a299911-c455-4e20-8fec-965019136f4f
https://sandbox.credentialengineregistry.org/resources/ce-61151031-c455-483b-8ce7-609415aec2e5
https://sandbox.credentialengineregistry.org/resources/ce-0cbe12f8-c455-4cc8-b8c2-71f1e69157c7

Are present in the Sandbox Registry, but not showing in the search API:
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/ce16793b-753f-4138-8b2f-5ba7fe26ab02)

Additionally, their description sets don't seem to exist:
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/9c5a3ef9-21b5-4401-8662-2eb3c1f9d5aa)

Though it is possible to get the graph data (other than the concept scheme itself) via the description set query (I assume that is not reliant on the index):
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/09154590-65f6-4052-83e2-cad99154ce5d)

**Comment by excelsior** [comment]
@siuc-nate Actually, only those four were missing. I re-indexed them. The process server was down. I think I turned it off for maintenance and forgot to turn back on. Sorry about that.
