### ISSUE TITLE
Referenced external Concepts missing from Description Set for a Concept Scheme on Sandbox

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#679]
For this Concept Scheme: https://sandbox.credentialengineregistry.org/resources/ce-61151031-c455-483b-8ce7-609415aec2e5

There are some Concepts from another Concept Scheme which are referenced via properties like skos:exactMatch
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/79daae14-0bab-4b8e-95ab-c9e8f2363ccd)

However, there is no data for those Concepts in the description set.

We have a partner that needs this to work ASAP.

Thanks.

**Comment by excelsior** [comment]
@siuc-nate The `skos:exactMatch` mappings were missing from the config. I added them manually and re-calculculated the affected concept schemes. Now the description sets look good.

```
> skos:exactMatch > skos:Concept
> skos:exactMatch > skos:Concept > skos:inScheme > skos:ConceptScheme
```

I'm investigating the reason they (and possibly others) were missing.

**Comment by siuc-nate** [comment]
Thanks.  Was that change made on sandbox as well? I'm still not seeing the related concepts included in the data
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/2e4b0dc9-8d5c-4e23-9e2e-1cf11da81dcf)

**Comment by excelsior** [comment]
These were the missing mappings i've added (taken from [this](https://credreg.net/page/descriptionsetprofiles) page):

![image](https://github.com/CredentialEngine/CredentialRegistry/assets/406292/8668660b-59dc-4bdd-b429-fb029dff7d9e)

Both have `skos:Concept` as the starting point. Meanwhile, `ce-61151031-c455-483b-8ce7-609415aec2e5` is a concept scheme, there are no mappings involving `skos:exactMatch` for it.

If you look up the concepts with the `skos:exactMatch` property, the description sets are present:

```
{
  "ctids": ["ce-b72407d6-c455-478c-808f-d4cb76463248"],
  "include_resources": true
}
```

Are some mappings missing from the Description Set Profiles page?

**Comment by siuc-nate** [comment]
Possibly. That page was intended as a starting point for developing code that could generate paths by going from everything with a CTID to everything else with a CTID along the shortest path allowed by the schema. But in order to avoid circular references and other such issues, it doesn't keep going from CTID thing to CTID thing to CTID thing except for some very specific paths programmed into it like "credentials to competencies via learning opportunities" and such. 

Anyway if that page is still being used, that would mean the above path is missing because hopping from Concept Scheme to Concept to Concept would be visiting the Concept class twice and it's also coded to not do that (mostly to avoid infinite loops). 

I don't think we've had anything that used those paths until very recently, so that's why we wouldn't've noticed.  There are several Concept to Concept connections that should be accessible from the description set for a Concept Scheme via various SKOS properties:
- skos:exactMatch
- skos:broadMatch
- skos:closeMatch
- skos:narrowMatch
- skos:relatedMatch (which I don't think we explicitly track in our schema data but it's there in SKOS)

There are possibly others we'd need to add at some point.  I can look into adding them on that page, if that is the preferred way to do it.

**Comment by siuc-nate** [comment]
Okay, that makes more sense. Thanks. It's probably okay to let it keep working the way it is, but I'm open to ideas.

Anyway, let's add:
```
skos:ConceptScheme < skos:inScheme < skos:Concept > skos:exactMatch > skos:Concept
skos:ConceptScheme < skos:inScheme < skos:Concept > skos:broadMatch > skos:Concept
skos:ConceptScheme < skos:inScheme < skos:Concept > skos:narrowMatch > skos:Concept
skos:ConceptScheme < skos:inScheme < skos:Concept > skos:closeMatch > skos:Concept
skos:ConceptScheme < skos:inScheme < skos:Concept > skos:related > skos:Concept
```

**Comment by excelsior** [comment]
I added the above and ones related (e.g. `skos:Concept > skos:closeMatch > skos:Concept`) and re-calculated the revelant resources on sandbox.

Let me know if those look good for you and I'll promote the changes to production.

**Comment by siuc-nate** [comment]
Thanks, I see them now.  They're still not showing in the finder but that's an unrelated second issue on our side. We can close this now.
