### ISSUE TITLE
Update How Some Envelope URLs are Handled 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/CredentialRegistry#688]
When resources for competencies, pathway components, rubric criterion, concepts, and collection members are published, they are within the envelope for their related, Competency Framework, Pathway, Rubric, Concept Scheme, and Collections.  Thereby, when a user uses an envelope URI for these classes, they get back, "Couldn't find Envelope."

https://credentialfinder.org/competency/ce-9d4c0fb0-42fd-4a03-8dfc-76890ff64c24 yields the following:
{
   errors:
[
"Couldn't find Envelope"
]
}

Preferred change: Registry team request a change to get the envelope for the related Competency Framework, Pathway, Rubric, Concept Scheme, and Collections for:

- Competencies
- Pathway components
- Rubric criterion
- Concepts
- Collection members

**Comment by siuc-nate** [comment]
I think the intended URL is meant to be:
https://credentialengineregistry.org/envelopes/ce-9d4c0fb0-42fd-4a03-8dfc-76890ff64c24

**Comment by excelsior** [comment]
@jeannekitchens @siuc-nate This feature is available on sandbox.

**Comment by siuc-nate** [comment]
Looks like this is working, thanks.

**Comment by excelsior** [comment]
@siuc-nate Bnode IDs are ignored now. If it looks good to you, I'll promote these changes to production.

**Comment by siuc-nate** [comment]
Looks good, thanks.
