### ISSUE TITLE
Sample credentials fail to validate

### ISSUE THREAD

**Issue by coffeejunk** [CredentialEngine/CredentialRegistry#69]
As [requested](https://github.com/CredentialEngine/CredentialRegistry/issues/21#issuecomment-294065437) I've updated the JSON Schemas, however upon trying to publish the [sample payloads](https://github.com/CredentialEngine/CredentialRegistry/issues/21#issuecomment-294204186) virtually all fail to validate (i.e. can't be published).

I've posted the [log and error messages for the resources in this gist here](https://gist.github.com/coffeejunk/99e467a389c0b1b768c7f8a6dcbd0242#file-publish-errors-txt).

**Comment by cwd-mparsons** [comment]
@coffeejunk 
Thanks Max. We will investigate the issues today.

**Comment by leolara** [comment]
@cwd-mparsons seems the issues are with the dates. there are some fields that have a specific date format in the JSON schema but the test resources do not match that date format

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara 
Nate made several updates to both how the validation schema is generated and how the Json-LD payload gets formatted. These changes require that new versions of the validation schema be retrieved from the credReg.net site:

http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true
http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?asGroup=true
http://credreg.net/ctdl/schema/validation/LearningOpportunityProfile/json?asGroup=true

**Comment by coffeejunk** [comment]
@cwd-mparsons I've updated the schema and publishing works now for about a third of the resources. I've created a [new gist with the error messages here](https://gist.github.com/coffeejunk/d9f53342dd65a120918eb620b1d8b81e).
