### ISSUE TITLE
Reverse lookup for members of a collection is missing some results

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#699]
This collection has 3532 values in its `ceterms:hasMember` array: https://credentialengineregistry.org/resources/ce-d4fc564d-0e77-4f5e-a5b4-7c14b9584a46

However, when doing this query, only 1528 results are returned:
```
{
  "^ceterms:hasMember": {
    "ceterms:ctid": [
        "ce-d4fc564d-0e77-4f5e-a5b4-7c14b9584a46"
    ]
  }
}
```

Other collections I've looked at return the appropriate results, so it seems to just be an issue with this one.

This is part of a use case that one of our partners needs to have resolved ASAP.

Thanks.

**Comment by excelsior** [comment]
The indexer used to consume too much memory when indexing large collections. I deployed a fix and reindexed this one, now the query returns the correct number of members.

**Comment by siuc-nate** [comment]
This is working now, thanks.
