### ISSUE TITLE
Add description field to definitions

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#7]
We can add a description field to each definition autmatically taking it from the RDF vocabulary description

**Comment by siuc-nate** [comment]
It's easy to do, but what is the value in doing so?  Do we intend to distribute the schema validation JSON?

**Comment by leolara** [comment]
@siuc-nate 

We thought the schema is the formal API spec

**Comment by leolara** [comment]
As an option

**Comment by siuc-nate** [comment]
I have added this as a parameter:
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?includeDescriptions=true

Specifically, the ?includeDescriptions=true part

**Comment by siuc-nate** [comment]
Closing this one, as there doesn't seem to be anything further.
