### ISSUE TITLE
Server error with query

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#705]
On both sandbox and production, the following query works:
```
{
    "@type": "ceasn:Competency",
    "ceasn:isPartOf": {
        "ceasn:creator": {
            "ceterms:ctid": "ce-6d0adaa3-ef92-4b1b-8bdf-608adb91d829"
        },
        "ceasn:publisher": {
            "ceterms:ctid": "ce-6d0adaa3-ef92-4b1b-8bdf-608adb91d829"
        }
    }
}
```

However, using arrays throughout the query returns an error:
```
{
    "@type": [
        "ceasn:Competency"
    ],
    "ceasn:isPartOf": [
        {
            "ceasn:creator": [
                {
                    "ceterms:ctid": "ce-6d0adaa3-ef92-4b1b-8bdf-608adb91d829"
                }
            ],
            "ceasn:publisher": [
                {
                    "ceterms:ctid": "ce-6d0adaa3-ef92-4b1b-8bdf-608adb91d829"
                }
            ]
        }
    ]
}
```
```
{
	"error": "undefined method `keys' for an instance of Array"
}
```

Either variation of the query should work.  Using an array with the `@type` property doesn't seem to cause a problem, but using an array with any of the other properties (`ceasn:isPartOf`, `ceasn:creator`, `ceasn:publisher`), or any combination of those properties, returns the above error.

**Comment by excelsior** [comment]
@siuc-nate This error and a couple of the other once reported last were fixed.

**Comment by jeannekitchens** [comment]
@excelsior the query below now works on production but I am getting and error message, "Error in search request: Internal Server Error" message on sandbox.

{
    "@type": [
        "ceasn:Competency"
    ],
    "ceasn:isPartOf": [
        {
            "ceasn:creator": [
                {
                    "ceterms:ctid": "ce-6d0adaa3-ef92-4b1b-8bdf-608adb91d829"
                }
            ],
            "ceasn:publisher": [
                {
                    "ceterms:ctid": "ce-6d0adaa3-ef92-4b1b-8bdf-608adb91d829"
                }
            ]
        }
    ]
}

**Comment by excelsior** [comment]
@jeannekitchens Fixed sandbox, too.
