### ISSUE TITLE
Missing description sets for new Competency Frameworks on Production

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#707]
We recently had a partner publish a large number of Competency Frameworks on production. However, none of them are returning description sets.

Compare competency frameworks that we've had in the system for a while:
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/2d9de44b-4189-41e5-9441-6601087a0622)

To newly-published ones:
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/94e5e90d-5481-4718-b2f8-935ace7d5ea0)

This seems to affect all recently-published Competency Frameworks. We need this working ASAP so that we can go back to the partner that published the data and show them that it works.

**This has been a [recurring problem for a long time](https://github.com/CredentialEngine/CredentialRegistry/issues?q=is%3Aissue+missing+description+set+framework).** What can we do to keep this from continuing to happen?

**Comment by excelsior** [comment]
Yesterday, 500+ envelopes were publishished, containing ≈5,000 resources it total. Pre-calculating description sets for all them took a bit a long time. Unfortunately, we don't track time of description sets creation, so it's impossible to tell how much time passed between the publishing and pre-calculation.

I'll try to optimize this process the similar way other recent slow queries were handled.

**Comment by siuc-nate** [comment]
This appears to be working now, thanks.
