### ISSUE TITLE
Relevance sort order not responding to reversal flag

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#708]
Both of these queries yield the same ordering for results:
```
https://credentialengineregistry.org/ctdl?order_by=^search:relevance
{
	"@type": "ceasn:CompetencyFramework",
	"ceasn:name": "nursing"
}
```

```
https://credentialengineregistry.org/ctdl?order_by=search:relevance
{
	"@type": "ceasn:CompetencyFramework",
	"ceasn:name": "nursing"
}
```

It's unclear whether they are being relevance-sorted at all, or whether they are simply always being sorted by most/least relevant, but the order doesn't change either way. It does appear to be working for other sort order types, including alphabetical sort by property name.

**Comment by jeannekitchens** [comment]
@excelsior update on this?

**Comment by excelsior** [comment]
@jeannekitchens @siuc-nate The fix is still in progress because the previous approach isn't compatible with the recent optimizations.

**Comment by jeannekitchens** [comment]
@excelsior @edgarf please provide a timeline update for this issue. Thank you.

**Comment by siuc-nate** [comment]
These are working, thanks.
