### ISSUE TITLE
Competency Framework search is slow

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#715]
When doing a blind search in the Finder for Competency Frameworks, the following query is generated:
```
{
  "@type": "ceasn:CompetencyFramework",
  "search:termGroup": {
    "search:value": [
      {
        "search:operator": "search:orTerms",
        "^ceasn:isPartOf": {
          "search:operator": "search:orTerms",
          "ceasn:competencyLabel": "",
          "ceasn:competencyText": "",
          "ceasn:comment": "",
          "ceasn:conceptKeyword": "",
          "ceasn:codedNotation": ""
        },
        "ceasn:creator": {
          "ceterms:subjectWebpage": ""
        },
        "ceasn:publisher": {
          "ceterms:subjectWebpage": ""
        },
        "ceasn:name": "",
        "ceasn:description": "",
        "ceasn:source": "",
        "ceasn:conceptKeyword": ""
      }
    ],
    "search:operator": "search:andTerms"
  }
}
```

This query takes ~12 seconds to perform.  An empty query for frameworks is nearly instant:
```
{
  "@type": "ceasn:CompetencyFramework"
}
```

Something about the various fields in the larger query is causing the slowdown, even though those are empty strings.  Perhaps there should be a step or a process or something that causes empty values to get stripped/ignored (maybe even before the rest of the query is processed)?

**Comment by siuc-nate** [comment]
Per our meeting today:
- We will update the finder to send a much simpler query to handle blind framework searches
- The registry will explore optimizations on their end

**Comment by jeannekitchens** [comment]
This is a Credential Engine team issue being handled with https://dev.azure.com/credential-Engine/CredentialEngine/_workitems/edit/434/

**Comment by siuc-nate** [comment]
Yes, this can be closed. Thanks.
