### ISSUE TITLE
Request to correct Florida ownedBy URIs in ce-registry 

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#717]
I recently noticed that the owned by and offered by URLs for Florida credentials in the public community contained the FL private community of /FDOE.
Example in
https://credentialengineregistry.org/ce-registry/resources/ce-cd52f70c-5d3a-4ea3-88c8-a5a47a2ba666
OF
"ceterms:ownedBy": [
        "https://credentialengineregistry.org/FDOE/resources/ce-898ab397-1f93-451d-b267-e189b186cdb0"
    ],

We would like all of these URLS corrected to remove the /FDOE

Let me know if there are any questions. 
Thanks

**Comment by excelsior** [comment]
@mparsons-ce The resources have been fixed but it will take some time to reindex them all and regenerate their description sets. I'll let you know once it's done.

**Comment by excelsior** [comment]
UPD: all good, there are no public resources with FDOE URIs anymore.

**Comment by mparsons-ce** [comment]
Thanks @excelsior
