### ISSUE TITLE
Search API returns a total of 0 results when the query has a "take" value of 0

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#723]
It seems that passing a "take" value of 0 is causing the total results to be returned as 0 as well.

We have a number of uses cases where a query is only interested in the total, and so the results themselves aren't necessary.

Is it possible that this is a regression from other recent changes?

**Comment by edgarf** [comment]
(just a note - we are working on it).

**Comment by edgarf** [comment]
@excelsior fixed and deployed the issue. He will provide more details on what happened.

**Comment by siuc-nate** [comment]
It looks like the fix was deployed to production, but not to sandbox (I still get 0 total results there with a take value of 0).  It also looks like something unintentional happened with the update - the format of the result data is different.  It now looks like this on production:
![image](https://github.com/user-attachments/assets/f13ee54a-c332-45c9-a7a9-611d1bdafaf5)

When it used to look like this (and still does on sandbox):
![image](https://github.com/user-attachments/assets/c7087c03-12d8-4926-86b7-1ba38df50f75)

**Comment by excelsior** [comment]
@siuc-nate Now it's available on sandbox, too.

**Comment by siuc-nate** [comment]
This appears to have been fixed in both places.  Thanks.
