### ISSUE TITLE
Missing data from description sets for frameworks

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#728]
These frameworks are missing references to progression models in their description sets:
https://credentialengineregistry.org/resources/ce-78dccffa-f509-47b6-9c63-22f9448cd313
https://credentialengineregistry.org/resources/ce-da5fa93d-293a-4546-bd9c-2e4b39fccec8

Each framework has some competencies in it which reference progression levels in one of two different progression models.  However, neither framework's description set references these progression levels nor these progression models.

Was this left out of the description set config?  Or is it a bug in the system?

**Comment by excelsior** [comment]
In the config, the only paths involving progression levels are between pathways and concept schemes. Could you please tell me how the exact connection between a framework and a progression model looks like?

**Comment by excelsior** [comment]
@siuc-nate I fixed the profiles, but couldn't find any competencies containing the `asn:hasProgressionLevel` property. In fact, the only resources that have it are pathways and rubrics. Could you like a couple of competencies that do have that property?

**Comment by excelsior** [comment]
@jeannekitchens @siuc-nate My bad, I was actually talking about frameworks and the `asn:hasProgressionModel` predicate, because Nate's comment mentions frameworks specifically. In the production database, only pathways have this property.

**Comment by excelsior** [comment]
@jeannekitchens @siuc-nate I regenerated the missing description sets.

Nate, there's a typo in one of the paths you listed [here](https://github.com/CredentialEngine/CredentialRegistry/issues/728#issuecomment-2411537879): the `isPartOf` connection  between a competency and its framework is outgoing, i.e. it should be

```
asn:ProgressionModel < ceasn:inProgressionModel < asn:ProgressionLevel < asn:hasProgressionLevel < ceasn:Competency > ceasn:isPartOf > ceasn:CompetencyFramework
```

**Comment by siuc-nate** [comment]
Good catch, thanks

**Comment by siuc-nate** [comment]
The data appears to be present now, thanks
