### ISSUE TITLE
Make timestamp consistent with ISO8601

### ISSUE THREAD

**Issue by rohit-joy** [CredentialEngine/CredentialRegistry#729]
Is this a PostgreSQL artifact or a Ruby artifact to have "UTC" in a timestamp string? 

`"created_at": "2024-10-11 15:01:23 UTC",`

Example: https://credentialengineregistry.org/ce-registry/envelopes/ce-82716513-d86c-4b36-8d43-d5634e1f5620

Seems like it is using RFC1123 format in some places and ISO8601 in others. This is throwing us off where we use these timestamps.
Can we switch it to consistently use ISO8601 format `"2024-10-11T15:01:23.913Z"`?

![image](https://github.com/user-attachments/assets/7480e0c1-f36d-49a1-9756-0f5d83b0b853)

**Comment by excelsior** [comment]
@rohit-joy This change is deployed to both production and sandbox.

**Comment by rohit-joy** [comment]
Thank you sir! Closing.
