### ISSUE TITLE
Missing search result

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#730]
https://credentialengineregistry.org/resources/ce-82fa2b39-39fd-4882-8c78-218b5eb9b4e5 was published a few days ago, but is missing from the search API results.  This query:
```
{
	"ceterms:ctid": "ce-82fa2b39-39fd-4882-8c78-218b5eb9b4e5"
}
```
yields 0 results.

It's possible that other resources are affected, as well.

**Comment by excelsior** [comment]
There are four stuck indexing jobs on prod. Restarting the background service resolved the issue.

**Comment by jeannekitchens** [comment]
@siuc-nate @excelsior can this be closed? If the issue is indexing jobs continuing to fail, please set up an isssue specifically for it.
