### ISSUE TITLE
Add CredentialRegistry to Coveralls

### ISSUE THREAD

**Issue by coffeejunk** [CredentialEngine/CredentialRegistry#76]
The link to [Coveralls](coveralls.io) in the README is dead as we haven't added CredentialRegistry to Coveralls yet (we were previously tracking the [metadataregistry repository](https://github.com/learningtapestry/metadataregistry)).

I'm not a member of the CredentialEngine organization so I can't add the project to Coveralls.

**Comment by leolara** [comment]
@coffeejunk Ok.

@cwd-mparsons @siuc-nate please add @coffeejunk and me to the CredentialEngine organization in github

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
I have added the two of you the organization.

**Comment by coffeejunk** [comment]
@cwd-mparsons thanks however apparently that wasn't enough? I still can't add the repository to coveralls :(

**Comment by cwd-mparsons** [comment]
@coffeejunk 
I gave you Admin access to the repository. Let me know if this solves the issue.

**Comment by cwd-mparsons** [comment]
@coffeejunk 
I received "Third-party application approval request for Credential Engine", and have approved.

**Comment by coffeejunk** [comment]
@cwd-mparsons That did the trick. Thanks!
