### ISSUE TITLE
Update ActiveSupport to 5

### ISSUE THREAD

**Issue by coffeejunk** [CredentialEngine/CredentialRegistry#78]
ActiveSupport 5 has been release ~6 months ago and we should at some point update to it, however since we are supporting JRuby updating to ActiveSupport 5 is currently blocked by [activerecord-jdbc-adapter #708](https://github.com/jruby/activerecord-jdbc-adapter/issues/708).

The following gems can't be updated to their newest versions until we update to activesupport 5
- grape-entity
- kaminari
- standalone_migrations

**Comment by leolara** [comment]
@coffeejunk Ok

**Comment by leolara** [comment]
@coffeejunk is there something blocking this or has this been done?

**Comment by coffeejunk** [comment]
this is still blocked by the library downstream.

**Comment by leolara** [comment]
@coffeejunk is any of our deployments using JRuby? Do we need to support it?

**Comment by siuc-nate** [comment]
Can this be closed?

**Comment by rsaksida** [comment]
We're still on 4.2 and upgrading to 5 would be nice.

**Comment by edgarf** [comment]
@siuc-nate @cwd-mparsons @jkitchensSIUC Should we do this task?

**Comment by cwd-mparsons** [comment]
Yes, upgrading to 5 would be good. Are there any risks or a downside side to the upgrade?

**Comment by jeannekitchens** [comment]
Needs status update.
