### ISSUE TITLE
Add semantic validation

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#8]
As per here: 

http://json-schema.org/latest/json-schema-validation.html#rfc.section.7

**Comment by siuc-nate** [comment]
I have added this for the "date-time" and "uri" formats; we don't appear to use any of the others in CTDL.

Note that this adds a slight complication for the JSON-LD style `@id` objects:

![image](https://cloud.githubusercontent.com/assets/21346519/23802149/0114af48-0578-11e7-80b5-c6002497dd35.png)

Identifiers for objects in published documents may be URLs or they may be an identifier (such as a blank node UUID) or they may be a CTID (urn:ctid:UUID), so I can't force them to be validated as URI (assuming that the URI validation requires a string that looks like a URL).

I can however require this for properties whose range is xsd:anyURI, which uses the same JSON-LD object (with `@id`) - this is why the screenshot above shows both a meta:identifier and a meta:uri where the only difference is that one has a format of uri.

**Comment by siuc-nate** [comment]
Actually, now that I think about it, I'm not sure if an xsd:anyURI would be published in a `@id` block or on its own like a string, since semantically it IS a uri rather than an object identified by uri. @stuartasutton can you chime in on this? Thanks.

**Comment by leolara** [comment]
@siuc-nate we can also add custom validators, that is, we can create our own string to put in format, and code in the ruby server how it is validated

**Comment by siuc-nate** [comment]
Currently the validation expects `@id` for xsd:anyURI values as well as object pointers - this seems to be in line with JSON-LD.  Unless there is anything further (or unless @stuartasutton has something to add), I believe we can close this.
