### ISSUE TITLE
Investigate named graphs

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/CredentialRegistry#814]
Use cases:

- We need to handle data about a resource that does not come from an authoritative source of data for that resource, in order to avoid publishing unvalidated claims about a resource. Examples: 
  - additional information about Credentials provided as part of an approval list; 
  - contextualizing information about competencies in an official framework.
- We need to handle data that has no authoritative source, so that such data do not overwhelm data from authoritative sources in results displays. For example skills created on an ad hoc basis rather than being part of well managed frameworks.
- We need to provide the source and licensing of data that we publish (#741) so that it can be acknowledged and used appropriately.
- We need to record provenance for data in the registry, such as who created them, when were they last checked, in order to ensure that the data meets our currrency policy.

Named graphs have potential to meet these use cases. [Further discussion](https://docs.google.com/document/d/1bd9TIWs1YyDEQ4CqLDbGxUac32dQaMvqEvG0YWQGAAw/edit?usp=sharing) in a Google Doc, focusing on the first example of the first use case, but showing how the others might be addressed.

Proposed initial step is to investigate how the Registry software and associated tools might handle named graphs.

**Comment by jeannekitchens** [comment]
@mparsons-ce please add the list of the data that's currently only avialable via a Registry envelope and we want to include in a named graph, e.g., last published data, publisher.  We're going to start working on this with the Registry team.

**Comment by mparsons-ce** [comment]
Additional candidates from the envelope to inject into a graph:

- owned_by
- published_by
- created_at
- updated_at
- last_verified_on
