### ISSUE TITLE
Setup of three environments at SIUC data center

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#83]
@leolara @science 
We have set up a new Linux VM at our data center for use as the credential registry. 
Next steps:
- identify administrator accounts (active directory), or maybe not necessary if can just log in directly to the VM via the public IP address.
- updating the new VM with staging data. Will this just be a restore?
- assigning the domain name (credentialEngineRegistry)
- what else will be necessary to start to use this server?

**Comment by leolara** [comment]
@coffeejunk Please, provide your public SSH keys

**Comment by leolara** [comment]
+ @cwd-mparsons are we getting a PostgreSQL instance somewhere else or do we install it?
 + @cwd-mparsons  Please, point staging.credentialregistry.org (or whatever domain is preffered) to the public IP
 + @cwd-mparsons I think we can start a fresh with the staging data. The JSON schemas will get loaded from the fixtures
 + @cwd-mparsons What Linux does it has the server? @coffeejunk Any preference? I prefer Ubuntu or Debian.

**Comment by leolara** [comment]
This is my public SSH key:

```

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkVQBPLH4znBRrv4v1XWRGlJuwOl4ROSnJ1AzG1+3NQnq6yyVf3tt64ADimKuRjzEQ+79K9HejLD55Il5u4Kze8FyF8dzocecnNqZvJtT574gpWmKJfXIzRW8zzttzyObzTPvP2gz2T6W1Ae4RnI3IIe/hNkl48KE+1XOLiwZsB3lQ2qCyuPIX5ZUke6vi0rSgACKSKxYBia+6z4SbUVspYeQjGl4cY6zXQM4RBw1j7MMZRol03I8TmySRWr7kRcnmIdZaQqcazpqIdYfl0QgpKvZJCbL08dqjMAY7L302RO1Twy66YLx96o7oglsA3m2qQYhHN7dZ23fVWoCuehWWB1nDCGKmt8UyTt85ug4bGm56fZTSNbUKe9qdv7w9PVpCwgSsutVBYgtkMYiLw2B+42+EleNlTLPBZw2mwkbji56E7R6fHrqf4D0Tl1zc3tuzxbDkJMxVykhNzsbjUMts5CN4xVJ+jBsTji6Gdtmfk/CeJg+WSdRXN79Hcyj0GvrF9d1xRTnkkZp0vgMkTRKXny8DC1MuLabIpnhRmxeW6GfWZl58yMs3CAVxpsEHHpLgF0GXDcPCotP8zTbvx5ABWw3FQUTN+L/aZuv18Cc3h2ylaCWF26KqQbLc5RvXmQLmSNADc6DSJqrGr03RLz9We+mQuVGhBX5hPGw3iuC5FQ== leo@Leos-MacBook-Pro.local

```

**Comment by leolara** [comment]
We provided information here https://github.com/CredentialEngine/CredentialRegistry/issues/18

On Mar 16th

**Comment by leolara** [comment]
Minimum specs from #18 : 

 + GNU/Linux Ubuntu 14.04.5 LTS
 + 2G mem
 + 20 Gb HD
 + 1 cpu Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz

**Comment by cwd-mparsons** [comment]
The VM was created with the above specs (actually the HD was 40 Gb just in case)
IP: 207.68.194.46

Domain:
credentialengineregistry.org

PostgreSQL 
- Yes, we would like for you to install this and everything else!

**Comment by coffeejunk** [comment]
My public key is:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBsrezqZaK26EcKdOFvVaHkQwjs5pOuwIJhe/7xKX5yunHn+i1Gil5IAk7jfExxCEfxR3JbdiJTXptnH64lB5AZu9gJqoJDrRCslNkuuwMFksPHhYYvVROPVAkV9km22saIXrLZY5YVjwl7Vy7K+eH10aW2svjgjMT84UDe26pANOIpUCzFkoKf64NPFTKyRFAtzXAC810c4qrUp1swVNaVevBaog54HXacNXLa7vRffO5QKXhTDvaNl1sLmOZp1GWO+oEaJbMIdIVNltGMFz+zf0AgdAsSSlTBldEg9vPwcfN00AapU661WPL8O1dfCZjazpqqkGmyjuLrtavCr4B
```

**Comment by leolara** [comment]
@cwd-mparsons we need a subdomain pointing to the server, like staging.credentialengineregistry.org

credentialengineregistry.org should be reserved for production.

As soon our SSH keys are uploaded we can start.

I tried to SSH to credentialengineregistry.org but it seems the port is close.

**Comment by cwd-mparsons** [comment]
@leolara 
I will add the suggested subdomain.
Re: ports
Sorry, as I am not familiar with the Linux environment, I didn't know what the initial configuration might be necessary. What ports need to be opened?
What other configuration steps might be necessary?

**Comment by leolara** [comment]
@cwd-mparsons Hi,

For accessing the admin console we need port 22 typically. I guess we will also need port 80 open for the registry. If we are going to use https for the registry we would also need 443, but I do not think we are going to use it.

Then, we need our public SSH keys to be added to the .ssh/authorized_keys file of the login user (in Ubuntu it is the user ubuntu and the file is /home/ubuntu/.ssh/authorized_keys)

Regards,
Leo

**Comment by cwd-mparsons** [comment]
@leolara @science 
As a curiosity, could communities be used for alternate environment (staging, sandbox, release_yymmdd, etc.). This would be an alternative to having multiple machines. Or would there be a risk of having non-production communities mixed with production communities.

**Comment by leolara** [comment]
@cwd-mparsons we could have one machine with virtual hosts. So to have different deployements do not **require** more machines.

The point is that we need staging to deploy the latest version of the software and test it before deploying it into production.

So, it is not only about different data (which the communities can handle) but also about different code base of the server, for which we need two deployments that could be in the same machine.

Once there are many users running and there is a normal amount of traffic it would be advisable to have separate machines for staging and production.

**Comment by cwd-mparsons** [comment]
@leolara
Thanks, I was just curious. I didn't think about the code base. I have sent a request to our datacenter to open the requested ports. 
Also, we do have a new team member with some Linux experience, so, if helpful, could have her help with tasks.

**Comment by leolara** [comment]
@cwd-mparsons Awesome!!

I hope we can integrate Cloud66 into this server. Is it possible? @coffeejunk

**Comment by coffeejunk** [comment]
@leolara yes, we can add (register) our own servers to Cloud66 (they do need to run on Ubuntu 14.04 or Ubuntu 16.04 and we need root/sudoer access rights).

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
We have a Linux server set up at our data center. The data center admin felt that it should not be opened to  the public (outside a VPN). The only exception might have been for a developer with a static IP address. If Max or others that need access have a static IP, then we can request access. 

VPN
Otherwise access is through a VPN.
Vpn.illinicloud.org
Passwords will be distributed separately
IP: 172.22.152.13:22
userId: linuxAdmin
Password will be distributed separately

**Comment by coffeejunk** [comment]
@cwd-mparsons VPN access is fine for me, could you send me the password? Thanks!

**Comment by cwd-mparsons** [comment]
@coffeejunk 
Do you have an email address I can use to send you the info?
Alternately, I created a private google doc that I will share with you once you attempt access
https://docs.google.com/document/d/1ev6iNwzTXPo5QCx_baOErAmtuGTFl7wkXPcgMHopT1w/edit

**Comment by coffeejunk** [comment]
got it thanks!

**Comment by coffeejunk** [comment]
@cwd-mparsons which VPN protocol/client do we have to use here? and do we need any additional certificates?

**Comment by cwd-mparsons** [comment]
@coffeejunk 
For windows 10, I downloaded the F5 client from the windows store. 
For windows 7, I have been using an F5 Firefox plugin. 
![image](https://cloud.githubusercontent.com/assets/26332112/25955974/383882ae-3630-11e7-961b-083844088f0e.png)

Then I start with the following url.
https://vpn.illinicloud.org/my.policy
Unfortunately, the latter plugin doesn't work after 47.0.1. So I make sure to not update Firefox despite the numerous reminders.

**Comment by leolara** [comment]
@cwd-mparsons 

This is not a http thing, so firefox plugin couldn't work. We need SSH access. I do not think you can get to that through firefox.

SSH is as secure as VPN, as some VPN protocols are based on SSH, https://help.ubuntu.com/community/SSH_VPN

But well, as long we can connect to the VPN from Mac and Linux and we can access the SSH port through that VPN, we will use the VPN.

**Comment by cwd-mparsons** [comment]
@leolara At work, I:
- use Firefox to login to the VPN
- use PuTTY to connect to 172.22.115.13

Unfortunately, that is the limit of my knowledge for connecting to the Linux VM.
I had done a search for Linux options for connecting to an F5 based VPN. The following seems promising.
https://support.f5.com/kb/en-us/products/big-ip_apm/manuals/product/apm-client-configuration-11-4-0/3.html

**Comment by cwd-mparsons** [comment]
@leolara As noted in the meeting on  Wednesday, we will require a total of three environments: production, staging, and sandbox. I am requesting the two additional VMs from our datacenter. 
Once the current linux box is completely configured, can these new VMs be configured by simply doing a restore from a backup of the first VM? This would simplify the configuration of the new ones. I wasn't sure if there might be something unique to each box that might preclude the use of a restore a new VM from the backup from another one.

**Comment by coffeejunk** [comment]
@cwd-mparsons @leolara I've registered the server with Cloud66 however as the configuration is right now, we won't be able to use it:

http://help.cloud66.com/article/23-registered-servers:
> Open at least TCP port 80, 443 and 22 to the outside world. Cloud 66 install a firewall on each box (…)

Cloud66 doesn't support managing servers through VPNs of any sort.

**Comment by leolara** [comment]
@cwd-mparsons 
 + I do not think we need three machines, I think one for production and another one for both sandbox and staging are ok
 + For easy launch of new deployments and configuration, the best option is to Dockerize and follow 12factor app practices https://12factor.net/
 + It seems the VPN is getting in the way and at least not more secure that our usual set up of ssh with password disabled (only private key auth allowed)

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
re: the Cloud66 reference, does this mean you cannot proceed with the installation?

**Comment by coffeejunk** [comment]
@cwd-mparsons yes, we need the server to be reachable without VPN to proceed with the installation

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara @science 
I have submitted an issue to our datacenter admin regarding this. I will follow up tomorrow with them to resolve this issue.

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk @science 
Max, the datacenter replied that they could open SSH while you are doing the configuration - but temporarily. Would this work, or would access via SSH be required ongoing?
It might be more efficient to arrange a call with the datacenter folks so that we don't have this lag as I pass info back and forth between parties.

**Comment by coffeejunk** [comment]
@leolara @cwd-mparsons if we want to use Cloud66 to continuously manage the server(s) we'll need them to have the above mentioned ports open permanently. The alternative would be to not have Cloud66 manage the servers but that would essentially make someone the sysadmin for the servers.

**Comment by leolara** [comment]
@cwd-mparsons Could we deploy outside your DC? Perhaps Learning  Tapestry could be in charge of the deployment?

**Comment by leolara** [comment]
@cwd-mparsons an alternative is to handover completely the deployment to your IT people. It seems we are working in different styles, and to conciliate both is going to be hard.

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
The data center has opened SSH for the Linux servers. 
Max was working on  the .13 server, which is the cerSandbox (207.68.194.46)

| Internal IP        | Public IP          | Host name  |
| ------------- |:-------------:| :-----:|
| 
172.22.152.13      | 207.68.194.46 | cerSandbox |
| 172.22.152.16      | 207.68.193.48 | cerStaging  |
| 172.22.152.17 | 207.68.193.47 | cerProduction |

**Comment by leolara** [comment]
@cwd-mparsons 

Thanks!!

It is very important that we add our private ssh keys and disable password login, as this way they are as secure as using a VPN.

Added this for it:

https://github.com/CredentialEngine/CredentialRegistry/issues/104

### For staging and sandbox

Then: 

https://github.com/CredentialEngine/CredentialRegistry/issues/105

### For production

If you are using postgreSQL already internally, we would prefer that the DB is managed by your IT, so they manage the replication and backup.

Another alternative is if your cloud provider has something like AWS RDS or we could hire something like compose.io.

Of course, we could set up the DB for production but that would be additional costs. We would need two more servers for the production DB, and a cloud files system to upload backups.

**Comment by coffeejunk** [comment]
@cwd-mparsons I can't establish a connection to any of the servers via SSH, unless I'm missing something the port for SSH (22) is not open.

Please note for Cloud66 to work properly we'll also need ports 80 and 443 to be open to the public.

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara 
I checked and found that the two new servers (207.68.193.47, and 207.68.193.48) are open, but not the original 207.68.193.46. server.
I have sent yet another ticket on this to the datacenter.

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara 
Sorry, for the newbie question:
           How do I had the ssh keys to these servers?

Again, I know nothing about linux.

**Comment by cwd-mparsons** [comment]
@leolara @science 
re: postgreSQL 
I didn't realize a separate server was needed for postgreSQL. We don't use postgreSQL at this time. If we were to host the db servers, we would probably want to use a windows instance. Would this be an issue?
I would lean to having the management being done externally.

What would be the costs for AWS RDS or compose.io?

What are all the environment requirements?

If we have three servers for sandbox, staging, and production, do we then need 
- three servers for postgress.  Why couldn't a single server be used to host multiple instances of postgres?
- three more servers for cloud file systems

**Comment by cwd-mparsons** [comment]
@coffeejunk 
The DC had given be the wrong IP address. 
The correct IP for the sandbox is:   **207.68.193.46**  (not 194.46)

**Comment by leolara** [comment]
@cwd-mparsons 

### re SSH keys

as I think we have password access now, we can enter that way and add the SSH keys, and then disable password auth

### re DB servers

We treat production DBs differently. For staging and sandbox we could run the DB server in the same machine as the API server, and the worst case scenario is that non-vital information is lost or that the sandbox or staging are down for a day max.

For production we treat it differently.

I would have at least two DB servers replicating continuously between them and automatic periodic backups. This is more difficult to set up and manage so it is better to use a service.

AWS RDS PostgreSQL Multi-AZ in N.Virginia costs $0.072 per hour, which is times 750 is $54

Compose.io Postgres with 4Gb of information is $53.50.

One thing we could do to save money is to have staging and sandbox in the same server (but different subdomain name).

**Comment by coffeejunk** [comment]
@cwd-mparsons I'm able to connect to the sandbox without VPN now however C66 is giving me the following error message:

> Cloud 66 cannot fire up all of your required servers due to the following error: Sorry, unable to create instances in the cloud: Please check port 22 on your server is open to accept connections from Cloud 66 gateway server (54.84.166.97)

Could you ask the DC to ensure that IP can access the ports? Thanks!

**Comment by leolara** [comment]
@coffeejunk @science @cwd-mparsons 

If we want to move forward this I would suggest we choose between to alternatives:
 + We set up the deployments with the tools LT staff are used to: AWS, Cloud66, SSH, etc
 + SIU IT staff takes charge of the deployment and do it with the tools they are familiar with

I think Linux/Open source IT and Windows IT are so different that it is going to be clunky if we try to mix both worlds.
