### ISSUE TITLE
Timeframe and process for updating registry with a new release of CTDL

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#84]
@leolara @science 
The next official release of CTDL is April 28th. We currently have an informal process for managing updates (especially for interim updates):

- We get the latest (generated) Json schema from credReg.net
- We update the Github repository with the updates
- We create an issue to request that the schema be updated

We would like to document the steps for the registry team to implement new releases, and an estimate of time. I would guess there is a need to testing. I recall references to tools to use to rerun test coverage. 
This next release is an opportunity to understand and document the effort and duration.

Related to this process would be the test data. For example, for the last update Max reran the test data that I had previous provided. A lot of these failed because of items like dates, or multiplicity of an item. These would have to be regenerated. So when I request a publish using the source data that gets formatted with the current CTDL, and fixes to format, the publish (usually) works. As it is easier for us to generate payloads, should we have a list of specific credentials, etc that should be provided, that is regenerated, each time there is a significant update?

**Comment by leolara** [comment]
@cwd-mparsons 

I think ideally we would have a more automatic testing, something like this:
 + You do a commit to https://github.com/CredentialEngine/CTDL_Json_Validation_Schema
 + A CI system is trigger, something like Travis https://travis-ci.org/
 + A ruby console program is run that test against the schemas a bunch of example resources, using the same library and version as Cred Reg
 + The results are registered in the output of Travis
 + (optional) On successful pass of all the tests, automatically the CredReg schemas are updated

If you think this is important we should create a task for this.

**Comment by leolara** [comment]
@cwd-mparsons 

This is being worked out in https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/pull/1

and you can see the example output in https://travis-ci.org/coffeejunk/CTDL_Json_Validation_Schema/jobs/228279368

Once @coffeejunk has write access we will merge it.

Then you should work on the next version of the schema on `latest` directory and make sure that all the tests pass before the release date.

**Comment by cwd-mparsons** [comment]
@leolara 
I gave Max admin access to the repo, but I have a question(s). 
Currently the validation schema is generated automatically on credReg.net, and then I copy the schemas and save on github. Is Max updating the schema files, or adding something new (I assume related to testing). So related to the latter, if I update the schema files will I be overwriting whatever Max is adding?

It appears the cool answer is that some automated testing is being added. If that is the case, we would need a process to update the test data. In the past, I gave Max test cases. Are these the test cases that Max is adding?
As a result of schema changes or bugs in how the payload is generated, then these test cases would have to be regenerated. I am in the process of reviewing the test cases and weeding out similar cases, and updating where new properties and classes have been added. If these are the source of testing, then, as noted we will need to update them. Or, are these test cases updated in some fashion before being added to the repo?

As this process is finalized, then for each release, would the steps include:
- creating a new schema folder (ex. Schema-2017-06-30)
- add the schemas
- add the test cases
- initiate automatic testing

**Comment by coffeejunk** [comment]
@cwd-mparsons I am not updating the schema files, I have solely implemented a way to automatically test the JSON Schemas with test data. The way I have implemented the testing infrastructure would create the following workflow:

1. You create a new version of the schemas (download it from credRed.net)
2. You create a new folder (eg. `Schema-2017-06-30`) and place the new schemas inside
3. You update the symbolic link called `latest` to point to the latest release (eg. `Schema-2017-06-30`)
4. You update the test cases (if necessary).
   They are located in the folder `/test_data` with subsequent subfolders named after their respective schemas (i.e. for `/Schema-2017-06-30/credentialSchema.json` we would have `/test_data/credentialSchema/credential_1167_payload_Successful.txt` or `/test_data/credentialSchema/invalid_credential.txt`)
5. You commit these changes to the repository and push them to GitHub
6. Travis CI automatically picks up the changes and runs the test cases against the new release of the JSON Schema. If test cases fail, you will be automatically notified (via email) and can inspect the log on Travis CI ([see this example](https://travis-ci.org/coffeejunk/CTDL_Json_Validation_Schema/jobs/228284043#L287)).
7. Bonus: You could use a Pull Request to release new versions of the schemas and as such ensure that all test cases pass before finalizing the release. GitHub will display the status of the test inside of the Pull Request ([like it does here](https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/pull/1)).

I've currently [included the test cases you gave me for the `2017-04-24` release](https://github.com/coffeejunk/CTDL_Json_Validation_Schema/tree/e8ae8e992927e04445a934caf0f02d007f27eb70/test_data).

**Comment by cwd-mparsons** [comment]
@coffeejunk 
Thanks, this sounds amazing!

**Comment by leolara** [comment]
@cwd-mparsons 

this is the open-source/githubish way of doing this type of thing, pretty normal :-)

**Comment by science** [comment]
@cwd-mparsons - creating the symbolic link might be the only minor challenge with this process. It can be done in Windows but to do it from the command line requires a tool. I think either of the following will do the job for you:

* https://technet.microsoft.com/en-us/sysinternals/bb896768.aspx
* https://technet.microsoft.com/en-us/library/cc753194(v=ws.11).aspx

You want a symbolic link (not a hard link), fyi. That's the default in both applications, IIRC.

**Comment by cwd-mparsons** [comment]
@coffeejunk 
Max
I updated the schemas (mainly adding ctid to org, assessment, , and learning opp).
I then created the payload files, with the ctid present - just for organization for now .
I removed the old org test cases, and uploaded the new ones to:
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/test_data/agentSchema
These files are now committed in github. 
It seems as if the Travis CI process would run automatically, but I have not seen an indication of any response.

**Comment by coffeejunk** [comment]
@cwd-mparsons Travis CI picked up your changes automatically and ran the tests, [the result can be inspected here](https://travis-ci.org/CredentialEngine/CTDL_Json_Validation_Schema/jobs/237651329).

If you simply push to `master` (as you did), you _should_ receive an email with the build status and you'll see an indication in the README:
<img width="639" alt="screenshot 2017-05-31 13 40 12" src="https://cloud.githubusercontent.com/assets/205556/26618984/b8ccc570-4606-11e7-9d25-6272f2e506c2.png">

Alternatively if you commit and push to a new branch and then create a Pull Request on GitHub, Travis CI will pick up the changes, run the tests and notify GitHub about the build status. You'll see an indication of the status in the Pull Request: [I've made a quick video demo here](https://www.dropbox.com/s/ltay0u87bpvzbdl/travis-demo.mov?dl=0).

**Comment by leolara** [comment]
@cwd-mparsons @science @coffeejunk in my original idea when I was organising this, symbolic links were not necessary. and if they are complicated on windows I suggest we follow the original workflow:

 + The schema designing people work in `latest` commiting their last changes directly as hard files there
 + Travis pick up the changes in latest and run the tests
 + When the version in latest is to become the official one, a new directory with the version is created and the schemas copied there

**Comment by leolara** [comment]
@cwd-mparsons @science @coffeejunk What do you think about the last design I mentioned?

I think @coffeejunk has some valid points, and perhaps we should mix what I said with git tags and github releases

**Comment by leolara** [comment]
Continuing conversation from  #120

**Comment by leolara** [comment]
@cwd-mparsons @coffeejunk 

My idea is:

 + the schemas in a folder named ```Schemas```.
 + tests in ```spec```and ```test_data
 + A git tag for each release
 + in the README.md, for each release a link to the corresponding tag inside the folder Schemas. This can be done before actually creating the tag, so when the tag is created already contains a link in its README.md

Of course, we can use Github releases and I think they are automatically created from tags. What I do not think it is a good idea is to relay only on Github Releases without tags, as tools based on pure git will not be able to use them.

In general the workflow with this design will be:
 + Working on ```Schemas``` and  ```test_data``` in master. The HEAD of master will be the development version.
 + When the current HEAD is ready for realease, add a link to its github tag (Schema subfolder) in README.md and commit
 + Tag that last commit with the release commit
 + I think the github release will be created automatically from the tag, otherwise there will be an step for it.

Please, let's discuss this option, what are your thoughts? @cwd-mparsons @coffeejunk
