### ISSUE TITLE
Handling of references especially assertions to an organization and other types

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#88]
@leolara @science 
We need to identify a process to resolve references such as where a credential alignment object references an organization/agent to an actual organization record, if it exists in the registry.
A similar need would be to allow validating assertions where someone publishes that their credential is accredited by an organization. This would be more complicated, and I will create another issue. I am leaving the comment here, as I believe the solution for the latter will be related to or an extension of the former.
Related issue for organizations
https://github.com/CredentialEngine/CredentialRegistry/issues/37
Scenario
Someone is publishing a credential. It may be offered by a particular organization. In this case (unlike some of the scenarios in #37), the user is going to publish with an alignment object that contains, at a minimum, a name and URL. The user should not have to check if the org exists in the registry. 
On publish it would be useful to have the registry be able to check and attempt to match to an existing org. This could be complicated with the minimal data of name and URL. If needed, what other data could be recommended to be provided? 
I am not sure how a match would be persisted, given that user data cannot be updated. 
Would this lead to having an index of organizations created as alignment objects, with essentially pointers to the actual organization?

**Comment by leolara** [comment]
@cwd-mparsons my understanding is that when a top level entity references another top level entity it will have something like this:

```js
{
  "@id": "URI to the refered"
}
```

considering the URI is domain.com/resources/UUID and that you can in private generate your own UUID for the organisation the organisation does not have to be previously inserted in the registry.

**Comment by leolara** [comment]
@cwd-mparsons is this solved? perhaps I do not understand what a alignment object is

**Comment by jeannekitchens** [comment]
@mparsons-ce you opened this issue in 2017.  Is it still an issue? if so, needs to be clarified as the most recent comment from 2019 was that it is not understood.
