### ISSUE TITLE
Registry validation shows 'false' errors with a valid error

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#94]
@coffeejunk 
While testing publishing, we saw validation errors on valid properties. In the example below, the real error is the last one (ceterms:image : did not match the following type: object). If I remove the image url, the publish is successful. If a url exists, then the other errors at the start are displayed, included the unexpected reference to a property '#/'

Resource JSON Schema validation errors: ["_ : The property '#/' contains additional properties [\"@context\", \"ceterms:address\", \"ceterms:agentType\", \"ceterms:name\"] outside of the schema when none are allowed in schema 6e0e81eb-d44a-563f-aeff-c54a6312e248#", "@type : did not match one of the following values: ceterms:QACredentialOrganization", "ceterms:image : did not match the following type: object"]

NOTE: the ceterms:image error required an update to the validation schema. Nate has made the update. I have updated the schemas in github.
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/blob/master/Schema-2017-04-28/credentialSchema.json
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/blob/master/Schema-2017-04-28/agentSchema.json

Just in case, following is another example of a 'false' error. This was for a credential, with a credential type of certificate ("@type": "ceterms:Certificate",). A secondary error on @type should not be shown.

Resource JSON Schema validation errors: ["ceterms:image : did not match the following type: object", "@type : did not match one of the following values: ceterms:SecondarySchoolDiploma"]

**Comment by coffeejunk** [comment]
@cwd-mparsons I've updated the JSON Schemas

**Comment by siuc-nate** [comment]
We need to test for this.

**Comment by leolara** [comment]
@siuc-nate what do you mean? Do you want us to test something? We implemented automatic tests for the JSON schemas here:

https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/pull/1

I think you can see the results of the tests in travisci

**Comment by cwd-mparsons** [comment]
@coffeejunk 
I attempted to publish an organization - with the CTID, that is not in the registry version of the schema, but is in the github version. So I expected that error related to ctid, However, as shown in the image, a second message is shown stating:
"@type : did not match one of the following values: ceterms:QACredentialOrganization"

![image](https://user-images.githubusercontent.com/26332112/27653928-39a7d094-5c06-11e7-8cd6-b8597c5b4413.png)

The registry schema should have:
 "anyOf": [
        { "$ref": "#/definitions/ceterms:Agent" },
        { "$ref": "#/definitions/ceterms:CredentialOrganization" },
        { "$ref": "#/definitions/ceterms:CredentialPerson" },
        { "$ref": "#/definitions/ceterms:QACredentialOrganization" }
    ],

**Comment by leolara** [comment]
@cwd-mparsons I think it would be helpful if you could provide the organisation json you are publishing

**Comment by leolara** [comment]
@cwd-mparsons I close this assume it has been fixed, feel free to reopen it if not
