### ISSUE TITLE
Test system for CredReg JSON Schema

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#96]
Implement test system in https://github.com/CredentialEngine/CTDL_Json_Validation_Schema so for each commit, the schemas are tested automatically.

 + There is a folder `latest/` with the latest version of the schema.
 + There are example resources in `tests/{schemaName}/[valid|invalid].exampleXXX.json` (or similar structure)
 + There is a test, based on a ruby test system, that runs all the examples against the schemas in `latest/`and generates errors for each incorrect validation (valid example which is returned valid, and invalid example which is returned valid)
 + This test uses the same JSON Schema library and version as https://github.com/CredentialEngine/CredentialRegistry
 + Connect to Travis, so for each commit the tests are run
 + Put travis badge in README.md of https://github.com/CredentialEngine/CTDL_Json_Validation_Schema

Change anything you consider for this plan @coffeejunk 

---

Related https://github.com/CredentialEngine/CredentialRegistry/issues/84

**Comment by coffeejunk** [comment]
@cwd-mparsons could you please grant me admin permissions to the 
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema repository so I can set everything up
