### ISSUE TITLE
Document search API

### ISSUE THREAD

**Issue by leolara** [CredentialEngine/CredentialRegistry#98]

**Comment by coffeejunk** [comment]
The documentation already exists [here](https://github.com/CredentialEngine/CredentialRegistry/blob/master/docs/07_search.md) or did you have something else in mind?

**Comment by leolara** [comment]
@coffeejunk Ok

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
I was reviewing the search API documentation for use on the credReg.net site (http://credreg.net/registry#search_api) and see that the samples are out of date - due to schema changes.

**Comment by leolara** [comment]
@cwd-mparsons yes, the best way we should have is an automatic system to convert the markdown documentation in the sources to the HTML on http://credreg.net/.

Should we work on it?
