### ISSUE TITLE
Publish api should not require envelope UUIDs for update

### ISSUE THREAD

**Issue by science** [CredentialEngine/CredentialRegistry#99]
Currently the publish api requires the publisher to know the UUID of the prior envelope that was used to publish a resource.

This feature should be improved so that the work flow is as follows
1. Publisher sends a new credential (aka resource) but doesn't provide UUID
1. Publisher sends update to credential but doesn't provide UUID
  1. Update succeeds b/c CER looks up the CTID in the resource, finds the prior envelope and publishes over it, as long as the JWT signatures match (per usual permissioning)

**Comment by leolara** [comment]
@science in my opinion it should be formulated as following:

1. Publisher sends a new  resource but doesn't provide envelop id
2. Publisher sends update to credential but doesn't provide envelope id
3. Update succeeds b/c CER looks up the `@id` field in the resource, finds the prior envelope and publishes over it, as long as the JWT signatures match (per usual permissioning)

More clear in my opinion
 + If on a resource update the user does not provide the envelope id, this is looked up through the resource `@id` field

I think for new resource creation, this is already implemented, the envelop is autogenerated if not provided

**Comment by cwd-mparsons** [comment]
@leolara Is there are status on this task? That is when can we start testing - not using the envelopeIds for updates?

**Comment by leolara** [comment]
@cwd-mparsons this has not been implemented yet. The new simplified (with automatic server side signature) publishing is going to change many things, and perhaps this will be part of it.

@coffeejunk do you think we can implement this quickly or will delay the new authentication and simplified system stuff?

**Comment by coffeejunk** [comment]
@leolara I think this shouldn't take too long

**Comment by coffeejunk** [comment]
It should also be noted that the update on the `/resources` endpoint is not done via the `envelope ID` but rather through the `resource ID`, so the user doesn't have to know the enveloped ID to begin with.

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara 
I see that some testing has been done (#110), but am not sure it the process has been implemented.
I have tried to test this feature using our registry assistant API:
- created a simple credential (ctid: "ce-5f521767-2209-4595-802b-e85cd8e62872"; envelope: http://lr-staging.learningtapestry.com/ce-registry/envelopes/516b29fa-ff2f-4fec-8bbb-0514037932cc )
- then attempted an update (without using an envelopeId)

I get:
Resource CTID must be unique

Also, all the top level entities **_will_** have a ctid.
